### ISSUE TITLE
Energy Acceptor does not accept Rotarycraft power

### ISSUE THREAD

**Issue by gwalther** [AppliedEnergistics/Applied-Energistics-2#1013]
Rotarycraft has recently updated its API, and it appears AE will no longer accept Rotarycraft power directly.

**Comment by BoboSims** [comment]
Should that not be posted with Rotarycraft?

**Comment by thatsIch** [comment]
mh, again?

**Comment by gixbit** [comment]
@BoboSims 

The issue is not rotarycraft. API is used to help other mods interface each other. If AE2 changes their API, they would have to adhere the new API, same for Rotarycraft's API, AE2 would have to adhere to their API. It's like building a car to use gasoline then suddenly saying, it has to use hydrogen now. Then blaming the car for not being able to use the thing it was made to work with.

**Comment by BoboSims** [comment]
I understand the logic, @gixbit. But were I to invoke logic, logic clearly dictates that if you live in a world with **only** petrol-driven vehicles and no hydrogen-driven vehicles whatsoever, and you **then** suddenly stop providing petrol in favor of hydrogen, then that is **not** the fault of the automobile industry! **You** changed your business out of the blue; **you** made your product incompatible with the established market!

Analogeously, if the *RotaryCraft* team made an almost ad-hoc change that caused the incompatibility, then that isn't the AE2 team's fault. Perhaps they could have allowed for a bit more time for others to adjust. Or maybe they could have made it backward compatible for now.

**Comment by thatsIch** [comment]
Its fine being posted here,
just would hear a heads-up from Reika himself,
so we know what its up

**Comment by gixbit** [comment]
@BoboSims

There is no reason to start a flame war. Mod devs can do what they want, there is no agreement between authors to conduct their updates in the interests of anyone. And even if there is, they do not have to honor anything. Thats how it works I would imagine.

**Comment by BoboSims** [comment]
@gixbit  I'm not starting a flame war. I didn't call anyone any names, nor did I curse are bear anyone any ill will. And I used logic to counter your own somewhat flawed analogy, that's all I did. I'm just stating facts and my honest opinion.

As you can see, @thatsIch at least agrees that he would have appreciated some note from Reika too. So, maybe I'm not even unreasonable.

I'll even throw in a similar example: recently, TeamCoFH changed something about their mods too, and as a result, their wrenches no longer work on certain blocks from other mods. I didn't blame those other mods, because the change was initiated by TeamCoFH. So **that** is where I went to report the incompatibility. Same kind of situation, same kind of logic.

**Comment by Cisien** [comment]
What it boils down to is that the API changed. If we still want to support the mod, then the issue is on us to fix. Can we stop debating this now?

**Comment by thatsIch** [comment]
Can somebody here test the build of https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/1103 ?

I have no clue how RtC works, so...

**Comment by ruifung** [comment]
Just hook up a creative industrial coil to test. it can only be found in creative inv. Ill test it later if it still needs to be.

**Comment by thatsIch** [comment]
Seems to work

![2015-03-28_07 48 17](https://cloud.githubusercontent.com/assets/2210496/6880099/e1d30d18-d51e-11e4-9fc6-775992d91e60.png)
