### ISSUE TITLE
Crafting Tree Construction Failed

### ISSUE THREAD

**Issue by Pkr1345** [AppliedEnergistics/Applied-Energistics-2#1042]
when I try and autocraft item such as the solar panel from IC2, it asks for an amount I want then spits me out of the me and gives me the error,

 (Error: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.RuntimeException: Crafting Tree construction failed.)

And it only happens rarely and repeatedly to specific items. It doesn't crash the client or server, it just refuses to craft the item. 

appliedenergistics2-rv2-beta-11

**Comment by thatsIch** [comment]
Do you have per chance the full log?

**Comment by Pkr1345** [comment]
http://pastebin.com/dSsGa8vp

Theres not much to see.

**Comment by yueh** [comment]
If I recall correctly, this will only happen with something like a corrupt pattern.
Either one definining no output at all or something is actively changing the output item somehow, maybe between restarts?

We should probably throw a more precise exception in `CraftingTreeProcess.getAmountCrafted()` like a `CraftingCalculationFailure`. Instead of using a generic `RuntimeException` and let it bubble up (after wrapping it in another `RuntimeException`)

**Comment by Pkr1345** [comment]
It appears that the same version is broken with shift-clicking recipes into the terminals, throws you to the main menu.

**Comment by Pkr1345** [comment]
The problem it the use of The Pattern Encoder from the addon AE2 Stuff is giving vanilla items insane id's. Some recipes still work, just some get messed up.

**Comment by yueh** [comment]
Yes, the pattern encoder from AE2Stuff is basically broken by design and will cause AE2 to crash.
