### ISSUE TITLE
Processing pattern retains the shape of the recipe

### ISSUE THREAD

**Issue by rashdanml** [AppliedEnergistics/Applied-Energistics-2#1049]
A suggestion, which would aid automation of some of the more complex machines which require placing items in specific slots of a crafting grid (Galacticraft electric compressor, for instance, which has a 3x3 grid). 

When encoding processing patterns, there should be an option to remember the shape of the pattern, instead of treating it as shapeless (which I think is how it's done right now). By retaining that info, you can arrange your pattern in such a way that it gets replicated exactly in the machine it goes into. 

Would make it a lot easier to interface with such machines.

**Comment by thatsIch** [comment]
From what I can read in the code, it is actually already done that way. The problem is probably, that the inventory of that machine does not accept it in the necessary order (and additionally, I have no clue, what that machine is doing, how it works, what it is currently doing, how it is currently interaction with auto-crafting in general).

**Comment by rashdanml** [comment]
Hmm, I think you may be right. OpenComputers, for instance, is able to see the Electric Compressor as an inventory, but even with its precise inventory control (which is able to place items in a specific slot in an inventory, chest or otherwise), it can't place items in a specific slot in the compressor.

**Comment by radfast** [comment]
@thatsIch   If you need an additional interface on the Galacticraft machines to give you this precise control, I'm happy to code it in.  But I'd need to know exactly what you need.

Our Electric Compressor code is [here](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityElectricIngotCompressor.java).  The crafting inventory slots are 3 through 11.  They are accessible using normal ```ISidedInventory``` methods.

One thing to watch is that the validity of items for slots [depends on whether the machine already has items in it making a valid recipe](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityElectricIngotCompressor.java#L374).  So if there is a valid recipe already, the machine will return that any different items are invalid for the slot.

Similarly, where a recipe involves two input items of the same type, the machine controls which of the two slots is accessible [according to which slot currently has the smaller ItemStack](https://github.com/micdoodle8/Galacticraft/blob/master/src/main/java/micdoodle8/mods/galacticraft/core/tile/TileEntityElectricIngotCompressor.java#L412-L419), this is to force even distribution of input items.

Both techniques allow this machine to be "smart" and to work correctly with vanilla Hoppers.

It may be that the problems players have with interfacing this with AE2 is that AE2 tries to place a whole stack of items in the machine at once, instead of adding 1 item per tick like a Hopper does?

If that's the reason, then we can maybe fix these problems on GC's side simply by switching off the "smart" parts of the code if an ItemStack of stacksize greater than 1 is presented?
