### ISSUE TITLE
Another option for the storage bus

### ISSUE THREAD

**Issue by XFactHD** [AppliedEnergistics/Applied-Energistics-2#1051]
Would it be possible to add a button to the GUI of the storage bus to be able to toggle the visibility of the items that are accessed by the storage bus? In my world I have the problem that I insert uranium fuel rods into my reactors by using a storage bus but I don't want to see the fuel rods and the heat vents that are in the reactor in my terminal and I am not able to blacklist them with a view cell because I want to be able to autocraft and access them as long as they are in a storage drive.

**Comment by yueh** [comment]
Use the mode to set it to insert only, so it will not report the contents to the network.

This will of course also prevent the network from accessing them for refilling (via the same storage bus). But any other blacklist will do the same.

**Comment by XFactHD** [comment]
The problem is that I need to be able to insert a new uranium cell and also pull the depleted cells out of the reactor because one quadruple cell is some iron and also plutonium which can only be gained by burning uranium cells in a reactor.

**Comment by yueh** [comment]
This can be solved with a better network design.

If you want the storage bus filter to work like a whitelist for extraction instead of just insertion as currenlty. Then it would only affect the not filtered items in such way, that these are not reported to the network.
As you want to store fuel rods, they will always be reported to the network (except in insert only mode).
Splitting it into visible for the network and terminals is also way too complex (and I think not even possible without rewriting everything)

**Comment by XFactHD** [comment]
Thanks for your answer. Then I will have to build a separate sub network for this. I will close this now.
