### ISSUE TITLE
Security permissions break connections

### ISSUE THREAD

**Issue by thatsIch** [AppliedEnergistics/Applied-Energistics-2#1074]
Issue to summarize the issue regarding security permissions:
- while chunks load into existing networks, there can be race conditions, where the "new" network will not be accepted into the main network
- this results into breaking the border connection
- depending on servers and mods, there can be rapid loading and unloadings of chunks

Temporary fix:
- **chunk-load the entire network**
- insert a blank permission (master permission for everybody)

Feel free to edit this, if anything was incorrect or incomplete

**Comment by Flukethoughts** [comment]
blank did not help

**Comment by yueh** [comment]
Any idea why the `CableBusContainer` is using a `ThreadLocal<Boolean>`?

**Comment by thatsIch** [comment]
no, a `private static boolean` should suffice imo.

**Comment by Farbdose** [comment]
Just being curious: 
as the break happens because ae2 security drop doesn't know who placed the cable that just appeared out of nowhere (new junk was loaded) could this be circumvented by placing a security terminal in every chunk so ae2 can see 
"Hey this cable belongs to _another network_ with a sec term that was placed by the same user as _this 
 network_, let's connect!"

**Comment by yueh** [comment]
Closing, as this can easily be caused by the TE/chunk corruption bugs in forge, which exist since 1.7.10 or maybe earlier.

**Comment by Solverbolt** [comment]
Good to know that this issue is being ignored despite it still being very much active as of now

**Comment by Solverbolt** [comment]
cannot even play because its kicking out error popups over the top of the screen.
