### ISSUE TITLE
Fuzzy Storage Monitor

### ISSUE THREAD

**Issue by gixbit** [AppliedEnergistics/Applied-Energistics-2#1088]
As a new item suggestion, would it be possible to make a fuzzy storage monitor? I'm not sure if this is possible but, seems like you might be able to make it. For example it would have the same image but, be able to pull any wood, for example, from the ore dictionary. The original item would still be it's first item to pull of course.

**Comment by thatsIch** [comment]
You mean ike http://ae-mod.info/View-Cell/

**Comment by yueh** [comment]
Sounds more like an OreDictionary converter.

Or maybe a manual version of the refill with shift clicking to craft a full stack.
But that is a feature for a terminal not storage bus and probably more annoying than being useful, if your inventory is suddenly filled with 1 item of every log because you had only half a stack left and did use shift click to fetch a full stack (or exactly what was left) and the system uses anything left to give you a full stack.

**Comment by gixbit** [comment]
Its for the storage monitor not conversion. Not quite like the view cell unless that supports fuzzy cards in which case yeah kinda like that for view. Except as a fuzzy storage monitor it doesnt pull items just shows approximate numbers. I am not suggesting a conversion counterpart for it That can pull oredictionary. Im just suggesting a monitor that can show approximate amounts of fuzzy materials. Either by metadata or oredict. preferably how fuzzy works currently with AE2.

**Comment by gixbit** [comment]
I realize what i said now about being able to pull too. my original intention was only to suggest what my second post is saying. But its really the fuzzy storage monitor part that interests me not being able to pull fuzzy items from conversion.

**Comment by yueh** [comment]
It might work as simple monitor, level emitters can already use fuzzy upgrades.
They would need to be a new monitor, otherwise it would not be possible to monitor fuzzy upgrades.

But it will not change anything for your bee setup as it would only sum things like tools or OreDict entries, like every different copper ingot.

**Comment by thatsIch** [comment]
Storage Monitor > Subnetwork > Storage Bus + Fuzzy == ME Interface > Main Network

?

**Comment by yueh** [comment]
Should not work. Using a fuzzy card with a storage bus only sets the whitelist/blacklist for insertion to fuzzy. Reading/Extracting will still see the actual item (not as fuzzy).

No idea if conversion monitors allow to dump items into the system, but that is the only case for a fuzzy card. For example store every cooper in network A and every tin in network B.
