### ISSUE TITLE
Facades do not have connected textures (Round 2)

### ISSUE THREAD

**Issue by Wykks** [AppliedEnergistics/Applied-Energistics-2#1107]
Same as #740

But !
I don't know how, Thermal Dynamics managed to do this : 

![connected texture cover](http://i.gyazo.com/0e78e42606b8bc10df0955aae83a2f9e.png)

(the block used are from chisel 2)

**Comment by itotallyrock** [comment]
EnderIO managed to do it as well by tricking the client into thinking it is the actual block.

**Comment by yueh** [comment]
EnderIO is not really a good example, they just choose the cheap way and just render it as a full block (making it mostly trivial). TD is similar, but it is a more sophisticated and renders a single side instead of the full block. Doing so enables them them render the conduit and facade together, but you probably also noticed that the facade textures are flat and the 1 pixel wide side is rendered as generic gray.

And this 1 px wide is extremely important, because it shows (most likely) that it is impossible to merge 2 different renders on the same side and you have to choose one exclusively.
This finally means choosing between connected textures and being able to integrate the terminals into the wall. In other words, you will not be able to see terminals with connected textures or have to live with a gap between the wall and terminal (or any other part).


But AE2 is open source. So if you have a solution, feel free to contribute and create a PR with it.
