### ISSUE TITLE
P2P Tunnel not working with ThermalDynamics Ducts

### ISSUE THREAD

**Issue by thePier** [AppliedEnergistics/Applied-Energistics-2#1138]
As written in the tilte, the P2P Tunnel does not support the tunneling with the new Thermal Dynamics Item/Fluid/Flux Ducts

**Comment by yueh** [comment]
P2P are generic tunnels not mod specific ones.
They are technically tunneling an inventory/tank/energyreciever and ducts are nothing from that list.

For example if you have a tank on the output side of a fluid tunnel and attach a fluidduct to the input tunnel it will fill the tank. This will also work with item tunnels and chests or something like redstone cells and RF tunnels instead of the tank and fluid tunnel..

It will not work with tunneling duct to duct. This would actually require a Duct P2P Tunnel.
But for now we refrain from adding mod specific tunnels.

**Comment by vScourge** [comment]
Adapting your liquid example to RF, if you put a Leadstone Energy Cell on the output tunnel, and attach a fluxduct to the tunnel input, the cell should fill with RF?  It does not... fluxducts don't connect to either input or output tunnels.  Replacing the fluxduct with an energy cell set to output power also does not fill the other cell.

I might just be using the wrong things.  I'm just looking for a specific example/setup where RF does actually move across an RF P2P tunnel.  Thanks.
