### ISSUE TITLE
not realy a bug but a weird mechanic

### ISSUE THREAD

**Issue by Aredrih** [AppliedEnergistics/Applied-Energistics-2#1139]
There a way to get this kind of render:

![100% normal](https://cloud.githubusercontent.com/assets/10573494/6886383/f86135dc-d63b-11e4-89ce-a255f2e756f7.png)

It stay permanently that way (except for the controller doing his color loop). It made by hocking this little module somewhere in the network:

![death module](https://cloud.githubusercontent.com/assets/10573494/6886386/0ff36490-d63c-11e4-8a61-898896e52489.png)

The p2p against the controller is linked to the one against the drive. Function: first, the p2p are inked together =>  the controller see each other => the controller crash => the p2p crash => the controller doesn't see each other anymore => the controller reboot => the p2p are linked together => .... For some reason, when the link is made in *that* particular order, the drive controller doesn't turn red and the module's controller just blink for a fraction of second and reboot instantly. However, the other order make the controller turn to red and waiting before rebooting.

It's not a bug, nor a feature request, but because it can be confusing (and perfect to troll btw) I judge better to just report it (I mean the blinking and unusual fast reload, not the possibility to instant kill a network when it boot)

----

Version tested: rv2-beta-21

**Comment by yueh** [comment]
Interesting, but the behaviour is actually valid. And it still cycles for me between the normal loop and broken/red controller texture.

P2P tunnels are asynchronous connection, technically only created after the underlay network works.
So what happens is, both networks join together and immediately power down because of multipe controllers. Doing this will then cut the P2P connection and make it 2 separate and valid networks again. Which will reboot them and then create the P2P somewhat later to break it again and send it into a loop.

We cannot really change the P2P tunnels, because without a working network it would be pointless to create their connections.
Maybe give the controllers a bit more time before the reset and make the broken state a bit more obvious/less likely to be overlooked?

**Comment by Aredrih** [comment]
Well my issue is that the controller doesn't seem to have broken state. The weirdest thing being the "connection order" thing which made the system behave correctly when it's the p2p on the drive which is connected first. Also, I've notice a huge lag when loading the chunk and some drive showed visual glitch:

![2015-03-29_18 48 55](https://cloud.githubusercontent.com/assets/10573494/6886632/505629c0-d644-11e4-9c99-e6cf43bbaedf.png)

Here's my view (the ticking is regular (just missing frame at 60fps) and the weird shader is because of my recorder):

![my view](http://i.imgur.com/XumEjcq.gif)

**Comment by Aredrih** [comment]
It might be just a single player glitch through...

And sorry for the 60fps-gif, it may be a bit big...

**Comment by yueh** [comment]
Any other mod like FastCraft or Optifine?

**Comment by Aredrih** [comment]
No, I just add CodeChiken core (nei util), NEI, coFH core, MFR and AE2 but it seem that removing ChickenCode core fix the issue.
