### ISSUE TITLE
Add ability to toggle crafting pattern using ore dictionary

### ISSUE THREAD

**Issue by Techjar** [AppliedEnergistics/Applied-Energistics-2#1156]
AlgorithmX2 was originally going to add this, but laziness.

**Comment by halvors** [comment]
I would love to see this :-)

**Comment by scroyall** [comment]
I was very surprised to notice that my crafting pattern for 1k ME Crafting Component is using Certus Quartz rather than Pure Certus Quartz Crystal if the latter is not available. That wouldn't necessarily be a problem, except that even when further processing steps to purify the crystals are available, they are not used. This wastes quartz, and is especially surprising given that the items in question are all native to Applied Energistics. Apologies if this has been addressed in later patches or is a property of my specific setup, but this feature would otherwise satisfactorily resolve my issues.

**Comment by Aralox** [comment]
I'm also looking forward to this being implemented/fixed 
(same issue as https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/784)
