### ISSUE TITLE
Pattern terminal convenience

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#119]
Have pattern terminals auto stock themselves with any available blank patterns in the AE system. minor feature, sorry if it was suggested already.

Originally Posted by ClockworkGod

This issue was migrated; For original details see http://ae-mod.info/Tracker/1102/

**Comment by thepaperpilot** [comment]
Since #1617 was closed, I think we should continue the discussion on how to implement this here. It sounds like there were four options to choose from:
1. That a new pattern is stored in the pre-configured slot, upon using the last one
2. That the slot is removed and the GUI is pulling directly from the network displaying something like a counter of the ones stored in the network
3. Using patterns from network as first priority, before using the internal slot storage.
4. 
    - Keep the slot
    - Prioritize the slot over the network
    - Add a "fake item" icon with the amount of the network when empty + a tooltip stating they will be used from there
    - Still allow patterns to be place into the slot once it's empty
    - Also needs some feedback in regards of security stations.

Personally I like option 4. I'm not 100% positive what @yueh meant by "feedback in regards to security stations", but I think it was about who is allowed to use the patterns inside the network, which I think should be anyone with the "crafting" permission.

**Comment by yueh** [comment]
4 is certainly the best option (which was also the old approach)

The problem here, is that it is actually not easy to obtain the amount of stored patterns in a network. Or at least it would be pretty ugly. On clientside there is only a collection of the complete network inventory, which must be searched for patterns. Certainly not nice, if you have to iterate over the whole list each tick to find the current number as caching will only be an option for static networks. Otherwise any change will invalidate the cached amount. Or some really bad workaround by making every terminal aware of blank patterns, even if they never need them.

The security terminal or in general any read only inventory could potentially report N blank patterns available, which then cannot be used. Without any indication about it. Therefore a user will only notice "have patterns, does not work".

In general it is something which should be postponed after a refactoring/rework for the whole gui/container part. Especially in the context of 1.11 or 1.12. IIRC it is actually one of the main blockers for finishing the port to 1.11. No idea about 1.12, but there is a good chance that we will not even be able to port anything crafting related.
