### ISSUE TITLE
Entropy manipulator

### ISSUE THREAD

**Issue by bookerthegeek** [AppliedEnergistics/Applied-Energistics-2#1244]
This glitch involves Applied Energistics and any mod/plugin that provides any sort of area protection. (i.e. towny, my town, GP, etc.) Yes this bug effects plugins, but is also reproducible with forge based grief prevention mods in a pure forge environment.

Previous Issue: https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/405
- Find an ore inside a claim.
- Right click that ore with the entropy manipulator and you get a ingot of the ore.
- FORGE based protection MODS will prohibit you from removing the block
- Infinite ores.

Steps to reproduce:
1. Install minecraft & Forge
2. Install latest AE2
3. Install your choice of Protection MOD
4. Find an ore inside a protected area you do not have rights in and right click on the ore.
5. Free Ores

With the understanding that I do not code Java, would it be possible to open up the right click event of this tool so that grief protection mods ( and hopefully plugins) will be able to check for player permission and block the event?

Thank you for taking the time to read this entire post and not dismiss it out of hand. And of course your wonderful mod.

**Comment by TheJulianJES** [comment]
For the ae2 devs, there is no interact event fired.

**Comment by yueh** [comment]
Can you name any forge only protection system?

**Comment by Pyeroh** [comment]
TerritoryZone : https://sites.google.com/site/reikasminecraft/territoryzone
ForgeEssentials : http://www.curse.com/mc-mods/minecraft/forge-essentials-74735

**Comment by bookerthegeek** [comment]
My Town : 

http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1287586-1-4-6-1-5-1-mytown-aperf-server-protection-and

**Comment by thatsIch** [comment]
MyTown is a Bukkit Plugin

**Comment by SirWilli** [comment]
MyTown is not the same as Towny. Towny is the bukkit plugin. MyTown is a forge mod ;)

**Comment by thatsIch** [comment]
Mh right, was missing the first line of information

**Comment by bookerthegeek** [comment]
Sorta understand (sorta as I don't Java) about the issue linked above.

But...

Is this still an issue with the full block issue reported here, or is it more of the same due to not full block breaking in the other issue? In my limited understanding the linked issue is that AE2 is not firing a break event so it cant be cancelled on things that are not full blocks. As this issue is in regards to breaking a block... I am slightly confused.

**Comment by yueh** [comment]
Mostly a similar issue.

This one is simply on a low priority. The tool is purely optional, could be disabled if actually causing issues and like nearly nobody uses it. :wink: 

For example we also call `PlayerEntity.canPlayerEdit()` before performing any action with the tool.
Why should this not be the right way to do it and any protection plugin is just sticking to an old convention migrated from bukkit to forge, but should ultimately be replaced with something else?

Forge has absolutely no documentation about it, which in my opinion means that there is simply no wrong way of doing something as long as it does not crash. Sending an event is as valid as calling `PlayerEntity.canPlayerEdit()` or whatever else is provided by forge. 
If something like `setBlock` would state that you should trigger a blockbreak event before actually calling it when it is a player or fakeplayer interaction, then this is something completely different because forge now states what is the right way.

**Comment by bookerthegeek** [comment]
Thank you for the clarification.
