### ISSUE TITLE
Cables disappearing?

### ISSUE THREAD

**Issue by furest** [AppliedEnergistics/Applied-Energistics-2#1246]
Hello
I have a medium me network (~300 smart cables for the main network) but smart cables keep disappearing! The main network is connected together using p2p tunnels but the cables connecting those tunnels don't disappear.
I have ME interfaces, busses and a room full of barrels, connected in serial with storage busses and interfaces.
The cables of the subnetwork don't disappear either.
The de-pops are happening at random intervals but on main lanes like the one connecting my kind of soaryn's super drive (with only ME drives).

I've updated to the lastest beta build (not alpha because too risky)

PS: don't blame me for not putting any log as it doesn't produce any entry ;)

Furest

**Comment by thatsIch** [comment]
Latest Beta is later than latest alpha.

Probably related https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1074

**Comment by furest** [comment]
FYI, my whole network is chunkloaded with railcraft chunkloaders ;)

**Comment by thatsIch** [comment]
I heard that like 1000 times already and still it was rarely the truth,
anyways I have no pictures, nor a sufficient description of the situation, nor a world to see it for myself. Not sure, how I am supposed to help here.

**Comment by astronouth7303** [comment]
I am seeing this issue, too. AE Multiblocks (cables+buses+interfaces) will disappear at random. This has never happened to me before, and it's not happening to anyone else on the server (even those with larger setups).

Also, once (so far), one of my ME drives disappeared.

AE2 Version 1.5.9 for 1.7.10.

I can confirm that it was not an explosion (no creepers, no explosion sounds, and the server has block breaking turned off). It might be a serialization issue, since I've only noticed it when logging in. Except that the ME Drive disappeared while I was logged in.

**Comment by wlhlm** [comment]
> AE2 Version 1.5.9 for 1.7.10.

This doesn't seem to be a valid AE2 version, please check again. Examples are rv2-stable10 or rv3-beta5.

Also check for other mods that alter Minecraft rendering like Optifine or Fastcraft and see if the problem goes away when you disable these mods.

**Comment by astronouth7303** [comment]
> This doesn't seem to be a valid AE2 version, please check again. Examples are rv2-stable10 or rv3-beta5.

Oops, it's rv2-stable10. Not sure how I read the wrong JAR file.

> Also check for other mods that alter Minecraft rendering like Optifine or Fastcraft and see if the problem goes away when you disable these mods.

Would this still cause problems in multiplayer, on the server? It's not just that the cable looks disconnected, the network is actually segmenting and stuff isn't connected anymore.
