### ISSUE TITLE
Accessing ME Chest doesn't trigger logBlock container history record

### ISSUE THREAD

**Issue by Paronity** [AppliedEnergistics/Applied-Energistics-2#1309]
Several plugins have this issue, and one that DOES work is IronChest.

The difference in the ones that do work and the ones that don't is that the access method doesn't leverage the onContainerClosed override, but my specialty is NOT JAVA so I'm just guessing. :)

Just thought I would throw it out there. Let me know if you need anything else.

**Comment by thatsIch** [comment]
What is `logBlock` supposed to be? Throwing around with half-knowledge won't help us fixing the problem. IronChest is a bad example, since it basically is nothing but a fancy vanilla chest.

And just by the information I saw, you request us providing support for a dead service, which is not supported by Forge, where we are a Forge Mod and not a Bukkit Plugin?

**Comment by Paronity** [comment]
Wow - didn't realize I had to have the solution to post a potential bug. I won't try again. Sorry for wasting your time.

**Comment by thatsIch** [comment]
I never said anything, you requiring to provide the solution. You are just saying something about `logBlock` without a context and just from my knowledge, I must assume, you talking about some random Bukkit Plugin, which is a dead service for about 5 month (for Forge).
