### ISSUE TITLE
Please refer to RecipeSorter

### ISSUE THREAD

**Issue by RAnders00** [AppliedEnergistics/Applied-Energistics-2#1333]
`[12:53:15] [Client thread/INFO] [FML]:   Unknown recipe class! appeng.recipes.game.DisassembleRecipe Modder please refer to net.minecraftforge.oredict.RecipeSorter`

This appears on loadup, but does not crash.

**Comment by thatsIch** [comment]
Its because you probably disabled some AE2 features, related to the disassembling?

**Comment by yueh** [comment]
It is just a notice produce by forge for whatever reason. Maybe as preparation for 1.8.

As long as it does not crash, or actually outputs a request to use it instead of `would be nice if you do not use it. But there might be some actual use cases left, then use it`, I do not think that spamming the issue tracker of every mod is really needed.

**Comment by thatsIch** [comment]
its actually a valid warning, since this was changed in 1.6.2 already.
