### ISSUE TITLE
Crash on shift-click in terminal with NEI delete enabled

### ISSUE THREAD

**Issue by Tergiver** [AppliedEnergistics/Applied-Energistics-2#1343]
Steps to reproduce:

1) In NEI options switch to either cheat mode or utility mode with the trashcan option available.
2) Toggle the trashcan on (left-click the trashcan icon).
3) Open an ME terminal (I was using a crafting terminal).
4) Shift+left-click an item in the terminal.
-CRASH-
Note that left-clicking an item in the terminal does nothing (including crash), only shifted.

**Comment by yueh** [comment]
Cannot reproduce, also no log.

**Comment by Tergiver** [comment]
Oops, the order is this (trashcan toggles off when opening an inventory GUI):

1) In NEI options switch to either cheat mode or utility mode with the trashcan option available.
 2) Open an ME terminal (I was using a crafting terminal).
 3) Toggle the trashcan on (left-click the trashcan icon).
 4) Shift+left-click an item in the terminal.

And the "crash" is not a process crash, it dumps you out with the message:
Connection Lost
A fatal error has occurred, this connection is terminated

So I think the 'server' is crashing? I'm playing single-player.

**Comment by TheJulianJES** [comment]
Please send in the minecraft/logs folder "fml-client-last" and "fml-server-last" (or something like that).

**Comment by thatsIch** [comment]
The general idea is, NEI is trying to delete EVERY item in the inventories you are currently looking at (player inventory, network content etc) That way it is basically hacking into any container you are looking it and **forcefully** removes the content.

Not sure, if we really want to support that, since this can only happen in creative mode + trashbin mode.

**Comment by yueh** [comment]
Could reproduce it. It is caused by NEI triggering an `IndexOutOfBoundsException`, because it does not validate that the slot is actually existing in the container and not just a fake for the GUI (like ours).

So nothing we could really prevent. It is probably a very rare case and might be only happening with AE2, but NEI should really validate the data instead of throwing exceptions.
