### ISSUE TITLE
Silk Touch Annihilation Planes

### ISSUE THREAD

**Issue by Infinitoa** [AppliedEnergistics/Applied-Energistics-2#1344]
Hello everybody,

on my server, I usually use a CC controlled frame with annihilation planes on it to make a quarry.
What I would love to be able to do is have a card for the annihilation planes that makes them pick up the blocks as if you're using Silk Touch and/or Fortune perhaps.
This would greatly improve the efficiency of frame quarries built in such a manner. 
For balancing reasons one could make the recipe require loads of resources if this seems too overpowered of a feature.

What are your thoughts on that? Would it be too difficult to implement due to the way the annihilation planes are coded? =)

Sincerely, 

Infi

**Comment by thatsIch** [comment]
Need to think about it

**Comment by yueh** [comment]
I doubt adding a a high resource cost to it is a good idea. When someone is able to build a large frame quarry, resource are not really a limiting factor anymore. And there are way easier ways to obtain infinite resources.

If it should probably be a way higher energy cost.
Also how to apply the upgrade? The moment we add a GUI to it, we will open the door for constant request to add a filter because the GUI is already there.

**Comment by thatsIch** [comment]
Maybe something like upgrade by applying an upgrade card to it which makes it render differently and upon wrenching, it drops the old plane and the upgrade?

**Comment by TomeWyrm** [comment]
Make it pink!

Seriously though, thatsIch's idea of applying it in-world, changing the in-world appearance, and skipping the GUI is both easier for future feature requests, and honestly simpler for the user. I so wouldn't want to check all the planes on a large frame quarry for silk touch individually by looking at a GUI... I've had to do that for parallelized processing machines... it is SO not fun

The color-change suggestion of the face is actually a great place to put that visual difference... the pink was a bit of a joke though :-)

**Comment by yueh** [comment]
In-World interaction would be quite nice, but is highly inconsistent with every other part.
Either every upgradable machine should support it or none to be consistent. So it would need some preparatory work to rework upgrades in general. Removing an upgrade will then still be a bit inconsistent as it would still be GUI based or not be really precise, like only being able to remove the upgraded added last per interaction. At least if there is no in world representation of the the upgrade cards. Thing like the color codes of EnderStorage.

Bulk changes could also be done with something like #1382. Even if it would still be a GUI based approach for upgrade a single one.

**Comment by thatsIch** [comment]
I have a FR somewhere (cant find it atm) where upgrades can be applied as in world interaction, that may be a stepping stone for that.

**Comment by TomeWyrm** [comment]
I don't know, consistency for the sake of consistency seems like it's hobbling you. If there's only one upgrade possible to apply, then why waste the coding time to add a GUI and in-game time to access it? Especially when changing the render ala EnderStorage color codes would (I assume) be trivial to implement and have the end-user understand.

Besides, you already have in-world crafting. In-world interaction with simple machines isn't THAT far of a stretch.

**Comment by thatsIch** [comment]
The idea of AlgorithmX2 was to refrain from using colors for coding information. 
There are a lot of people out there, which for example have red/green weaknesses.

**Comment by TomeWyrm** [comment]
Hmm, point.
Changing the pattern on the plane?

**Comment by Alaberti** [comment]
Why not add a config setting? At least for silk touch, that seems feasible based on its current functionality.

**Comment by TomeWyrm** [comment]
Honestly, I don't want all my annihilation planes to be silk touch. There are a lot of times I want more traditional block-breaker functionality.

**Comment by Deshiba** [comment]
*I was working on an AE2 resource supplied auto-fortune contraption, which failed because the annihilation plane broke the certus quartz ore before my autonomous activator could break it. I can think of other ways, but having the option to fortune/silk touch with annihilation planes would be preferable.*

Anyway, the many requests for a GUI on the a-plane got one answer: "Use the ME-Interface..." ... to filter specific blocks. So maybe an option would be to add upgrade slots to the interface and make a card for annihilation/formation planes specifically?

Or maybe even a 'plane-interface' to govern both annihilation and formation planes so we can finally have plane equality.

/5cents
