### ISSUE TITLE
Level emitters or export buses sometimes misbehaving

### ISSUE THREAD

**Issue by JamMasterz** [AppliedEnergistics/Applied-Energistics-2#1363]
Hey there. I have an autocrafting setup that exports needed materials into Inscribers when the amount of processors gets low. I did it with export buses and level emitters. It works perfectly when i keep my eye on it, nothing is exported if there is enough processors, but after a few days, the system collected thousands of processors of each type (i had it set to stock 200 max). You can imagine this is an issue with Engineering processors. This is probably because either the emitters sometimes bug out and give a redstone signal when they're not supposed to, or the export buses that don't react to redstone properly. The area is on a server loaded all the time with chicken chunks loader.

I do realize this is a really hard thing to reproduce, but i just wanted to put it out there so that you are aware of the issue. AE 2 rv2 beta 8

**Comment by Gowcu** [comment]
I am having the same problem and i believe i have figured out why. I believe that the level emitters arent staying loaded when the chunk loaders are active and no one is physically there, but the rest of the system is, so for the time that you are away from your base, the import/export buses act as if there is no redstone signal because the level emitters are unloaded.

AE2 rv2 beta 8

**Comment by XFactHD** [comment]
Why are you still using beta 8? The newest version is beta 30.

**Comment by yueh** [comment]
Update AE2 and I would also recommend not using chicken chunks. We have encountered enough bugs caused by them, because they do not load the chunks in a reliable way. 

Under some circumstances they are not constantly keeping a chunk loading but it looks more like they are constantly reloading the chunk. Thus the level emitters or other parts of the network will be unloaded missing potentially notifactions about finished crafting or reaching a level as they are either no longer part of the same network (chunk with a cable connecting them gets unloaded) or are unloaded themselves.
