### ISSUE TITLE
Infinite power with Rotarycraft

### ISSUE THREAD

**Issue by jeremiahwinsley** [AppliedEnergistics/Applied-Energistics-2#1384]
The Energy Acceptor and ME Controller can produce infinite power with no input. 
I'm using version rv2.beta build 32 of AE2, and version v6f of RotaryCraft, in single player.
Steps to reproduce:
- Place down an Energy Acceptor and a RotaryCraft power source.
- Once the power is going into the Energy Acceptor, use a Screwdriver to rotate the RotaryCraft power source. 
- Now remove the RotaryCraft power source. 
- With a Network Tool, you should see the Energy Acceptor producing power by itself.

**Comment by thatsIch** [comment]
Sounds more like a RtC issue to me, waiting for Reika to respond, will test it later on eventually.

**Comment by yueh** [comment]
The best idea is probably to throw the current implementation away and just use `SimpleShaftPowerReceiver`.

**Comment by thatsIch** [comment]
hardly applicable if you read the descripton and  methods

**Comment by thatsIch** [comment]
https://github.com/ReikaKalseki/RotaryCraft/blob/master/API/Power/PowerAcceptor.java

might be better

**Comment by thatsIch** [comment]
cant look it up atm which is more appropiate since looking at github is just meh

**Comment by yueh** [comment]
I think `PowerAcceptor` is not intended to by implemented directly. At least I would read the documentation so. So we still need to implement `ShaftPowerReceiver` and everything from `ShaftMachine` (even with `PowerAcceptor`).

`SimpleShaftPowerReceiver` is just the 'dump energy here' interface, without caring about torque and the other things (which is what we are currently doing).

**Comment by thatsIch** [comment]
Just tried it and RtC is not reacting like it used to be in v5, so I assume its a bug in RtC, neither is it disconnecting itself from the energy acceptor, nor is the industrial coil working in creative mode.

**Comment by jeremiahwinsley** [comment]
@thatsIch Have you taken this up with Reika, or should I post an issue on his tracker?

**Comment by thatsIch** [comment]
@jeremiahwinsley I tried, but no response.

**Comment by ReikaKalseki** [comment]
For one, last time I checked, AE is still using the version of the RC API from before I changed it more than 6 months ago.

Two, you do not want `SimpleShaftPowerReceiver`, as per the javadoc:

> unsuitable for actual machines due to the total lack of sensitivity to the amount of power

Three, the methods are called every tick both client and server side from the machine `updateEntity()`. Seeing as AE works with energy, not power, the only way you can have a "persistent" power source is by adding to the energy buffer yourself in your own tick, rather than letting the method add energy.

**Comment by yueh** [comment]
I have mostly glanced at the API and only later realized that the `SimpleShaftPowerReceiver` is just a boolean. But it would be perfect for us, if it would just be a similar interface with a int power. All the other things (especially the render stuff) is not really needed for us.

The documentation did not say anything about being called once per tick.
It even looks more like a static system, which only recalculates when something changes and not necessarily once per tick. Which on itself would be quite nice to save performance, but sadly is not true and just recalculated every tick.

**Comment by ReikaKalseki** [comment]
What you want is `AdvancedShaftPowerReceiver`, added in the update 7 months ago.

It also has the doc you claim does not exist

`Implement this instead of {@link ShaftPowerReceiver} for more advanced and dynamic control over the power reception capabilities
 * of your machine. To use this, you must implement the methods as you see fit but also set the power to zero at the end of the tick, allowing
 * for it to be set again if the machine remains powered or drop to zero if not. If your intent is purely to receive power for conversion
 * purposes, you may be able to forgo this, instead just adding to the internal buffer each time addPower is called.`

`Called every tick to add power at a given torque and speed, to a given side. For a block receiving multiple inputs, standard RC behavior is to sum the torque of all the inputs at the highest speed and ignore all others (eg 512@32+256@256+64@256 = 320@256) Depending on the intended function and "in-universe" mechanics of your machine, you may choose to do this or do something else. For those using the mechanical power directly (as opposed to internal conversion into a more nebulous form), it is strongly recommended to use the RC summation procedure for the sake of consistency and realism.`

**Comment by yueh** [comment]
Yes `AdvancedShaftPowerReceiver` documents it is ticked. But none of the others or that they need to be reset.

**Comment by ReikaKalseki** [comment]
Depending on the implementation, they may or may not. For yours, they do not.
