### ISSUE TITLE
Ability to extract energy from AE

### ISSUE THREAD

**Issue by HexagonalDiamond** [AppliedEnergistics/Applied-Energistics-2#1391]
I was thinking about power converters and I came up with the idea for an Energy Supplier in AE. It can be used to power machines with AE power. In fact, it could even go so far as to use AE cables for power supply without an extra block. I could probably implement this myself, but I just wanted to hear thoughts.

**Comment by thatsIch** [comment]
Its fine as an addon, but not meant in AE2 itself. 

AE2 is not a power converter, but if you want to add it as an addon, the API should supply you with everything you need.

It is not advised to use them directly as energy suppliers. I think EnderIO has a better approach to them, especially since you lack the control of parts (no redstone control or similar possible). 

Having a part which acts like the opposite of the Energy Acceptor is probably.

**Comment by Entoarox** [comment]
With energy based p2p tunnels I dont really see the need for a separate power export block, especially since adding it would bring back at least some of the "a single cable for everything" behaviour of AE1
