### ISSUE TITLE
Security Terminal upgrade suggestion:

### ISSUE THREAD

**Issue by kutsuukun** [AppliedEnergistics/Applied-Energistics-2#1393]
I play on a large server and have quite a few people on my security terminal, mainly because its the most advanced one in our town(we use towny), and every now and again I notice that I'm out of something I thought I had a bunch of, or have a bunch or resources I didn't have before. Could you somehow make an upgrade for the Security Terminal or maybe a ME Security Monitor so that people who utilize the Security Terminal can see who has been taking things or putting things in?

Something like these:
![](http://img8.mmo.mmo4arab.com/feature/swtor/120405guild_banks_vehicle_achievements/guild_banks_vehicle_achievements05.jpg)

![](http://3.bp.blogspot.com/_A0Fn7CNAyZo/SxJMEv1QExI/AAAAAAAADtA/JQ9wE_3D46M/s1600/gbank_log.jpg)

**Comment by XFactHD** [comment]
I don't think that this is possible because of the immense storage requirements needed to save the list (just look at the fml-latest-log of a modpack with 200 mods or more and you get what I mean).

**Comment by yueh** [comment]
The fml-latest.log is probably small compared to the requirements and the usual MMO logs are a an extremely tiny fraction of what we produce. I would not be surprised when AE2 produces the amount of log entries, their banks generate in a week or month, every couple of seconds on more frequently used systems.

I remember a similar issue here and someone mentioning the idea of making an AE2 addon for it.
But I cannot find it currently.

**Comment by thatsIch** [comment]
I think we already have a similar FR somewhere..

**Comment by Entoarox** [comment]
You could easily limit the log by making it so only manual insert/removal is logged (as editing the network is a separate permission) and having a separate permission to have logging of certain users ignored. (Unmonitored Access?) and you could aggregrate it so multiple transactions by a single user in a certain timespan (say 1 minute) are aggegrated so that in cases of crafting it doesnt show 'removed 5x blabla, inserted 1x blabla' or similar, and so you can add only a single "user X removed Y and inserted Z" (omitting the "removed Y and" or "and inserted Z" as needed)

**Comment by Jonis326** [comment]
it wouldn't have to be in a txt (.log) you could literally make a .jar or someting of the sort to keep the log. How does the mod know what is in your ME network when you have a shit ton of stuff.. its not stored in a .txt file

**Comment by ruifung** [comment]
The storage requirements shouldn't be that bad if you are storing data in a non human readable format,  And with compression too (GZipOutputStream maybe?)

**Comment by Entoarox** [comment]
@Jonis326 The network only knows what is in the network while the server is running, the log would have to persist in some fashion between server reboots to ensure that no logging disappears.

@ruifung The log would likely have to be in NBT format, storing the UUID, a list of 'extracted' and a list of 'inserted' itemstacks just like they are stored in the player.dat files.

**Comment by ruifung** [comment]
@Entoarox There is no reason the log cannot be in some arbitrary format. Also, if I remember correctly AE2 doesn't actually use UUID internally?

**Comment by Entoarox** [comment]
@ruifung Using a custom format would mean that they would have to write a system to convert stacks into their custom format, while a system for NBT already exists, and NBT is a relatively small format anyway, it is just somewhat slow to convert to/from, but the server can easily keep the transactions in memory untill the world save happens, and then write the changes to file.

**Comment by ruifung** [comment]
*shrug* Writing stack data to a simple format isn't too difficult, write the item name, write the amount. You pretty much have to do the same thing with NBT when you read it back into whatever data structure is used to represent the data.

But yeah, using NBT would allow the server itself to handle persistence data for it.

But personally, I feel that NBT isn't well suited to storing transactional records as its mainly working with key value pairs. Although you could probably use a NBTTagList though. But then you would still have to read all the NBT data into whatever format you use to represent it in memory though.

It would be about the same amount of work as using InputStream and OutputStream though. (IMO)

**Comment by yueh** [comment]
Limiting it to just log manual entries is pretty stupid. Players will just attach an export bus or similar and it will never be logged. 

So we need to log every single change inside a network and this is where it starts to get ridiculous.
32 bytes per entry is way to less. It cannot store how much was extracted/inserted, who did it and even when.

It needs at least these values:
* Item ID (int, 32bit). The internal ID not the String based, these can easily be 10-20 chars each with 16 or 32 bit per char
* How much (64bit), AE stacks use long as size
* Who (64bit), the internal mapping of long to a GameProfile. The sign could be used with some bit trickery to encode player or machine
* When (64bit), simple timestamp

Resulting in at least 224 bit, which could be easily extended by things like which machine and its location, probably doubles it at least.

An enderquarry for example can produce 9 stacks per tick. Add automated ore processing to it and can easily produce a multiple of it (ore imported, ore exported, ingot imported, etc) and some general background "noise" like any farm, keeping the power gen running on charcoal etc.
Assuming a couple of dozen or even few hundred events per tick for a smaller server is probably not a bad estimation and can easily produce a couple of GB per day as log. Large servers (or even just some players mostly hoarding stuff) can easily produce a multiple of it. By just looping stuff it will also be a nice denial of service. Except when using something like a round robin database/circular buffer. But I doubt a log being overwritten after a couple of minutes is helpful.

Which is also a nightmare to seek any information in it, potentially with a huge performance impact on the server. So a real database might be more feasible and allow some more information to be stored without exploding the size requirements like storing the actual item id in another table, some more information about the machine, etc. But the required information will not really be smaller, most likely even a bit larger (the usual tradeoff between performance and size)

**Comment by ruifung** [comment]
I expected my wild ass guess to be off, but not off by that much. But yeah, NBT isn't really suited for logging like this.

**Comment by Entoarox** [comment]
@yueh Logging exports and such would quickly bulk out any player actions in a large network, further, since this is intended to be part of the security system, you are supposed to block people you want to log transactions for from editing your network anyway.

The log would only need to store transactions through terminals because its supposed to be part of the security terminal, a way to see if a player abused their access to the items in your network quickly and easily.

If you aggregate the entries over a short period so that equal removal & insertion cancel out and do not show up in the log, and that multiple transactions by a single player are summarised into a single entry it could be reasonably small.

Below is my idea of the tree you could use:
```
TAG_Compound: Root
    TAG_Compound: Networks
        TAG_String: Network name (Dynamically generated by the security terminal upon placement)
            TAG_Int: Player
            TAG_Int: Timestamp
            TAG_List: Insertions
                 -Unindexed stack compounds-
            TAG_List: Extractions
                -Unindexed stack compounds-
TAG_End
```
You can then have a quick overview (List of entries with "Player X inserted Y items and extracted Z items.) that upon clicking then shows a detailed view of that transaction, with the actual stacks for each and every item inserted and/or extracted in inventory grids.

I honestly feel you are thinking of this in a much more complex fashion then is needed, since its supposed to be a method of checking interactions by players, not the machines.

**Comment by yueh** [comment]
So if someone uses an export bus or interface to "steal" something, you find it ok to not log it?

**Comment by Entoarox** [comment]
@yueh Isnt that the whole point of the permission for network editing?
The ability to edit the network is in itself already a great trust (Since they could abscond with your entire network, not just the contents) And it also wouldnt help a single thing if you have "Export bus into Diamond chest extracted all your diamonds" as a log, since it still wouldnt show you the culprit, just that it happened (And an absence of diamonds should say enough there!)

**Comment by yueh** [comment]
Permissions are not really important here, as creative use of game mechanics or mod interaction can circumvent them. So it boils down to as long as your culprit is creative enough to prevent being caught, you are fine with it. Which is certainly an interesting gameplay concept but probably not what most are expecting.

Also not all interactions are all player based, like requesting crafting will be a machine extracting the items from the network. So it can get quite complex about what things need to contribute to the log.
Also AE2 addons will then not be covered. Maybe there is a bug in one of the addons, which ignores the security protection (like Steve's Addons, but this is on another level). If we log every extraction/insertion, we could also identify faulty machines as they will be logged. This is more or less the only level we have control over any addon and being able to monitor them. Every more selective solution, will need the addon to actively support it and also be required not miss anything.
Or another example is that interfaces will happily import anything you pipe into them, even with a security station. Say if someone tries a denial of service and overflow your network with cobble.
If we log it, at least you would know which interface was responsible for it.

Sure it might not catch the actual culprit, but if you know the time and maybe who was online around that time you might be able to narrow it down enough or at least be able to build a better protection.

**Comment by ruifung** [comment]
So how would you store all this data on a server with a lot of active ME networks?

**Comment by yueh** [comment]
That is the question, we would even have to actually serialize the whole itemstack, as it is not that uncommon that items/blocks are now using NBT data to indicate their real function, which can be way more data. 
Just imagine some bag type stuff, which can easily accumulate a couple of KB for a single bag. We could do some deduplication, but if someone does something like "export the bag, import it, put 1 cobble in, loop" it would be a nice way for denial of service. Just 1 bag looped every tick with 1 KB would accumulate about 1.7 GB per day.
For example we already had issue with some network inventories breaking the limit of 2 MB or so per packet, I cannot remmeber the exact circumstances, but it might be even a single item causing it...

**Comment by Jonis326** [comment]
@Entoarox I don't need to know what is in a ME network while the server is down. What is the point of that???

@yueh Don't you tell people to get grief protection because the security terminal doesn't protect griefing? If that is in place, then export bus attached to your ME network is a moot point because it will never happen. All I would be looking for is a minimal log if someone on the server had a hard decided to snag all the diamonds or shiny ore from you ME network. I mean I guess you could even limit it to specific items logged. You could do this kind of like the way the way you tell a inport/export bus what to pull out and it would only log those items.

**Comment by ruifung** [comment]
@Jonis326 If something isn't prevented in the code, inevitably someone will end up doing it, (That's just my approach to programming stuff)

But @yueh, if its just logging items in and out, wouldn't it be possible to just store the unlocalized name instead? Since even NBT based items will still have seperate unlocalized names, I think?

**Comment by Jonis326** [comment]
@yueh. You bring up a nice example with the cobble. People should really get Deep Storage Units for their ME network tough. They would totally save your ME network getting dumped on.

**Comment by Jonis326** [comment]
@ruifung Who doesn't use at least 1 Reika mod.... They should get Territory Control it will prevent damage to an ME network.

**Comment by yueh** [comment]
@ruifung Not really as the unlocalized name could just be something like "GenericTileMachine". There are just enough mods devs around doing strange things because it somehow works and allows them to save one ID number or so.

Also you cannot distinguish, if the player A took that bag out and emptied it and placed it back or was it one of the other 10 players doing the same. Not all bags are showing a tooltip with their content, but at least you could provide a fake itemslot to copy that item in creative (if we would fully serialize each itemstack).

If you look at #1077, this was a single item exceeding 2 MB when serialized and this is the crap we need to consider. We even do not know the exact size, so it might be somewhere between 2 MB and 16 MB.
Just imagine someone loop an item with 2 MB each tick. Which is easily in the area of a couple of TB per day. Even with some serious deduplication it will create a ridiculous amount of data, even when allowing to only log a couple of user definable items. Someone will abuse it and just let it monitor bags.

The normal inventory is pretty basic as it will only allow one item to always exist, so it will always be 2 MB large. Also AE is already deduplicating NBT data, so even 1 million of them will still be 2 MB. 
Doing any change to it will simply erase the old and replace it or it is just to expensive to generate them with a serious frequency as it is still limited by ingame mechanics.
But once you start to log it, you will make a copy of them and just accumulating more and more data.

**Comment by ruifung** [comment]
Wouldn't doing that for the unlocalized names break the display names?
