### ISSUE TITLE
Ae2 lag

### ISSUE THREAD

**Issue by johnny112** [AppliedEnergistics/Applied-Energistics-2#1394]
I play on a server that has 3 active players (all friends) with enough ram (about 4-5gb) and whenever I try to craft a stack plus of items in the crafting terminal in creates lag for everyone on the server and takes about 5-10 seconds to finish crafting. If I happen to craft around 5 stacks or around that, it'll lag everyone out besides the person crafting the stuff and the server will lag for a good 20 - 30 seconds. I'm running my ME System on about 6 channels and I'd like to know if there's a way to fix this. Btw, pretty new to AE2 so don't get annoyed by my noobiness

**Comment by thatsIch** [comment]
means the CPU of the server is not handling it well. If you still think it should be sufficient, send us a profile 

---

http://ae-mod.info/profiling/

**Comment by XFactHD** [comment]
I don't really think it's a cpu problem, but a ram problem. I am playing a big modpack (about 200 mods) in singleplayer with 10gb of ram and when I play for 2 hours or more, my ram starts to heat up and any manual crafting operation lags the hell out of my computer.

**Comment by thatsIch** [comment]
as long as you do not craft anything with a wire cutter..
maybe you should also send a profile, when that is happening.

**Comment by XFactHD** [comment]
I don't think that in my case it is how ae2 works but the combination of a extremely huge me system and a computer that heats up and looses performance. Also, I once tried to make a profile because of an ic2 reactor controlled by EnderIO redstone conduits and setting the profiler up and running it costed a very long time and I couldn't get a profile out of the profiler.
