### ISSUE TITLE
Crafting terminal huge server freezes

### ISSUE THREAD

**Issue by vlad20012** [AppliedEnergistics/Applied-Energistics-2#1448]
![123](https://cloud.githubusercontent.com/assets/3221931/7590688/51e54d92-f8d2-11e4-8c17-9146b1ae6af9.png)

Shift+click in crafting terminal performs (number_of_items_in_crafting_grig)*stack_size calls of Platform.extractItemsByRecipe. MEMonitorHandler.hasChanged sets to true and next calls MEMonitorHandler.getStorageList.

As result, 300ms per one shift+click - common occurrence. I can click faster than 3 clicks per second and... =)

And what do you think about this patch:
MEMonitorHandler.notifyListenersOfChange:122 replace `this.hasChanged = true` to

``` java
        for(StackType d : diff)
            cachedList.add(d);
```

We keep cache valid without full rebuilding.

**Comment by yueh** [comment]
If you want that any user can dupe items, this will create a good way for it. Otherwise I think you know the answer.

**Comment by vlad20012** [comment]
I will be very grateful if you explain the dupe mechanism.

**Comment by yueh** [comment]
It will no longer post the changes to any listener and updating their states/caches/whatever, so actually it would even break more things.
Like Terminals will no longer work, the autocrafting status and probably subnetworks.

Duping might be a bit hard and involve something using the invalid cache. I cannot remember anything in AE2 itself would do this, but an addon might.
Nevertheless as you will no longer be able to access the items/crafting through terminals, it will probably be hard to actually exploit it.

**Comment by vlad20012** [comment]
>> It will no longer post the changes to any listener

No, why, I did not break any code that post changes into listeners.

**Comment by yueh** [comment]
It is just posting invalid data to the listeners, basically making it usless and thus can be considered as nothing at all.

If we just extract a single item from the network, it means the cache is invalid because we cannot assume that this the actually extracted amount. For example you can hook up multiple barrels with bspace upgrades and this will report a multiple of the actual amount. So extracting 1 item, could for example actually result in 8 items missing from the network. So we actually have to revalidate it again.
And as the listener will use the cachedlist it will propagate this invalid cache to every listener.

**Comment by vlad20012** [comment]
OK, thank you very much for your answers.
Let me know if there are other ideas to solve this problem.

**Comment by yueh** [comment]
Also it should only rebuild the cache in the lowest storage grid and then propagate a diff of the actual changes upwards. But the larger the networks gets, the more data it needs to revalidate. (In other words P2P tunnels are probably bad for servers)

If you actually want to improve the performance, it needs to be handle on a higher level.
Mostly `Platform.extractItemsByRecipe` and `SlotCraftingTerm.craftItems()`. For example instead of extracting 576 iron ingots piece by piece, try to extract them at once and use that to craft and deal with the overflow if it extracted less materials as requested. But this gets really tricky once the oredictionary needs to be considered. Overall there might be enough ingots of a single metal to craft a stack of blocks. But that might be scattered over 9 different mod ingots and needs to constantly extract another type until it has enough for a stack.

I already considered rewriting it, but once it has to deal with the oredict or more complex recipes, it really looks like reimplement the planner for autocrafting itself, just without patterns.
Even considered using a constraint satisfaction solver, which be even used for the normal autocrafting, but time..

**Comment by vlad20012** [comment]
This solution is too hard for me =D

I wrote totally BS hack and hope, that it will work.

MEMonitorHandler.notifyListenersOfChange:122
```java
	protected void notifyListenersOfChange( Iterable<StackType> diff, BaseActionSource src )
	{
		if(um_is_crafting)
		{
			for(StackType d : diff)
				cachedList.add(d);
		}
		else
		{
			this.hasChanged = true;// need to update the cache.
		}

		...
```

SlotCraftingTerm.doClick:133
```java
if(isinst)
		{
			MEMonitorHandler<IAEItemStack> memon = (MEMonitorHandler<IAEItemStack>)inv;
			memon.hasChanged = true;
			memon.um_is_crafting = true;
		}
		
		for( int x = 0; x < maxTimesToCraft; x++ )
		{
			if( ia.simulateAdd( rs ) == null )
			{
				IItemList<IAEItemStack> all = inv.getStorageList();
				ItemStack extra = ia.addItems( this.craftItem( who, rs, inv, all ) );
				if( extra != null )
				{
					List<ItemStack> drops = new ArrayList<ItemStack>();
					drops.add( extra );
					Platform.spawnDrops( who.worldObj, (int) who.posX, (int) who.posY, (int) who.posZ, drops );
					return;
				}
			}
		}
		
		if(isinst)
		{
			MEMonitorHandler<IAEItemStack> memon = (MEMonitorHandler<IAEItemStack>)inv;
			memon.hasChanged = true;
			memon.um_is_crafting = false;
		}
```


So we recounting cache before and after crafting, but while crafting we updating cache direct.

**Comment by yueh** [comment]
That does not really work. Revalidating the cache is probably the only thing, which can never be removed or disabled.

Just consider this setup.
You have 2 barrels with bspace upgrades each attached to their own storage bus holding 8 copper ingots and chest with a single leftover copper ingot from another mod. So overall 9 ingots and enough to craft a copper block. But the barrels will report the double amount, so the system will actually see 17 copper ingots. If we do not extract each ingot on its own and just use the cache, we will never realize that we have run out of copper ingots from the barrels after extracting 8 in total and need to fetch the leftover one from the chest.

**Comment by vlad20012** [comment]
OK, now, I fully understand what you mean.
But I think those small inconveniences (manifesting only during crafting in terminal) pale in comparison with lags created by CraftingTerminal...

**Comment by vlad20012** [comment]
Update:
We have tested your setup on our test server with my patch. No any bugs. I see 17 items in storage. After craft it fills crafting grid and empty storage (gets one item from chest, yes)

Thanks for all your answers.

**Comment by yueh** [comment]
It will probably work in most cases. It is more about some corner cases in more complex networks.
Maybe something like using a level emitter to keep a certain amount of yellorium available to power the Big Reactor. Then crafting some more reactor blocks (using yellorium) might cause the level emitter to miss the notifaction and not activate the export bus to craft more until the whole system runs out of power.

Overall there are not that many reports about this particular issue. But we would trade this with potentially hard to track down issues. Basically who would suspect that crafting some reactor blocks yesterday caused the level emitter to break. It would just be a "level emitter broke randomly" issue.

**Comment by xanderc2** [comment]
same issue but with much longer delay, something like 15s each craft and 20s for add a new channel, while server running great even with insane spam of non ae machines
version: rv1 stable/forge 403
server running with 12% cpu usage and i'm the only player

**Comment by XFactHD** [comment]
@xanderc2 update your AE2 to the latest version (rv2 stable 3).

**Comment by xanderc2** [comment]
sorry, missclicked on keyboard, yes i am using rv2 stable 3

**Comment by vlad20012** [comment]
I use my solution 16 days in production, no any problems.

**Comment by brunyman** [comment]
I confirm this issue on SkyFactory2 modpack with mod version appliedenergistics2-rv2-beta-28 .
I was getting random timeouts and could not find the source until i got a report from a player.

Everything is recorded in this video:  https://www.youtube.com/watch?v=_FucHAxq6XY

This is a major issue and should be fixed asp, or was it fixed an a newer version?

**Comment by thatsIch** [comment]
Please no double post
