### ISSUE TITLE
Seared Bricks not storable by Spatial IO

### ISSUE THREAD

**Issue by JigglesTheFett** [AppliedEnergistics/Applied-Energistics-2#1455]
So, in creating a 'smithy' type area to be stored on a spatial IO drive, I realized that it does not take seared bricks from the Tinker's Construct Smeltery. It does take the other components, the controller, the tanks, the drains, etc. Just not the Seared Bricks that are the main component of that. I am using the newest version of both, and didn't see any other issues like this.

**Comment by yueh** [comment]
If they are not moved by SpatialIO, this means they are TileEntites but are not whitelisted to be moved.
Some TileEntites do not like being moved around. So instead of just moving them and potentially corrupting your world, AE2 will just leave them in place.

Tinker's Construct has its own AE2 integration and does whitelist some blocks. So I would assume they just missed these blocks. Therefore I would recommend to inform them about it. Maybe some other blocks too.
