### ISSUE TITLE
Feature Request:

### ISSUE THREAD

**Issue by Badcholo** [AppliedEnergistics/Applied-Energistics-2#1514]
A way to get access to an inscriber press other than finding them.
Another way to get skystone without meteors.
Craftable Inscribers press: maybe a single use craftable stone/iron inscriber press.
Craftable Skystone:
Or Skystone that spawns underground like ores.
I didn't like the craters So i removed them. All of them get found and none are left for players. it removes the skystone but it is used for crafting. Craters just destroy the land and i didn't like that.

**Comment by yueh** [comment]
Already possible with [custom recipes](http://ae2.ae-mod.info/Custom-Recipes/) and config options.
Maybe not Skystone as ore, but you can make it craftable. Or use something like cofhcore to spawn it as ore, no need to reinvent this wheel again.

**Comment by Badcholo** [comment]
I hate that saying,"reinvent the wheel" it means you want to stay outdated and full of bugs and you better like it.
With enough people not liking this feature and many others, you'd think you would have made it simpler or removed it by now. no point in making something super over complicated if you gotta keep fixing it all the time. I just use it for storage and input/output of machines. Crafting as well. I don't understand all this seeds in water bs, needing a inscriber press to make an inscriber press, growth accelerators for seeds that grow on the ground. wtf? or the dumb skystone that you have to go find after it destroys your land and with a chest in the middle, wtf? when have you seen a meteorite with a stinking chest in the middle of it. specially with a dang inscriber press in it. someone on your team is just messing shat up. I don't see many new abilities from older versions. I just see a whole lot more work and grief to get the same results. Thanks for the link.

**Comment by XFactHD** [comment]
Making an inscriber press with an inscriber press is not so unrealistic, if you want to go for completely realistic then you would need a negative out of ceramics or whatever.
The same thing counts for the meteorites. In reality they also bring rare things to earth. The chest is just to hold the items. I don't want to think of 100 of meteorites with 1000 of dropped items.

**Comment by Badcholo** [comment]
Making an inscriber press with an inscriber press is not unrealistic. Making it the only freaking possible way to make one IS unrealistic. Do you know anything about meteorites? Rare things? Maybe some minerals, but mostly junk. Plus this is minecraft so i understand the concept. Same way i understand that it should be removable in a simpler way. Crafting is already hard enough without having to destroy your world with meteorites just to mine a simple block that does nothing but allow you to craft. It doesn't have a good execution or storyline behind it either so i just see it as pointless. I see a lot of servers owners having to put in a lot of work to simplify this mod. Removing things, changing crafting recipes, installing other mods like this one. 
http://www.curse.com/mc-mods/minecraft/225194-ae2-stuff
This was made to fix things cause someone here just didn't freaking feel like changing something no one liked. make a poll, see what people really think.

**Comment by yueh** [comment]
So you are playing/administrate/owning on a pay2win server, which is violating the Mojang EULA as well as AE2 license and complaining and trying to insulting us?

**Comment by bookerthegeek** [comment]
As a general rule, insulting people will not get you very far.

Ask your server owner to set up a shop that sells them and disable the meteors. Problem solved. Just because you, and a few of your friends don't like something does not make you a majority. I personally love the way this mod works and I consider it a vast improvement over previous versions. 

wait, that makes it the majority of players like it this way then, right?

**Comment by Badcholo** [comment]
I don't see where you get the pay2win server. I also don't see where you get the violating EULA or AE2 license. The Server isn't even setup to accept donations. I'm not insulting anyone, just expressing my opinion. Ya kind a ticked me off with that reinvent the wheel comment. This is the first time i have commented here. By the looks of it and by that comment clearly your sick of hearing it, so i must not be the first to not like the way it works. Someone with big balls just won't change it or give an alternative. If bookerthegeek likes playing in creative and is ok with building this way cause it's the only challenge he ever gets then, that's his choice and opinion. I don't like banning items or selling things at spawn just because a mod author wont' add a config for a simple alternative option. I don't see what the big deal is. I'm not asking you to rewrite the whole dam mod. 
bookerthegeek you look like an idiot trying to be sarcastic in text. Now i insulted someone. 
I make valid points and just cause you guys don't like them it doesn't mean i'm wrong and your all right cause you choose to gank up on me. If this other mod is doing something wrong or not allowed, well i didn't know and you prob should go talk to him.

**Comment by Badcholo** [comment]
Using stone instead of skystone, a crafting recipe for a few inscriber press. That is all i asked for. Is that really worth all this drama? Did i really ask for too much?

**Comment by bookerthegeek** [comment]
Asking a mod author to change his mod just because you don't like a feature and then getting upset when they say no? Yeah, that is to much.

Not your mod = not your choice for anything in the mod = no right to get upset when your told no to your idea.

Secondly, I did not insult you. I was making a point by using your logic and turning it around to show you how it sounds. Not insulting but educational. And don't worry, I forgive you for the little comments about me. :)

My basic point is that you asked for a feature. And you were told no. You might not like the answer but that is the way it is. If you really want to press the issue, the correct way to go about it would to make a pull request after coding the features you would have wanted added. Then politely asking the mod author to add it in.

**Comment by XFactHD** [comment]
I assume that you have an archive program like WinRAR. So you can simply open the AE2 jar, edit the recipe files with a text editor (add a shaped recipe for the presses and either change the shaped recipe of the controller or add an unshaped recipe for raw skystone), save the text file and close WinRAR or whatever you are using.

**Comment by Badcholo** [comment]
I hate it also when trolls jump on and just start running their mouths when no one cares nor was even speaking to them pretending like it's their mod. I guess drama queens like their time in the spotlight. I spoke my opinion and was looking for a response as to why there wasn't a simple way to offer players an alternative. I can make the changes myself quite easily, but i was wondering why all the drama about not adding a simpler way to change things. Most mod authors seem a lot less stressed and laid. It seems like there is a much deeper issue here and i'm not willing to stick around and keep feeding these trolls.
bookerthegeek: your profile pick doesn't reflect the little drama queen you have inside you. I'd get rid of it.

**Comment by Badcholo** [comment]
I speak for others that are scared of getting attacked for asking such things. This happens more often than you think.

**Comment by thatsIch** [comment]
The intended way to generate the wanted recipes is the custom recipe interface. It exists for this sole purpose to actively change the recipes to the servers needs (setting a main mod, adding new recipes, removing unwanted recipes etc) Making all these options a boolean config option would result in a bigger config than GregTech has. 

Yes, you are in particular just asking for a specific sub-set of items, but then the next one comes and says: want easier recipe for fluix, easier recipe for certus quartz etc. 
You may see the problem we are facing, there is no way to make the default setting suitable for everybody, but we can add something, so everybody can change the mod up for their respective needs. 

I am currently rewriting the recipes API to make it a little bit easier for people to modify the AE2 recipes, but the approach stays the same.

**Comment by Badcholo** [comment]
That make a lot of sense. Sorry i got a little carried away. I just didn't like the way i was replied to from the start. This really is a really nice mod and it is easy to set-up to fit your needs.

**Comment by thatsIch** [comment]
No problem, we all want the same: a better mod :)

**Comment by mikeloeven** [comment]
you really used my post to necro a issue this old ?

**Comment by mikeloeven** [comment]
you really used my post to necro a issue this old ?

but regardless the issue goes beyond the ability to make custom recipes to the fact that should this unsustainable unfair and clearly flawed mechanic be the Default setting??

the simple fact remains that administrators frequently use default modes because often times they cant be bothered to change the configs or in the case of plug and play servers do not have the technical skills to even follow the instructions

the issue is not about whether or not there is a workaround the main issue is making sure the AE mod remains accessible to all players not just the first few people on the server its a much deeper issue than this and i am shocked that in so many months this still has not been fixed because there is simply no legitimate way to justify the current mechanics because it completely unbalances the game and gives a select few lucky players a complete monopoly over the mod

the issue is not that people want a easier recipe for the inscriptions the fact is that they want A! recipe for the inscriptions in the first place

the sky-stone chest mechanic simply does not work, cannot sustain in a highly populated / limited radius server


Please reopen this issue
