### ISSUE TITLE
Cell type display

### ISSUE THREAD

**Issue by Deshiba** [AppliedEnergistics/Applied-Energistics-2#1524]
# The issue
When you currently configure a cell in the Cell Workbench with 1 item it can only hold that type. However the tool tip for the cell you have configured will still say 1/63 types when in reality it can only hold 1 type. The system knows this when you enter it into a chest/drive because it'll show that all types are used.
## The question
Could you make the cell show the amount of types it actually holds after a configuration? (Showing: "X Type(s)" instead of "X Of 63 Types")
## Why?
To remove any possible confusion about how many types a cell can actually hold.

**Comment by yueh** [comment]
Configuring a cell with a single item does not imply that only 1 type can be stored.
There are a couple of cases which allows many more types to be stored. The highest I currently can think of are >4096 different types and still using a single item.

So it would actually need to display "4096 types", which would be way more confusing and is actually wrong as the limit of 63 items would still apply. So it would need to display something like "63 of 4096 types" and then stop accepting any new item but already stored types are fine and could be still added. More confusion.

Neither the creative tabs nor NEI will actually display all 4096 different types, just a single base one (even without mods grouping them). Without knowing some minecraft internals, most people will not be able to actually tell why a single item just expanded to 4096 types. So adding even more confusion.

**Comment by Deshiba** [comment]
This response got confusing to me really fast. I was under the impression that adding a cobble would only allow for cobble, same with a sword that has 1 point of damage allowing only other swords with 1 point of damage. Could you give an example as to when this wouldn't be the case?

**Comment by yueh** [comment]
Mostly cells with a fuzzy card or inverter card. For example filtering for wool and putting every color into the cell will currently display 16 of 63 types used.

Just consider other examples like dyes. Vanilla only adds 16 different ones and there are enough other mods which add their own versions.
The cell could actually accept more then 63 different types, but 63 is really the hard limit for storing them. Say you have 4 mods (including vanilla) adding different dyes, so 64 different items totally. But the cell will only be able to store 63, the last one needs to find a place somewhere else.

The example with 4096 different items are the EnderStorage EnderChests. Basically each color combination is 1 item (16^3). Because they all share an oredict entry. No idea about the tanks, but they might also share an oredict entry. So configuring a cell to chests and tanks would mean 8192 possible items. But NEI will only show a single entry for both.

Even AE2 has an example for a massive amounts with facades. A cell with 1 facade + fuzzy card will be able to accept every other facade. The total amount is only limited by what other mods you have and can even fluctuate with between mod updates.

Would you immediately think of all these cases, when a cell suddenly shows "32 types" instead of "16 types" after a mod update? Or would you consider it a bug with AE2 first? Or in case of an inverter card why does it suddenly display 0 of 7654 items (Vanilla with AE2 has about 7k items total)

Would it be really less confusing to show something different for every configuration option and most of it requiring some knowledge of the internal behaviour of other mods?
