### ISSUE TITLE
Show coordinates for interfaces in interface terminal

### ISSUE THREAD

**Issue by scifibob** [AppliedEnergistics/Applied-Energistics-2#1528]
When you have added some interfaces in the network witch do not craft anything, and you forgot to click the "show or hide on interface terminal", it would be nice to have an option to display the coordinates of those interfaces.
Sometimes I make a processing factory, and add some interfaces. Days later I'm in the interface terminal, and there is several blank lines saying "Nothing".
It's a pain to locate those interfaces if you have a large network..

I know it's a "lazy man's request", but maybe it's not that much code required to have an option to display the coords in the list, maybe as a tooltip.

**Comment by Blue64** [comment]
Rv2 Stable 10, still there. It'd be nice to see it implemented as a default name toggle in the config. It of course would only work for newly placed Interfaces, it'd just grab it while it's being placed and use the XYZ as it's internal name instead of "nothing". The only drawback this causes is that it means they won't stack when picked up, unless crafted between it's Panel & Block form again, which clears the Meta containing such info(aka ".withTag({})")

**Comment by mindforger** [comment]
not finding your unnamed interfaces is just the punishment for beeing lazy and not naming them in an inscriber at first!

**Comment by Blue64** [comment]
So we should instead not be aware that our Interface isn't hooked up? If we name them ourselves, it won't tell us that it's not connected to anything. If we don't name them, we're lazy. Make up your mind.

**Comment by mindforger** [comment]
hey i was just posting my opinion why so agressive?
just look at the "issue" about "power consuming while stuck" inscribers .. if you are lazy you'll have to pay a prize

it's a game where you have to achive something and not get everything presented on a silver dish, "make up your mind" ...

**Comment by Blue64** [comment]
You posted your opinion as an exclamation, which means you posted more aggressively than I. I was simply reminding you that if we name them, it won't notify us that it's not connected, which is, in my opinion, 20 times worse than them being unnamed and connected to nothing, as we have no idea in larger networks where these bad connections are located, but at least we know it's a bad connection. I could recommend offering an upgrade or something, but the only way that'd be possible is by introducing a few new items, the first one to craft with the interface to provide XYZ coordinates, the second is the item it would produce, which would mimic the interface, which I'm sure the Devs aren't in the mood for adding because their plates are still overflowing with stuff to program, such as 1.8 stable, and various bug fixes.
