### ISSUE TITLE
Quantum Entangled Spacial Storage Cells

### ISSUE THREAD

**Issue by mindforger** [AppliedEnergistics/Applied-Energistics-2#1539]
Some sort of crafting recipe, including one spacial cell containing a dimension and another empty spacial cell + 2 entangled singularities

Result: 2 entangled spacial cells linking to the same dimension

Use: For building a sort of dimensional teleporter, where you can have 2 spacial pylon constructs with each one of the entangled spacial cells and whenever you put a redstone signal to one of the pylon they do their thing. 

without this feature i have to somehow teleport the cell from A to B while inside to achive the same effect :)

**Comment by thatsIch** [comment]
I think @yueh had something similar in mind

**Comment by yueh** [comment]
I was more thinking about something like a P2P tunnel to allow swapping two areas directly.
But this probably introduces a couple of issues.

This sounds just more a complex description for "allow spatial cells to be copied".

The current way should actually be even safer as the redstone is pretty simple and not really something to fail. The only thing which can fail is moving the cell arounds and this can be easily prevent as long as the networks are fully chunkloaded and in the best case separate from any unrelated functionality.

Copied cells will need the setup to not fail cycling back after the activation, the redstone signal needs to be transmitted remotely and a couple of other issues. For example P2P redstone tunnels, but then there is already a ME network available at both ends for simple item transport.
SpatialIO is also one of the few things actually being pushed back to later ticks (besides ME P2P tunnels and annihilation planes), so it would be very sensitive to timing issue. Just because the timing worked the first ten times, is no guarentee that a player will not get stuck with the 11th attempt.

Not even considering what could happen when both cells are simultaneously activated. Something easily achieveable by placing a lever between two ports.

**Comment by mindforger** [comment]
heh ... okay you are right, i also thought about the problem when doing redstone simultaneously on both cells and always ended in some sort of .. server lagg of hell conditions :) .. 

your idea is quiet better! instead of placing spatial cells, insert the entangled singularities directly into both spatial controllers and swap their contents (conditions: connected via ME, enough power to do 2 spatial operations)  no need of additional components, just a little more logic and nobody can get stuck and no other dimension needed

**Comment by mindforger** [comment]
is the state-waiting label adressed to me? or @yueh

**Comment by thatsIch** [comment]
It just indicates, that it needs to be discussed further

**Comment by Anomerly** [comment]
I like the idea of the Spatial P2P tunnel as a teleportation device though I think it would be more inline with the ideals of AE2 to provide an upgrade to the Spatial IO Port to allow both a method of importing and automatically activating a Spatial Drive as well as a method of automatically exporting a drive after it has been activated. These states would have to be mutually exclusive to each other to prevent an uncertain state and oscillation.
With the addition of a spatial config terminal that would allow spatial drives to be dispatched\retrieved from Spatial IO Ports via your ME network you have the makings of a really nice teleportation system.
The only difficulty here would be having more than one SCS on the same network. I can imagine sub-networks could come into play here, but that would make the workings a spatial config terminal inconsistent with the rest of AE2's design, perhaps this is where your Spatial P2P tunnel's fit.

With a terminal controlling individually named spatial tunnels allowing Spatial IO Ports to be linked, as Tx and Rx pairs may just be the perfect solution.

**Comment by Anomerly** [comment]
Just to clarify in my last comment I see the Spatial P2P tunnel's working more like interfaces and interface terminals than p2p tunnels.

**Comment by chorman0773** [comment]
Actually the most likely effect is the Tile Entity that was added first will be ticked first, which means that it will empty the storage cell, into the pylon array, and the other would follow, doing the same thing. That is, if it is handled with a slight bit of respect to the way that minecraft handles tile entities.
