### ISSUE TITLE
AE2 for cauldron

### ISSUE THREAD

**Issue by BenTHEpeiceOFcode** [AppliedEnergistics/Applied-Energistics-2#1549]
Hi i need help getting AE2 to work on my server im running cauldron
git-Cauldron-MCPC-Plus-1.7.10-1.1207.01.198 
Please help

**Comment by vallard192** [comment]
I don't think anything has changed since #375 and #921 and your problem is
most likely related to #1516.

Short version: The team doesn't support cauldron.  You'll need to look for
help from them to get it working.

**Comment by thatsIch** [comment]
Information missing, 


there should be generally no problem running it on cauldron. Just pay attention that Cauldron modifies the used Forge Code, so if it runs on a normal server and not on Cauldron, look for a fix on their side.

But Cauldron is **dead**. Yes it is kept maintained in the underground, but the original author even states, that it is dead software since last December. 

I will give the Issue Creator the chance to state his problem though, if it falls into the category of any of the posted issues, they will be marked as **will not fix** or **duplicate**

**Comment by vallard192** [comment]
Thanks thatslch.

**Comment by BenTHEpeiceOFcode** [comment]
Thanks for your help but i have just downloaded AE2 R0 or something like that and it is working just grate
But yeah thanks anyway
