### ISSUE TITLE
EnderIO Conduit Facade

### ISSUE THREAD

**Issue by UnDeadClank** [AppliedEnergistics/Applied-Energistics-2#1557]
Is it possible to add EnderIO Conduit Facade as a possible way to hide the Cabel ? 
The Conduit Facades work perfekt with connected textured

**Comment by yueh** [comment]
Not without heavily reworking the facade system. They will also hide any part, so you will no longer be able to see your terminals.

**Comment by UnDeadClank** [comment]
Ok, is it possible to add Connected Textured on the normal facades ?

**Comment by Entoarox** [comment]
@UnDeadClank It is not, the only reason ender IO conduit facades can do it is because they provide a fake block and let that handle connected textures, although it might be possible for @yueh and the team to create their own implementation of the basic design, but it wouldnt work with the current facades, it would require a new 'full block' version that acts as a facade on all 6 sides with the same block texture.
