### ISSUE TITLE
Make the level emitter accept multiple items

### ISSUE THREAD

**Issue by Techjar** [AppliedEnergistics/Applied-Energistics-2#1579]
Yes, doing this will probably require reworking the way you configure the level emitter a bit, but it seems like a rather useful feature. Placing several level emitters to have multiple items on a single thing is dumb.

**Comment by yueh** [comment]
If it is really a useful feature, could you please name a couple of use cases for it?

Under the assumption of not turning them into a SFM GUI, as it will certainly need operators for `AND`, `OR` and `NOT` as well as something like `()` to indicate the order of evaluation.
Which just dumbs down the channel management as well as replace normal minecraft logic (or other mods providing logic gates)

When limiting to a single operation (only `AND` for example) it certainly make it unusable for the majority of possible uses cases. Which are actually not that many outside of `turn off that light when > 1000 cobble and > 500 dirt`. For example it would make it impossible for `emit redstone if crafting ( pureCertus | pureNetherQuartz | pureFluix )`

**Comment by Spordo** [comment]
Alright. i will provide some explanation since i was the one who asked Techjar to create issue such as this one. 

so i have good idea of fixing that issue of what you said. quoting (turn off that light when >1000 cobble and >500 dirt.) 

I even thought of that since techjar created this issue. so Emitter would have to have 5 spots.. so each one will have it own number such as (x>1000) for cobble. the cobble would be put in number 1 spot.. while the number 2 has dirt and its number is (x>1000). you would have to click the spot to change the number... that may works.. but its up to the author to do with that issue.. 

i will give you a good example why "multiple spots in one emitter" is need. So if you only make one "auto-crafting block" (A.C.B). just one.. and its purpose is to make a special ingots.. such as "signalum ingot" or "other special ingots" from (thermal mods). so the A.C.B will getting the dust or pulverized ingots (P.I) from the "ME drive", but the problem is if that "ME drive" has run out of dust or P.I.. thats where the emitter come in.. because i can put more than one dust or P.I in that emitter.. so when it see that it has enough ingredients to make special ingots.. it will light the cable or pipes to send the dust or P.I to the A.C.B to craft the special ingots (dust) then send it to the furnace or alloy smelter (from thermal mod).. it make thing easier that i just used one A.C.B and one emitter.. since A.C.B's only purpose is to make a special ingots.. and the all of the content in that emitter is any type of dust or P.I. 

so that would be good example why it would be useful.. 

If you have any more questions regarding this issue. let me know.

**Comment by Techjar** [comment]
What are pulverized ingots? Anyways, yes yueh, I'll admit the use cases are probably limited, but in those cases it may be very helpful. I can't think of an example though. However, I have another idea that suits the intentions better than this.

What I'm looking for is a better way to control export buses. Let me explain by example: I have an ME condenser which has export buses feeding it the items, with level emitters so that I'll always have at least some amount of the item rather than condensing all of it. This currently necessitates a separate bus and emitter for each item type, which is a bit problematic when I need to handle many item types. What would be nice is a way to toggle exporting of each item in the bus individually and in a compact manner, maybe through some special "bus controller" device. This way I could handle a lot of item types on the condenser without needing to slap buses all over it, or possibly even needing to add a condenser because there are no free sides.

Hopefully I explained that well enough.

**Comment by yueh** [comment]
Clarified on IRC, actually unneeded as the wanted functionality is already possible (autocrafting).
