### ISSUE TITLE
Neighbor nofity performance issue

### ISSUE THREAD

**Issue by sfPlayer1** [AppliedEnergistics/Applied-Energistics-2#1621]
As pasted below I've observed neighbor notifies towards an AE block using an average of ~12%/6.2 ms of CPU time measured over 2 minutes. It looks a lot like the update may be redundant or overly frequent, but it's certainly way too expensive.

```
codechicken.enderstorage.storage.liquid.TileEnderTank.updateEntity 12.98%
codechicken.enderstorage.common.TileFrequencyOwner.updateEntity 12.54%
net.minecraft.world.World.func_147453_f 12.54%
appeng.block.networking.BlockCableBus.onNeighborChange 12.42%
appeng.parts.CableBusContainer.onNeighborChanged 12.41%
extracells.part.PartFluidStorage.onNeighborChanged 12.41%
appeng.me.Grid.postEvent 12.38%
appeng.me.NetworkEventBus.postEvent 12.37%
appeng.me.NetworkEventBus$MENetworkEventInfo.invoke 12.37%
appeng.me.NetworkEventBus$EventMethod.invoke 12.36%
java.lang.reflect.Method.invoke 12.36%
sun.reflect.DelegatingMethodAccessorImpl.invoke 12.36%
sun.reflect.GeneratedMethodAccessor38.invoke 12.36%
appeng.me.cache.GridStorageCache.cellUpdate 12.36%
appeng.me.cache.NetworkMonitor.forceUpdate 12.23%
appeng.container.implementations.ContainerMEMonitorable.onListUpdate 12.15%
appeng.container.implementations.ContainerMEMonitorable.queueInventory 12.15%
appeng.core.sync.packets.PacketMEInventoryUpdate.appendItem 9.79%
java.util.zip.GZIPOutputStream.write 9.11%
```

**Comment by sfPlayer1** [comment]
Deflater doesn't like small writes, the flushing kills the compression ratio and the tmp buffers are probably too large and cause GC churn. I'd probably use a ByteArrayOutputStream instance of reasonable initial size in the packet. The append writes go there and getProxy() deflates it all at once.

**Comment by yueh** [comment]
As the callstack contains ExtraCells as well as being mostly fluid related, can you rule out that this is not the actual issue?
For example how does a similar setup with a normal storage bus and say an enderchest perform?

I cannot remember the deflater showing up in any profile when loadtesting heavy inventory changes.
It might be just a sideeffect caused by EC2, but nevertheless could be improved.

**Comment by sfPlayer1** [comment]
The extra cells code involved looks indeed a bit fishy (without knowing the API involved), I may have skipped over that a bit too quickly. It's posting MENetworkCellArrayUpdate + MENetworkStorageEvent + another MENetworkCellArrayUpdate and IPartHost.markForUpdate practically unconditionally.

Considering the tank may do a neighbor notify whenever its contents change this seems rather problematic in ec's side, regardless of what ae does in the end.

**Comment by yueh** [comment]
Wow. Sending a `MENetworkCellArrayUpdate` in these cases is really broken and the same thing twice even more. It basically forces the network to reevaluate the whole storage network. Which should only happen, if something large changes like adding a new cell to the network.

The packet itself should only be send when a terminal or similar is open.
But then potentially still twice per notify per fluid storage bus (and I will not be surprised if the endertank updates every tick).
These are normally handled once per tick by the container itself. Except `MENetworkCellArrayUpdate` can force an update with every event...

The `PacketMEInventoryUpdate` needs probably some reconsiderations, just using `ByteArrayOutputStream` and only flush once can introduce new issues. The current flush allows it to fail fast and not accumulate a couple of hundreds of megabytes before failing. There are enough people who use backpacks recursivly with a couple of MB as NBT data.
We probably need a compromise here, like accumulate 2-8 MB (raw) data then flush it and validate the packetsize. Maybe also change it to accept a collection instead of pushing every item on its own.

**Comment by yueh** [comment]
Still mainly an EC2 issue.

#1780 will handle deflate a bit better (as far as it is possible without breaking an important API interface)
