### ISSUE TITLE
Autocrafting gets stuck when using Pams Harvestcraft tools.

### ISSUE THREAD

**Issue by Shoulon** [AppliedEnergistics/Applied-Energistics-2#1630]
You can autocraft any 1 item but after that it'll try to autcraft the base tool's used to craft that said item.

*Was trying to autocraft cheesecake from Soybean products*

**Comment by yueh** [comment]
Just tried it, except I did not use soybean products as these do not use any tool.
I did not encounter any issue with it, worked perfectly fine with requesting a single item as well as a couple of stacks.

So you should provide more feedback to actually reproduce the issue.

**Comment by Elvarion** [comment]
Ill post in this issue since my problem is related to both Pam's and AE.
I setup some autocrafting for Pam's Smoothies. The recipe use the Juicer that is not consumed when crafting. Sometimes the Juicer gets stuck in the Interface when crafting and thus halting the crafting.
As can be seen here
http://gyazo.com/99180a32cfc6b309b632e6831ab93a23
(Making room for the juicer wont help, because sometimes it will go into the slot where the smoothie goes and thats when it breaks)

**Comment by BaIthamel** [comment]
The bug is that autocrafting with pam's harvestcraft cooking items like the pot to make salt from water CONSUMES the pot instead of returning it.

**Comment by yueh** [comment]
Reopen once you can provide more information on how to reproduce it consuming items.

@Elvarion the interface is a simple chest with 9 slots, if you block them all by keeping a stack, nothing can insert items into them and strange things happen.

**Comment by EdTheDog** [comment]
I am having this issue now! Please, I need help! :(

**Comment by mindforger** [comment]
there is no solution, auto crafting always takes as many tools as available and store them in the crafting cpu, you could maybe half automate the system by using either the assembler as crafter with fixed recepie or another autocrafter and loop the tool in a closed process
