### ISSUE TITLE
Crash with HQM on crafting failure

### ISSUE THREAD

**Issue by Timeslice42** [AppliedEnergistics/Applied-Energistics-2#1638]
Crash Log: http://paste.ee/p/44LoZ
Full Log: https://www.dropbox.com/s/1rbgd17kkcprhim/fml-client-3.zip?dl=0

What I think I have here is a crafting job that failed due to external circumstances (such as the Molecular Chamber not being powered, or whatever), but the "I crafted something" event is still being fired. When HQM checks to see if crafting that item completes any quests it appears to be indexing into an empty array of items to see what was crafted. This issue is a little hard to reproduce as I believe it will only happen once for each item.

Assuming my analysis is correct the issue should be solved on AE's side as it shouldn't be sending bad events, but HQM could benefit from a sanity check in this case.

Cross-posted here: https://bitbucket.org/Newcastlegeek/hqm-bugtracker/issue/191/crash-in-hqm-on-a-failed-ae-craft

**Comment by Timeslice42** [comment]
On a related note I bet you rolled your eyes when you saw I created another issue :P

**Comment by yueh** [comment]
As usual forge does not document their code.
So there is really nothing like a bad event as they would need to state that doing X is bad.

The code for HQM seems to no be open source, so I have no idea what it does. It might even fail because we can potentially send the event without a player when machine requests it, forcing HQM to fail because the internal array for null as player is an empty one. (Just guessing here).

Also it seems to be a common HQM issue as there are other open issues on their tracker without a relation to AE2. So closing it for now.

**Comment by Timeslice42** [comment]
The part of the problem that you can fix is the fact that the PlayerCrafted event is being fired even when the crafting didn't actually happen.
