### ISSUE TITLE
Random crash on world load

### ISSUE THREAD

**Issue by twothe** [AppliedEnergistics/Applied-Energistics-2#1679]
When entering my current single-player world the game crashed with an error related to AE2. The full crash report can be found here: http://pastebin.com/ZQvrF3e6

The crash was not reproducible. After restarting the game and entering the world again everything loaded fine.

**Comment by yueh** [comment]
The actual mod causing the crash is FMP, but the crashlog happens in the context of AE2 updating the light level of a block and thus FMP also recalculating their blocks, but (still?) missing some information about the multiparts itself.

Based on the crashlog I have no idea, what the actual culprit is. Based on the crashlog it could be any mod with FMP support and is ablock next to the cable or in the same block as the cable.

**Comment by yueh** [comment]
Inactive, please reopen once you have more information.
