### ISSUE TITLE
Shift-click Crafting uses ALL items in Crafting Terminal

### ISSUE THREAD

**Issue by Xemiru** [AppliedEnergistics/Applied-Energistics-2#1683]
_enhancement, low priority_

Version: appliedenergistics2-rv2-stable-9

I've avoided ever using the Crafting Terminal purely because I'm so used to shift-clicking the resulting item in order to just send it to the next available slot in my inventory. Whenever I do this in the terminal though, it uses _ALL_ the items it can find and crafts with that, usually making 64 of something like a Peridot Sword. If its not too much trouble, I'd like to be able to set an option so as to not let it use everything in the terminal if I shift-click to get the result, only using what I've placed in the crafting grid.

**Comment by XFactHD** [comment]
I don't think this is the way to go. In terms of items that don't stack I would say you are right but for items that do stack I don't think shift-click should only craft one item.

**Comment by Xemiru** [comment]
Not necessarily what I meant; what I'm asking for is for shift-clicking to follow the inventory of the crafting grid only, without including the contents of the storage network. For example, if I lay out the recipe for a Peridot Sword with two of each required item, then shift-clicking should only give me two using the items I've laid out in the grid, not 9000 using all the items it can find in the terminal.

**Comment by XFactHD** [comment]
I will have to test this but I think unstackable items will only craft one if you shift-click them.

**Comment by yueh** [comment]
I am not sure, if I understood you correctly.

But the crafting terminal will only craft a full stack per shift click. In case of tools only a single one, like Diamond Swords. This is completely based on the maximum size any itemstack reports, meaning if this fails, either the Peridot Sword are incorrectly reporting 64 as maximum or some other mod is interfering with it.

At first I read it as being related to the oredict and that it uses this to find an equal item to replace the original item once it runs out. Which is probably a valid feature request.

Otherwise I currently do only see one small improvment, which aims at players wanting a vanilla crafting bench and manually fetch the exact amounts (this of course turns 2 stacks of diamonds + 1 stack of sticks into an inventory full of swords and not limited to 1 full stack) or never want to craft more than one item when using NEI.
But these are also regressions, say if someone is heavily using NEI, they will need to shift click the recipe for every single item. 32 times in case they need 32 items and being pretty tedious.
Or they need to remember every recipe in their head (or use NEI) and then fetch everything needed from the network and probably realizing that half of it is missing and needs to be also crafted by hand.
So not really sure about it, for the most cases it will not provide any improvement, mostly it will reduce the usability in some cases and in contrast AE is there to make crafting easier by automating it, not make it harder by more manual work.

**Comment by Xemiru** [comment]
Well, you do have options on the left side that toggles between options like search or organization; this doesn't necessarily need to be forced upon the way it currently works when we're able to switch between modes like that at one click.

And autocrafting's 10/10 and all, but until I get to the stage where I'm able to make a sufficient autocrafting factory I'd like the benefit of crafting within the terminal without having to worry about accidentally making 64 of something I'd only make once in my entire playthrough--especially if its something expensive.

**Comment by yueh** [comment]
An option will not really prevent accidents, you can still forget to toggle it on or maybe not even realize there is a button for it. It just moves it to something else, instead of blaming shift click, it is then blaming the option. The option then also causes it being blamed for the opposite. Wanting a stack of sticks, but only getting 4 and needing to place the recipe again. Mabye also not realizing the mode and at first wondering, if there are no planks left and checking that first.

Also check if it is on, when not toggling it on, craft something and toggle it back off is way more work than just not to hold shift and drop it directly in your inventory.
Even with an icon, the time it needs to realize in which mode it is, should not be that much faster than the time to put it into the inventory.

**Comment by Xemiru** [comment]
Alright, I see the point. There're sure to be other ways to handle it so I'll hunt around.

**Comment by natewilliford** [comment]
I know this is old, but +1 to adding an option or config to restrict shift-click crafting to the crafting grid rather than my entire network inventory. I'm constantly accidentally crafting a full stack of something like iron plates when I only need 8.

Also I don't agree that toggling an option is more work than not holding shift, for example, when you need 8 of something. And some people (like me) who are used to laying out the mats they need would always have the option set to their preference.

**Comment by Xemiru** [comment]
If you don't want an extra GUI option for that, implementation can always perform to where if any item stacks in the grid hold more than one item, it will only make however many the inventory in the grid can.

| A | B | C |
| --- | --- | --- |
| 2 | 2 | 2 |
| 2 | 2 | 2 |
| 2 | 2 | 2 |

**Only makes 2 of the target item.**
**Refills the inventory if the network inventory has enough to do so, and will not make more unless told to again.**

| A | B | C |
| --- | --- | --- |
| 2 | 2 | 3 |
| 1 | 2 | 1 |
| 2 | 1 | 2 |

**Only makes 1 of the target item.**
**Items are refilled as needed to where each slot has at least 1 item if it had one, and will not make more unless told to do so again

| A | B | C |
| --- | --- | --- |
| 1 | 1 | 1 |
| 1 | 1 | 1 |
| 1 | 1 | 1 |

**Uses the network inventory to make as many of the target item as it can support.**
