### ISSUE TITLE
Iron Nugget Recipe not working

### ISSUE THREAD

**Issue by beulemann** [AppliedEnergistics/Applied-Energistics-2#1703]
I try to automate crafting of "Photvoltaic Cell" from "Solar Expansion".
I am playing FTB Infinity 1.8.1

I created a pattern for crafting iron nuggets from iron ingots and placed it in an interface at a molecular assembler.
I am able to craft nuggets from a crafting terminal now.
If i now use a recipe which uses iron nuggets and i run low on nuggets it only shows missing, but does not craft nuggets.

**Comment by yueh** [comment]
You need to use the same type of nuggets as defined as output for other recipes, otherwise the crafting cannot resolve the crafting process.

It can use existing iron nuggets which are oredict with the other ones. But for the crafting calculation it would be way to expensive in terms of computing power to consider oredict entries for it. (Probably an exponential increase of the required time)
