### ISSUE TITLE
auto-crafting pure crystals

### ISSUE THREAD

**Issue by hijackster99** [AppliedEnergistics/Applied-Energistics-2#1716]
With AE2 if you set up a recipe of 1 certus seed makes 1 pure certus crystal when you go to craft it, it doesn't include the seed as a crafting component. It is the same for all the other seeds as well
![2015-07-16_13 36 15](https://cloud.githubusercontent.com/assets/13369465/8730643/1deebcc8-2bc0-11e5-8815-54d82d39e45a.png)
![2015-07-16_13 36 26](https://cloud.githubusercontent.com/assets/13369465/8730645/1df18aa2-2bc0-11e5-9bcd-7252a2d27981.png)
![2015-07-16_13 36 37](https://cloud.githubusercontent.com/assets/13369465/8730644/1defa610-2bc0-11e5-8614-3d7b1dde730e.png)

**Comment by yueh** [comment]
What does the pattern tooltip say? Also which modpack is this and do they change the AE2 recipes?

**Comment by hijackster99** [comment]
it says it crafts 1 pure certus quartz with 1 certus seed, it is FTB infinity and they don't change the recipe for pure certus quartz

**Comment by yueh** [comment]
Works fine for me with the latest Infinity version (1.8.2).

**Comment by Zaflis** [comment]
You are not showing where the interface should send the seed. Depending on cableing, priorities and stuff it might go right back in the system. How i used to send seeds in the water is with:
Flat ME interface with the pattern -> ME interface in a subnetwork (quartz fiber) - cabled to a formation plane above water.

But you have more choices, simplest maybe Botania's open crate that directly drops it upon receiving from interface.

**Comment by hijackster99** [comment]
I was using computers because I apparently can't do anything simple. I don't know if that's the problem or what.

**Comment by NoX-programer** [comment]
The mod AE2 Stuff adding Crystal Growth Chamber, which allows pure crystals to grow in it. It is addon for Applied Energistics 2: http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2434203-ae2-stuff-v0-4-2-addon-for-applied-energistics-2

**Comment by yueh** [comment]
How does advertising the mod actually helps?

**Comment by NoX-programer** [comment]
It really helps. As I said, Crystal Growth Chamber allows pure crystals to grow right in it, and there can be inserted 5 (if I remember correctly) AE speed upgrades. And there is almost unnoticeable thing: if I attach unconfigured import bus to it (to import always), it will import only mature crystals, so that chamber is not giving to pump out not fully growed crystals. And sorry for advertising, but it is the right case for it.

**Comment by yueh** [comment]
So you are basically saying you did not read what the actual issue is or care about it, but just want to advertise it here?

**Comment by NoX-programer** [comment]
I saw the guy have some indistinct problem with crystal growing and provide a solution - that's all. He can use this solution or not, but you're right - it will be good if primordial issue will be solved.

**Comment by Zaflis** [comment]
> I was using computers because I apparently can't do anything simple. I don't know if that's the problem or what.

Send to chest first and then to computer?

**Comment by yueh** [comment]
It is completely pointless, if this is now dumping into a chest, a turtle or the ae2stuff thingy. Nothing from this will provide any solution for it. Mainly as the autocrafting does not care about the used machine at all.

Something is messing with the recipe or pattern and breaking it. The question is what is it. It works for me with Infinity 1.8.2. So maybe it is already fixed in this update.
Or it is something randomly. For example Infinity contains ThaumicTinkerer, which ships the AE2 API.
But the way this works can force forge to load the old outdated Version they are shipping and thus cause some strange issues.

**Comment by yueh** [comment]
No further feedback provided.
