### ISSUE TITLE
Wireless Terminal can not locate station

### ISSUE THREAD

**Issue by xobo3211** [AppliedEnergistics/Applied-Energistics-2#1754]
Whenever using the Wireless Terminal after it is linked, all I get is the message "Station could not be located". I do have a wireless access point with 8 wireless boosters inside of it, and I am standing right next to it.
![2015-07-30_11 05 56](https://cloud.githubusercontent.com/assets/9968917/8986649/1e95b3ca-36ab-11e5-93e8-3944710ff63d.png)
![2015-07-30_11 07 32](https://cloud.githubusercontent.com/assets/9968917/8986670/34d06680-36ab-11e5-808e-3bb634767703.png)

**Comment by yueh** [comment]
Could you please post the `settings.cfg` inside your world folder on pastebin?

I cannot really recognize the shown terminal, but it might be an idea to verify the issue with less mods in the modpack. So we can exclude that any other mod is affecting it or alternatively indentify a conflict with another mod.

**Comment by xobo3211** [comment]
The terminal is an Arcane Crafting Terminal from Thaumic Energistics, but I do have a normal Crafting Terminal next to it. http://pastebin.com/jNtJTDpH
Here's a picture of my ME system if it helps.
![2015-07-31_11 30 02](https://cloud.githubusercontent.com/assets/9968917/9010851/88a44af2-3777-11e5-86f9-a7b9cd877fed.png)

**Comment by yueh** [comment]
Can you make a copy of the world and just try it with only AE2 as mod? Alternatively you could also start removing some mods. Best idea would be the AE2 addons first. Mostly to remove anything which could interfering with AE2 (or find the one interfering)

**Comment by treknib** [comment]
Had the same issue multiple times with a wireless only network on a mps. (no terminal, no griefer :)
It worked at first, but after one day this problem appeared. 
Setup is: 
- storage drive
- dense energy cell
- security station
- energy acceptor
- wireless access point + updates

Config is default, accept chanels are switched off
File is appliedenergistics2-rv2-stable-10.jar

For solving i had to place the acces point to a different location. After two days it happend again, so again i changed the location. Now its running since some days without problems.

**Comment by thatsIch** [comment]
Are you using a QNB in there somewhere?
This generally happens only if the QNB or the Security Station are unloaded or invalidated (e.g. by moving them via frames, SpatialIO etc)
