### ISSUE TITLE
Strange freeze bug in entire netwerk

### ISSUE THREAD

**Issue by Visstick** [AppliedEnergistics/Applied-Energistics-2#1755]
Hello everyone,

I am kinda new to this whole AE2 thing so this might just be something that I did wrong. However looking trough multiple tutorials I can not find anything wrong in my setup.

The problem:
All my items and crafting paterns disapear in AE

my AE is working fine, I can craft items, deposit items etcetera. However on random intervals the entire system freezes. I can not craft anything anymore nor look on my items on my hard drive. To fix this I have to manually replace every drive to be able to see my items again and put out 1 crafting patern from a molecular assembler interface and insert it again. This sounds like a small inconvenience but it happens multiple times a day and when the ammount of drives increases (12 now) it is going to be neither impossible to maintain the system.

The setup:
I have a ring shaped controller (7x7) with dense cables going into 4 directions. The dense cables go into smart cables which go into various machines. There are no p2p's in the network at the moment. Everything is directly connected. 

http://puu.sh/jiOhE/0c883e3991.jpg   (bottom)
http://puu.sh/jiO4U/e78ba7456e.jpg  (top)

Things i tried to fix so far:
1) Disconnected all other machines from the network by destrying the dense cable leading towards other things accept the drives and the terminal.

**Comment by mindforger** [comment]
which version of AE2, there was a bug previous to rv2.stable 10

**Comment by Visstick** [comment]
appliedenergistics2-rv2-stable-9
that is the name of the .jar from ae2


we use thise one too
ae2stuff-0.4.0.38-mc1.7.10

**Comment by mindforger** [comment]
try updating then and of course the obligatoriy advice: install at least 1 ME energy cell into your network to encounter power surges as it does not depend on your powersource but on your network's internal capacity when doing large transfers

**Comment by Visstick** [comment]
I will contact our modpack maker/ serveradmin and ask him to update as soon as he has time for it.

**Comment by laci200270** [comment]
Can you send a screenshoot of your network while you looking at with a network tool?(Both when working and not working)

**Comment by Visstick** [comment]
I have had contact with the modpack creater, He is going to update our pack this weekend to the newest version

screenshot of the network while working, the other screenshot will follow when it is broken again.
http://puu.sh/jkrvk/e278d032a0.jpg

**Comment by Visstick** [comment]
A screenshot of the network while having the bug
http://puu.sh/jlcJJ/7dbc30aa13.jpg

**Comment by Astrobirder** [comment]
I'm having a similar issue as well.  The ME system is working, in that I can deposit items, I can can run crafting recipes and it all works, however when I go to an ME crafting interface, I cannot remove any items.  The items are there, any clicking on the item does nothing (left, right, or shift left click).  I recently added 1 DSU with storage bus and export bus, and I disconnected and rebooted ME (pulled power feed) and it seemed to go away, but today it's back and now won't seem to get out of this partial lockup mode.  

Yes, we are on rv2-stable-9, so an upgrade may fix, but I'd like to know a bit more about the lockup bug that mindforger mentioned above, before I try to convince the server admin that an update will fix it.  I read through https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1611 and tried removing a drive and putting it back, but that didn't help.  We are using ChickenChunks and I removed one of the loaders, but there is another that I can't remove (not owner of it), but will try later.

The other difference is that we are running with the AE2 channels disabled (primarily so we can use Enderio ME conduits and make base layout much prettier and easier since it is a rather large base with a widely distributed set of buildings.

No, I don't have screenshots with a network tool, since the tool, and all the parts to build another one are stuck in ME :-).  I'll try to get that when I can get back into ME, or go hand craft the pieces.

Anything else I should do other than upgrade to 10?

**Comment by laci200270** [comment]
@Astrobirder if you need your items you can setup a minimal AE system with just few drives,a power acceptor,and a crafting terminal

**Comment by laci200270** [comment]
@Visstick did you chnaged anything between the two pictures?I just ask because power usage is double.

**Comment by Astrobirder** [comment]
Interesting new observation.  If I go to an Arcane Crafting Terminal instead of the ME Crafting Terminal I CAN pull items out.  How very strange.

**Comment by Visstick** [comment]
I have not changed anything in my setup, (only the suggested power cells)

Also for me all items just disapears. Like it doesnt see the hard drive. So its a bit different then the problem Astrobird is describing. It could be the chunk loading problem, I will move some of my hard drives into the same chunk as the terminal and see if that helps. I also tried removing power from AE en reataching it but that didnt work. Our server admin told me he has the same issue. Hes a very experienced minecraft player who knows AE quite well. He still hasnt done the version update for our modpack so it could all be fixed after the update. (costum pack and that will take some time to set all the item ideas etcetera right)

**Comment by yueh** [comment]
#1611

**Comment by Visstick** [comment]
Thanks for the reference to the other topic and the assistance of the others.
