### ISSUE TITLE
Is there a way to order a result from Ic2 Replicator ?

### ISSUE THREAD

**Issue by ExDomino** [AppliedEnergistics/Applied-Energistics-2#1767]
My question is to know is there a way to order the Ic2 Replicator to "craft" an item when AE2 needs it for a crafting or when the used requests it?

**Comment by yueh** [comment]
No, autocrafting does not support anything based on probability.

See #1007 for more information.

**Comment by ExDomino** [comment]
There is no probability with the Ic2 replicator. If there is enough energy and uu-matter and the item is known, it will produce it at 100% of chances. I don't talk about scrapbox here.

**Comment by yueh** [comment]
Oh. I have not used IC2 in ages. Mistook it for the recycler.
But else no idea (mostly because I never used it)

**Comment by XFactHD** [comment]
@yueh The replicator gets a list of known items form an adjacent pattern storage and the user can choose which of those items should be created and if only one items or an undefined amount should be created until the user stops the machine.
@ExDomino This is not possible because the ME Interface can't choose the item and how many should be made, this would need special integration which an add-on would have to provide.
