### ISSUE TITLE
Assign uuid to interface

### ISSUE THREAD

**Issue by bookerthegeek** [AppliedEnergistics/Applied-Energistics-2#1779]
Would it be possible to have a toggle inside of, or a variation of, the machine interface and import/export busses have them pass along the uuid of the player that placed it?

This would allow for 
 Thaumcraft cauldron crafting
 Access to privately locked machines from other mods.

**Comment by ruifung** [comment]
I don't think this would work for privately locked machines, mainly because I seriously doubt the IInventory and ISidedInventory interfaces actually support having a player UUID passed in. And privately locked machines probably just disable connection abilities of pipes.

Also, I don't think cauldrons are actually meant to be automated in the first place, and it probably checks a for a player dropping an item. Theres that automatic cauldron thingy though, and its not that space consuming?

So, I think that this is not something that can actually be implemented?

**Comment by bookerthegeek** [comment]
Sorry, am on my phone and did not realize my post did not fully post. The automated cauldron does exist, it was listed as an example.

The order reason being that since cauldron died, servers are either developing in house claim stuff or slowly experimenting and moving to forge based protections. A prime example is MyTown2.

Also sponge is being devolved for 1.8, which IS forge based.

This would allow for players to use AE systems that interact with forge protected devices/machines without using funky workarounds, as since they placed the machine, and the machine is "them", it will work. 

Another prime example is AE and botania. Using MyTown2 a claim is protected from other placing blocks. This will NOT allow formation planes to place stone and logs as they are not the player. If we could get the system to emulate the player then this would be allowed to work. Trusting the entire mod to the claim would allow others to place the block directly next to the claim and interact with machine inside.

**Comment by ruifung** [comment]
While I'm not sure how the forge protected devices and machines are protected, I still seriously doubt that the inventory interfaces actually support passing of a player UUID. Sure theres sponge, but unless sponge actually adds a Inventory interface that supports that..? 

And while the formation plane and region protection is probably a valid use case, I think instead of having it track which player placed it should just inherit the network owner from a security terminal, although... if there was some kind of logging plugin logging block places, this would probably spam it pretty good (since mods typically use a fakePlayer which can be filtered out..?).

**Comment by yueh** [comment]
Passing some UUID is not even a thing. What thaumcraft does is listen for an `ItemTossEvent` and then attaches the playername to it and use this later once it hits the crucible.

This is also not an option to fake, as suddenly all dropped entities will have a new NBT tag making them something different. So it is not unlikely that it will simply break any autocrafting or filters as you would have to use unobtainable items to filter them correctly.
And there are other mods adding random data to items, so giving them more ways to break things is not a good idea.

Even with some protection mods slowly migrating to Forge, it is still quite a mess. Forge is nowhere near a point where something like a protection can be implemented without some workarounds or being overly restrictive/permissive. For example there is nothing like an `ItemSpawnEvent`. Just some generic `ItemEvent`, which could be anything and the `ItemTossEvent` and some to cancel the expiring of an itemstack.
This means also there is nothing like passing the owner with with an exportbus. These things simply do not exist.
I am also not really convinced that sponge will improve anything, it is still on top of forge and not being part of forge. So it lives basically in the same space as any other mod and if not every mod is actively supporting it, some will simply bypass it or they patch forge in a way that it causes similar issue like bukkit and mod devs will just drop their support once it causes enough strange bugs.

**Comment by ruifung** [comment]
That being said, I believe forge at least had some kind of BlockBreak/BlockPlace Event? Or at least I think I remember reading one of the MyTown developers mentioning it in another github issue somewhere... So probably just firing a event with the proper player would at least get formation and annihilation planes to play nice with protection mods using those 2 events. (Unless it doesn't exist or AE already does this)

**Comment by yueh** [comment]
We use the normal `Item.onItemUse()`. If this does not trigger these Events, there are really two options, either forge itself does not trigger them or forge expects us to use a different method, but as usually does not document it and in my opinion as long as there is no associated JavaDoc saying use this other method, we are not doing anything wrong.

Of course we are using a `FakePlayer`, so it will not work when something expects the original player.
But this will be a consistent behaviour. Using the whoever played the part will behave extremely inconsistent. It is not that uncommon that multiple players share the same network or you ask someone to help with a build.
So the part will now be bound to someone else and in case of Thaumcraft with potentially a different knowledge state. So you might research some additional recipes, configure the network for it, but it simply will not work as you do not own the required part.

We could use the source of the interaction, which in case of dropping some items into the network will be the corresponding player (also when say manually requesting crafting), but there are still machines around and these are not assigned to a player (see the previous issues with it).
Manually requesting Nitor would work perfectly fine, but if you setup something to keep a specific amount stocked, this will be requested by machines and suddenly not work.

Not working is of course not the best option, but at least it is a consistent and observable behaviour.
Which makes it way better than something, which appears as being random and works in some cases but not on others.

**Comment by ruifung** [comment]
Yeah which is why my suggestion is to have a card? That uses the player who owns the security station active on the network, that would produce a consistent behavior?

Although this is probably more trouble then its worth to code though.

And yeah, the block place / block break event emission is something that should be left to forge though.

**Comment by bookerthegeek** [comment]
Fair enough.  Thank you for all the input on this. I'll go ahead and close this then. :D
