### ISSUE TITLE
Max CPU size limited to 17^3, why?

### ISSUE THREAD

**Issue by Chaos234** [AppliedEnergistics/Applied-Energistics-2#1783]
Hello,

want to know why the MB limit is 17x17x17? This a max amount of 314.432.000,- if you set it up with only 64k units (no co unit, no crafting monitor).

I wanted to build a 30x10xn (n = 3 or more layers) but after I place the 18th block (nk unit, co unit, monitor, ...) the MB doesn't form itselfs any more. So why is there this not edit able limit? Why is there this limit which destroys the designment of CPUs?

I hope that this limit will be removed or is editable over the configuration file because I think that there is no limit. Well, ok, how needs such many bytes on a singel CPU you think, but this isn't the point. The point is, that my CPU should not only have a high amount of bytes, it should also be well designed ;).

So pls remove this limit if it's possible or write it in your wiki because I can't found any information about this limitation.

Screens can be added if wished ;).

**Comment by ruifung** [comment]
What? In what scenario would you actually need a crafting CPU that large? Normally I go for several smaller CPU's to be able to do concurrent jobs..

**Comment by Chaos234** [comment]
If I using the autocrafting system then I want to have at last one CPU with a large storage so that I can craft many of one type (e. g. +100 ultimate solar panels or bedrockium drums). This verry good if you are longer then three day's not ingame, because when you are back then you should have the required item after autocrafting.

Also my building ist 61 width so it will be possible to use it for two 30x10x3 (w-h-d) CPUs with a rly great storage to carft high complex things in a short time but also many of them.

Well, smaller CPUs are also good but my building hasn't this ability for such CPU cubes so I must build thin greater then 17 blocks.

Is there a special point why it's limited to this amount?

**Comment by yueh** [comment]
We simply need to enforce a limit at one point, otherwise verifying the CPU will put too much load on the server/client. Even `17^3` already needs to test up to 4913 blocks for being some type of crafting CPU block. 

Just doubling that to allow your version would increase this by a factor of 8 and this can really put stress on your server. Also it would allow them to cross multiple chunk borders and thus also increase any potentialy issue with unloaded/reloaded chunks as it is easier to miss some by a chunkloader (or do not use any at all)

17 is still fairly reasonable for most things. We could probably consider adding a config option to change it, but this size will most likely be still the maximum amount, just to prevent potential issues.
(17 sounds also strange, it really sounds like an off by one error and should actually be 16 to match a chunk)

**Comment by Chaos234** [comment]
Hi @yueh 

well, I can understand you, that CPUs greater then a chunk can be make trouble but then this should be not realy your problem because I also know that a to high value can destroy the server.

But actually it can be 17^3 so one compleate layer-side is out of a normal chunk. But if I'm right a chunk is only 16x16x265, isn't it?

**Comment by thatsIch** [comment]
correct

**Comment by Pultex** [comment]
Could they change it so there is a special CPU system like the one before that used a case and had blocks inside of it to represent the system core.
That way items could identify the CPU size and not blocks.
They could be Node clusters, or a Neural Net like Skynet.
