### ISSUE TITLE
Crafting not working

### ISSUE THREAD

**Issue by CheesyPotatoes** [AppliedEnergistics/Applied-Energistics-2#1785]
When i try to craft things or applied energistics 2 the image for what i am crafting does not appear but when i hover over the output on the crafting table it lights up as if something is there but i cannot pick it up. Im using forge for 1.7.10.
This is an image of the mods I am using.

![mods](https://cloud.githubusercontent.com/assets/13727065/9161828/18a75180-3f11-11e5-92ae-262d0d72aef8.JPG)

**Comment by yueh** [comment]
Are you playing on a server?

**Comment by CheesyPotatoes** [comment]
No this is SSP

**Comment by yueh** [comment]
The slot will hightligth always, even without any output.

Usually these things happens when the server uses different recipes, but as this is SSP...
So it might be some other mod interfering with AE2, the best idea is to start a new instance with just AE2 and then slowly add the other mods pack until it reappears (it also might be an idea to use default configs)
