### ISSUE TITLE
CompassService memory leak

### ISSUE THREAD

**Issue by sfPlayer1** [AppliedEnergistics/Applied-Energistics-2#1810]
Apparently appeng.services.CompassService (temporarily?) leaks some (~5?) invalid world references through worldSet.

**Comment by yueh** [comment]
Yes, there should be a potential memory leak when worlds are unloaded as it does not clean up the reference to the world in this case.

"Temporarily" is probably caused as a server stop will explicitly free these references. "some" most likely due to not everyone enters a world with a compass, thus the reader for this world is never loaded.

I would appreciate, if you could point in some directions to verify it. Also to test a potential fix and not just hope it might work.
For example just changing it to a `WeakReference`, can cause real memory leaks (native), as we are potentially no longer be able to close the compassdata files. So we most likely have to deal explicitly with `WorldEvent.Unload` for a cleanup.

**Comment by sfPlayer1** [comment]
I unfortunately don't know any details as I've only stumbled across it through analyzing a heap dump after 1-2 days of uptime (FC2). I can only offer to install a new build and observe its behavior.

The finalizer of whatever holds the file descriptor should eventually close the file, which is of course no alternative to (also presumably) stopping the CompassService explicitly from the unload event.

**Comment by yueh** [comment]
Is FC2 currently on rv2 or rv3?

**Comment by yueh** [comment]
Keep it open for further feedback.
