### ISSUE TITLE
items in a crafting process gone after power died.. 

### ISSUE THREAD

**Issue by PRavenhold** [AppliedEnergistics/Applied-Energistics-2#1812]
did a few test to see how my system would behave with big crafting orders. now since the system seemed unable to load my reactor with fuel during this process the power was cut(using about 500kRF/t normaly). 
anyway i ordered about 1500 Vibrant capacitor banks to be crafted so about 100k-200k number of materials in the process. 
power died at some point as i fell asleep and now only 12 capacitors were made. and i lost the rest of the materials that was in the process. the crafting order was also gone when i powered up again. 
is  this supposed to happen?

**Comment by yueh** [comment]
If the crafting cpu is somehow changed (breaking, adding new parts, chunkunload), it will cancel the current task and try to dump all items back into the network.
Should this not be possible, say because the storage also unloaded, it will simply spill out all items into the world as last resort. Of course the despawn timer will take care of them and just delete them after 5 minutes..

**Comment by PRavenhold** [comment]
ah crap.. so then because i fell asleep and my client lost connection i lost it all ok, thanks. ill try and se if MFR chunkloader works with tha Ae2 system better than chickenshit.. :P

**Comment by XFactHD** [comment]
@PRavenhold The MFR chunkloaders work perfectly with AE2. I have also exchanged all chickenchunks loaders with those. One thing: Supply them with enough mob essence or the power consumption will raise into nowhere.
