### ISSUE TITLE
Interface with Crafting Card stops filling 1 craft short if there's no storage for the item

### ISSUE THREAD

**Issue by endreman0** [AppliedEnergistics/Applied-Energistics-2#1833]
Telling an Interface to stock items and give it a Crafting Card, on a network that has no storage for the stocked item causes some strange behavior. (For this test, I was attempting to stock 32 Stone Bricks).
 - The interface gets 28 of the 32 Stone Bricks as expected. Then it stops filling.
 - The interface on the Molecular Assembler accumulates Stone Bricks indefinitely.

Expected behavior was that 32 Stone Bricks would be crafted and sent to the interface, and then crafting would stop.

This is in an SSP world using only AE2.
[Gallery of screenshots and other information](http://imgur.com/gallery/8tDRi)

**Comment by yueh** [comment]
Caused by the order in [CraftingCPUCluster.java#L293-L303](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c0b62fd5192e0976ecc53209de6a2a06c89580cc/src/main/java/appeng/me/cluster/implementations/CraftingCPUCluster.java#L293-L303).

`completeJob()` will invalidate the crafting link, but this is required by the interface to accept the items.
Moving `injectItems()` to the front does fix it, but I am currently not completely certain how it handles the left over itemstack, as changing it will not make it a simple `return injectItems()` (Should you want to take a look @thatsIch)
