### ISSUE TITLE
Illegal mod repost!

### ISSUE THREAD

**Issue by TheRobloxBloxa** [AppliedEnergistics/Applied-Energistics-2#1837]
That website minecraftdl and sixminecraftmods are illegally hosting AE 2! At least I think. I'm assuming you didn't give them permission? But the point is you guys need to fix this :( They're getting credit for your work! This is in the issue section because this is an issue O_o

**Comment by XFactHD** [comment]
Those two pages and many more are illegally hosting Minecraft mods. But as a single person you can't do much against that, but there is a campaign against that (it's called "stop mod reposts" if I recall correctly).

**Comment by ruifung** [comment]
Not to mention technically speaking its not illegal, not for AE2 anyway. AE2 IS licensed under the GNU license after all.

**Comment by TheRobloxBloxa** [comment]
No, The source is GNU the compiled mod however is not. And Yes the campaign is stop mod repost

#StopModReposts

**Comment by TheRobloxBloxa** [comment]
Oh and btw I'm saying this to the devs. So they can rake action. Not sure anyone of them is willing to take legal action? Lol

**Comment by TheRobloxBloxa** [comment]
I ment take action. And if you read the #StopamodReposts page then you know there is away to get mods off those sites. First make a new email (so you don't get spammed) then confront them.

**Comment by ruifung** [comment]
The source is GPL v3. And If you've read the license, it covers distribution of compiled code. Not sure where you are getting your ideas, but this doesn't really belong on a development issue tracker.

**Comment by hunterboerner** [comment]
> No, The source is GNU the compiled mod however is not. And Yes the campaign is stop mod repost

I don't think you understand how GPL works. With GPL, if your receive a binary (in this case a jar file), you have the right to a copy of the source as well.

**Comment by yueh** [comment]
Nothing in AE2 is licensed as GPL.
The core is LGPL, which is similar but still is an important difference.
API is MIT and the assets are CC BY-NC-SA.

So rehosting it can easily violate GPL (no source provided) and the moment you make any money with it (ads are enough) is a violation of CC NC.

The problem here is where these sites are hosted. Sending a DMCA to them is like trying to hit your PC with a wet noodle to make them disappear (this might be even more effective).
The only purpose of this #StopModReposts campaign is to generate press for them. Which is a win for these sites as there are really no bad press for them. 
They are just increasing their page views, traffic, etc, which finally means more money for them through ads as now an army of furious warriors for mod rights are visiting these sites to check for these mods. Probably even being a better "customer" than a other visitors as they will most likely search through a big list of possible mods.

The best is really to just ignore them and maybe try to let google remove them from their index.
But currently none of these sites are on the first couple pages of google results and a twitter campaign/browser addon will most likely not reach their target audience.
I can only repeat myself and say that it generates press for them an keep them visible. Honestly it might be even a good idea for them to start such a campaign by themselves.

**Comment by hunterboerner** [comment]
> So rehosting it can easily violate GPL (no source provided)

No it doesn't. You must provide the source **on request**. That's as simple as giving people a link to this repo.

> Nothing in AE2 is licensed as GPL.

LICENSE contains LGPLv3 and GPLv3, if it's under LGPLv3 only then the GPLv3 license should be removed to prevent confusion.

**Comment by mindforger** [comment]
you can probably DMCA them from google and co. from their search results as owner ... i did this with a ppt which was mirrored by some slideshow pages

worked quiet well, after filing the claim, i had to provide the rights under which they were published in first place to proove their illegal presentation before they got finally removed after a week ... you need at least a copy, that you filed a DMCA to the provider to sustain the removal from the results!

So hitting with that wet noodle can still be powerfull as a supportive action
