### ISSUE TITLE
Security Terminal not saving Ownership upon unloading/reloading Dimension Chunks (Interaction with RF Tools)

### ISSUE THREAD

**Issue by MonkeyMechanic** [AppliedEnergistics/Applied-Energistics-2#1841]
I have an issue where I cannot setup a Security Terminal within my Void Dimension using RF Tools as upon leaving the dimension enough for it to unload and then re-entering, complete access to the system is denied and I can only view the items using a terminal. Interfaces/Import Buses cannot also put items into the system as well as they too are locked out. I cannot also access the Security Terminal to change these permissions. The only way to regain access to my system and to restore Interface/Import Bus functionality, I have to remove the Security Terminal from the network entirely.

I believe the issue has to deal with ownership of the Security Terminal/Network being saved the server when the Dimension is unloaded as there are no chunk loaders keeping it loaded. I do not have access to the server logs at all as the server isn't mine so I cannot confirm by looking into these logs.

Also my apologies for posting the ticket in the beginning without this comment, I accidentally hit enter for I got to type this.

**Comment by yueh** [comment]
Did you experience this with any other dimension? (mystcraft, extrautilities, nether, etc)

I cannot remember any similar report with any other mod? Could RFTools simply missing a call to notify TileEntities/etc abou unloading the world? As far as I remember it has some external power requirements to meet else it would unload it? Which is maybe not the default behaviour when unloading chunks/worlds?

**Comment by MonkeyMechanic** [comment]
I went to Extra Utilities' Last Millennium Dimension to test to see if this issue was isolated in RF Tools Dimensions, and that seems to be the case. I made a small system containing the Security Terminal, an ME Chest with a Color Applicator in it, and a Terminal to access the chest and a power source.

Leaving this dimension for long enough to unload the chunks and then returning didn't affect the system at all. I could access that system normally. From my understanding, RF Tools does require it's dimensions to be powered using RF, however that doesn't unload the dimension when no powered. Unpowered dimensions end up giving a dark fog effect and place negative effects on the player until they leave or die as a result. I believe the default behavior for unloading chunks/worlds still applies to RF Tools Dimensions. I know how those dimensions work is documented in-game through it's Dimensional Manual book, whether or not it's documented online very well is something I don't know about.

**Comment by McJty** [comment]
I have doubts that this is related to RFTools but I do want to check this out. For this it would be nice to know what exactly AE requires for this to work. Where is this security loaded/unloaded and so on? Any technical information related to this can help. Thanks

**Comment by yueh** [comment]
No idea currently. But if it would be a general problem with dimension, there would be already reports about it. Enough players are living in a Mystcraft ago or other dimensions and it would even apply to the normal overworld/nether/end. The only issues being reported with something similar is with cracked clients, so that is not really our problem. This also does not apply here as it would not be limited to RFTools dimensions.

The [security terminal](http://ae-mod.info/ME-Security-Terminal/) is just a simple tilentity with an inventory. So nothing special. But compared to other inventories they make it way more visible when something is going wrong. You would probably not notice a single tile entity storing the wrong amount of power or an old inventory state (at least not immediately)

I cannot currently look at minecraft/forge source and do not know it out of my head.
But if I am looking at [RfToolsDimensionManager.java#L135-L161](https://github.com/McJty/RFTools/blob/master/src/main/java/mcjty/rftools/dimension/RfToolsDimensionManager.java#L135-L161) it modifies the loaded tite entities and I would suspect that minecraft only saves the loaded as the other ones should not change.

Not even sure that it is an issue with RFTools, But from all I have read about it, it differs from other dimension mods by adding a power requirement and thus needs to somehow change the behaviour (like unloading tileentities without power). Nothing the other ones are actually doing.
But if it is, I would not exclude that it could be a potentially abused to dupe the content of inventories.

**Comment by McJty** [comment]
That code in RFToolsDimensionManager only applies if the power of the dimension has been depleted. I would assume that is not the case because then that dimension is pretty much unusable. But the original reporter will have to confirm that. That code is otherwise never called. The power requirement that dimension has is totally independent and something the MC dimension system doesn't know about. It is simply a counter that is maintained independent from the dimension and that counter ONLY has an effect if it gets to 0 (power runs out). If power is sufficient the dimension is just a dimension.

**Comment by MonkeyMechanic** [comment]
Power is not depleted in the dimension.

Also I was able to get a hold of the server host for the server I am on and nothing is outputting in the console when the dimension is unloaded/loaded that would be of any use unfortunately.

**Comment by bookerthegeek** [comment]
I'll test tonight and look into this. Other then AE2, RFTOOLS and supporting core mods, what other mods would you like testing with, and what information are we looking for? This will be tested on a forge single player, forge server and kcouldron server. For comparison I'll also test in another mods void world (Last millinium )

**Comment by yueh** [comment]
Probably related to #1986.
