### ISSUE TITLE
[Request] ME Monitor

### ISSUE THREAD

**Issue by NanoCats** [AppliedEnergistics/Applied-Energistics-2#1849]
Hi! I believe there should be a block that gives you the option to put some information (Like the information provided by a network tool) on a big screen, Letting you view for example, the amount of power stored by the dense cells in your system, my configuration uses a bunch of dense cells as an uninterruptible power supply and i have no real way of knowing how much time i have left if the power is cut aside from the cells that are made visible, or a network tool.

This is my first attempt at using GitHub, So please forgive anything wrong i've done with this post.

**Comment by grantopher** [comment]
+1

**Comment by denzuko** [comment]
I believe one can do this with OpenPeripherals and a little ComputerCraft Computer+Advanced Monitor:
https://www.reddit.com/r/feedthebeast/comments/2u5u03/help_computercraft_openperipherals_ae2/
https://github.com/OpenMods/OpenPeripheral-Integration/tree/master/src/main/java/openperipheral/integration/appeng

**Comment by NanoCats** [comment]
The problem with computercraft being that you need sufficient programming knowledge and you're in deep if your computer system's position doesn't allow for it.

**Comment by denzuko** [comment]
lua scripting == programming knowledge? Since when? That's like saying html or xml is programming. Besides, a good search on pastebin will find a lot of code for computercraft.

As for a power monitor well we have Ender IO's [Power Monitor](http://wiki.enderio.com/Power_Monitor) to help with that.

Albeit is not my decision on if a AE2 based power monitor feature be added or not. I'm for it for the most part since I do not like having a ton of add on mods (most of which does the same thing but only adds one thing more). I'm just attempting to point out there is other ways to achieve the same functionality being requested.

**Comment by yueh** [comment]
#115
