### ISSUE TITLE
Inscriber draws power when it is completely full, and cannot complete the last item.

### ISSUE THREAD

**Issue by Lodran** [AppliedEnergistics/Applied-Energistics-2#1861]
If you "overstuff" an inscriber, so that it has 64 items in it's output buffer, and one being inscribed, it will draw full power even though it's effectively idle.

**Comment by mindforger** [comment]
yeah i noticed that also, this is very unconsistent to every other type of machine i know! The machine can't finish the process and keeps drawing power without making progress ... i was told once it is intended as it needs to "sustain the pressure of the press" until done

**Comment by yueh** [comment]
CGAs are constantly drawing power, TE dynamos are constantly burning fuel even when full, vanilla furnaces are always burning the complete fuel even when nothing is left to do. Some IC2 or IE can be toggled to always consume a bit a power to stay "heated", etc.

There a enough machines with an idle power usage or which are not perfectly efficient out of the box.
So just because some mods do it, does every other mod have to reward being a bit lazy and take the fast route? Instead of rewarding the players who put a bit more thought into it?

The old/related issue is #1531

**Comment by Lodran** [comment]
From a "lore" point of view, I'd have to say that a machine is badly designed if it doesn't check to make sure that it has somewhere to put it's output before it manufactures it - perhaps the inscriber should make horrible jammed servo noises when it's in this state?  Just sayin' ;-P

At any rate, this makes full automation of processor production inefficient at best.  Of course, I could just build a reactor, and ignore the issue - it only makes it consume more power, doesn't stop the machine from working.

**Comment by mindforger** [comment]
"TE dynamos are constantly burning fuel" not if you upgrade them and without upgrade they burn WAY LESS fuel in this situation and not the full amount!
"vanilla furnaces are always burning the complete fuel" no they dont! they just finish the last burning cycle then end burning until you make place in the output!
"There a enough machines with an idle power usage" as i stated above always way less than under operation!

Drawing the full Power over and over with no end is very out of order! Sorry. I accept your point, but not the dimension.

**Comment by yueh** [comment]
Let me get this straight. If you use other mods to compare how they handle balance exactly and not just on a abstract level (like they also are not super efficent out of the box), you basically already have lost as this is AE2 and not EnderIO or TE.

We are way more inclined to arguments like "check to make sure that it has free space available".
Sure it is not perfect currently. But it basically only applies to 2 cases.
Either you let it backlog, because you designed the throughput not right (say 3 inscribers per circuit -> 1 for all final processors), which should really not be the most efficient way.
The other is that you use an inscriber as stockpile and keep constantly exporting the required mats into them. But if you are at a point, where constantly exporting gold/pure certus/diamonds are not an issue, 10 AE/t (20RF) additional power is nothing compared to quarries, mining lasers or what not requiring a couple of hundreds or thousands RF/t.
Both are cases you can prevent, like a better design, stop exporting items once they are full, import the finished products instead of creating a backlog, or 10 AE/t are really not relevant when consuming a couple of thousands each tick (like a wireless access terminal).

To make it easy, make an actual suggest on how to solve it under some conditions:
* Do not simply copy CGAs and just let it consume 10 AE/t even when idle
There should be a different way to make it perfectly efficient
* Nothing which would punish every user even with a good design.
Like change it to 1-2 AE/t idle, but have a charge up time in which it consumes say 100 AE/t for a second before it actually starts crafting and then 10 AE/t during crafting. This would just punish anyone as completely cutting the power will let them lose the charge and it needs to be rebuild for every crafting operation. Even with the most efficient design you cannot completely cut it off the power grid and it is a pretty hefty price for early game.
* To not reward any lazy solution, which just involves placing the inscriber without any thoughts and have the perfect efficency in terms of power consumption or speed.

**Comment by mindforger** [comment]
okay, sorry in first place, i was not intending to insult here! 
I was just correcting/completing your argument as it was not correct and somewhat biased!

You didn't even recognize @Lodran's comment, because he stated that he could go "reactor" and ignore that power issue, but hey, you won't believe there are people out there playing on a lower pace, having under 300RF/t for days/weeks and not using any quarrys or "OP" Stuff anyways, like Big Reactor :P 

Loosing 20RF/t sometimes can break the balance of your system without knowing why and there is no animation or something stating your inscriber is stalling without checking it's inventory or using the network analyzer! (like Lodran said)

i also said, i am accepting your point but i also stated that for me and my point of view, the dimension of the loss in not appropriate, this was only my opinion

i won't yet go into the points you mentioned as they are probably written a bit charged up 

but for the repeated reference to CGAs, they are part of the crystal growth craftingdesign, an very unique way to craft items and in my opinion and very plausible to not be able to recognize the presence of stuff that can be "ionized" or whatever you will call it ... i toggle them with a lever and a togglebus, i like them but i do not like the "hidden" behaviour of the inscriber.

**Comment by Lodran** [comment]
@yueh - Let me get this straight - This was a conscious decision made up front when designing AE?  You actually considered that players would want to overflow the inscriber for stock balancing purposes, and decided to make it an expensive solution?  If so, I have to respect your decision, and applaud your foresight.

OTOH, if you are just arguing that position now because you would rather justify the existing mechanism than change it, well, I have to respect that too - just don't ask me to like it ;-p

@mindforger, I've been trying to make the transition from Magmatic dynamos to Solar cells without resorting to Big Reactors, and without having to build huge piles of dynamos, or pump lava from the nether.

**Comment by yueh** [comment]
Absolutely not insulting. Think of it more of a hint in general. Most mods have their own balancing and the authors probably know that there is mod X, which dumbs it down and just putting a machine down is already the most efficient way to do it.

This also covers the opposite direction, like any GT player could request that AE is not grindy enough and processors should be locked behind different tiers. Say just allow the silicion/logic to be crafted with the t1 inscriber, require enderpearls/blaze rods to craft a tier2 for the calculation ones and tier for the engineering ones should require a nether star. Or that even a 1k cell should cost you like 4 stacks of nether and certus quartz and grow it exponentially that the 64k cost like 1024 stacks each or so.
Probably nothing the general player wants.

Just keep TE as example, in 1.6 your only option to not let them constantly burn fuel when full (even if was a low amount), you had to toggle them off (or on) with a redstone signal. With 1.7 they added the augments so you can use an augment for it. But you are always limited to 4 augments, so you need to make some tradeoffs. Like no longer be able to able to have the highest output and still be redstone controlled, or at least use one of the efficency upgrades to save a bit of fuel when running (not when full)

But back to the inscribers, I honestly have no idea, if Algo did it intentionally or just is/was a bug.
I personally find it mostly an interesting feature as it more or less punishes only bad designs.

Say if you are really limited to 300 RF/t, you will mostly not have enough materials to craft over a stack, which is one requirement for it to occur as the output slots stacks to 64 and not 1 like the input ones. It could apply to the final processor, when crafting different ones.
Even then, you need a build which automatically insert the input, but then forget to add a hopper to extract the products or you output chest is full with 27 stacks of processors (just unlikely based on the material requirements). Or maybe you operate it manually and just forget that you have left a finished processor in it and added materials to craft a different one.
But even vanilla will punish you for forgetting that you dropped a stack of gold and just let it despawn after some time.

So I still think the cost is fair as it is extremely unlikely to encounter in early game or when then just by doing some foolish things. But if anyone can suggest a better way to handle it and while do not affect normal use in any negative way but still have some downsides in inefficient builds, I would really like to hear them as I currently simply cannot think of any.

But we should probably change the wiki entry to state that it will constanly consume power when jammed. So at least someone can read about it.

**Comment by mindforger** [comment]
hahahaha thats funny :D 
>Edit: Also keep in mind that AE requires power to insert/extract items from the network (import/export bus/interface/terminals/etc) and consumes 1 AE per item (itemstack of 1). So just dumping a whole inventory will cost about 1.7k AE. In terms of early game and low power.
With some more active farms/quarries/etc you can easily pass the 10 AE/t an inscriber would consume.

i was thinking on my last comment about to mention, to add this information as wiki entry to the energy cells, but i scratched that XD 

would be nice if you could add this information too, so hopefully people will stumble upon it to not double/triple/quadrupel post issues with "mah network is not wokin, but i has big powa on the acceptor but no energycell" (honestly, many people seem to not understand the need of the powercell, because they have an "auxillary powerstorage with the same capabilities" :/ )

my early builds always consist of 5 inscribers, 2 drives, 1 or 2 terminals and 3 toggleable CGAs and 1 energy cell ... but my power production always is behind the demands in peak output, but buffered and steady ... as i try to not rely on coal power ... 

and my AE was drawing around 40RF when idle ... whe suddenly it went alsmost 60RF, the additional 20RF were bugging me out like hell until i noticed the progressbar beeing stuck
...that was when i posted my comment in that earlier issue!

it was confusing when you not "easily" see whats going on ... and silicon production is extremly easy with a TE grinder and a barrel of cobble you gain while mining

**Comment by thatsIch** [comment]
I think it would be far more interessting if the user is rewarded for an efficient setup, 
thus 

* no drain if no items in input (no idling required)
* low drain if input but no matching recipe
* medium drain for inscribing
* high drain if output is stuck (requires checking nearby inventories to output thus more power usage)

**Comment by yueh** [comment]
Draining a bit of power is probably not that ideal, as the presses are usually left inside the inscriber. Thus they will never idle.

Switching presses is actually possible, but is really finnicky to get right as well as requiring a bit of time to switch them around. Even when making the inscribers faster themselves, it will not really compensate the additional time for every single crafting operation.
Potentially not worth the effort to save a bit of energy.

The other things are already more or less valid for the inscribers currently.
* No drain when idle.
* Fixed amount for inscribing.
Could be considered medium.
* Variable amount when stuck.
Could be consider high, as it will continuously drain more energy and basically rewards the player based on how fast they can resolve it.

**Comment by thatsIch** [comment]
The idea is to either shut off the factory or try to have a constant production > detect if crafting is in action and disable that sub network
