### ISSUE TITLE
Autocrafting simulation won't start

### ISSUE THREAD

**Issue by geech** [AppliedEnergistics/Applied-Energistics-2#1868]
Modpack: FTB Infinity 1.10.1
Version: rv2-stable-10

From reading the bug at #1036 it seems to have the same problem with storage buses, compacting storage drawers and drawer controllers.

I am trying to craft an Ultimate solar panel from Solar expansion.  I am able to craft every other solar panel up to advanced but the ultimate solar panel opens the crafting window, says I have the items, the available space in a crafting CPU and the button is able to be clicked but when I click it it doesn't do anything.  When I had everything stored in the ME system it crafted just fine.

Due to the nature of the Solar Expansion mod I've been kind of on a mission to find the quickest way to craft and ultimate solar panel (Just using AE2 has the crafting process at over 20 hours), and because the mod requires a lot of nuggets and compacting storage drawers make nuggets, ingots and blocks available from a single block I thought it would cut down on crafting because the item is already there.  But I ran into the bug with the simulation hanging at the, "would you like to craft this?" screen.

I'll be glad to give anymore information if you need it.

**Comment by yueh** [comment]
Storage drawers (and especially the compacting ones) are a bit broken by design. They more or less announce the triple of the actually stored items. Say if you store 9 iron ingots, it will report 1 iron block, 9 iron ingots and 81 iron nuggets. 2/3 of it is simply fake and cannot be used, thus the autocrafting will simply fail when trying to extract all needed items.

I think there is an issue for a better feedback, when it actually fails to extract all necessary items.
It is simply nothing we can verify during the calculation and just need to handle when actually submitting the request and then fail.

**Comment by geech** [comment]
I think I understand the concept on why they're broken but I'm having a bit of trouble following why only 1 crafting recipe fails.

Your example would make sense if no AE autocrafting from storage drawers works but like I said above it's only one item (as far as I know) that won't craft.  It will craft the solar panel one tier below the one that fails but the ultimate solar panel won't craft. Is it the sheer mass of items it's transferring and it's not reporting the true size of the crafting process or is it something else I'm not understanding properly?

**Comment by expl0s1ve** [comment]
For example if you are using lead nuggets to craft the items AND have the nuggets from ingot pattern in your autocrafting system, it will think it has (can craft) much more lead nuggets than it has. You probably don't have the crafting patterns of other nuggets or have enought materials not to craft any more for everything else.

Short: Try removing block and nugget recipes from your autocrafting system. (If you have any.)

**Comment by geech** [comment]
Well, I forgot I had other nugget recipes in my system.  Either way it still hasn't fixed it.

I just tried crafting the equivalent solar panels required in the recipe for one tier down but after some finagling it is only able to craft 6 of them and not the full 8.

So once again, it's able to craft from storage drawers, but from what I can tell I don't think it's showing the proper size of the crafting process.

**Comment by expl0s1ve** [comment]
I almost had all my items in storage drawers and had no block or nugget recipe in my system and never had a problem. What do you mean by "other" nugget recipes?

**Comment by geech** [comment]
I currently store ingots from mineable ores in compacting drawers like gold, iron, copper, lead and such.  I used to have recipes to create nuggets from those that were required to make solar panels in my AE system for autocrafting back when I had everything stored with AE.  Now the only nugget recipes in my system are alloys that are crafted on demand that are never kept in large amounts, like electrum and invar and the like.

**Comment by yueh** [comment]
You simply do not have enough materials to craft them.

**Comment by geech** [comment]
OH!!!  *Face palm*

Now I understand what you meant by triple...  Well that's sneaky...  I guess it's time to activate the quarry again!

**Comment by expl0s1ve** [comment]
Looks like it's actually a feature with a side effect. I think either AE2 devs can fix it with a special Storage Drawers integration or the feature can be removed. Otherwise I don't think there is any way that AE can know how many items really exist.
Not sure tho, I'm not a modder.

**Comment by ruifung** [comment]
Just need to implement the IExternalStorageHandler interface... Either in the Storage Drawers mod or in AE, although I daresay AE already has a ton of integration as it is already.

**Comment by yueh** [comment]
No idea if they provide an API, but if we basically have to remove the compacting drawers through it and only show the actual stored items. Not the fake ones.
But in general this functionality just waits for exploits. Like I wouldn't be surprised when SFM starts to dupe anything inside them.

**Comment by jaquadro** [comment]
StorageDrawers has implemented IExternalStorageHandler for nearly a year now.  I even PRed some API changes but ultimately we didn't go that route.
https://github.com/jaquadro/StorageDrawers/tree/master/src/com/jaquadro/minecraft/storagedrawers/integration/ae2

So far as I've heard the integration has been working well.  Compacting drawers do expose the theoretical maximum of each item individually, which does overstate available material.  It's the only presentation that makes much sense, as you'd either need to present just the nuggets, or just the blocks and up to 8 ingots or nuggets to make up the difference.

When materials in a compacting drawer are withdrawn, e.g. 1 block, the corresponding ingot and nugget values are adjusted during that operation.  So long as individual requests get made to IMEInventory.ExtractItems, duping can't occur.  But you could unexpectedly run out of materials for a job, and I don't have a good idea how to deal with that with existing AE2 API.  StorageDrawers does export an "IFractionalDrawer" as part of its API, but I don't know where this could be of use within AE2.

Yes, there have been problems with SFM in the past :)  But that had more to do with the tricky nature of these deep storage systems and the badly-designed nature of Minecraft inventories.

**Comment by yueh** [comment]
Providing nonexistent items is more or less broken and will result in dupes. Maybe not with AE2 or StorageDrawers itself. But what I have seen with the AE2/SFM integration is, that it considers any reported item to be existing, which in my personal opinion is at least not wrong. Maybe a bit gullible, but announcing nonexistent items is then also gullible in a similar way.

You are probably just lucky that most mods are either actually validating each and every item that they want to extract and not rely on the inventory content, canExtract and try to remove any used items at the end (when it is too late)

But for the AE2 integration you can only announce what is actually stored. Say if it actually has 11 iron ingots stored, then you can only announce 1 iron block, 1 ingot and 9 nuggets (or any other combination resulting in 11 ingots total), otherwise it will simply result in unexpected behaviour.

**Comment by jaquadro** [comment]
That we have mods like JABBA in the first place requires some level of validation already, because IInventory is going to spend some time in weird states.  I don't see how this really differs from what compacting drawers do.

While the compacting drawer reporting does require some awareness as to what's going on, switching its behavior could actually break an AE system if it's given high priority.  If I only report nuggets, the system would never be able to represent an ingot or block as every insertion would immediately convert.

**Comment by expl0s1ve** [comment]
Well I don't know about the potential bugs but I'm pleased with how it currently works.

**Comment by yueh** [comment]
Maybe JABBA is in a weird state, but it does not report 123 million cobblestone, if it has only one.
The `IMEInventory.getAvailableItems()` is named intentionally `available` and not `potential` items.
The autocrafting works as a simulation on top of the available items, to calculate if it has enough items available. Should it work on invalid input data, it will simply produce bogus.

If you want to do it correct for AE, you need to report it similar to the WAILA display. So report it as 0-N Iron Blocks + 0-8 Iron Ingots + 0-8 Iron Nuggets, based on what fractions are left over after converting everything to blocks. Of course you can change the thresholds and say only overflow to the higher item after you have 1 stack stored.

What you can actually do is to not announce it as inventory (or just nuggets), but as an `ICraftingProvider` which then also provides crafting for ingots and blocks, thus the crafting simulation can still calcuate with the correct amount of available items. But speedwise it will be mostly similar to the normal autocrafting.

**Comment by jaquadro** [comment]
Even with an ICraftingProvider, if I only expose nuggets, users still won't be able to extract blocks or ingots from the system.  You'd have crafting recipes in the interface but trying to craft them would just convert them back to the base material if they end back up in the main system.  It would solve the remaining crafting problems.

An arbitrary tiering for block/ingot/nugget might be the most workable compromise, but it has similar problems where you need at least 80 ingots worth of material in the system before you can pull a single block out.  It makes the terminal experience less useful and external system interaction less intuitive or useful, though I will take some time this evening to play with the SFM/AE2 combination.

**Comment by yueh** [comment]
An `ICraftingProvider` would provide the required recipes for ingots/blocks. No need for an extra interface/patterns. But the user has to explicitly craft them and not simply extract them.

I can only repeat, AE2 is not designed to work with fake items during any simulation phase, as no extraction will appear and any solution would be AE2 specific due to the `IExternalStorageHandler`.
We will not start to dupe items like SFM as there is still a modulate phase actually verifying it.
Maybe we could add a notice about the crafting failing due to not enough materials. But this would be very confusing as a player would see the actual amount just tripled inside the terminal and can wrongly assume there should be enough.

**Comment by jaquadro** [comment]
I would like to find a solution that makes the inventory fully compliant with your crafting system, but does not result in the block being a headache for all other inventory management.  If I knew what system was calling the IExternalStorageHandler, then I could alter the behavior based on that.  But I don't believe I have any way to get such information.

**Comment by expl0s1ve** [comment]
As a regular player and NOT a perfectionist, I wouldn't change anything so simple, it requires so much thinking and has very little outcome. As long as it doesn't cause exploits, I don't mind keeping this in mind while using autocrafting. 

Plus, if you don't have the nugget/block patterns in the MAC interfaces, the odds of this happening is astronomical; you need to be crafting something that use at least two of the said counterparts of the same material (bloks/ingots/nuggets) and you need to have not enough materials. For example, if you're crafting Notch Apples (or an ME Interface, or pickaxes, basically almost anything) the simuation will never fail. On the other hand if you're crafting golden angel wings from extra utilities (that require 4 gold and 2 nuggets) and have only 4 gold ingots in your compacting drawer (AE thinks it has 36 nuggets) the crafting will fail. 

I'm surprised that even came up in the first place. Anyway sorry I know I didn't need to explain so thoroughly but I got carried away. :) 
(or maybe I'm just dead wrong)

**Comment by geech** [comment]
So, I may be a programmer and I might not understand all the intricacies of minecraft modding but it sounds like the compacting storage drawers need to be changed from a block that stores and shows all possible items that *could* be stored in it changed into a block that is something like a storage/packager/unpackager combo rolled into one.

But anyway, this sounds like less of an AE2 issue as I thought it was (even though AE2 could probably add some kind of special integration, but if everyone got special treatment the mod would be large and unwieldy) but a storage drawers confusing feature causing AE2 to act weirdly.

**Comment by jaquadro** [comment]
I don't have any hard statistics, but I would guess that the comp drawers are the most-liked part of the mod, and AE2 is the most-liked integration.  This is the first time I've been notified of failure in the crafting system.  This is a Storage Drawers problem, and I understand why the requirements are what they are.  But as expl0s1ve points out, I think this is also a very remote problem, or I would have heard more about it.  Other than that, I think the current integration works well and that most players understand what they see in the terminal and find it intuitive.  It's consistent with how the drawer's native interaction and IInventory behavior works, and this has been propagated to other systems like Automagy.

Your suggestion that a comp drawer should be an auto-packager that holds its items is not so different from the above suggestions of tiering.  It would fix AE2 autocrafting (combined with a crafting provider), but I think it would clash badly with everything else.  How will you get nuggets or ingots out through a terminal or bus if you have an auto-packager watching the network at all times and greedily compressing your items as they are inserted or crafted?

My biggest concern is really the one yueh pointed out earlier, which is the risk that another mod could mis-handle the inventory.  It's not a risk that's unique to AE2, as it could also happen through normal IInventory interaction, and that's a wide-open door.  So far, I've had at least a dozen duping and destroying bugs related to deep storage implementation, and none related to false advertisement.  I'm also somewhat reassured in testing SFM auto-crafting that it behaved well with the comp drawers trying to pull multiple item tiers.  I'd like to test it through AE2 as well, but absolutely cannot figure out how to get SFM to talk to AE2.

**Comment by yueh** [comment]
Honestly the first time I tested them, I immediately had known this will at one point show up as isse.
Not very likely, but then I expected it to take a bit longer.

I am currently have no idea how to actually solve it. But you should keep in mind that you already have different interactions, which can be handled differently.

Even if you change it to work internally like a packager, the actual player interaction can just work as currently and allow them to extract whatever they want by interacting with the block.
You might store everything internal as nugget and then just remove 81 nuggets of someone fetches a block of iron. But that is purely an implementation detail and not something a user will notice.

Then there is the `IInventory`, which is used by like every existing TileEntity, so the machine level.
This is probably the level, which probably needs to be 100% correct about which items are actually available.
Someone with more knowledge about forge internals can provide more insight. Maybe it is even ok here to report theoretical items. Nevertheless this is not required for the AE2 interaction as this is handled by the `IExternalStorageHandler`.

Your own `IFractionalDrawer` can probably solve the integration for any mods supporting theoretical items. This will not require that you write an integration for every possible mod. But any mod ok with theoretical items can opt in by writing their own integration for it. This would increase the amount of work for each mod developer a bit, but is probably the safest approach. Maybe these devs can even work together for a common API, so anyone just needs to create one integration for and and not every mod which has similar functionalities. (Thinking of any Equivalent Exchange mod, as they will face the same issue with a deeper AE2 integration)

At last we have the AE2 integration, which is a bit tricky. As `IExternalStorageHandler` you can only provide items, but not crafting via `ICraftingProvider`, this would also require joining the AE2 grid. Just hook up a cable in terms of player interaction instead of a storage bus. Then you could act as storage for the smallest/nugget item and provide crafting patterns for the 2 higher ones. Probably be wise to provide `nugget => ingot` + `nugget => block` instead of `nugget => ingot` +  `ingot => block` as this will usually be faster as it eliminates one crafting step. But even this is not without pitfalls, say in case there is also an `ingot => block` pattern provided by an interface, it can potentially use this and just use the storage drawer for ingots.
Requestable items might also be something to consider, which mostly indicate that something has not stored them, but can provide them on request. Thus it should not fail when starting a crafting job, but simply get wait until the drawer can fullfill the request. But I am not certain, if this is usable through a storage bus.

**Comment by jaquadro** [comment]
Internally, it will always operate as a nugget/base material store -- essentially the opposite of an auto-packager.  Anything being discussed is really the presentation on top of that, lightly constrained by the rest of the storage API it's built around.

On the IInventory level, I think the vast majority of TEs don't even need awareness, because they operate in a serial manner on slots.  Of the small handful that could have a problem, I would prefer to try and work that out with the author.  Most likely, a small tweak to the inventory handling would be sufficient without needing to drag out any additional APIs.  IFractionalDrawer was created at request of the Automagy dev for purposes of cost calculation, rather than manipulating inventory.

On AE2, manual crafting request is the part that I am still unclear on, and think would be broken.  Consider a system with a comp drawer attached at highest priority.  As a grid device, it exposes only gold nuggets, and provides crafting recipes for ingots and blocks.  What then happens when I request the system to create some ingots so that I can pull them out?  Those items are going to return to the storage grid first.  If the comp drawer is operating as intended, any ingot or block would be accepted for storage and "returned" to nuggets.

**Comment by yueh** [comment]
I really have no idea how to fix it currently. There are a few somewhat hacky approaches. 
Like you could monitor the crafting requests and then dynamically adjust the splitting. Say if someone requests 100 iron ingots you will report 100 ingots until all are extracted.
Or use the `BaseActionSource` to cache the result over multiple extract calls and report a matching amount (like 33% for each item)

**Comment by jaquadro** [comment]
Do you have any more information on monitoring crafting requests? (What APIs to look at, requirements on how I need to connect to the network, etc.).  It's a little hacky, but if I can query the crafting status during extraction, I think it would be a big improvement over the current state.  I'm willing to spend some time playing with it.
