### ISSUE TITLE
P2p tunnels losing connection causing massive console spam and timeouts

### ISSUE THREAD

**Issue by AiwendilCiunio** [AppliedEnergistics/Applied-Energistics-2#1872]
This happened a few times before, but only now did I realize that this could have been the cause of timeouts on our server.

Occasionally, for no apparent reason, some of my p2p connections would break. This cause a massive spam in console:

http://pastebin.com/d6mq2vpE (search for p2p entries)

After I removed and replaced the tunnels, spam stopped and so did the timeouts.

ae2 version rv2-stable-10
Infitech2 modpack

If you need more data, please let me know.

**Comment by yueh** [comment]
I am note really positve that 64 log entries count as spam. Especially when about 2/3 of nearly 3k lines are produced by "info.servertools". Maybe start by testing it without this?

Also these are just notices that the P2P tunnels could not create a connection, usually because the connected networks are owned by different players. This is more or less the same as when you prevent a connection between two cables with a cable anchor or similar.
The log entry was mostly added that people can identify these connections, but sometimes it feels anything written to the log is immediately consider as an error...

But without any actual information, I have no idea how to really help you.
Just looking at the log will most likely not solve any issues. You probably need to actually start profiling the server and identify what is actually causing it.

**Comment by AiwendilCiunio** [comment]
Let me clarify - this is in my base, I placed all these tunnels myself, also they're all inside one network that's about 6 chunks big.
Are you suggesting that tunnels randomly losing connection even though they were working an hour ago and noone touched them since then is an intended behaviour?
Also everything seems to suggest that this indeed was the cause of timeouts on the server, since it all stopped after I replaced the tunnels.

**Comment by yueh** [comment]
All I am saying ist there is not enough data to determine the actual issue.
Currently it is just guessing, which helps noone.

For example these servertools seems to provide something like permissions or are maybe interacting with the server in a different way than normally with just forge and thus somehow affecting how AE2 is saving the owner of a cable or similar and thus causing issues further down. Or another example is ExtraCells, which can have some nasty effects on the server performance in some cases. And so on.

The best option to make a backup and start removing mods or even just start with only AE2 and see, if is still causing timeouts. If not it is probably some interaction with another mod and you can start adding them back until it will happen again. If it is still happening with AE2 only we really need profile of the server, what can be done with jvisualvm or maybe the sampler mod by player (see fastcraft). But not Opis, this will not provide any useful information for us. In my experience it is simply not able to detect AE2 as we do not use any ticking TileEntity.

**Comment by ruifung** [comment]
*Off topic*
@yueh If extraCells has performance issues, could you please inform me =P, I don't know the AE2 codebase that well so I can't really hunt down said performance issues unless someone gives me some pointers to start from.
