### ISSUE TITLE
[Feature Request] Cables that can transmit 64 channels

### ISSUE THREAD

**Issue by Silly511** [AppliedEnergistics/Applied-Energistics-2#1883]

**Comment by yueh** [comment]
No

**Comment by Blue64** [comment]
Alternatively, make your own Add on which adds these Hyper Dense Cables you desire, but considering that it's already possible to EASILY surpass 256 channels, just by using ONE line of each Color of Dense Cable (not counting Fluix), I seriously doubt you really need this, especially since to add more channels to an already maxed network, all you need to do is add a sub network to it (avoid direct recursion if at all possible, maybe throw a few chests and a Hopper in the middle for recursion)

**Comment by thatsIch** [comment]
We have a hard-coded upper limit at 32 channels. Not even addons can circumvent that.

**Comment by Blue64** [comment]
Thats impressive
