### ISSUE TITLE
Missing Recipes

### ISSUE THREAD

**Issue by soulknight72** [AppliedEnergistics/Applied-Energistics-2#1890]
No other mod has this issue, but most, if not all, crafting recipes for AE2 are missing. The items are there, and the items themselves work fine. But even when i put the correct items into the crafting grid, nothing comes out.
I've tried reinstalling, tried it with no other mods, and have the newest 1.7.10 Forge Loader, and the problem still exists.

**Comment by yueh** [comment]
Need more information like the fml-latest.log

**Comment by soulknight72** [comment]
The what? Where do i find this?
And what other information do you need?

**Comment by yueh** [comment]
A good starting point about what informations are useful can be found [here](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/CONTRIBUTING.md#reporting-an-issue).

The `fml-latest.log` can be found inside your instance folder inside the `logs` folder, but it is most likely be named `fml-client-latest.log` since the name depends on being clientside (including singleplayer) or serverside.

**Comment by soulknight72** [comment]
A lot there. I'm scanning for stuff relating to the mod, so far no red flags that i can see.
Anything I should be looking for in particular?

**Comment by thatsIch** [comment]
If you are playing a modpack, make sure the changed recipes are intentional. In modpacks the recipes displayed in the wiki are not valid. Use NEI to identify them.

**Comment by sokratis12GR** [comment]
I have the same problem, but even the NEI don't show Recipes, Please help

**Comment by thatsIch** [comment]
Upload your log file as stated above

**Comment by Blue64** [comment]
I've been slowly patching this problem via MineTweaker/ModTweaker, I play SSP offline, and I've not had the AE2 recipes possible for months. I have no idea what broke it, and I shall upload a Log shortly, along with the list of Mods I'm using. Anyone by chance know how to add Inscriber Recipes? MT doesn't have very solid documentation. I also looked into it being a Folder issue by creating a new Superflat World, the problem still persisted. Even the Meteorite Compass has no recipe. I do hope the problem gets identified and resolved, as this is getting rather frustrating.

**Comment by Blue64** [comment]
I found a rather large issue, it can't find the %appdata%\.minecraft\config\AppliedEnergistics2\index.recipe file during initialization, that could be causing the problem easily. I'll manually throw the file in there and report back to let y'all know if it worked.

**Comment by Blue64** [comment]
I used 7-zip to extract the entire recipe section of the .jar into the \config\AppliedEnergistics2\ folder, it worked flawlessly. Now we know the appropriate fix for this problem.

#Issue Located
#Solution Located

**Comment by sokratis12GR** [comment]
You could just reset the recipes from the forge  config ingame and then
restart your game. this alot easier

**Comment by Blue64** [comment]
I thought I did that once already actually, with no result whatsoever, but good advice nonetheless. I shall note if the issue arises again as I'm going to be redoing my mod setup soon (crashed my game world, thanks OresPlus, now if only it removed the erroring tile entity [OresPlus Grinder & Crusher both], which should be covered by the "erroring entity" option of forge)

**Comment by thatsIch** [comment]
If you use a later version of AE2 rv3 it should handle the recipe configuration for you. I know for sure MT has an inscriber integration though, since we broke it with the Inscriber API we added. I am not familiar enough with MT though, sorry.

**Comment by Blue64** [comment]
It's the custom recipe boolean causing the issue, it doesn't extract the recipes out of the jar when first enabled, AE2 rv2 v10 needs to do this manually, I used 7-zip to get them, works fine now, just leave the recipe files in the \%appdata%\.minecraft\config\AppliedEnergistics2\ folder and it should resolve it's self next time you launch MineCraft. It's just an issue with it only checking for custom recipes and not checking for original.

I'm glad to hear it's fixed in rv3, but I'm waiting for it to go from Beta to Stable before I upgrade xP
