### ISSUE TITLE
Low TPS with large AE system

### ISSUE THREAD

**Issue by Namikon** [AppliedEnergistics/Applied-Energistics-2#1904]
I've been busy monitoring our server over the past weeks, to find the cause for the low tps we have. After a while, I figured out that one player has build an impressive AE system which by itself drains 2500 EU /t just with normal workload and autocrafting. If this AE system is online, the tps are dropping down to 2-5 which makes it almost impossible for others to play. However, it is not bad right after he switches it on. It takes about 20-30 minutes until it gets really bad.
I used warmroast to see what's happening, and it seems that the most time is spent on
`appeng.me.storage.CellInventory.extractItems()`

Now my question is, is it possible, that his AE system is just too large for our Server? I haven't counted his import/output busses, nor the interfaces. But just opening the terminal takes almost 10 seconds.

The full warmroast screenshot is here:
http://imgur.com/ddI0shC

Is there anything I could do or check to improve the performance? The Server is running forge 1492, AE version is "rv2-stable-9".
It is a private modpack with a ton of mods, including thaumic energistics. A full list of mods and versions can be provided on request

**Comment by XFactHD** [comment]
1. How many GB of ram is allocated to the server?
2. Do you have ExtraCells?

I am playing on single player (with ExtraCells and ThaumicEnergistics) with 10 GB of ram allocated to MC and I have a ME system which consumes about 12000 RF/t and I have 20 tps constantly.

**Comment by Namikon** [comment]
Allocated ram is 8GB, although the Server is barely reaching this limit. And yes, we use ExtraCells; v2.2.74b140.
As I said, it's really weird. You can still play, there is no crash nor timeouts. It's just using a ton of time to do the described function, and the time to break a block is measured in seconds :P 
If he switches his AE off, the TPS skyrockets back to 20 within a few seconds

**Comment by yueh** [comment]
First of all, do not use warmroast. It is merely a toy and not comparable to something like visualvm or the sampler mod. Also do not post the screenshots as this is even less helpful, always post the full `.nps` snapshot.

But this particular case is caused by your player probably having a ton of export buses constantly requesting something to craft, say in rapid succession or constantly failing ones (most likely failing ones). Each request needs to be calculate even when failing and this will simply add up.

RV3 should bring some improvements, but they will not be extremely huge ones. Simply because there are to many strange inventories around, which require to be checked for every single crafting request.
The best option for now is letting the player fix their setup and toggle these export buses on when actually required.

One issue I currently see, is that export buses do not respect failed crafting requests for their dynamic tickrate. This should clearly be changed so they will slow down after enough ones have failed. By default they tick between every 5 and 60 ticks depending on the load. This is also configurable in the settings, so a server could even increase the max tickrate of them quite a bit.
But as long as a single request goes through, they will speed up to their fastest tickrate over time.

Another issue might be that cells are using a unnecessary complex data structure, potentially something which could be further improved, thus scanning them for every request would be faster.

**Comment by Namikon** [comment]
Aha, ok thanks, now I have a vague idea. I will check if he has these export busses, then we can check (by disabling those) if they cause the problem. And I only knew warmroast (besides opis) to get at least *some* information about what's going on. Gonna dig into that nps thing now.

**Comment by XFactHD** [comment]
@Namikon does this player have a "Super Soaryn Drive" (arrays of 6 drives with a storage bus and an interface)?

**Comment by Namikon** [comment]
We've checked his system, and no he doesn't have those. All drives are attached to the main AE network. He does use a ton of P2P tunnels, but no Soaryn drive setups.

**Comment by thatsIch** [comment]
another thing you can consider is upgrading to latest alpha. Since this is private modpack, upgrading should be easy.
