### ISSUE TITLE
Improvements to Cell Workbench

### ISSUE THREAD

**Issue by ruifung** [AppliedEnergistics/Applied-Energistics-2#1923]
- Ensure the displayed inventory matches the cell config inventory as in ExtraCells for fluid cells items are turned into placeholder fluid items.

EDIT: Heck I noticed it's calling getConfigInventory  everytime a change is made. And updating the display for every slot... except the one clicked. 
- Call isValidForSlot to check if the config inventory actually accepts that type of item for configuration.
  --- this isn't a problem if the first issue is addressed.

**Comment by thatsIch** [comment]
So change `ICellWorkbenchItem::IInventory getConfigInventory( ItemStack is )` to `ICellWorkbenchItem::IMEInventory<StackType extends IAEStack<StackType>>`?

**Comment by ruifung** [comment]
not a bad idea actually, although... how would clicks on a nonempty slot be handled hmm? I don't quite think IMEInventory can handle that scenario?

**Comment by ruifung** [comment]
But that aside, there is a inconsistency between the displayed inventory and the actual inventory if that inventory doesn't just set the item as passed in or doesn't set on the slot thats passed in. - At least until the cell is removed and replaced into the workbench,

**Comment by yueh** [comment]
Changing the signature will not change anything, the used slots require an `ItemStack`.
It would actually make it worse as `IAEStack` has no way to obtain these and we have to implement it for every possible addon on our side as compared to allow the addon handling the conversion.

Improving the fluid support makes absolutely no sense without adding full support for it and making ExtraCells itself more or less obsolete.

I do not know the actual architecture of AE1 and if already did use the same grid approach as AE2. But the only reason for the minimal fluid support in AE2 is more or less only to share it across different networks via interface/storage bus and maybe for an easier registration of different cells.
Otherwise it could just be another grid service.

Dropping the whole fluid support is probably a way better idea and then replace it with a generic storage approach, thus allowing any addon to share their storage with other networks. Which would more or less result in dropping the `StorageChannel` enum and replace it with something similar to the `IGridCache`.

**Comment by ruifung** [comment]
what? I don't really need an IAEStack - ItemStack is fine, but the main issue i have is when my setStackInSlot doesn't change the slot passed in and doesn't set the itemstack passed in as I swap those for fluid placeholder items.

**Comment by yueh** [comment]
Further the slots also require an `IInventory` as the slots are just slightly changed vanilla slots, which probably do not synchronize as it is in nearly all case useless to check something like "did I really just place 4 cobblestone into the slot after I placed 4 cobblestone into the slot".

Could it maybe be an issue on your side? Maybe you only replace the item inside the partition list, but not for the `IInventory`, thus forge/vanilla simply not updating it? I never have checked this, but this should for example still happen when two players are using the same workbench, as the cells are handled serverside and thus shared.

**Comment by ruifung** [comment]
It is replaced for the IInventory - its being done in setStackInSlot.

**Comment by ruifung** [comment]
https://github.com/ExtraCells/ExtraCells2/blob/rewrite/src/main/scala/extracells/core/common/inventory/InventoryECFluidConfig.scala - this is the  relevant inventory

**Comment by yueh** [comment]
Just was an idea. Maybe it is simply impossible to replace these items dynamically and have minecraft/forge handle it correctly and sync it back to the client.

**Comment by XFactHD** [comment]
@ruifung you could probably do it the way @Nividica did it: https://github.com/Nividica/ThaumicEnergistics/blob/master/src/main/java/thaumicenergistics/tileentities/TileEssentiaCellWorkbench.java

**Comment by ruifung** [comment]
He. reimplemented the entire cell workbench - for reasons I now understand - and I do not wish to reimplement the cell workbench in EC.
