### ISSUE TITLE
Encoded Patterns - importing / exporting into different worlds / modpacks

### ISSUE THREAD

**Issue by seppp** [AppliedEnergistics/Applied-Energistics-2#1928]
i would like to request this feature.
i just love AE2 and usually always "work" with it asap when i start a new world or modpack.
it's a real hassle to everytime encode new patterns for the simplest recipes i memorised years ago, and also other ones i have already encoded hundreds of times. sticks, pistons, planks and up to ingot smelting in furnaces and other stuff.

player inventory ex/importing does not work.

newb idea: maybe save them in a separate file than can be copied between worlds?

**Comment by yueh** [comment]
Probably a nice feature, but it has some difficult issues when implementing it.

First of all is how minecraft actually stores items. To allow a reliable way of transfering them between two worlds the following conditions need to be true when creating both worlds.

* Exactly the same mods/modpacks being used
* Exactly the same version for every single mod
* Exactly the same config options for every mod
* Exactly the same minecraft instance (no restart between creating both worlds)

This is roughly sorted in a descending order of how likely issues can appear, so restarting the client will in most cases work, but modifying mods or the modpack will certainly result in invalid patterns when transfering them between two worlds (when they are even still patterns and minecraft did not simply change them into a plank).

More likely would be something similar to the buildcraft template (?) library, which can share configs between multiple worlds (A separate file would also require this approach).
But this would more or less mirror the current way to encode patterns. Like "open the pattern library, select the pattern, hit encode" vs "open the pattern terminal select item from NEI, hit encode". Maybe saving a shift click.
With a pretty massive downside, as most of the patterns will not be useful for you except you play exactly like the world before. For example your old piston recipe, if you used oak planks in our old world because you had a farm for oak wood, you will also need an oak farm in the new world. If you want to use another wood type, the old pattern will simply not work for this world. It is basically the same issue the AE2Stuff has as it will produce patterns with a high chance of simply not working reliably (and other disadvantages).

Also balancing would be an issue, we cannot simply spawn a new player with thousands of patterns floating around them. Like no other mod spawns you fully equipped just because you already used crafted these items in another world.

Maybe @thatsIch has some ideas about how to solve in in a reliable way and not break in every other case.

**Comment by seppp** [comment]
also related to this (ill open a seperate ticket if you so wish):
is a creative "do it all" pattern possible? 
i am thinking of something like import ALL THE THINGS possible from NEI..

**Comment by yueh** [comment]
No, as every pattern can only provide a single output item.

**Comment by seppp** [comment]
Creative molecular chamber maybe?

**Comment by thatsIch** [comment]
The idea was a brute-force export and import. Basically trying to match every item possible. Even using stuff like localizations and unlocalized names?

Since this is a process which is **not** done on every start-up nor being passive, this can be computational expensive.

Validations of recipes **if** it being a crafting bench recipe is probably required. Would display something like **missing item.localiedName()** so they know which recipe it was. This information does not need to be created in the pattern itself but can be applied upon spawning e.g. via command? `/ae2 importPattern`. or provide a way to say `/ae2 importPattern noIllegal` or something along the line, which do not spawn the recipes in this world, which are not appliable because a mod is missing.

In the end @seppp is this really faster than encoding it new? :laughing: Required to sort tons of pattern is probably very time-consuming too

**Comment by seppp** [comment]
I understand. It is definitely not a must have, just an idea I had that
seemed to be nice.

Thanks for the effort of thinking about it though!

**Comment by thatsIch** [comment]
I guess if you do not own NEI this could be a nice to have.
