### ISSUE TITLE
VersionChecker unhandled exceptions

### ISSUE THREAD

**Issue by DestinyPlayer** [AppliedEnergistics/Applied-Energistics-2#1932]
My friend has that weird freeze issue. From what he sees, there's some weird exception in AE2 VersionChecker which freezes his game dead stop.
https://dl.dropboxusercontent.com/u/77108893/Crash%20Reports/AE2%20log.txt

**Comment by yueh** [comment]
This is just a notice created by the JVM, but no case for any freeze.
But we should really have a better exception handling for invalid version configurations.

**Comment by DestinyPlayer** [comment]
But still, there's still some weird dead-freeze issue. Are you sure it's not due to AE2? Any ideas what might cause it? Because the game constantly freezes up for my right after that message.

**Comment by yueh** [comment]
Yes, the version checker intentionally runs inside its own thread to prevent it from affecting the main minecraft one. It is even marked with a low priority, in case the JVM wants to defer the execution in case it is heavily loaded.

It is probably just the last entry, because the JVM probably decided to stop the thread and just adds this notice to the log. There are also a couple of other exceptions logged, like the ones from Witching WitchingGadgets.
But I would consider JourneyMap as possible offender, it immediately started a second earlier and I had similar issues with it myself until it has finished the rendering. As far is I remember it is also multithreaded, so this might be the cause why the JVM stopped our version checker at this moment.

**Comment by thatsIch** [comment]
I would wonder more why the `stable` is not matching with either `alpha, beta` or `stable`. I do not see any code flaw regarding that logic issue.

also your `EventBus` overflowed which is there for stitching the textures together.

**Comment by yueh** [comment]
Probably due to #1521

**Comment by thatsIch** [comment]
oh my, that was ages ago.
