### ISSUE TITLE
[Suggestion] Alternate Crafting Recipie For Inscriber Patterns

### ISSUE THREAD

**Issue by mikeloeven** [AppliedEnergistics/Applied-Energistics-2#1933]
I have been using AE in my builds for a while I took a break from MC and when i come back what do i fine a brand new AE and for the most part there are many improvements however the major showstopper is the inscription patterns. Where did this meteorite idea come from in the first place it is beyond stupid. unless these meteorites are spawning in real time they result in a situation where on populated servers with either a large population or a hard map limit it literally makes one of the most critical components of the AE mod a finite resource and no matter how i look at it it is simply a absolutely horrible design. 

Players should be able to progress in the mod by their own merits their own grinding and their own mining operations. making inscriber patterns so rare and providing no other method of crafting ME chips destroys the capability of players to progress past a certain point unless they get lucky 
(i have tried the compass and it repeatedly gets false positives leading me to biomes where there are no meteorites

I would like to request a sane progression mechanic that allows production of chips using legitimate crafting mechanics and sane resources

**Comment by yueh** [comment]
#1514

**Comment by mikeloeven** [comment]
you really used my post to necro a issue this old ?

but regardless the issue goes beyond the ability to make custom recipes to the fact that should this unsustainable unfair and clearly flawed mechanic be the Default setting??

the simple fact remains that administrators frequently use default modes because often times they cant be bothered to change the configs or in the case of plug and play servers do not have the technical skills to even follow the instructions

the issue is not about whether or not there is a workaround the main issue is making sure the AE mod remains accessible to all players not just the first few people on the server its a much deeper issue than this and i am shocked that in so many months this still has not been fixed because there is simply no legitimate way to justify the current mechanics because it completely unbalances the game and gives a select few lucky players a complete monopoly over the mod

the issue is not that people want a easier recipe for the inscriptions the fact is that they want A! recipe for the inscriptions in the first place

the sky-stone chest mechanic simply does not work, cannot sustain in a highly populated / limited radius server

**Comment by Pyeroh** [comment]
So admins of your server should be aware of the way to get inscriptions pattern, and make these available by another way (CustomNPC, quests, events, etc.), or a new player should ask an "older" player (on the server) if he could copy pattern for him (or her).
If your admins are not able to manage a server, and by that I mean at least have the required technical knowledge of the mods they manage, then they shouldn't be admins.

By the way, on the server I play on, I got every inscription pattern, and the map is limited, but if any player doesn't find anymore meteorite, I'll be glad to copy pattern for them. And meteorite compass search for skystone blocks, so if it points to a chunk, and you don't see any skystone block, it doesn't mean there is no meteorite (hint : did you dig ?).

As it was said in the referenced issue, this place is open for issues and suggestions, but if you suggested something, and you was told no, then you should deal with it, and find your own way to work around it. I'm a big fan of mods, but I almost never ask for features that ever exist, but that don't suit my needs. There are enough mods to modify gameplay and mod rules to don't ask to change a feature.

(I hope I've been clear, because english is not my native language, so feel free to correct me ;) )
