### ISSUE TITLE
AppEngCore.toString() does not return ModId

### ISSUE THREAD

**Issue by Nazfib** [AppliedEnergistics/Applied-Energistics-2#1953]
071ae6d6808a701afd95f22762a9a39e8cede3d5 changed `AppEngCore.md`
into `AppEngCore.metadata` This broke the class' `toString()` method; it now returns the FML default string `"Dummy Container ("+label+") @" + System.identityHashCode(this)`

This appears in the modlist as returned by `Loader.instance().getIndexedModList()`
For example, [ServerSync](https://github.com/superzanti/ServerSync) uses this string to compare the mods installed on the client and server. Because the result of `toString` is different for each launch of Minecraft, the comparison always fails.  
In my opinion, since the metadata for the coremod is defined, `AppEngCore.toString()` should return the modID. See #1954

**Comment by yueh** [comment]
I have a couple of issues with this.

First looking at `DummyModContainer` makes it clearly visible that the whole class itself is broken/bad designed and should be handled on their side. But as usually Forge will most likely refuse doing so, because it might break broken implementations (which should clearly be fixed).

Secondly depending on `toString` for anything besides debugging is a bug. It is not intended for machine readable output, only for a human readable representation of the instance. Adding any random value to it is a perfectly valid option.
Thus I really do not see any reasons to provide a workaround to fix a bug located in another mod.

**Comment by thatsIch** [comment]
I am wondering why would you favor `toString` over `getModId`

**Comment by Nazfib** [comment]
Basically, `Loader.instance().getIndexedModList().toString()` gives a mostly nicely formatted list of mods. This method called `toString()` on every entry. ServerSync (used to) use this list to determine if a client needs updating. However, I already fixed this with a PR into ServerSync's repo (it now uses `getModId` and `getVersion`). This fixes the issue for me.

**Comment by thatsIch** [comment]
This sounds like a better solution,

cheers.
