### ISSUE TITLE
[AE Compass Service/INFO] [AE2:C/]: Failed to create AE2/compass/

### ISSUE THREAD

**Issue by DestinyPlayer** [AppliedEnergistics/Applied-Energistics-2#1960]
So, there's this weird problem. It doesn't crash the game, but it completely overspams the whole console, and probably causes lags, although I'm not sure about the lag part.
Log - https://dl.dropboxusercontent.com/u/77108893/Crash%20Reports/AE2%20Can%27t%20Create%20Compass.log
Modlist - https://dl.dropboxusercontent.com/u/77108893/Crash%20Reports/SCREEN%20AE2%20Can%27t%20Create%20Compass.png

**Comment by yueh** [comment]
This indicates that AE2 cannot create the necessary folders inside the current world.

See #911, #397 for more information.

**Comment by mindforger** [comment]
@yueh did you notice the OS language in the screenshot(upper left corner below the 1.7.10 folder)? maybe there is a charset related problem or something? i remember some very old (unresolved because missing feedback) issue about a problem with the OS charset/codepage, but i can not find it

**Comment by DestinyPlayer** [comment]
The OS language never was a problem until now. Maybe it's a mod conflict or something? Maybe ChromatiCraft is to blame, because it happened only after I installed it?

**Comment by yueh** [comment]
No idea. The few cases reported were one time issues, most likely because some mod leaked the current world, resulting AE2 in obtaining the wrong folder for the current world. A restart usually fixed it.

If ChromatiCraft now makes it appear every start, then it is probably their issue.

It might also report to any mod (like the Tardis one) that the AE2 Api is not intended to be shipped with their mod and can potentially cause issues. I really should consider pulling that PR which throws an exception in this case...

**Comment by gamecompiler** [comment]
If youd use BOP:

Could it be that Biomes o plenty has a problem with AE mod rv2 ? Appearantly that "Bug" do not appear when using the default WorldGen.

I try to figure out why BOP-1.7.10-2.1.0.1394 and AE2-rv3-beta-1 work perfectly, but BOP... with AE2-rv2 not.

So the "resolution" for this problem is to update to rv3-beta-1.

**Comment by mindforger** [comment]
this is very necro and again use the latest beta1 is very bugged that is a very bad advice of yours
