### ISSUE TITLE
rv 10 crashes to desktop; ticking memory error

### ISSUE THREAD

**Issue by cocopuffs99** [AppliedEnergistics/Applied-Energistics-2#1961]
http://pastebin.com/k3SWpELC

**Comment by yueh** [comment]
Nothing indicates any issue related to AE2.

**Comment by cocopuffs99** [comment]
Do you think it might be related to a mod interacting with AE2?  When I remove AE2 I can launch and load up just fine; adding it again produces the same error.

Thanks =)

**Comment by siasur** [comment]
You have multiple mods which doesn't like each other...

Mantle Environment: DO NOT REPORT THIS CRASH! Unsupported mods in environment: optifine
EnderIO: Found the following problem(s) with your installation: "Optifine is installed. This is NOT supported."
Hardcore Ender Expansion: CAUTION! Ars Magica 2 is not supported by HEE, if the crash is caused by a conflict of the two mods, it will very likely not be possible to fix.

**Comment by thatsIch** [comment]
try removing BetterFPS

**Comment by Blue64** [comment]
I've always wondered, why all the hate on Optifine? On a related topic, why do some mods not fix these problems? They obviously know that the problem is very narrow and specific to at least 1 mod.

**Comment by XFactHD** [comment]
@Blue64 To improve MC's performance, Optifine changes vanilla Minecraft code and as it's closed source, nobody knows what it is doing, meaning it is impossible to adapt the render code to the changed code.

**Comment by Blue64** [comment]
Ooh, that is unfortunate. I assume nobody who tried getting ahold of the developer could get a copy of the source code either then. Hopefully they one day make it open source.
