### ISSUE TITLE
shift clicking ? in NEI auto fill recipes to ME Pattern Terminal

### ISSUE THREAD

**Issue by DGPhil** [AppliedEnergistics/Applied-Energistics-2#1979]
![3](https://cloud.githubusercontent.com/assets/6955282/10864997/5ae404d0-8039-11e5-809d-9a483ba42d49.jpg)
![4](https://cloud.githubusercontent.com/assets/6955282/10864998/5b697304-8039-11e5-8043-54bfb6e3e4bd.jpg)

I have a question about ME Pattern Terminal. I think the auto fill recipes is a very useful function. But something wrong? Please look at these pictures. Sorry for my poor english.
mod version: AE2 RV2 stable10, NEI 1.0.5.118, neiaddons-1.12.11.36, NEIIntegration-1.0.12
forge: 1492

**Comment by wlhlm** [comment]
You are missing an Engineering processor. You need to have at least one of every type of item needed to fill in a pattern. That means in order to make a pattern for the ME Controller you need at least one Sky Stone Block, one Pure Fluix Crystal, and one Engineering Processor in your ME System or Player inventory.

**Comment by DGPhil** [comment]
Thank you for the help.
