### ISSUE TITLE
Blinking Drive Lights

### ISSUE THREAD

**Issue by haXs** [AppliedEnergistics/Applied-Energistics-2#1993]
Hello, 

Apologies if this has been requested before but I cant find any reference to it, In AE1 there was a config option to enable the drives to blink when being access but this feature is not present in AE2 and I can not find any discussion of why, I assume there is a reason for it not being included, perhaps it could be discussed here?

**Comment by XFactHD** [comment]
The lights of the drives are blinking when accessed, this feature has never been removed.

**Comment by gixbit** [comment]
Are you asking whether or not drives still blink? Or the config to turn this on and off is still present?

If drives aren't blinking, it's probably due to  the way your network is set up, (Multiple locations). If you don't like blinking drives, put them in another dimension so you never have to see them again. I've never known anyone to hate the look of the drives that much or lag out cause of it. But, fair enough.

**Comment by yueh** [comment]
#75
