### ISSUE TITLE
Chromaticraft Void Cell can not be preformatted.

### ISSUE THREAD

**Issue by lossycrypt** [AppliedEnergistics/Applied-Energistics-2#2005]
(This is NOT a feature request.)

##### Explanation:
Chromaticraft adds a special storage cell called the "Void Cell". It can store up to 268,435,456 (2^28) bytes, but only a single item type.

##### [This issue at Reika's tracker](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/398) (he says it's on your side):
Void Cells can not be formated for a specific item type using the Cell Workbench. Also if they are in an me chest (not tested with me drive), you put something in them, and then take all items out again, then they will not accept any items at all until taken out of the chest and put in again.

Version used is rv2-stable10.

**Comment by yueh** [comment]
Complain to Reika for not implementing the cell correctly and persisting its partition.

**Comment by ReikaKalseki** [comment]
I have no idea what that even means.

**Comment by yueh** [comment]
`IStorageCell` handles everything related to the serialization of itemstacks internally, because that is not trivial but pretty straightforward to handle for every addon.

Nevertheless it does not handle configuration options like the cell size via `getBytes` or `getBytesPerType`, the power consumption or like here the partition.
Anything it actually exposes to you is up to you to implement it. Especially things like the partition of a cell is not trivial to handle internally, it is perfectly valid to have a addon cell with a static partition for every cell.
For example if an addon wants to only store its own items in its cells. This should of course also apply to any new item. Would we by default serialize this to NBT data, then an addon would need to explicitly handle this case and modify this list for every new item after a cell was created. Or some stupid stuff like adding a new method to the interface to indicate a cell needs an update for its partition list and a mod would have to save the mod version as NBT data to know when an update is required etc...
Thus it is way easier to just use the provided `IInventory` at runtime and if it does not require any serialization towards a specific cell, there is not reason to pollute the NBT data with it.
This might allow for a partition list of over 63 items as long as it is marked as not editable with a cellworkbench, but I currently cannot remember if there is another limitation somewhere besides the GUI of a cell workbench.

**Comment by ReikaKalseki** [comment]
Nothing in the interface is explicitly about partitioning, and I have no idea what would happen "on my end" to notify the item that an AE block has just tried partitioning it.
