### ISSUE TITLE
Server: Cant access any style AE Terminal

### ISSUE THREAD

**Issue by Sodiscrubbdu** [AppliedEnergistics/Applied-Energistics-2#2033]
I currently run a Skyfactory 2 server, Server is as is with only Bukkit essentials and Bpermissions added in. However, When right clicking on any terminal, nothing happens. Haven't changed anything in the config file except turning off achievements to try and fix the issue. Permissions aren't blocking use because not even a OP can access terminals.

**Comment by wlhlm** [comment]
Applied Energistics does not support Bukkit. It also does not support any kind of permissions plugins/mods since AE2 uses its own network protocol and thus bypasses their checks completely.

You can use Forge Essentials as an alternative.

Also, you could check if the network has a security terminal attached to it.
