### ISSUE TITLE
Unable to use an export bus to export items in a ME Interface buffer

### ISSUE THREAD

**Issue by PhoenixMage** [AppliedEnergistics/Applied-Energistics-2#2040]
I am trying to automate a Mekanism Metallurgic Infuser and I have a block Interface connected to the network with the pattern I want in it and a multipart Interface connected to that to create a subnetwork. In that subnetwork I have 2 export interfaces with filters to export the required items into the sides of the infuser.

Everything is powered

The items get as far as sitting in the buffer of the multipart interface but they wont export from the export buses. I replace the infuser with a chest for testing and I don't end up with anything in the chest either.

**Comment by wlhlm** [comment]
You need at least one type of storage interface (storage bus, ME drive, formation plane) in order for a subnetwork to work properly. You have to replace the export bus with a storage bus.

This is what I got from experimenting.  How I understand it, is that just using interface + export bus, there is no actual place in the network to store items. The interface looks like a chest to the outside, but to the network it is some type of import with a cache, that needs some place to store the items.

The export bus on the other side exports from a network to an adjacent inventory, but since your subnetwork cannot hold any items, it thus cannot export any items.

ME networks don't work like pipes.

(BTW, reverse also works by having a storage bus on the importing side and an export bus on the other.)

**Comment by yueh** [comment]
Items are exported into an interface and no longer not part of network (see [ME Interface](http://ae-mod.info/ME-Interface/) for more details). Thus they simply cannot be exported again.
