### ISSUE TITLE
io port is not working

### ISSUE THREAD

**Issue by theflyingsockie** [AppliedEnergistics/Applied-Energistics-2#2080]
here is a you tube vid showing it

https://youtu.be/fmFTelJ83RE

**Comment by yueh** [comment]
Please read the [guidelines for contributing](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/CONTRIBUTING.md).

I cannot find any issues with them with my setups. Also due to how frequently they are used, there should be already a report or fix created way earlier, should they really not work.

**Comment by theflyingsockie** [comment]
Could it be a tps issue ?

**Comment by thatsIch** [comment]
Try recreate a minimal setup in a new world: IO Port exporting items into ME Drives
