### ISSUE TITLE
Feature Request: FavoriteItems support

### ISSUE THREAD

**Issue by thecodewarrior** [AppliedEnergistics/Applied-Energistics-2#2094]
Because the AE terminal has custom handling for space-click—instead of just repeatedly shift-clicking—and I don't think using ASM on an open source mod is reasonable or practical, any items that are favorited will be moved.

**My suggestions on where to start, feel free to do whatever.** Just trying to be helpful.

Since favorited items are only client side, `InventoryAction.MOVE_REGION` would likely have to be ditched/modified, in it's place just shift+clicking all the matched items. If the items are simply shift clicked no extra integration is necessary. My mod can handle shift-clicks, or any type of click that isn't a custom packet.

From what I can see the changes would take place in [AEBaseGui](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/client/gui/AEBaseGui.java#L458), [GuiCraftingTerm](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/c83946420eec8edc25cf05fce1192442b06a76cf/src/main/java/appeng/client/gui/implementations/GuiCraftingTerm.java#L69), and [AEBaseContainer](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/17bdd085b169e129a67d3c5d64f606e67e59957b/src/main/java/appeng/container/AEBaseContainer.java#L828).

I'm wondering too, what is the reasoning behind a "move region" packet instead of just shift-clicking all the stacks? Bandwidth? Addons having custom region handling?

I can create an API for FavoriteItems if you want one, though shift-clicking seems like the simpler option.

**Comment by yueh** [comment]
All `InventoryAction` are AE2 specific handling, so even our shift clicking will not work or at least not reliably. This is mostly done done due to the different requirements like the terminal slots, fake slot, etc, which cannot be handled by vanilla directly. Not sure, if it would actually cause many issues like infinite loops in combination with security protected networks or simply start duping when not handled correctly.

We probably would have to add explicit support via an API, but there are a couple of issues with it.
The easiest is that we would have to potentially scrap it again for 1.8.
Also I am not really convinced that limiting it to the displayname is a good solution. Players do not just want to keep their tools, but also a couple of blocks like a stack of cobble or torches. Dumping any excess back into the system would get very tedious. The same should someone need a large amount of cobble and shift+clicking will no longer be possible to extract it from the network.
