### ISSUE TITLE
Letter "T" 'T' is not working right

### ISSUE THREAD

**Issue by Mementh** [AppliedEnergistics/Applied-Energistics-2#2095]
The letter T is not usable unless your directly over the search box for some ODD reason.. 

its not linked to the chat command and was not in the prior version we had.

:/ thanks  :)

this seems to be a issue with the remote terminal only

**Comment by wlhlm** [comment]
I cannot reproduce this with just JEI installed. First make sure you have the lasted version and then try to remove mods one by one to see if it's caused by cross-mod interaction.

**Comment by Mementh** [comment]
nei? jei? what? 
i don't know how to check through 100+ mods to test when its happening on multiple packs and only on the wireless remote ( a youtube streamer also had issues nonsanity) 

how can i check mods one by one easily for you?

**Comment by wlhlm** [comment]
Oops, I mistook the repo. Sorry :)

JEI is an alternative to NEI for MC 1.8.9. But this isn't relevant to your issue.

The problem with 'T' not being registered is a known problem and is caused by ExtraUtilities. 

See https://www.reddit.com/r/feedthebeast/comments/3voef5/ftb_infinity_evolved_expert_applied_energistics_2/cxpel2n?context=1

**Comment by Mementh** [comment]
thanks :) also the word "che" seems to cause graphics issues? looses icons and causes forge microblocks to go away?
