### ISSUE TITLE
I have some problems with AE craft reciepts with energy crystals from IC2

### ISSUE THREAD

**Issue by adamsonich** [AppliedEnergistics/Applied-Energistics-2#2111]
if i use fresh crafted energy crystal in reciept and has some charged energy crystals AE stops in crafting.
    https://yadi.sk/i/rk665v2MnHvrZ
    https://yadi.sk/i/o2XYwS6LnHwqg
    if I remove any charged crystals then AE crafts lapatron normaly
    if I use charged energy crystals in reciept then AE even dont start craft
    https://yadi.sk/i/pJY_hbT-nHviD
    https://yadi.sk/i/8zMEUlQwnHxaK

**Comment by adamsonich** [comment]
as I see it's NBT problem

**Comment by yueh** [comment]
This works perfectly fine for me.

Keep in mind that you need to use the energy crystal produced by the compressor when creating the recipe. Not some previously used ones. Should IC2 add some random NBT data, AE2 might no longer be able to consider that one as valid input as it might no longer be an equal item to the one defined in the pattern (or the ones produced by the compressor are not equal to the one in the pattern)

**Comment by adamsonich** [comment]
I uesed fresh-crafted/untoched/unused crystal in first sample. problem is: if there are other crystals in system discharged or fully charged AE cant craft with reciept with unused crystals

**Comment by thatsIch** [comment]
The lapatron has charge on it, please do not use anything like gravichest or similar which can charge your inventory. This will make the official recipe invalid for the crafting system. IC2 adds its own crafting system which handles charge based crafting. But loading this into AE2 would destroy the calculation (due to sheer amount of possibilities to consider)
