### ISSUE TITLE
Initializing Error

### ISSUE THREAD

**Issue by rsebestian** [AppliedEnergistics/Applied-Energistics-2#2114]
java.lang.NoSuchMethodError: appeng.api.definitions.IItemDefinition.isEnabled()Z
That is the Error i get while starting appliedenergistics2-rv3-beta-5.jar
Is the Z a typo ?

**Comment by yueh** [comment]
Please post the full crashlog on pastebin or similar, otherwise we cannot help you.

**Comment by atomic-sunshine** [comment]
i'm having the same problem. I tried to disable/remove all the AE2 addons and ran my pack with just AE2 enabled but still got the same crash. Here's my pastbin for the crashlog. http://pastebin.com/mHUy4HgT

I've also attached my forge log if that helps. it's to big for pastbin. 

[Crash Forge Log.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/102526/Crash.Forge.Log.txt)

**Comment by yueh** [comment]
Can you please try it without Thaumic Additions?

**Comment by atomic-sunshine** [comment]
It worked! now i'm going to try adding the other AE mods back in

**Comment by yueh** [comment]
They ship our API, probably even a very old one. As well as a couple of other API, looks like everything they can get their hands on, even when never using it.

Also they are using a core mod, so forge cannot really prevent them from replacing our version. Neither can we really. I planned to add something to detect, if the API was loaded from another source and warn/crash due to it as the forge detection is not really perfect. But even this will not work in this case. 

Thus probably nothing we can fix on our side. Except some pretty dirty hacks, which probably cause more issues for normal player, than they would solve.

Excuse me for being a bit rude, but the only option is really to tell them to fix their shit and stop shipping every API they find as it probably can affect many other mods.
