### ISSUE TITLE
AE2 Crashing Minecraft Client upon Rebooting ME System

### ISSUE THREAD

**Issue by LokeYourLord** [AppliedEnergistics/Applied-Energistics-2#2134]
So, i made a reboot system for my ME System, which uses Tinkers Construct Bridges to place ME Controller blocks. I used AE2 RV2 latest version, then i updated to RV3 beta 5. Once i had to reset my ME (because the overlarge ME bug apparently still exists, where if you have way to much hooked to your ME, it cannot handle requests anymore after you log out of a server for a while). Anyways, here the crash : http://pastebin.com/mBwqzbhP

PM: Also it is most likely caused by the fact that the Tinkers Construct Bridges are placing the ME Controllers, and as they don't act as a player and thus have no player ID, the system fails to handle exception. Its not a major bug, but some as me have to sometimes do this because of what i explained in the part below. Also, as a side note, this bug did not exist in AE2 RV2 (any version for that matter).

To explain further: I live on a gigantic GalactiCraft SpaceStation which i built. Now, my ME System stretches across this whole base, with in each room (i have about 20 rooms) are at least 32 or more devices that use alot of Channels, so i have BDew his AE2Stuff mod to assist me with Wireless Connectors. Anyways, my ME System is huge, it has probably more than 500 different things attached, from Import/Export bus, to Terminals, to ExtraCells2 stuff (Gas and Liquid Bus). The problem is, that if i logout for lets say 20 minutes from the server (the dimension seems to be somewhat loaded by the Dimension Loader from Immibis wich i placed down, of course i cannot tell if it works or not when i am not there :P), and come back, the ores which my MineFactoryReloaded Laser Drill is collecting and injecting into the ME System, are still in the ME System, even if they should have been processed immediately by my 2 IC2 Furnaces (which have 28 Speed Upgrades and process everything at the instant). So, the thing is, it seems that the ME System cannot handle as many requests when it is not loaded by a near player, as Chunk/Dimension Loaders only seem to work somewhat.

**Comment by Yanniclord** [comment]
Bump

**Comment by vallard192** [comment]
Can you recreate the crash without bukkit?  That'll be the first step
because bukkit/cauldron are unsupported due to known incompatibility issues.

**Comment by Yanniclord** [comment]
Well, i cannot even start the server without Cauldron, simply because it crashes on normal Forge, and Cauldron resolved that. Anyways, i am still quite certain that it is not because of bukkit, because i when i had RV2, i also had bukkit back then, but it did not crash, but since RV3 beta, this crash has existed.

**Comment by mindforger** [comment]
@Yanniclord how can you know the way that bukkit is treating the data you file them and how they are retrieved and then presented to forge?! 
this is not some sort of cauldron bashing, it simply is reality that they treat things and data differently than expected and as yueh wrote this is only the first step ...
I for myself found a bug where the bukkit API is reporting a player to "ride" an entity on an totally different calculated height than vanilla/forge does, so when you "sit" on an armor stand f.E. on a vanilla client you are sitting on the correct height, where on a forge client you are sitting almost 2 blocks higher ...

**Comment by vallard192** [comment]
@Yanniclord <https://github.com/Yanniclord> If its a true bug in AE as
opposed to an issue with multiple mods interacting, then you should be able
to recreate it with a minimum number of mods / other factors.   In a new
world that probably only has AE2 and Tinkers Construct  (but maybe
Galacticraft) if you can recreate the crash there's a much greater chance
of it being fixed.

I just noticed you mentioned chunk loaders in your first post.  Another
common issue that could cause your problem is an issue with chunk loading.

You should ensure that your entire network is chunkloaded and try a
different chunkloader.  I don't know which one they feel works best with
AE2 right now, but in the past I believe it's either been Railcraft world
anchors or MFR Chunk loaders.

**Comment by XFactHD** [comment]
Yep, both of those chunkloaders are good, Chickenchunks is causing issues.

**Comment by yueh** [comment]
The issue is actually that they are using their own fake player, which have an incomplate profile, thus no UUID assigned (as oppossed to forge fake players or say fake the player who placed the bridge).

For performance reasons, why cache these UUID as ints and therefore require them to exist and be able to map it back to the real user.

Not sure how to handle it as I really do not wish to introduce special cases to prevent some broken fake player implementation.
