### ISSUE TITLE
Ore Dictionary missing for Charged Certus Quartz

### ISSUE THREAD

**Issue by mskurnik** [AppliedEnergistics/Applied-Energistics-2#2161]
While there is a Certus Quartz ore dictionary entry (crystalCertusQuartz) there is no entry for Charged Certus Quartz (crystalCertusQuartzCharged).

This was discovered while submitting a TE bug report at CoFH/Feedback#1084.

**Comment by wlhlm** [comment]
This has been addressed in rv3. See #1634.

**Comment by mskurnik** [comment]
Sorry.  I didn't see that one.  Thank you!

**Comment by yueh** [comment]
We do not have a special oredict entry for charged certus as this is mostly just a gated item and we need the exact item and not an oredict entry for these cases (fluix crystals/in world crafting).

Otherwise there is no difference between charged and non charged one. Therefore both are simply registered as `crystalCertusQuartz`.
