### ISSUE TITLE
Grown Pure Crystalls despawn.

### ISSUE THREAD

**Issue by dovahkiin4991** [AppliedEnergistics/Applied-Energistics-2#2179]
I play on a direwolf 20 server and once the crystals are grown they despawn. This can be an issue if you are not constantly check the crystals and because its at the beginning it takes longer for them to grow without the accelerators so I often leave the server(I have a chunk loader) and when I come back they are gone. It is not from players as it is covered for that reason. Please fix this issue to make them not despawn until picked up.

**Comment by mindforger** [comment]
@dovahkiin4991 most certainly a problem of the server owner using some sort of plugin or mod that despawns unused entitys to prvent lag (nolagg f.E.) try to blacklist the items in the config of the tool or remove it and use nolagg afaik it has a blacklist feature especially for this

if not, check if ther is probably a hopperhog with a mana pool in the vincinity, they have an enormous range when supported with mana

**Comment by vallard192** [comment]
I think that it might be by design.

Code could have changed since I last looked at it, but previously the seeds
had their despawn time set to a greater time than the time it takes them to
grow (IE they'd never despawn).   However, Pure Crystals didn't have that
setting and would in fact despawn after the default time.

**Comment by ktole1999** [comment]
That is correct. Full grown seeds are subject to despawn settings unlike seeds still in the growing stage. Slap a transfer node on it or a vacuum node to such up the grown seeds


Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: vallard192 <notifications@github.com> </div><div>Date: 3/9/2016  8:40 AM  (GMT-06:00) </div><div>To: AppliedEnergistics/Applied-Energistics-2 <Applied-Energistics-2@noreply.github.com> </div><div>Subject: Re: [Applied-Energistics-2] Grown Pure Crystalls despawn. (#2179) </div><div>
</div>
I think that it might be by design.

Code could have changed since I last looked at it, but previously the seeds
had their despawn time set to a greater time than the time it takes them to
grow (IE they'd never despawn).   However, Pure Crystals didn't have that
setting and would in fact despawn after the default time.


On Wed, Mar 9, 2016 at 1:46 AM mindforger <notifications@github.com> wrote:

> @dovahkiin4991 <https://github.com/dovahkiin4991> most certainly a
> problem of the server owner using some sort of plugin or mod that despawns
> unused entitys to prvent lag (nolagg f.E.) try to blacklist the items in
> the config of the tool or remove it and use nolagg afaik it has a blacklist
> feature especially for this
>
> if not, check if ther is probably a hopperhog with a mana pool in the
> vincinity, they have an enormous range when supported with mana
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2179#issuecomment-194141492>
> .
>


---

**Comment by yueh** [comment]
Growing crystals whoe switched from growing to finished will not despawn. They are still the same entity object, which will constantly reset their life time to prevent them from despawning.

This will only happen, if a player or machine picks them up when fully grown and drops them again. In this case they will be spawned as a normal item entity, which will despawn after 5 minutes.

Or some mod deletes them from the world, nothing we can really prevent.
