### ISSUE TITLE
Duplicate glitch

### ISSUE THREAD

**Issue by Scrik** [AppliedEnergistics/Applied-Energistics-2#2196]
Duplicate glitch
Version AE2 rv2-stable-10
https://www.youtube.com/watch?v=a72alZDiQIk

**Comment by siasur** [comment]
It would be nice if you write something about that glitch...

**Comment by Stepan1404** [comment]
When ME system is unloading (Unloading chunks with ME system) and ME system crafting something it's do. Sorry for my bad english =).

**Comment by mindforger** [comment]
old bug  

try reproducing with rv3

**Comment by vadimyer** [comment]
- Build an auto crafting system like the one in this video, in 4 separated chunks.
- Create a custom recipe, that doesn't even exist.
- Start the auto craft and move away from these chunks so they are unloaded.
- Wait a bit, come back, voila.

I'd hope that it would be fixed somehow in rv2, because rv3 is still just beta.

**Comment by mindforger** [comment]
`because rv3 is still just beta` but still very very stable imho :) give it a chance
rv2 stable with it's issues seems almost more beta than rv3 beta

**Comment by linkinkov** [comment]
Anybody test dupe with rv3?
Or can say that commit fix it?

**Comment by xLivan** [comment]
Tested with rv3. Confirmed working.

**Comment by linkinkov** [comment]
@thatsIch

**Comment by vadimyer** [comment]
Yes, rv3-beta5 has that glitch too. Please fix that, players use that.

**Comment by yueh** [comment]
Duplicate of #1430, #592

Extremely hard to fix, as it is nearly not debuggable due to chunk loading.
With normal minecraft/forge it is also not that easy to exploit, but with more aggressive chunkloading it will get way easier.

Currently we do not have enough time to resolve it.
If you really need a solution now, feel free to make a PR.
