### ISSUE TITLE
[Feature Request] Retain patterns when you break/move ME Interfaces

### ISSUE THREAD

**Issue by Sorbe** [AppliedEnergistics/Applied-Energistics-2#2210]
Please consider **not** dropping all of the patterns on the ground if you break an ME interface block.  I've made giants messes now a couple of time by moving/rebuilding my Molecular Assembler arrays(w/ME Interfaces).

Just keep the patterns inside the block when it becomes an item.

**Comment by PiggyWhiskey** [comment]
Be more careful?

**Comment by mindforger** [comment]
he has a point there, as it "may" be possible to save the content information inside the item stack like other mods do, thats why he calls it feature request :)

**Comment by yueh** [comment]
While this sounds nice in the first place, it has some nasty issues once actually implemented.

AE2 tries to be consistent as possible.
Therefore either every block/part should drop their inventory/store settings or not.
Not some do and some do not.

The problem starts with drives then keeping their cells. Which will cause them to great some massive amounts of NBT data in a single item and essentially allow the player to increase the stored amount of data at least one magnitude in the same inventory (10 slots for cells + 1 slot for the  drive => 1 slot for all 11 items). Which can finally lead to a corrupted `player.dat` and cause the player to potentially loose all their items. There are already rare cases, for example when players decide to move their complete base and place everything into recursive bags until they exceed their data size.
So your choice here is either making a mess or corrupting your world. I would say this is an easy decision.

Also it would make other cases way more annoying. Want to tear down a larger build?
Have fun with reseting each and every block/part manually through the GUI otherwise you will end up with a giant mess because nothing will stack.
Thus it would just make it a bit better for you, other players would be highly annoyed by it.
Who should we choose? Currently I cannot remember a single other request for it, so it would favour a very small playerbase vs. annoying a potentially large one. Which will only response after it was changed.
