### ISSUE TITLE
[Feature Request] Timing external crafting steps

### ISSUE THREAD

**Issue by Adonis0** [AppliedEnergistics/Applied-Energistics-2#2215]
In my latest update of AE that I'm playing on, I noticed that it gives a time for how long crafting will take in the crafting status window, however I found this is only accurate with purely internal crafting as any external crafting steps took time not accounted for.

Would it be possible for a recipe in an interface accumulate average times required to craft this recipe, so that the crafting status window can display accurate time estimates, even with external crafting steps

**Comment by yueh** [comment]
Too complex/unstable to be feasible.

The ETA is just an estimate based on how much time elapsed, the amount of finished crafting operations and total amount of operations.
AE2 crafting is mostly consistent over the time it requires, external is a bit more tricky.
But as long as these are mostly consistent, it should report it mostly correct.

Especially short jobs might be incorrect as it needs a bit of input to estimate it.
Longer ones should mostly converge against the actual time. Except in cases of the last tasks suddenly requiring a couple of minutes instead of seconds.
