### ISSUE TITLE
Game Crashed After Running My Modpack

### ISSUE THREAD

**Issue by Chomper32** [AppliedEnergistics/Applied-Energistics-2#2218]
My game crashed when trying to run my modpack, please help!
The crash report is here: https://paste.ee/p/YPrNh#

**Comment by wlhlm** [comment]
This is the issue tracker for Applied Energistics, but your log doesn't show any with. The crash is caused by other mods. Not sure how you got the idea to post your issue here.

Anyways, the log includes some minor problems with Food Plus and MCHeli, but those aren't fatal. Your main problem here is with FMP (Forge Micro Blocks). You've downloaded the `dev`-version of the mod:

> ForgeMultipart-1.7.10-1.2.0.336**-dev**.jar

Notice the the last part of the filename? This version of it is for _mod developers_ to put into their environments. When you develop mods, you run a modified version of Minecraft for testing which requires a different build of the mod jars (at least int 1.7.10).

So make sure that the next time your download a mod, it doesn't have the `-dev`-suffix.

**Comment by Chomper32** [comment]
Thanks! And the reason i posted it here was because the last words in the log were "Exception in thread "AE2 VersionChecker" "
