### ISSUE TITLE
Blinking ME Level Emitter

### ISSUE THREAD

**Issue by Cbert** [AppliedEnergistics/Applied-Energistics-2#2248]
ME Level Emitter blinks when level of a specified item changes fast.
So I suggest to add a function similar to EnderIO Power Monitor. It would help to reduce blinking.
![2016-04-24 12 55 24](https://cloud.githubusercontent.com/assets/9320867/14766687/142c4c88-0a1c-11e6-9cff-25ff2a3c4026.png)

**Comment by Rixxaw** [comment]
So its a feature request you wanted and not an "Issue" ?  There are facades if you just want the blinking to stop....

I'd love to have an Inverted Redstone mode, where it "Emitted Redstone while not crafting."

**Comment by thatsIch** [comment]
how does the power monitor stop it from blinking?

**Comment by Cbert** [comment]
Rixxaw
Yes and no. It is request an issue same time, blinking can possibly cause lag 
with other mods and devices. My request can make ME Level Emitter more mod friendly and exclude possible lags that blinking can cause.

thatsIch
http://wiki.enderio.com/Power_Monitor
Actually power monitor don’t prevents it (ME Level Emitter) from working, but it makes it emit less frequently due to the fact that specifies the upper and lower threshold, that as a result increases time interval between on and off states or redstone signal. Instead percentages, level of a specified item.

**Comment by mindforger** [comment]
@thatsIch what @Cbert means to add some hystersis, either number specific or maybe time based hysteresis .. i've also seen this effect once in a while and know from other uses of redstone that a fast on/off will cause server load because of redstone-updates and let redstone glitches appear

**Comment by yueh** [comment]
If a few fast switching level emitters causes a server to overload, it has certainly other issues already.
Especially as level emitters will not cause any light updates. Just notify their neighbors. Which is certainly already done many more times by other TE, if you have some fast moving items. Pretty much most inventories or machines involved in obtaining these items are already doing it.
Maybe also use a mod with redstone wires without light updates instead of vanilla redstone.
Providing a profile to support your claim might be helpful to resolve the real issue.

A range approach is certainly violating our design idea as we want to keep every part as simple as possible and you should be able to combine them for more advanced builds. Like 2 emitters connected with an OR.

Time based might be an idea because it certainly fits the theme and acceleration cards could be used as upgrades. Like by default change every 20 ticks, 10 with 1, 5 with 2 and every tick with 3 cards.
But it would mean that level emitters then have to tick. We could put them to sleep until a change wakes them. But this might get complicated, should they update every N ticks and not N ticks after a change has happened.
But they are not reliable enough to be used with the current inventory change events. Simply because too many strange inventories stick currently around and requiring some duplicated events to occur. Resolving without a major API rewrite is certainly not possible. So more of an option for 1.8 or 1.9.

**Comment by mindforger** [comment]
`A range approach is certainly violating our design idea` i'll accept that :)
i just wanted to support the reason behind what @Cbert requested

using fast vanilla redstone on servers can never be forbidden and unexperienced users will always be using "known for server lag" stuff if either the source of the issue or the technic used to cause this lag can be disabled in any way ... 

players are always abusing stuff either by accident or on purpose if you don't actively block it

that is one reason why i also support this idea .. and to your "other things cause more lag" ... it's experience with spigot and cauldron that tells me to always check once in a while for larger or faster ticking redstone contraptions to reduce tick load ... vanilla redstone is a bitch and fires up to indefinately events if your contraption is evil enough

**Comment by Cbert** [comment]
Notably
Mods that based on this functionality include word “[hysteresis](https://en.wikipedia.org/wiki/Hysteresis)” in their name.
[[A16] Hauling Hysteresis](https://ludeon.com/forums/index.php?topic=26958.0)
