### ISSUE TITLE
Player position not changing when entering Spatial Dimension from within The End

### ISSUE THREAD

**Issue by Farbdose** [AppliedEnergistics/Applied-Energistics-2#2254]
So I encountered the following problem: 
1. When entering a pocket dimension from within the end, the player coordinates in the dimension stay the same as they were in the end (while entering from somewhere else sends me to 0x0 - where the blocks that were transported into this dimension will appear)       
2. The transported blocks are missing inside the pocket dimension (potential cause: 1.)
3. By flying to the location where the blocks should be and then re-login the blocks can be made visible
4. So ... Now I am standing on the blocks I transported but I am trapped in a 1x1x2 barrier and can't move at all.

**Already checked:**
- entering a pocket  dimension works from Overworld and RFTool-Dimensions but not from the End 
- Dimension ID changes as it should -> I am teleported to the right dimension.

**Screenshots** showing coordinates before and after entering from within the End:
[http://imgur.com/a/dYNib](http://imgur.com/a/dYNib)

**Useless Log** [http://pastebin.com/jRufNiB2](http://pastebin.com/jRufNiB2)
**Playing on a server**
**Modpack:** FTB Infinity Evolved 1.7 1.7.10 - Version 2.5.0
**Forge Version** 1.7.10 - 10.13.4.1614
**AE2 Version:** Build rv3.beta.5

Poking around in the IRC wasn't successfull so I took a short look at https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/spatial/StorageHelper.java#L63  but couldn't find anything obvious :-/

... it would be good to know if someone can reproduce this...

**Comment by leagris** [comment]
Reproduced using Forge 1614 and AE2 rv3 beta5

#### Steps to reproduce:

1. Create Spatial pylon in The End
2. Activate pylon teleportation with you inside
3. You as player entity is moved to spatial storage dimension at same coordinates you where in The End. Blocks moved to Spatial storage are at the expected Spatial location
4. If allowed flight (ModularPowersuit), player can move around freely inside Spatial storage but fall into void if no flight because there is no block to stand on.

Non-Player entities moves at the right location. Example: A fenced sheep is teleported with fences from End to Spatial Storage. When teleported back to The End. Sheep is back where it was left. So Sheep does not fall in void and cant move out of teleported fences and gound. Proof it was moved at the right location.

If allo

**Comment by Farbdose** [comment]
Thought: From my understanding the dimension with only sheep inside (and no player) wouldn't be chunkloaded so it couldn't fall down even if there were no blocks, right?

**Comment by leagris** [comment]
@Farbdose So I entered the pylon structure with my sheep and we where both teleported into spatial storage:
* Me at same coordinates as I was in The End and found no sheep around or falling down.
* Sheep was likely at correct location of blocks, and its safe return from storage confirmed it.

I then warped out of Storage:
Reloaded storage to teleport back blocks and sheep.
Sheep was still alive undamaged inside fences.

I then can confirm only player is affected by wrong coordinates but not other entities.
