### ISSUE TITLE
Feature Request: Two small changes to improve the ME Interface

### ISSUE THREAD

**Issue by mjevans** [AppliedEnergistics/Applied-Energistics-2#2265]
I think that the ME Interface could be even more useful than it presently is with two tweaks.

* Extend the modes offered by the Crafting Card, instead of the crafting card switching from 'stored items only' to 'stored/crafted items' mode, allow the Crafting Card to be set to /force/ item crafting (like in the export bus).

* Allow the Acceleration Card (or some other card) to disable the internal inventory for stored items and instead make the ME Interface /push/ the items in to, and regulate the item size based on, the connected interface.  Ghost items might be used to represent the seen quantity of items in the target inventory.

With these two improvements, the ME Interface could be used as part of an auto-stocking system that does **not involve redstone (and thus chunk) updates**; everything could remain entirely within tile entities.

The first change would make the ME Interface behave more closely to the export bus as noted (which is an independent reason to make it).

The second change literally just allows the ME Interface to be a regulator; using an external inventory the 'target size' can also be larger than one stack.

If the cost of an acceleration card isn't high enough I'd actually suggest using an ME Controller item as the upgrade.

That's why this is different from several previous feature requests by others in older versions of Minecraft; each of the changes alone makes sense and is useful; together they happen to also provide the feature I'm presently seeking.

**Comment by VT-14** [comment]
I believe by using a wrench on a full block ME Interface, it will show arrows and auto-export to the side they are pointing at.

An Export Bus with a Crafting Card set to force craft should provide a full container of one item, and adding a (or maybe 2?) Capacity Card will allow you to fill up 9 different items if the container is properly limited (which give me an idea for my own suggestion).  "properly limited" can be a chest that has at least 1 of the item you want to keep stocked in several slots (I don't think that will work well with a storage bus though), or using something like Storage Drawers with several locked drawers connected to a Drawer Controller.


My way of handling this would be to allow users to reserve a certain number of items in a cell workbench.   Instead of saying 'this cell can hold bones and rotten flesh' and then having the entire thing fill up with only rotten flesh, you could say 'this cell has 1,000 items reserved for rotten flesh, and 1,000 items reserved for bones, and the remaining space on the drive is free for anything (or free for anything that is not bones or flesh)."  I would also lock this feature behind adding a capacity card to the drive.

I would agree that the ME Interface should have the same crafting options as the export bus when both are given a crafting card.

**Comment by mjevans** [comment]
At least with the version of Applied Energistics included with FTB Infinity Skyblock, appliedenergistics2-rv3-beta-5.jar this is what I observe as behavior:

* ME Interfaces + Crafting card; behavior is as I outlined previously (no crafting only option).
* Full block ME Interface: When the arrow is facing towards a vanilla chest, it will not push the held inventory (let alone when the arrow is facing something like, say, an AE Storage Bus block).  Instead the test item (in this case stone bricks) sits in the ME Interface.  In my other tests I use the new slim form of the Interface, which effectively makes the only block it's facing the 'arrow' face.

There aren't slots for other cards, but I figured the Capacity card wasn't costly enough to be worthy of providing the regulator (Like Red Power 2 used to have) function.

**Comment by XFactHD** [comment]
The arrow setting on the interface is to be used when you build a row out of more than 8 interfaces and need to disconnect two of them to respect the channel limit.

**Comment by VT-14** [comment]
Huh. I thought that was how ME Interfaces with the arrows worked.  Wasn't that part of their function in AE1?

So I was mostly wrong about how the arrow mechanic worked on ME interfaces.  The arrow will point towards the inventory crafting items will be pushed to.  That is, if you a furnace and a chest both touching an ME interface and are trying to craft smooth stone, but the arrow points into the chest, the cobblestone will be stuck in the chest.

I also investigated the channel connection option.  The side the arrows points to will separate the rows... but it will also break autocrafting as items will be pushed into the interface it has to be looking at to break the connection.  I can't think of any reason to use this feature at the moment, but there probably is one.

**Comment by mjevans** [comment]
Well the correct fix for isolating network segments is the use of the Quartz Fiber (or another support of some type).

I like the quartz fiber though because I tend to build the majority of my networks out of the normal cheapest cable, then at corners use the smart cables.

I'm also going to get around this limitation in 1.7.10 and the mod pack that I'm in by abusing storage drawers to 'lock' drawers at a given multiple of stack size and actually use export busses on drawer controller slaves with crafting only mode, and a storage bus on the drawer controller with a very high priority for get/put normal.  It's going to be a /serious/ pain setting that up but that's how I'm going to work around the lack of a /regulator/ function (lack of binding to regulating item count in attached storage device).

**Comment by yueh** [comment]
1) No idea. But I would currently not consider it being an oversight. There simply a bunch of differences between export buses and interfaces. Maybe therefore it was not added due to potential issues.

2) Clearly out of the scope for interfaces. They already provide an autostacking functionality, which can also be used without any redstone. As well as providing way more flexibility without making them ridiculously complex. Like turning them into a lite version of SFM.
