### ISSUE TITLE
How to implement wireless, ideally directional, ME connectivity (like a QNB), *without* using core AE classes or code?

### ISSUE THREAD

**Issue by ReikaKalseki** [AppliedEnergistics/Applied-Energistics-2#2268]
I have received [a request](https://github.com/ReikaKalseki/Reika_Mods_Issues/issues/786) to make [the CC world rift](https://camo.githubusercontent.com/306b55b7bc48e096f8030b08938ba1bf89f25f2b/687474703a2f2f692e696d6775722e636f6d2f35364b524757572e706e67) be able to wirelessly transfer ME data. I have absolutely no idea how to do this - looking at the QNB and AE2Stuff code has not helped.

Also, is directional connectivity (that is, one side connects to one network, another to a different network), like in the screenshot above, possible?

**Comment by yueh** [comment]
Not possible.

**Comment by ReikaKalseki** [comment]
Is that for directionality, or any kind of wireless connectivity?

**Comment by yueh** [comment]
Not possible in regards to your actual question about "without core classes/code" as everything related to grid connection is handled by the AE core. So no user has to actually care about anything related to it directly (and probably to prevent breaking it due to incomplete implementations).

Forcing a connection between two gridnodes is possible, by itself it would be a non directional connection. But these can be considered internal connections and it is up to you how you expose your gridnode for external connections.

**Comment by ReikaKalseki** [comment]
Nondirectionality is fine. But by "without core code" I mean without explicitly referencing any AE class that is not part of the API - whether it be extending a core AE tile class, or implementing non-API interfaces, or calling non-API methods.

What would happen if two tiles share the same grid node?

**Comment by yueh** [comment]
No and this should be obvious through the API. Every gridnode is linked to exactly one tile entity through the `IGridBlock`/`IGridHost` (location etc). Otherwise AE cannot traverse to neighbour blocks.

Non worldaccessible gridnodes might be used for it. But it is way harder to implement it correctly instead of just using 2 gridnodes.

I simply do not have time currently to provide a copy&paste implementation, therefore I would recommend looking at AE2Stuff or PneumaticCraft as both are using wireless connection and both are pretty trivial implementations. QNBs are probably not the ideal example, due to their multiblock structure.
