### ISSUE TITLE
combining 8 channel cables into dense cable

### ISSUE THREAD

**Issue by Nex4rius** [AppliedEnergistics/Applied-Energistics-2#2296]
When you connect 8channel cables together into a dense cable the dense cable still only allows a maximum of 8 channels to be used.

I tried to do that because the toggle bus doesnt work on dense cables -> split into 4 cables each with toggle bus and combine them again.

<a href="http://imgur.com/a/Jf2lW"><img src="http://i.imgur.com//m5SHu19.png"/></a>

**Comment by vallard192** [comment]
It's because there are two equal length paths to where the channels are
trying to connect.

Check out this page: http://ae-mod.info/Channels/ and search for "Equal
Length Route"

**Comment by HadesDurin** [comment]
make it simpler, the first line who connects to the dense cable gets the ownership and blocks of the rest.
no matter what you try you only have 8 channels aviable.

**Comment by ktole1999** [comment]
Dense cable only allow 32 channels when directly connected to controller. Me cable only allows 8 channels regardless of how it's placed.

Sent via the Samsung Galaxy S® 6, an AT&T 4G LTE smartphone<div>
</div><div>
</div><div>-------- Original message --------</div><div>From: DarknessShadow <notifications@github.com> </div><div>Date: 6/5/16  10:16 AM  (GMT-06:00) </div><div>To: AppliedEnergistics/Applied-Energistics-2 <Applied-Energistics-2@noreply.github.com> </div><div>Subject: [AppliedEnergistics/Applied-Energistics-2] combining 8 channel cables into dense cable (#2296) </div><div>
</div>
When you connect 8channel cables together into a dense cable the dense cable still only allows a maximum of 8 channels to be used.

I tried to do that because the toggle bus doesnt work on dense cables -> split into 4 cables each with toggle bus and combine them again.

<a href="http://imgur.com/a/Jf2lW"><img src="http://i.imgur.com//m5SHu19.png"/></a>

---
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub:
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2296

**Comment by yueh** [comment]
AE2 uses a greedy algorithm to mark cables as visited to not get stuck in loops and also does not keep track of the origin of them. It is just an number set after a block was visited.

Yes this prevents joining multiple smart cables into the same dense one, But that is a pretty rare case because who would waste 96 channels to do it? It would also mean we would have to track the source of every single channel to allow it. Which would be a massive requirements on terms of needed memory and probably make the pathing algorithm way slower as it has to do up to 32 checks per cable and not 1.
