### ISSUE TITLE
Porting to 1.9.4

### ISSUE THREAD

**Issue by Dhvagra** [AppliedEnergistics/Applied-Energistics-2#2305]
Since the original "Porting to 1.8" issue became a back-forth of "NO 1.8, 1.9 STINKS "" NO IT DOESN'T 1.9", I wanted to open a new issue regarding the port to 1.9. This way all the comments that don't matter/ can be considered spam won't bother.

Please only discuss AE2 to 1.9 here.

About a year back, the original issue had a checklist with things to do. Can you (developers) please make a new to-do list for 1.9?

I think many people share the opinion that AE2 is an "essential" addition to any modpack and playthrough (pick a LP or modpack at random, and it has AE2 99% of the time) and it would be a damn shame if it would be abandoned.

I also think that the devs from the community are willing to help out, if you're low on man- or will-power.

**Comment by HadesDurin** [comment]
i think first should be thought over the remaining work from 1.7.10 befor moving forward to 1.9.

one of the first things that is open since the port to 1.7.10 is the crossover work with logistic pipes.
which hasnot been done till today.
for me storage sharing is more than sufficient to do so.

i am a friend of moving forward, but doing so without leaving mess behind.

**Comment by Dhvagra** [comment]
I don't know if it is such a good idea to do the remaining rv3 points and only then do 1.9. I mean, rv3 is still alpha, so that means it's easy to never release rv3 for 1.7, and go straight for 1.9.

That'll be the easy way to go, because the team can say "we won't fix 1.7, we're all 1.9 now". But whatever they please :)

**Comment by HadesDurin** [comment]
at the moment there are 11 pages full of bug reports, issues and feature suggestions including from the ae-founder @AlgorithmX2 . 
@Dhvagra ignoring all of that is a bad way

**Comment by Dhvagra** [comment]
Hmm welll okaaaay you're right ;)

**Comment by JelmarG** [comment]
Why would you even consider staying on 1.7 if the majority of mainstream mods are making the transition to 1.9 or have already done so? That just doesn't make sense. The fixing of bugs and developing additions like compatibility with logistics pipes can still be done once the transition to 1.9 has been completed. At least people will be able to actually use EA2 in the meantime, because let's face it, 1.7 is rapidly on its way out. Spending a lot of work on fixing a version that will not be used in the near future seems like a waste of time to me, especially since making the transition to 1.9 doesn't exclude fixing the issues. In fact, it might prove to be a nice opportunity to look at those issues since the code will get worked on anyway.

**Comment by HadesDurin** [comment]
latly i hear lots of stuff like that, but thing is work needs to be done in 1.7 and that has to be solved befor going to 1.8 1.9 and further. it is a messy way moving to 1.8 and 1.9 and leaving unsolved things behind, because of your comfortness and carelessness. if you really care about ae2, do the open work clean things up and move forward.

**Comment by GuntherDW** [comment]
Mods are a continuous piece of work, if you really feel that you can only update to 1.8/1.9/1.10 if th current version is "bug-free" then you can *never* update to any version.
The beauty of git makes it so you can branch off the 1.7 code if need be in the future, but I agree that most of the attention should be porting what's already there to newer minecraft versions.

Especially seeing as this mod is one of those few mods that many player consider "essential" and will not update to newer versions of minecraft without.

We've seen this kind of "hanging on to older versions" in almost all minecraft versions the last couple of years. Even when lots of other mods openly stated that they would not give bugfixes for older minecraft versions.
