### ISSUE TITLE
new idea AE2

### ISSUE THREAD

**Issue by mat4297** [AppliedEnergistics/Applied-Energistics-2#2317]
I came across a particular crafting, I would like to add two autocrafting by the applied, the result of crafting is the same (eg gold block that becomes 9 9 ingots and nuggets that become 1 ingot).
you could create an interface to choose which of the two ricepe choose before you start the craft to see and choose the cheapest?

**Comment by Dhvagra** [comment]
So, you want an interface to take over the main thing patterns are meant for.

**Comment by mat4297** [comment]
I would  be able to choose which recipe to use among those saved
nell'autocrafting , to make an ingot , you can use the block or nughett ,
they can choose when I want to part with the autocrafting on the me
Il 07/lug/2016 20:31, "Quinten" <notifications@github.com> ha scritto:

**Comment by Dhvagra** [comment]
If you make patterns for `block -> ingots` and `nuggets -> block` , the system will do this automatically. You  can also use Storage Drawers' compacting drawers, they wil automagically do that for you.

**Comment by mindforger** [comment]
`use Storage Drawers' compacting drawers` i would not recommend them, they caused heavy crafting lag in the past, dunno if this is still an issue (because they force a reevaluation all the time or something like this)

**Comment by Dhvagra** [comment]
Good point, although i can't remember if I've ever noticed.

**Comment by VT-14** [comment]
Compacting drawers also display an inaccurate number of items.  If you have 1 Block of Gold, it will tell you that you have 1 Block of Gold, 9 Gold Ingots, and 81 Gold Nuggets.  Autocrafting can start if your process takes 1 Block of Gold and 4 Gold Ingots; but the Drawer will only give up the 1 Block of Gold that you have, causing autocrafting to stall.

Making a loop crafting style (Nuggets -> Ingots -> Blocks -> subnet that goes from Blocks to Nuggets) sounds like the best bet to do what you want.  It's an interesting design challenge using the existing features, and doesn't involve adding another GUI/popup to the mod (and no additional work for the busy dev team).

**Comment by yueh** [comment]
To some extend this can already be achieved on a per request basis with toggling interfaces.

Otherwise it would way to cumbersome to let players pick every single crafting step by hand. Just imagine crafting torches. You would end up with something like 

* Use the oak, birch, spruce or jungle planks to craft sticks? 
* Use oak, birch, spruce or jungle logs for the missing planks? 
* Use the previously crafted planks or craft new ones from oak, birch, spruce or jungle logs? (repeat n times) 
* Use the normal 1 log => 4 planks recipe or use the slow machine with more planks as output? 
* Do again for not enough planks and use oak, birch, spruce or jungle logs form them. 
* Use coal or charcoal to craft the torches? 
* Use oak, birch, spruce or jungle logs to craft charcoal? 
* Use that charcoal or craft new charcoal from oak, birch, spruce or jungle logs? (repeat again)
* Use coal, charcoal or a bucket of lava to smelt the logs to charcoal?
* Use the previous bucket to fill a new bucket of lava or craft a new bucket?
* Use iron ingots to craft the bucket or another mods ingots or buckets?
* Smelt the iron ingots from iron ore with coal or charcoal?
* Use sticks to smelt the logs to charcoal?
* Use the oak, birch, spruce or jungle planks to craft sticks? 

Just make the chain deeper and add more alternatives to it and you will pretty much have to accept every single crafting step like you would shift click them from NEI/JEI into a crafting table. With exception that the crafting table now fetches the items from somewhere and dumps it somewhere.
