### ISSUE TITLE
Bug with automation and quartz kutting knifes 

### ISSUE THREAD

**Issue by DididanLP** [AppliedEnergistics/Applied-Energistics-2#2323]
In skyfactory 2.5 is a bug that you cant automate the crafting for circuits because of the durability (i think) if i request 1 circuit and try another the system says missing item quartz cutting knife

**Comment by VT-14** [comment]
Change those recipes to allow substitutions.  

If you make large batches of processors, then it will craft 1 cutting knife for each processor (due to needing 1 per processor at the start of the crafting).  If substitutions are allowed, then it will keep a bunch on hand and steadily go through them.

**Comment by DididanLP** [comment]
i tested it and it won´t work if i want to craft 50 circuits the system says 49 missing

**Comment by VT-14** [comment]
As I said, It needs 1 for each processor at the start of the crafting.  The recipe assumes the entire knife is used up.  After you have 50 knifes on hand, the next 50 should use your existing knifes.

Blame the modpack maker for the silly processor recipe.

**Comment by Quest79** [comment]
No reason to blame the modpack maker. I don't think this is a bug though, just missing code to have AE crafting intelligent enough to understand durability on tools (this is the same for Minicio stuff). Hopefully added in a future version.

**Comment by VT-14** [comment]
The 'issue' isn't durability, that's covered by the 'allow substitutions' button.  The issue is that AE can't tell that there will be items left over after the crafting using the standard auto-crafting setup.

It's relatively common with buckets.  Someone will add a recipe that uses a fluid in the crafting grid, so they make a bucket of that fluid part of the crafting process.  When that is done, an empty bucket is usually left over.

Using Treated Planks from Immersive Engineering as an example (8 wood planks with 1 bucket of Creosote Oil in the middle); AE sees the recipe as 8 planks + 1 bucket of Creosote Oil = 8 Treated Planks.  When you craft one set, it will make 1 set, and then the Molecular assembler will push the left over empty bucket into the interface and back into the system.  The ME system just sees that bucket as something being inserted through the interface; not as part of crafting.  Because of this, when you craft 80 treated wood planks, the AE system will go "I need 10 buckets of Creosote Oil, and for that, I need 10 buckets!" And from there it will either yell at you for not giving it 10 buckets, or craft whatever buckets it needs if you programmed that recipe in.

You may think that this is a ridiculous bug, but it's not.  AE can't assume that buckets are always left over, as sometimes they are intentionally consumed.  Plus, there are tons of items that aren't consumed which are added by other mods.  AE can't manually keep up with every mod out there, and mods tend to not follow random APIs.  That's why not every item has Thaumcraft Aspects, and AE2's Spatial Storage is mostly unused.

So, yes, I completely blame the modpack maker for making the recipe of several integral items that will be mass produced to play an auto-crafting mod; something that said auto-crafting mod can't properly auto-craft.  I will especially blame them due to it being pretty obvious that the recipe was made to bypass the inscribers (easier to auto-craft, but whoops); unlike most other skyblock packs that just make the inscriber presses craftable.

**Comment by XFactHD** [comment]
I always have a recipe for cable anchors in my ME system and if I want to craft a couple hundred of them, the system calculates how many knifes it needs and the knifes get used completely and the only things left at the end are my anchors and exactly one knife (if it didn't get used up too).

**Comment by VT-14** [comment]
Cable Anchors are an 'vanilla' AE2 recipe.  It's reasonable to assume AE2 specially supports itself and Vanilla Minecraft.

It's also reasonable to assume that using Mine Tweaker to change the recipe would break that Cable Anchor recipe.  Depending on how AE2 handles the recipe (Either the default recipe is hard coded to work, or the knife is somehow specially recognized to be persistent) It is possible that this bug is caused directly by MineTweaker or maybe the Modpack Creator not using it correctly.

At this point I assume it's a limitation between MineTweaker and AE2.  MineTweaker goes "here is a new recipe" and AE2 goes "recipe from another mod; assume everything is consumed and pick up any remnants after the fact."

Yes, I am assuming at this point as I am not in a position to test right now, and don't know enough Java or general programming to pull it out of the code.  Assuming that the knife does work with Cable Anchors in auto-crafting, I will admit that the 'silly recipe' mistake is much more reasonable.

**Comment by XFactHD** [comment]
I definitely agree on your last sentence.

**Comment by DididanLP** [comment]
okay I Changed now to allow substitutions and now is everything working find and the auto crafting works normal

**Comment by yueh** [comment]
There is no special behaviour for cutting knifes at all. If sky factory changes the recipes and breaks something with it, it is clearly not our fault and should be reported to them.

Container items (like buckets or cutting knifes) work just fine with AE. 
But  pretty stupid, as they are a major performance issue. With normal items, we can just calculate a single step and multiple the result with the amount of requested items. With container items, we actually have to calculate every single step on its own to take account of broken tools. So it is not like `10 * 20`, but `10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10 + 10`. Scale it to a few hundred of requested items and you easily have to wait up to a minute. Do something insane like HV solars or the BM tanks and it can easily take an hour or more. Should the server even survive it.
