### ISSUE TITLE
Can't access crafting terminal

### ISSUE THREAD

**Issue by yamipirogoeth** [AppliedEnergistics/Applied-Energistics-2#2331]
I am using a Quantum Network Bridge to remote access my drives. I have created the entangled singularity and placed appropriately in the chamber for both rings. The issue is at my remote ring when I place a crafting terminal nothing comes up when I right click. I don't even get an empty terminal when I right click, it's interacting as though I'm right clicking any non-interactive block.
![remote crafting terminal](https://cloud.githubusercontent.com/assets/20690674/17193086/ab6e1482-540e-11e6-9646-7b55b18238ad.png)
![remote quantum bridge](https://cloud.githubusercontent.com/assets/20690674/17193087/ab6f7796-540e-11e6-8d3e-ddd2c65d7849.png)

WAILA shows that my terminal is online.

If I put a piece of dense or smart cable between the terminal and the ring it doesn't show that any channels are being used.

My main ring is located about 2466, 2503 and my remote ring is located about 25000105, 24999954.

The main ring is connected to a 3x3x3 hollow cube of ME controllers via a dense cable. There is also dense cable going from the controllers to 3 drives.
![home network](https://cloud.githubusercontent.com/assets/20690674/17193133/d9aed976-540e-11e6-82af-581fd10bc437.png)

When I use the network tool at the remote ring it shows both the remote and primary network setup.
![image](https://cloud.githubusercontent.com/assets/20690674/17193168/017be4bc-540f-11e6-8f8d-c73269549ce3.png)

I'm wondering if the vast distance between singularities is a cause or if there is something else I should look at.

Mod versions:
Forge Mod Loader version 7.10.99.99
Forge Microblocks 1.2.0.347
Forge Multipart 1.2.0.347
Applied Energistics 2 rv2-stable-10
AppliedEnergistics2 Core rv2-stable-10

This is happening on a server environment.

Let me know if you need more info, I'm more than happy to get what's needed.

**Comment by XFactHD** [comment]
First of all, you should update to rv3 beta 6 as it is much more stable than the version you are using.
The reason for your problem is not the distance itself but rather the position of the remote ring. The maximum positive and negative x and z coordinate is 30 million. At about 1.5 or 2 million in any direction, the game starts to act weird because of so called floating point errors. One example of that is that normal redstone lines are rendered with the width of a full block. You should move your remote base to about 1 or 1.5 million in both x and z direction.
