### ISSUE TITLE
Crash on server

### ISSUE THREAD

**Issue by MJRLegends** [AppliedEnergistics/Applied-Energistics-2#2337]
Crash log: http://pastebin.com/pGKELF7x

My server is running a mod pack, and its using thermos https://github.com/CyberdyneCC/Thermos not forge, not sure if its there fault or a mod issue.

A player just had a import bus placed on the side of a Chemical Decomposer (machine from minechem) nothing else interacting with it just that import bus going to a me network like normal....

Also my minechem version is Minechem-1.7.10-5.0.5.406 and AE2 is appliedenergistics2-rv3-beta-6

Any ideas?

**Comment by thatsIch** [comment]
This seems to be a Minechem problem. We are just asking the TileEntity of Minechem what slots of its inventory are accessible from that side you put the ImportBus on.

https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/util/Platform.java#L1648

and then Minechem can not handle that. 

Their checks in that version are insufficient since `getManager` does a lot more than just being `return this.manager`.

https://github.com/iopleke/Minechem/blob/53bc9d17c25bd0b35f222f20b2068589528d7e89/src/main/java/minechem/tileentity/prefab/TileEntityProxy.java#L227-L229

They are also on a newer version without release, so it is a bit difficult to see, if they have already fixed that (they refactored a lot)
