### ISSUE TITLE
Crafting stuck in simulation

### ISSUE THREAD

**Issue by aqm1123** [AppliedEnergistics/Applied-Energistics-2#2351]
I don't know why but my ME system doesn't allow me to craft any kind of item anymore. All it says is simulation with the button grayed out. I've checked online for solutions but none of them make sense. Really need some help otherwise I will no longer be able to auto craft.

**Comment by aqm1123** [comment]
![2016-08-15_22 21 02](https://cloud.githubusercontent.com/assets/21049597/17686012/e8615098-6336-11e6-8cc7-a05c08b6491f.png)
![2016-08-15_22 21 23](https://cloud.githubusercontent.com/assets/21049597/17686014/e862a09c-6336-11e6-8625-b1154ad368e7.png)
![2016-08-15_22 21 52](https://cloud.githubusercontent.com/assets/21049597/17686011/e8608c4e-6336-11e6-8633-cae9a98f0a7a.png)
![2016-08-15_22 20 45](https://cloud.githubusercontent.com/assets/21049597/17686013/e8628756-6336-11e6-9667-6a3d1df8f768.png)
![2016-08-15_22 20 52](https://cloud.githubusercontent.com/assets/21049597/17686015/e86ad7ee-6336-11e6-8732-8291c69e75f4.png)

**Comment by aqm1123** [comment]
Update: If I disconnect the cable going to the cobble generator, the autocrafting works.

**Comment by mindforger** [comment]
would you kindly share your game details? 

MC Version, AE2 Version

Also, as far as i can see you do not have ANY energy cell in your system! the fact that it is working after disabling the cobble input is a strong hint your system is overloaded

**Comment by aqm1123** [comment]
I have Sky Factory 2.4 from the AT Launcher. Minecraft 1.7.10 and Applied Energistics rv2-beta-28. The cobble gen was moving the cobble to the deep storage unit so I don't think I overloaded? All my cells are still full of space.

**Comment by aqm1123** [comment]
Btw I have a tesseract moving power from a lava generator.

**Comment by yueh** [comment]
See #1036 for more information.

Also we can never help or solve bugs, if you never update your modpack. Or the modpack does not update their mods.

**Comment by mindforger** [comment]
`Btw I have a tesseract moving power from a lava generator.`
simple calculation:
system capacity 10k RF -> 1 full charge per tick == 10k RF/tick even when you pump in 1gazillion RF/tick your system is only capable of 10k/tick ... increase the capacity to increase the capability to move power ... you fell for a very common mistake

**Comment by aqm1123** [comment]
Sorry I'm not experts like you I just wanted fucking help.

**Comment by bookerthegeek** [comment]
@aqm1123 I'm sorry you an entitled little shit. They did help you out, and pointed out that it is a common mistake people make. Don't be a D-Bag.

**Comment by aqm1123** [comment]
How does pointing out that I'm an idiot help me? How does calling me an entitled little shit help me? I read the thread Yueh referenced, but like I said I'm not an expert. I just started picking up this game again a month ago. Maybe you shouldn't be such an asshole. I only made this account to ask "the experts" a question. Mindforger I used the network tool while the cobble gen is running and the network only uses ~600RF/tick. I saw that storage buses are buggy or something and I do have one on a DSU. What do you suggest I do instead of using a storage bus?

**Comment by bookerthegeek** [comment]
Import into the network at a slower rate. Do you need all the cobble avaliable all the time? If not then...

Fill a chest with cobblestone from the DSU automatically. Use a hopper or item node.

Put the item interface on the chest.

Export cobble overflow back into the DSU.

**Comment by bookerthegeek** [comment]
Also you still don't need to be a D-Bag to people because they don't barney style how to fix things for you. If you don't understand an answer just say so. :)

**Comment by aqm1123** [comment]
Thank you.

**Comment by bookerthegeek** [comment]
You are welcome.

**Comment by mindforger** [comment]
@aqm1123 like i calculated for you, when your system has only limited total capacity but requires more power in one tick than you have, it offlines for 1 tick and then gets stuck because on the next operation it is empty again!

(This game is still tick based, so 20 times a second you can fill up the networks capacity with power but when ther is not enough power stored in the network the operations will pause)

try adding at least one energy cell and see if your system works more smoothly, also an important hint, do **never** lock the DSU, it might fuck up AE2, something that has to be changed by MFR but never did

when you constantly import stuff into an DSU (item by item) connected via Storage Bus, your network keeps updating it's content ... this is very tick time consuming and may render other network operations slow or paused!

Maybe build an stand alone network for working on your all time crafting stuff and only import the results as an idea.

@bookerthegeek to be fair, starting with `I'm sorry you an entitled little shit` maaayy have spilled a little oil into the flames :)

**Comment by bookerthegeek** [comment]
@mindforger yeah... :/

But you know self improvement has been helping, I did say sorry... next time I'll make sure to preface it with "no offence". Then they can't get mad right? ;)


Srs though, point taken and I'll attempt to not be such a firestarter.

**Comment by mindforger** [comment]
aaaand now i got "the prodigy - firestarter" in my ears XD
