### ISSUE TITLE
Recipes are Broken

### ISSUE THREAD

**Issue by mightydanp** [AppliedEnergistics/Applied-Energistics-2#2375]
All Recipes are non-functional. This can be seen during startup:

```
[00:58:54] [Client thread/WARN] [AE2:C]: Unable to register a recipe:Unable to find item: appliedenergistics2:ItemMultiMaterial:2
...
```

This is due to changed registry names and should be fixed with search&replace.

**Comment by mightydanp** [comment]
what do you mean by search&replace

**Comment by KamranMackey** [comment]
@shartte Any status on when this will be fixed?

**Comment by yueh** [comment]
This is one of the last things we will resolve. Thus expect it to be part of the beta releases.
Maybe during the (late) alpha cycle, but very unlikely.

**Comment by KamranMackey** [comment]
Maybe I could fix it. In which files are the recipes located?

**Comment by shartte** [comment]
I think yuehs intention here is to avoid misleading people into believing they can safely use an unreleased version in survival playthroughs.

**Comment by DFliyerz** [comment]
Not cool. All of the names are messed up so the recipes are referencing non-existent items, while the names of the items can be easily found. I was able to fix it, but then lost the files to a Windows Explorer issue. Why aren't you fixing it?

**Comment by KamranMackey** [comment]
I'm not using it in a survival playthrough. I do however want this issue to
be fixed, and I'm willing to fix it. I just need the names of the files
where the recipes are located.

**Comment by KamranMackey** [comment]
@shartte ^

**Comment by DFliyerz** [comment]
@KamranMackey All of the recipe files are in the config folder.

**Comment by JosephRymer** [comment]
@KamranMackey what exactly is going on with the recipes that makes them broken

**Comment by yueh** [comment]
Preventing usage in survival is one of the reasons. But not the major one.

The item names are still not final, which means

1. Anyone using it currently will certainly lose items, due to the nature of AE it might even include everything they have stored.
2. It will be wasted time as the recipes have to be constantly updated. It is still a manual process without any refactoring support. Using normal search and replace can also break it and thus must be tested.
3. We certainly need to rework the whole recipe system. It is lacking NBT handling, which will very likely become a necessity in future minecraft versions. Extending the current parser for full NBT is probably way too complicated/tedious. Therefore we did consider using yaml or a similar serialisation language as base and just extend it to support the required data types for NBT. Which also means the current recipes and any work in them will be wasted.

Therefore even if someone would submit a PR, we certainly would not merge it before everything else is done.

**Comment by DFliyerz** [comment]
I've made a version of the user config folder with fixed recipes, I can release it if needed

**Comment by shartte** [comment]
I think the recipes should now work in the 1.10 branch. Please report any that are broken.
