### ISSUE TITLE
Shift pull

### ISSUE THREAD

**Issue by dpeter99** [AppliedEnergistics/Applied-Energistics-2#2395]
The shift click is not working
It only grabs the item.
It should move it into the player inv.

**Comment by shartte** [comment]
Might be an issue with changes to:
> appeng.client.gui.AEBaseGui#handleMouseClick
Will look into it. I think I have observed other issues with the click behavior as well. I will have to look into the expected behavior first though.

**Comment by yueh** [comment]
Regarding the current click behaviour in terminals.

Condition for all:  
* Limit to stored amount, when less items than requested are stored. 
* Anything regarding stacksizes usually applies to the amount stored. Extract half a stack means `min(maxStackSize/2, storedAmount/2)`
* any means `empty hand` or `holding the same item`. Not `holding anything`, except otherwise stated.
* `*` means really anything

**Network inventory**

Click | Action
------------ | -------------
Left Click + empty hand |  Extract 1 full stack from the network, place under cursor
Right Click + empty hand |  Extract half a stack, place under cursor
Left Click + holding itemstack |  Place hold item into network
Right Click + holding itemstack |  Place exactly 1 item into the network
Shift Right Click + any |  Extract exactly 1 item into the network when same item
Shift Left Click + * |  Extract 1 full stack to the player inventory
Shift + Mousewheel Down | Extract exactly 1 from the network
Shift + Mousewheel Down | Place exactly 1 into the network

**Crafting grid**

Click | Action
------------ | -------------
Left Click + any | Craft once place under cursor until "full"
Right Click + any | Craft until curser holds a full stack
Shift Right/Left Click + * | Craft full stack to player inventory

**Player inventory**

Click | Action
------------ | -------------
Shift Right/Left Click | Place full stack into network
Shift Right/Left Double Click | Place all of that item into the network (second click basically on empty slot)

**Pattern grid**

Similar to crafting grid in general. Except due to using fake slots the crafting works slightly different.
Instead of crafting that item, it first tries to extract the item from network before actually crafting anything. This can lead to false reports about duping, because it appears to "craft" even without the required items, but is actually just extracting the existing one from the network

**Slightly unrelated**

There might be some potential for QoL improvements.
Like the mousewheel interaction only works when the cursor is over the same item. It might be idea to extend it to the overall gui. So shift+mousewheel can directly interact with the network even when the cursor is over one of the player inventory slots or just holding an itemstack.
