### ISSUE TITLE
Security Enabled Blocks

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#24]
The idea is that these can be used to fortify your base / storage room with your network security system.

Planned still need to get to them.

Originally Posted by AlgorithmX2

This issue was migrated; For original details see http://ae-mod.info/Tracker/0244/

**Comment by yueh** [comment]
I would say there are two options for it.

1. Create new special blocks for it.
These would be pretty limited design wise, but might be a good starting point to add facades to fullblocks.
2. Apply it to every part of the grid, would for example already allow facades

Instead of just making them invincible while powered, we could also let them actively consume power to prevent breaking blocks instead just a simple passive consumption.
For example preventing a TNT explosion will consume more power than a player trying to break a single block.
This would require the player to plan enough buffer capacity into the network instead of simply throwing more power at it. The passive power consumption could be pretty less in this case.

Maybe rv3, but could probably be postponed.

**Comment by Technici4n** [comment]
Probably not going to happen, but addon developers are welcome to implement it.
