### ISSUE TITLE
spatial dimension selection grid

### ISSUE THREAD

**Issue by dpeter99** [AppliedEnergistics/Applied-Energistics-2#2455]
![2016-10-11_15 17 33](https://cloud.githubusercontent.com/assets/7725817/19271915/eda9e65c-8fc6-11e6-9b56-929ba95c2c26.png)

is this intentional (the extra line on the blocks side)?

**Comment by shartte** [comment]
Ah no this is a rendering bug.

**Comment by yueh** [comment]
There are a couple of issues it causes

1. **No selection box at all**, usually the normal state
2. **F3 will enable it again**, but only until I change to another hotbar slot. 
3. **Diagonal line**. Only happens when I open the chat input, otherwise it appears never.

If it is using `GL_LINES`, would not even be surprised, if behaves differently with another graphic cards model/driver.

**Comment by shartte** [comment]
This is most likely caused by the sky renderer i'd wager. I had the same issue with custom TESR code and will look into it here.
