### ISSUE TITLE
[1.10.2] Extra Utilities 2 Crash

### ISSUE THREAD

**Issue by whatthedrunk** [AppliedEnergistics/Applied-Energistics-2#2465]
http://pastebin.com/nVP3gack

It looks like its crashing from looking at the facade sprite in JEI. It's probably not a rush for you guys to get fixed but is there a way to disable facades from showing up in JEI? This might be a nice fix for similar issues in the future.

**Comment by shartte** [comment]
> It's probably not a rush for you guys to get fixed but is there a way to disable facades from showing up in JEI?

You can disable individual facades in the Facades.cfg config file. But I will look into cross-mod compatibility soon.

**Comment by yueh** [comment]
While we probably should add a more sophisticated check to detect, if blocks can be turned into facades. For example like C&B does it.

Here it is clearly an issue of XU2 not respecting the method contract allowing to pass `null` due to the parameter being `@Nullable`. Further `null` is actually being passed along by JEI based on the callstack.
Thus we are more or less just caught in the middle.

**Comment by shartte** [comment]
@whatthedrunk To fix this after updating to the latest revision, you have to delete your `Facades.cfg`. 
AE2 will now by default not enable facades for blocks with extended block states (all of XU2's blocks have that). One can enable it on a case-by-case basis via the config, but in XU2's case, it would continue to crash.
