### ISSUE TITLE
CraftingCPUCluster not correctly cleaning up after finish

### ISSUE THREAD

**Issue by yueh** [AppliedEnergistics/Applied-Energistics-2#2530]
`CraftingCPUCluster` are not correctly cleaning up the internal `MECraftingInventory` due to using `isEmpty()`, which takes craftable items into account and not just the stored ones, thus it still keeps a list of itemstacks with a size of 0 around and constantly tries to clean it up.

**Comment by shartte** [comment]
Note that this only happens if a crafting task uses intermediary items that are themselves craftable, since apparently they are added to the internal inventory as "craftable" when they are stored for use by further steps in the crafting job. Upon being extracted from the internal inventory, their stack size reaches 0, but due to still being marked as craftable they are not removed from the inventory.
