### ISSUE TITLE
Use IDeepStorage for Quantum Storage Unit

### ISSUE THREAD

**Issue by RealGrep** [AppliedEnergistics/Applied-Energistics-2#2550]
#### Description
I've attached a storage bus to a Quantum Storage "DSU". However, it only sees 64 items which are in its output slot. It should be able to see the actual number of items in the deep storage. I assume it's simply not using IDeepStorage to access it, as it would have for MFR DSUs in 1.7.10, and needs special handling.

The Quantum Storage Unit's name is quantumstorage:quantumdsu, in case that's relevant. You can find it here: https://minecraft.curseforge.com/projects/quantumstorage and the Github is here: https://github.com/gigabit101/QuantumStorage

#### Environment
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-2
- Forge Version: 2116
This is in SMP.

Mod list: https://www.dropbox.com/s/xbk3sl3cnncjbdi/MODS.txt?dl=0
No crashlog or anything of use in the logs. I can certainly provide it, but it seems quite irrelevant in this case. Let me know if you need anything else. Thanks for all your work, folks! Really appreciated.

**Comment by yueh** [comment]
We decided to drop any support for special inventories in 1.10 because forge provides  a common interface now for anyone to use (at least up to 2^31 per slot, like a dsu).

This results in longer having to add support for every storage mod out there to every mod interacting with storages. Now each storage mod can implement their own solution and everyone can use it. And it just works. For example storage drawers, there is no special support for it on our side.

Should a mod still insists on doing it as in 1.7.10 instead of adapting to 1.10, they certainly can expect other mods not supporting it when there is another solution which requires less work and provides more benefits.

**Comment by RealGrep** [comment]
Thank you very much. I'll file a PR with Quantum Storage, then.

**Comment by EmlJnke** [comment]
Just wanted to add that there is a MFR version for 1.10.2, so you can just use the original DSU's like in the good old 1.7.10... (And they **ARE** supported by AE2 storage bus!)
Hope this helps anybody ^^
