### ISSUE TITLE
Add a filter to identity annihilation plane

### ISSUE THREAD

**Issue by Ravin890** [AppliedEnergistics/Applied-Energistics-2#2563]
#### Description
I have used both annihilation planes and when trying to automate picking up blocks with it, the results include lag. Also it does have identify in name (yes i know it more or less just silk touches the blocks it picks up) but it should allow the player to specify the blocks it should identify as well.

**Comment by yueh** [comment]
#98

**Comment by VT-14** [comment]
You can filter the planes by allowing the local ME system to only accept the items you want.  It's relatively strait forward with sub-nets.

This suggestion has been rejected many times due to it being possible with the tools already present in the mod.  The developers are not interested in bypassing the tools they already made and giving a no-brainer solution.
