### ISSUE TITLE
Allow Storage Cells to be Directly Placed into Drive Bays

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#2583]
When right-clicking with a storage cell onto a ME drive or ME chest drive slot, it should be possible to directly place the storage cell into the drive without having to go through the UI first.
Shift-Right-Clicking a storage slot should then remove the storage cell in that particular drive bay.

**Comment by misson20000** [comment]
Conventionally, shift-right-clicking anything that has a right-click action will not invoke that action, like when you shift-right click a chest holding a block, it'll put the block down instead of opening the chest. Shift-right-clicking anywhere on the drive should preserve this behaviour and seperate the storage component and the storage housing on the drive you're holding (if you're holding one) just like if you had right clicked anywhere else.
