### ISSUE TITLE
Power Acceptance

### ISSUE THREAD

**Issue by Ravin890** [AppliedEnergistics/Applied-Energistics-2#2591]
#### Description
In the 1.7 version of AE2, the controller was able to get powered by multiple mods. In 1.10 I could only get EnderIO to indirectly power it. Immersive Engineering's connectors/wires won't power the controller nor will ExtraUtils2's wireless battery/transmitter. The generator from ExtraUtils will power the controller though.

**Comment by mindforger** [comment]
install Tesla API mod

**Comment by Ravin890** [comment]
Would not have thought of that.

**Comment by mindforger** [comment]
power systems in 1.10 are a mess currently, but i found another issue where backward compatibility to RF and IC2 should be coming with the next build, don't quote me on that, was just a drive by reading

**Comment by Ravin890** [comment]
okay. Will test that in a few hours, when i can get to my pc.

**Comment by ItzKdoge20YT** [comment]
i did installed Tesla-API mod and it still doesn't connect rf cable to ME Controler or Energy Acceptor

**Comment by XFactHD** [comment]
Tesla doesn't have anything to do with RF and as @mindforger said, RF is currently not supported but might be in the next version.

**Comment by mindforger** [comment]
>connect rf cable

also this argument isn't detailed enough to help in any way, which cable from which mod ?
@Ravin890 was referring to IE, which is only compatible when having Tesla API and using connectors, direct powering is not possible (... yet ...) 

i have no exact idea which API EXUtils is using, but this might be also Tesla related

for mekanism i only know that their current/past implementation is wonky, i have no idea of the actual status or direction they are going

using Tesla API helps out a bunch but not all, please refere any statements that go about "not working" with which exact mod!

**Comment by yueh** [comment]
As @mindforger said, the energy systems are currently a mess. RF is pretty much obsolete with IE being pretty much the only mod using it as the only option.

Everything else supports usually at least 2 power APIs. With Tesla or Forge Energy/Units usually as the secondary option. Tesla is a bit more complicated, as it has to be droppend into the instance as .jar. But that is thanks to forge and their poor design concept for dependencies and certainly nothing which will go away in the future. So players will have to deal with needing to download api .jars on their own.

I could see supporting RF for a transition phase (read as "Will be droppend with rv5 or IE supporting Forge/Tesla. Whatever comes first."). But then wrapping RF into a handler for forge energy is certainly not complicated and would allow anyone support it to access it, while your own mod can still use RF internally and does not have to switch to a different one. Especially as in terms of balance there is absoluetely no difference between RF and Forge Energy.

Otherwise see #2438

**Comment by XFactHD** [comment]
[Here](https://github.com/BluSunrize/ImmersiveEngineering/issues/1622) BluSunrize stated his opinion on Tesla and FE support.

**Comment by ItzKdoge20YT** [comment]
@mindforger using solarfluxreborn cables, i tested enderio still not connected.

**Comment by mindforger** [comment]
from their informations i read they are using RF like IE, so you'll have to wait until either AE supports RF again or Solarflux switches to something compatible (there are plans to support EU(IC2) conversion on their project site)

**Comment by ItzKdoge20YT** [comment]
okay

**Comment by ItzKdoge20YT** [comment]
Rv-4-Alpha-5 seems AE2 re-added EU API because P2P EU is missing before Alpha 5

**Comment by ItzKdoge20YT** [comment]
if AE2 rv4 is updated, ill test on my survival world in few days.
if doesn't work might try on creative testing or waiting another update and test again.

**Comment by ItzKdoge20YT** [comment]
what happen if AE2 updating from alpha 10 rv4 to ? beta or alpha 11?

**Comment by VT-14** [comment]
As was posted by p455w0rd in #2438, Here is a [Google Spreadsheet](https://docs.google.com/spreadsheets/d/1cay91dfNXrell8swa43yk2L6JVOlzSD0Qo7AOxz3nGk/edit#gid=534173858) which goes over most mod power APIs.
