### ISSUE TITLE
Loading causing spongeforge servers to crash whilst starting (no crash report generated)

### ISSUE THREAD

**Issue by dovahkiin4991** [AppliedEnergistics/Applied-Energistics-2#2642]
Upon starting a server with any spongeforge file in 1.10.2 appliedenergistics loading order causes the server to crash within seconds of starting server.

#### Description
When starting the serve I expect spongeforge to load first being an api for the server, but ae2 is prioritized and it loads class files before spongeforge can patch them. Implementing a way to put off its loading till later would be helpful or a dependency file/config so the loading can be delayed till other mods are loaded
#### Environment
This issue is when loading the direwolf20 1.10.2 pack that has been released and is a server. I have successfully isolated it to be applied energistics causing the issue and testing alone still causes this issue. No crash report is generated by this but I was able to get most of the command promt print before is crashed the only bit not included is giving information on sponge forge and applied energistics but nothing involving the crash
http://pastebin.com/944xtcux
- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-5
- Forge Version: forge-1.10.2-12.18.2.2124-universal.jar

**Comment by dovahkiin4991** [comment]
why was this closed

**Comment by XFactHD** [comment]
Because this is like the 30th post with the same crash. I would be nice if people would use the search to see if it was already posted by someone else before posting stuff. There is even a discussion going on about this were yueh stated that he is working on AE's coremod to see if it is even needed before taking the simplest fix for this.

**Comment by Stuart74** [comment]
Guess there wouldnt be 30 different issues like this if the dev actually fixed the issue instead of closing it with no response to whether its going to be fixed or not

**Comment by dovahkiin4991** [comment]
simply adding a configurable dependency would resolve the issue

**Comment by mindforger** [comment]
> Guess there wouldnt be 30 different issues like this if the dev actually fixed the issue instead of closing it with no response to whether its going to be fixed or not

Guess complaining is easier than searching? Seriously, why so bold?

> simply adding a configurable dependency would resolve the issue

No it wouldn't(at least the devs stated so), it is beeing worked on but the issue is more complex, stay patient please and don't go bold like the other one :)

**Comment by Bubble0seven** [comment]
> Guess complaining is easier than searching? Seriously, why so bold?

You make the assumption that he didn't search such ignorance. Why such an ego?

**Comment by mindforger** [comment]
>You make the assumption that he didn't search such ignorance. Why such an ego?
sorry for making assumptions on things happening all over and over and over and over ... again

you may not know but there are several mods, that have died due to people complaining and shitposting, i just hate (ye that word is very hard but it hits the spot) his ignorance ... he himself said "30 different like this" not noticing how much effort it is to always get the up to date link to the relevant issue where it is already beeing worked on BECAUSE THERE ARE ALREADY 28 OTHERS ... 

he is complaining about something he himself is inducing ... now THAT is some level of ignorance i can not tolerate!

**Comment by Bubble0seven** [comment]
Then instead of doing exactly the same thing as your complaining about maybe post a link to the the most up to date issue instead of shitposting his post remember it is a community and there are good and bad in every one of them, but to complain about somebody complaining that is simply you trying to feed your own ego more than anything, it does not solve the issue your just creating more drama. Have you ever considered that he has said what he has out of sheer frustration of having to look through a plethora of links both here and on sponge forums about the same issue but not seeing much results....

Also i am sure most developers do have thicker skin than you think they are not going to crumble because of a few frustrated comments being made, and yes i have seen mods leave due to shitposting the dev from thermal expansion is one big one that comes to mind.  I am not advocating people shitpost or be negative but i do see that frustration sometimes comes across as something more than it should be taken.

You also felt the need to insult the member to another person in the thread such maturity you show there. There was no need to be that way you were just being bold yourself and a hypocrite.

End of the day you should of ignored it instead of making such remarks there was no need you are just being a snowflake.

Anyhow back on topic

**Comment by mindforger** [comment]
>insult the member 

where did I? you are making hollow assumptions

by the way you did it just by yourself ... so much for **your** ego and level of perspective
>hypocrite, feed your own ego, such maturity you show there, you are just being a snowflake

just leave me alone and don't escalate things

>Have you ever considered that he has said what he has out of sheer frustration
and by the way, did you consider that i did the same on your post? 

funny how you describe your own behaviour more accurately than mine

**Comment by Bubble0seven** [comment]
thank you for proving my point

**Comment by dovahkiin4991** [comment]
Just stop this isn't going to solve the issue, I didn't check if other had posted this issue, that Is my fault, but there is no need to turn this into anything more, we all want the issue to be resolved but complaining wont make it come any faster.
