### ISSUE TITLE
is there a way to remove ESPECIFIC ores from the grindstone?

### ISSUE THREAD

**Issue by Tsukiumy** [AppliedEnergistics/Applied-Energistics-2#2643]
appliedenergistics2-rv4-alpha-6
forge 2157
i was looking at some recipes and found that the grindstone is taking some of the mekanism ores that need a real lot of work to be processed and making it very easy to bypass, pobably because of the oredict name of the itens, Crystal*ore*. 
i looked at the config file, but it only allow me remove the oredict from there, not the specifc keyworld,
is there another way other than minetweaker?

**Comment by yueh** [comment]
Not really, it will automatically create mappings from anything `(ingot|gem|crystal)`, but only if these types are whitelisted.

Also it only allows them to be turned into dusts. Pretty much anything with a grindstone/pulverizer/macerator/whatever adds turning ingots back into dusts. Which are usually the first step of any further processing. If Mekanism has a different order and places crystals before the dust version, there are certainly many other mods breaking it.

**Comment by Tsukiumy** [comment]
its basically the second or tird stage for the 5x ore processing, and so far only the grindsone adds the direct way, as it only happened after the inclusion of the mod, but meh, not much to do if there is no easy way.

**Comment by yueh** [comment]
I am really not familiar with Mekanism. Could you please summarise the steps shortly?

Also note that the grindstone cannot be automated. It takes about 4 seconds for each ingot to be turned back into dust. So a bit over 4 minutes for a single stack and you cannot scale it up really and I doubt it is time efficient to do it manually.

I just rewritten some part of the registry for grindstone recipes, it might be an idea to add a blacklist for exact oredict entries as additional option instead of just the whitelist for the types. But that requires the other PR for configs to be merged before.
Maybe also remove the crystal case completely and just keep the `ore -> dust -> ingot` + `ingot|gem -> dust` cycle.

**Comment by Tsukiumy** [comment]
http://wiki.aidancbrady.com/wiki/File:Mekanism-flowchart-v7.png
this ^
the tier 4 part is the cristal formation

**Comment by VT-14** [comment]
You still need all of the 4x ore processing machines to even use those crystals.  I would be more concerned about that breaking the Grindstone's 1.9x ore processing for the early game.

Did you try sticking a piece of Iron ore (or another ore) in there?  If you get 2 dusts out, then it's just a case of JEI finding multiple recipes that you can't actually use (semi-common with the ore dictionary; for instance, making IndustrialCraft 2 Blocks of Copper when you have Immersive Engineering).  If you get 2-5 crystals, then there is a significant bug where you can't use the grindstone for ore doubling early on.  If you get 5 crystals, then there is also the issue of being able to bypass the initial 5x ore processing portion when you reach that point.

**Comment by yueh** [comment]
Added blacklist with #2644. Should be part of the next build.
