### ISSUE TITLE
Connection between Dense Cable and ME Dense Conduit renders as a ME Smart Cable connection

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#2681]
#### Description
https://github.com/SleepyTrousers/EnderIO/issues/3878
![2016-12-04_15 41 02](https://cloud.githubusercontent.com/assets/8670392/20867218/8913843e-ba3f-11e6-9fb4-e09ef44da6f5.png)

#### Environment
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/629596/list.txt)
- Minecraft Version: 1.10.2
- AE2 Version: alpha 8
- Forge Version: 2135

**Comment by yueh** [comment]
EnderIO issue as they tell us to render it as smart cable, not dense.

**Comment by HenryLoenwind** [comment]
I don't really see anything in the API to set that. I see GridFlags.DENSE_CAPACITY and AEColor.TRANSPARENT, but nothing about the cable type.

On the other hand, it does not make any sense to render a different cable type than the cable that is in that block---as we will always render a conduit with a connection plate. AE2 doesn't use connection plates, I think? Otherwise it'd make sense to render that on your side, too.

**Comment by yueh** [comment]
`IGridHost#getCableConnectionType()` is responsible for neogating the maximum supported cable render type between two sides as cables have to share them across a single blockspace.

**Comment by HenryLoenwind** [comment]
thx

**Comment by HenryLoenwind** [comment]
This enum really needs a "I_AM_NOT_AN_AE2_CABLE___RENDER_AS_YOURSELF_CONNECTING_TO_A_BLOCK" value...

**Comment by mindforger** [comment]
dense cable always connect as 8 channels to blocks (as default AE blocks only can handle 8 channels), this would result in the old and wrong behaviour :P
