### ISSUE TITLE
[1.10.2] Terminal crafting very slow

### ISSUE THREAD

**Issue by DeadSix27** [AppliedEnergistics/Applied-Energistics-2#2695]
- Minecraft Version: `1.10.2`
- AE2 Version: https://github.com/AppliedEnergistics/Applied-Energistics-2/commit/a2b20f1d678cb7b28960af295d7a950f639d9dd6
- Forge Version: `forge-1.10.2-12.18.3.2185`
- List of mods: _`If you need that, say so.`_

I went through most of the seemingly related issues and couldn't find a proper answer to my question (Altho admittedly I didn't read every single reply):

A video explains this way better (see bottom of issue)

Crafting things seems very slow compared to 1.7.10, where this kind of crafting was visually instant.
Performance of server should be alright, tps is fine too. ~17ms Mean tick time.

If this is a known issue, please link to the issue :) and sorry for dupe.
If not, any idea what causes this?
Storage network is just a controller, terminal and a drive with 4x 4k cells + fluix glass cables.

![f67546a32652](https://cloud.githubusercontent.com/assets/1492505/21079793/5a385b18-bf9d-11e6-97d3-e62105185621.gif)

**Comment by yueh** [comment]
Without any profiling, I doubt we can find anything.

It might even be just a change how 1.10 updates the inventory itself. Shift clicking will split it into multiple crafting ops (basically 64/outputStacksize) and each one will be crafted independently. Thus maybe 1.10 is just synchronising the inventory less frequently.

Or 1.10 crafting handling is even shittier than 1.7.10 already was. But at least the major issue with AE2 causing timeouts is now fixed in 1.10.

**Comment by DeadSix27** [comment]
I'll keep an eye on it and play around with it, but it indeed seems more like 

> Thus maybe 1.10 is just synchronising the inventory less frequently.

Is probably the answer.
