### ISSUE TITLE
Autocrafting is not working for semi-big projects

### ISSUE THREAD

**Issue by TheiMacNoob** [AppliedEnergistics/Applied-Energistics-2#2701]
I am trying to autocraft a triple compressed cobblestone on AS2 (Agrarian Skies 2) on my server. It wont craft for some reason. I have 32 KB storage and 18 co-prossing units. Here is a video or my problem.  https://youtu.be/Nn3ejPqTtTI

Have a Good Day!

**Comment by GuntherDW** [comment]
Notwithstanding that you didn't provide any information on the versions used (besides the fact that AS2 is quite an old pack with even more outdated mod versions), it is a 1.7.10 pack.

The 1.7.10 version of AE2 is no longer being worked on.

Nevertheless, seeing as the pack is quite old, try updating to a more recent version of AE2 first.
You'll likely have to update a bunch of addon mods as well because of a rv increase.
