### ISSUE TITLE
[1.10.2] Crafting Voids Item from Mod

### ISSUE THREAD

**Issue by Elvarion** [AppliedEnergistics/Applied-Energistics-2#2752]
#### Description
Autocrafting that has items being returned are lost upon crafting.
I am trying to craft some items from the mod called "Woot". These crafting operations require a "Hammer" and a "Casing Dye". Both which are **returned** upon crafting. Crafting them normal in the Crafting grid will give them back. However when using the Assembler and Autocrafting the hammer and casing gets voided. Also the system does not think it will be getting the Hammer and Casing back so crafting more then the amount you get from a single crafting will tell you that you need more Hammers and Casings.

Since we have Refined Storage also on the Server I tried it there and the Hammer and Casing are returned upon crafting.

Tried some crafting with Buckets in AE2 and these were returned upon crafting. So not really sure where the issue lies.

Pre-Crafting
<a href="https://gyazo.com/1850aa1397540a5d943179c0e5c4ae2b"><img src="https://i.gyazo.com/1850aa1397540a5d943179c0e5c4ae2b.png" alt="https://gyazo.com/1850aa1397540a5d943179c0e5c4ae2b" width="589"/></a>
Pattern
<a href="https://gyazo.com/e718f77edbc4356739b0e5cdf9ff4de8"><img src="https://i.gyazo.com/e718f77edbc4356739b0e5cdf9ff4de8.png" alt="https://gyazo.com/e718f77edbc4356739b0e5cdf9ff4de8" width="587"/></a>
Crafting Screen
<a href="https://gyazo.com/edb7e1692ed8c9c868ac947d254c9b89"><img src="https://i.gyazo.com/edb7e1692ed8c9c868ac947d254c9b89.png" alt="https://gyazo.com/edb7e1692ed8c9c868ac947d254c9b89" width="727"/></a>
Post-Crafting
<a href="https://gyazo.com/95a58f6d5b77b903a55eaf57182be5c2"><img src="https://i.gyazo.com/95a58f6d5b77b903a55eaf57182be5c2.png" alt="https://gyazo.com/95a58f6d5b77b903a55eaf57182be5c2" width="593"/></a>
As you can see the Hammer and the Casing Dye is now gone.
There is no Exporting on my network of any sort. Its a closed system with 3 Interfaces connected to Assemblers, a 1k Crafting Storage and 1 Drive

#### Environment
SMP Server
Resonant Rise mod pack

- Minecraft Version: 1.10.2
- AE2 Version: appliedenergistics2-rv4-alpha-11
- Forge Version: 12.18.3.2185

**Comment by yueh** [comment]
Opposed to buckets and other tools, these are not valid container items. Therefore they will not be returned as part of the vanilla crafting. Instead they are duped back into the crafting inventory by a custom recipe handler.

For performance and stability reasons, AE only performs the recipe once when loading a pattern and considers the normal output + container items as valid options. The crafting itself just dupes the cached output as actually performing a real crafting operation can easily be a major performance issue with poorly written custom crafting recipes in a high throughput situation. As well as break the whole crafting chains due to crafting random items, which no longer meet the defined item for the pattern.

Thus you should request that woot actually uses the vanilla way to handle tools with container items, if you want to see it work.
