### ISSUE TITLE
Drives not working when placed above air (Server Issue?)

### ISSUE THREAD

**Issue by UnPure** [AppliedEnergistics/Applied-Energistics-2#2778]
I'm currently playing with a skyblock modpack. I just crafted a drive and everything else i need to get a basic ME System running. I placed the Energy Acceptor, a Fluix-Cable on the side of that and the Drive on top of that cable. The cable is flaoting above the void (x:69), no solid blocks under it ([Example](http://i.imgur.com/HiLQ7ha.png)). Once the Drive is placed, its completly broken. You cant open the GUI and cables are not connecting to it from any side.
I removed the cable, placed a solid block at the same position and the drive on top and it was working fine. If the Drive is already placed, you can remove any solid block below it and its still working for some reason (and its still working after a restart), so the issue is only there if you place it directly with no solid blocks below.
I tried to recreate the issue in a singleplayer world but i cant recreate the issue. It seems to be a multiplayer problem. 
Its not a sync issue because reconnecting or restarting the server does not solve the problem.

Sorry for my bad english, i hope its not to hard to understand.
If you need any other informations, let me know.

### Environment
* Client Java: 1.8.0_112
* Client OS: Windows 7
* Server Java: 1.8.0_111
* Server OS: Debian 8.6 (64Bit)

### Versions
- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: 12.18.3.2221

**Comment by yueh** [comment]
Missing cables or no GUI is usually an indication that the corresponding tile entity was not created when placing the block.

If it is reproducable, a full log might contain a log entry should it be failing on our side. Maybe also enable the debug logging before, otherwise it might suppress usually.

But I doubt, it might be on our side, there is literally no check is based on the neighour blocks.
Most likely something else is interfering with it. Like some protection mod.

**Comment by UnPure** [comment]
I enabled all the logging stuff and managed to recreate the problem.
I had to break and replace the drive a few times until i could recreate it.

[fml-server-latest.log](https://gist.github.com/UnPure/5022b919d71ba89c832291deb125537d)
[fml-client-latest.log](https://gist.github.com/UnPure/3075aaa7dd2d6c26c1452946c96ef7d1)

I also tested it twice because the chunk that i was testing in, was claimed and chunkloaded with FTB Utilities. After unclaiming the chunk i was still able to recreate the problem.

[Client Modlist](http://pastebin.com/ESd0ZaWL)
The server is running the same mods with 2 mods added:
* "CanIJoinNow-1.10-1.0-5"
* "Morpheus-1.10.2-3.1.13"

and 4 mods removed:
* "CustomMainMenu-MC1.10.2-2.0.2"
* "jeibees-0.9.0.4-mc1.10.2"
* "NotEnoughItems-1.10.2-2.1.3.199-universal"
* "WailaHarvestability-mc1.10.2-1.1.9"

Besides the FTB Utilities stuff, there is no other "protection" mod.

**Comment by yueh** [comment]
Way too many mods to resolve. The fastest way should be to disable one half of the mods, then try to reproduce it. If not test the other half. If it still happens, split the current half again.

Not sure about FTB Utilities claiming being an issue, it might just because there mod is there. The 1.7.10 version did some pretty horrible things, thus my trust in it is not very high.
