### ISSUE TITLE
Redstone Duping

### ISSUE THREAD

**Issue by zlainsama** [AppliedEnergistics/Applied-Energistics-2#2791]
Formation plane duplicates redstone dust when mod Flux Networks is also installed.

This happened with rv4.alpha build 11.

This is a related issue ticket i found on this repo:
#2764
I want this got more attention, so i created this ticket.

This is the related issue ticket on Flux Networks:
SonarSonic/Flux-Networks#28
This also happened with SpongeForge, they have it fixed in:
SpongePowered/SpongeForge@8230a5277a856ecb9d9c35fac5d350374d324e11

This is the related lines in Flux Networks code:
https://github.com/SonarSonic/Flux-Networks/blob/c5f3358aa565c1a6ee93aa6046e1406e89ee7be1/src/main/java/sonar/flux/FluxEvents.java#L73-L97

**Comment by yueh** [comment]
There is nothing we can really do. Flux Networks cancels the event, which essentially means "do nothing and do not destroy the item". While then continuing to dupe the redstone.

No way to distinguish between the valid canceled event, which can happen for various reasons and should not result in voiding items vs the "canceled but not really canceled" approach by flux networks.
This is really something, which needs to be resolved at forge level. Like providing a way to replace the spawned entity without having to cancel it.

**Comment by fsedarkalex** [comment]
Does someone know the sense behind this in Flux Networks? Can't AE2 just ignore this event cancelling?

**Comment by GuntherDW** [comment]
Flux Networks does this to replace the "vanilla" redstone with a redstone item (the same happens to a bunch of other items/blocks as well) that is fireproof.

FN does this to get flux instead of a destroyed item when it touches said fire.
We can't "just" ignore the event cancelling because there are other reasons as to why it might be cancelled. AE takes the safe approach and would rather not destroy items in the process.
