### ISSUE TITLE
charged quartz fixture does not attach to bottom of bottom aligned half slabs

### ISSUE THREAD

**Issue by brnnnrsmssn** [AppliedEnergistics/Applied-Energistics-2#2799]
placing a quartz fixture on the downward facing surface of a half slab that is occupying the bottom half of the block space is impossible. however if the half slab occupies the upper half of the block space placing the fixture on the upward facing surface works as if the block below was a full block. placing on the downward face of a full block also works.

from the ftb infinity evolved 1.7 (v2.6.0) modpack on a multiplayer server

- Minecraft Version: 1.7.10
- AE2 Version: rv3-beta-6
- Forge Version: not sure which you are asking for
minecraft forge 10.13.4.1614
forge modloader 7.10.99.99
forge microblocks 1.2.0.345
forge multipart 1.2.0.345
forge relocation 0.0.1.4

**Comment by VT-14** [comment]
1.7.10 is no longer being supported.  I'm unable to reproduce this issue in the current 1.10.2 version (rv4-alpha-11 on Forge 12.18.3.2221).

For future reference, "Forge" is Minecraft Forge.

![2017-02-16_00 05 53](https://cloud.githubusercontent.com/assets/12564251/23008188/0d0e2c1e-f3dc-11e6-94ab-d069740b1253.png)

**Comment by mindforger** [comment]
1.7.10 is not supported anymore, sorry

**Comment by brnnnrsmssn** [comment]
closing as the version i am using is unsupported.

**Comment by yueh** [comment]
IIRC they use the same conditions for a valid placement as vanilla torches. As these cannot attach to the bottom of a block at all, it might simply not consider a slab as solid block (vanilla limitation).

Thus could be fixed after 1.7.10.

**Comment by VT-14** [comment]
In vanilla, slabs and stairs are not solid (double slabs are solid).  They are 'partially' transparent (block light and have special features, but otherwise have the same block properties as glass, glowstone, pistons, etc.).  I believe vanilla also has special coding to allow redstone components, torches, and rails to be placed on top of them.  Mobs can also spawn on top slabs in vanilla (not sure about stairs).  However, since they are partially transparent, you can do things like open chests even with these blocks directly on top of them.

Forge considered that a bug, and made it so these blocks are solid on any side which they take up the entire side.  Bottom slabs will block chests from opening while top slabs will not (and similarly for stairs).  I have no idea when this 'fix' was introduced, but I don't remember having any issues with slabs on top of chests in 1.7.10.  This could easily be a change in Forge for Minecraft 1.8+.

**Comment by yueh** [comment]
It is not really solid in the context of the fullblock, but the side. Which has a couple of hardcoded cases for slabs and what not.

The usual semantic issues with using solid, fullblock, normalcube, fully opaque and what not in some cases with a distinct meaning and in others as interchangable and you end up with solid non-solid blocks.
