### ISSUE TITLE
Compatibility Issue in FTB Beyond

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#2829]
#### Description
While playing FTB Beyond I've come across a compatibility issue which I haven't been able to track down. When attempting to pick up items using shift+right-click you can pick up one item, but not a second one. Additionally when using middle-mouse-button to craft an item that's already present in your network, nothing happens.
It's probably not AE's fault but I haven't been able to track down what causes it.

#### Environment

- Server
- Minecraft Version: 1.10.2
- AE2 Version: alpha-11
- Forge Version: 2254
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/831633/list.txt)

**Comment by Hazmatik** [comment]
Having the same issue here in FTB Beyond, also I can't right click while holding items to insert only one into the system.

**Comment by p455w0rd** [comment]
can you tell me if the same is true with Wiresless Crafting Terminal? I have disabled MouseTweaks via the MouseTweaks API, so if things work as intended with WCT, then it's definitely MouseTweaks.

**Comment by Xiaminou** [comment]
Confirmed, it's mousetweaks. I completely glanced over it for some reason, good call.

**Comment by YaLTeR** [comment]
Please try Mouse Tweaks 2.8, I changed some stuff there that might be relevant.

**Comment by GuntherDW** [comment]
The 2.8 version of Mouse Tweaks is included in FTB Beyond 1.2.1, and does not fix the issues from the OP.
Whilst I can request a craft job using middle click, I cannot use right click in any terminal, even if it's target is ghost items like a Pattern Terminal.

I can take out "half" by using right click, but I can't put single items back using right click.
I also can't specify how much items I want without having them in advance in the pattern terminal.
It doesn't even register that I pressed anything, because the slot stays empty.
Left click to clear the pattern slot works.

**Comment by Hazmatik** [comment]
I went into the mouse tweaks options by pressing "esc" in game and then going to "mod options" and choosing mouse tweaks and then clicking the "config" button and changed the first option "RMB tweak" to false and now the right click works as it should in ME terminals
