### ISSUE TITLE
Portable cell takes and dupes items.

### ISSUE THREAD

**Issue by FeistyPancake** [AppliedEnergistics/Applied-Energistics-2#287]
I had previously taken some food and stored it in my cell, but when I open it later, it's all gone so I try to relaunch. That does not work so I take some items out of the cell, but when I go back into it, the items i took out are still in there, BUT the original items are in my inventory. So I take those items out, and it turns out they are not phantom items when I decide to relaunch again. This is in single player, but not a mod pack. I have a mod list though you can breeze through. Mod List: http://pastebin.com/f0n8HSJ6
![2014-10-10_20 41 42](https://cloud.githubusercontent.com/assets/6760847/4601346/a4e91f5e-50f9-11e4-8007-8ced227ff35f.png)
![2014-10-10_20 41 58](https://cloud.githubusercontent.com/assets/6760847/4601348/a4ec4aee-50f9-11e4-9cca-d5f307f0e6fd.png)
![2014-10-10_20 42 08](https://cloud.githubusercontent.com/assets/6760847/4601347/a4eb3d8e-50f9-11e4-8f4d-1b8a5feb638e.png)

**Comment by ZombieWeeD** [comment]
having a simalar ishue myself i have over 80 mods installed so dont wana list them all i noticed somone said that it worked when facing a certain direction at first this seemed to be true but i quickly noticed its acting funny if when you r.click it is on an object/block if you leave yourself plenty of room so that nuthing is in your focus it seems to work normal if an item/block is in focus when u r.click it only looks like it works and dupes/deletes items as stated towards the top.  I also am in single/lan world.

**Comment by hisorange** [comment]
This was an issue on the old tracker, where the report described that the portable cell dupes items but only when you are right clicking to a block and not to "empty" air. Algo fixed it that time, seems like its back? No version tho.

**Comment by Cisien** [comment]
This issue is closed and ancient. Open a new issue of you can reproduce this on the latest version. It was fixed a few build ago

**Comment by ZombieWeeD** [comment]
sorry yeah i always leave a reply when i google an error report up im using
1.7.10 mc the ae2 version is "rv1-stable-1" at least thats the end of the
tittle.
