### ISSUE TITLE
Processors "drop" items in them if the processors/storage units are in different chunks

### ISSUE THREAD

**Issue by CaptainHooks123** [AppliedEnergistics/Applied-Energistics-2#2885]
#### Description
I have 10 crafting processors with 6x 64k storage blocks and 6x coprocessor blocks. The chunk was split exactly in the middle so the storage blocks and coprocessor blocks were each in their own chunk.
I decided to test things out by using 8 processors to smelt 100k draconium each and then the remaining 2 processors to crush 100k nether quartz each.

The result is the screenshot where I had a million items on the ground which made the server drag to a crawl. I tried to save as much as I could by tossing it back in my system but I wasn't fast enough and lost about half of the resources after 5 minutes or so and the server cleared the items on the ground.
I rebuilt the processors so that each one was in the same chunk and it seems to be better now. Was quite an interesting adventure though :)

#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: RV4 Alpha 11 (FTB Beyond 1.5.3)
- Forge Version: ForgeMultipart-1.10.2-2.0.0.31
![minecraft](https://cloud.githubusercontent.com/assets/28035747/25417740/cdf6b01c-2a0b-11e7-93e9-a9863baaef1a.JPG)

**Comment by mindforger** [comment]
yeah thats a known "thing" as i won't call it "issue" because of duplication reasons if it would behave different
i made a proposal in the past to drop some sort of "read only" disk instead but to be honest i lost track of that idea, dunno if there is still work on it

for now you can either try to chunkload the crafting cpu or move it over a bit to be in a single chunk ... yet nothing that can be done about without introducing duplication glitches

**Comment by CaptainHooks123** [comment]
Completely understood :)  Thank you guys for all you do with this mod!  I absolutely love it.  With the processors/storage in the same chunks everything worked perfectly so I'll just make sure my buddies know to do the same.  Have a great week 👍
