### ISSUE TITLE
Programming

### ISSUE THREAD

**Issue by sergeygta4pony** [AppliedEnergistics/Applied-Energistics-2#2895]
Is it planned to create programming in a new block that performs the function of the desktop. To create resource processing branches as implemented in Steve's Factory Manager

**Comment by CraftMinerKyle** [comment]
Do you mean a Chunkloader? Please edit this comment for the DEV's to understand better.

**Comment by mindforger** [comment]
What he describes is some sort of automation, see Steve's factory manager mod

**Comment by CraftMinerKyle** [comment]
Oh. Well, isn't this why we have P2P Tunnels?

**Comment by mindforger** [comment]
i honestly have no idea what he wants exactly, but i can imagine he tries to compare the mods but AE2 lacks a lot of interfaces the facctory manager provides, likes RS receiver to trigger actions ... i don't quiet see the use in adding such a thing to AE2 which is a item storage mod, factory manager is for managing external storage and machines

**Comment by CraftMinerKyle** [comment]
I'll see what research I can do into Steve's Factory Manager, and post what I can on this thread.

**Comment by CraftMinerKyle** [comment]
Yeah. this mod is pretty much like P2P Tunnels for inventories of almost every mod.

**Comment by CraftMinerKyle** [comment]
This is the Desc. of SFM: Steve's Factory Manager is a mod that allows players to set up systems to manage and move items between inventories and machines. The manager in this mod is unique because it has commands set up as a graphical flow chart removing the need for programming knowledge. Items move instantaneously throughout the network (up to 999 items in one command) and can be processed on a timer (between 1-999s), redstone signal, or block update.

Added Features[edit]
Blocks[edit]
Machine Inventory Manager: Main machine, required in any setup. Manages all blocks along the network.
Inventory Cable: Used for to connect blocks to the network.
Redstone Emitter: Can add/subtract/change redstone signal on any side of the block.
Redstone Receiver: Reads redstone signal on any side of the block.
Inventory Relay: Interacts with inventories of adjacent entities (such as a moving minecart chest), but not players.
Advanced Inventory Relay: As the Inventory Relay, except that it can interact with players. Players are required to register their own names on the machine to reduce the chance of griefing.
Item Valve: Picks up item entities from the world. Items falling in pickup range obey the standard delay that a player has when dropping items. Can pickup from a 7x7x7 area in front or a 3 block radius around it.
Rapid Item Valve: As the Item Valve, but does not have the standard delay on picking up items.
Block Detector: Detects when block updates occur (such as blocks being placed or crop growing to the next state).
Block Gate: Can break and pickup blocks (input mode). Or can place blocks in the world or drop items on the ground (output mode). In output mode items are always placed 2 blocks away if possible, then 1 block away if possible, then dropped on the ground. Can use an item if it has a use action (like a hoe), but it will also drop the item after use. Items can be pumped into the item and they will be immediately placed.
Sign Updater: Can update vanilla signs.
Cable Camouflage: Can alter any block face to mimic another block.
Double-Sided Cable Camouflage: As the Cable Camouflage except that you also have access to the inside faces of the block (only seen when using transparent faces, like glass). These can also be conditionally set based on viewing side of the block (a real life example would be a one-way mirror).
Transforming Cable Camouflage: As the Double-Sided Cable Camouflage, except that you can also alter the block's 3D dimension in the world (similar to a ForgeMultipart block), and it's collision detection.
Cable Cluster: Condenses other Steve's Factory Manager blocks into a single block (except for the Machine Inventory Manager and Inventory Cable), and is capable of performing any of the tasks those containing blocks can do.
Advanced Cable Cluster: As the Cable Cluster except that it also acts as an Inventory Cable. (Sounds like a P2P Tunnel to me)
Creative Supplier: CREATIVE ONLY. Allows an infinite output of any item in the game.
