### ISSUE TITLE
Weak Signal vs Strong Signal Level Emitter.

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#29]
Originally Posted by AlgorithmX2

This issue was migrated; For original details see http://ae-mod.info/Tracker/0304/

**Comment by Technici4n** [comment]
No clue what this is supposed to be.

**Comment by shartte** [comment]
@Technici4n Probably is supposed to mean the level of redstone signal emitted should depend on a certain storage range?

**Comment by Technici4n** [comment]
Oh, well that can be done with 2 level emitters and an AND gate imo.

**Comment by ArcheCraft** [comment]
What is probably meant is that there are two types of redstone signals. Strong ones as emitted by repeater, comparator and weak ones as emitted by normal redstone dust. Weak signals can't power a redstone dust through a block, while strong signals can. So if there was a configuration option in the level emitter to specify this, you could build some contraptions more compact because the level emitter wouldn't power redstone dusts you don't want powered by it.

**Comment by Technici4n** [comment]
Oh I see, thanks for your explanation! :)

**Comment by Technici4n** [comment]
I just implemented this, and honestly it's more confusing than anything. As such, we will not be implementing this feature.
