### ISSUE TITLE
item p2p tunnel is broken

### ISSUE THREAD

**Issue by mgdgfbhevdyeh** [AppliedEnergistics/Applied-Energistics-2#2925]
![2017-06-09_13 49 17](https://user-images.githubusercontent.com/20567492/26962794-427727d2-4d1b-11e7-9d40-03b142569186.png)
![2017-06-09_13 52 30](https://user-images.githubusercontent.com/20567492/26962792-42676c0c-4d1b-11e7-9ee6-7bddf61d69e7.png)
![2017-06-09_13 52 32](https://user-images.githubusercontent.com/20567492/26962793-4276533e-4d1b-11e7-8ef2-58f68436fb30.png)

- Minecraft Version: 1.10.2
- AE2 Version: rv4 a11
- Forge Version: 2281

**Comment by mindforger** [comment]
well i don't see anythign broken, maybe you can explain a little what exactly is broken ?

**Comment by mgdgfbhevdyeh** [comment]
Can not transfer items
can't use pipes

**Comment by mindforger** [comment]
please explain a little more, i will give you an example from what i see and you can tell me the rest that at least i do not get rom the pictures
>you insert into an p2p item bus with an itembufer from enderIO, the output goes ....

an now you have to finish because i see no output anywhere .... and if you by chance mean the other p2p bus attachted to the same cable, you should add somethig that it can insert to because item tunnels can not drop items!

**Comment by mgdgfbhevdyeh** [comment]
You can test it
In my game, it{item p2p tunnel) can not transfer anything
but fluid p2p tunnel work well

**Comment by CraftMinerKyle** [comment]
Wait: Do you have AE2 Stuff installed? There have been past issues with P2P Tunnels and AE2 Stuff. I have had similar issues with AE2 Stuff as well.

**Comment by mindforger** [comment]
i can not see ae2 stuff, how did you catch that? @CraftMinerKyle 

and @mgdgfbhevdyeh lets start this one over as you did not tell anything helpful yet
while ingame, press and hold F3 + C for at least 6 seconds until your game forceibly crashes, upload that crashlog as attachment or pastebin (no wall of text please)

then you will have to explain your setup as your pictures are NOT telling what your setup is ... from what i see you have items inerting from an EIO Buffer into an p2p tunnel but i do not see the OUTPUT p2p tunnel ANYWHERE

did you have proper linked both p2p interfaces, what is your target interface, is it at the same nework and not accidentially stacked as p2p in p2p in p2p, because this is impossible!

**Comment by mgdgfbhevdyeh** [comment]
![2017-06-14_13 52 44](https://user-images.githubusercontent.com/20567492/27117454-3a7ce26e-5109-11e7-8e1b-02971f71af09.png)
![2017-06-14_13 52 45](https://user-images.githubusercontent.com/20567492/27117459-3af9adda-5109-11e7-835b-cdc04a090822.png)
![2017-06-14_13 53 07](https://user-images.githubusercontent.com/20567492/27117457-3ade6926-5109-11e7-8cdc-403e66b1c0bf.png)
![2017-06-14_13 54 01](https://user-images.githubusercontent.com/20567492/27117456-3aacd910-5109-11e7-9d0d-ab0bd5815c63.png)
![2017-06-14_13 54 03](https://user-images.githubusercontent.com/20567492/27117452-3a5cae72-5109-11e7-9594-990eeeeb8874.png)
![2017-06-14_13 54 05](https://user-images.githubusercontent.com/20567492/27117453-3a629472-5109-11e7-8e79-d9aba7e04404.png)
![2017-06-14_13 54 06](https://user-images.githubusercontent.com/20567492/27117455-3aa4acb8-5109-11e7-9a7d-b7f0f4779e72.png)
![2017-06-14_13 54 09](https://user-images.githubusercontent.com/20567492/27117458-3adf7ff0-5109-11e7-8fc2-9eb7b2c776c9.png)
[crash-2017-06-14_13.54.26-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1073633/crash-2017-06-14_13.54.26-client.txt)

**Comment by mindforger** [comment]
you are not using the regular release! please only report isues with the downloadable version in future, but i just found the issue and a comment from yueh
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/2653

the item tunnel does not use the forge capability system, this is possibly a reason for it not working even with hoppers!
@yueh do you have an insight eventually on how far the p2p rework is done?

**Comment by mgdgfbhevdyeh** [comment]
i try use rv11,but it still isn't work
[crash-2017-06-14_19.39.26-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1074440/crash-2017-06-14_19.39.26-client.txt)

**Comment by mindforger** [comment]
>i try use rv11,but it still isn't work

nah that wasn't the reason at all :) i just wanted you to remember for the future, before posting an issue, to make sure you are using the original file :)

let's wait for a comment from the devs hopefully

**Comment by mgdgfbhevdyeh** [comment]
@yueh are you still work here?

**Comment by CraftMinerKyle** [comment]
@mgdgfbhevdyeh Yes this thread is still open. Sorry, the ERROR is still open.
@mindforger I caught AE2 Stuff when he said the P2P Tunnels weren't working, and AE2 Stuff is a garbage addon that barely works that often causes tremendous lag when opening some interfaces and causes P2P Tunnels to just go to poop. I used it before, and some things happened that I didn't think was even caused by AE2 Stuff. Looking at anything copper caused my game to drop to 1FPS (TiC Copper Workbenches, Copper blocks, Copper Chests from IronChest, etc), any looking at modded ores also caused 1FPS, Opening and interacting with BigReactor stuff, P2P Tunnels break, placing the Wireless Receiver causes a game crash, Growth Chamber causes world corruption, much more.

**Comment by CraftMinerKyle** [comment]
I still have a copy of that modpack and world I made for myself. I was saved by COFH Backups, but if you want the copy I had during AE2 Stuff, you can have it. AE2 Stuff is the ONLY MOD I RECOMMEND NEVER GETTING!!! IT IS GARBAGE!!! WHY IS IT STILL ALLOWED ON CURSE?

**Comment by mgdgfbhevdyeh** [comment]
I don't installation AE2 Stuff

**Comment by mgdgfbhevdyeh** [comment]
@yueh are u give up(AE2)?

**Comment by CraftMinerKyle** [comment]
@mgdgfbhevdyeh No, we are not giving up on Applied Energistics. In fact, most of the devs are working on the 1.10 version to make it better. Why do you keep asking that? Also, your P2P Tunnels are registered on the network, As I see the faint lines on the smart cable.

**Comment by mindforger** [comment]
@CraftMinerKyle i already stated that it is possible due to p2p tunnels still not implementing the forge capability system, i asked yueh on a quick insight but he did not yet respond

**Comment by yueh** [comment]
Duplicate
