### ISSUE TITLE
Add back Wrench Support for 1.11+

### ISSUE THREAD

**Issue by mindforger** [AppliedEnergistics/Applied-Energistics-2#2945]
This is just a reminder for future to keep an eye on common solution for wrenching 

missing wrench support did pop up several issues for 1.10

for references Buildcraft skipped 1.10 and was the base mod for wrench support through all other mods with wrenches, it is less likely that AE2 for 1.10 will get any COFH wrench support

**Comment by yueh** [comment]
And CoFH then skips 1.12 and BC 1.13 again. Or the other way round. Or both die in 1.12. Whatever else you can imagine.

If we want a working wrench solution, which does not suck or break every other version, convince Forge to add a generic one. Pretty much every tech mod adds their own incarnation of `canWrench()/doWrench()`. There might be some mod needing a bit more, but nothing prevents them from adding their `IAdvancedWrench`. In every other case a forge one will solve the issue of having to support a dozen different wrenches. Yes, we could just pick a few common ones. But there will always be that one mod not supporting the ones you picked because they do not like it.   

With coremods being pretty much banned in 1.12 (due to having to jump through so many hoops), there is pretty much no option to support any alternative wrench without having this particular mod as hard dependency. Which is pretty much a no-go for AE.

Maybe there might be a capability based on. But Iirc itemstack caps are still utterly broken in forge. So I would not count on it happening...

**Comment by mindforger** [comment]
will have look at the forge tracker then, i fear to find something i don't want to see and fear the confrontation :D

**Comment by yueh** [comment]
It might be an idea to discuss it first with mezz. He is certainly way more reasonable and might be able to put a bit of weight into it. So instead of being immediately rejected, it will at least stay open for half a year without any feedback from lex until it will be closed for inactivity. 😉

**Comment by mindforger** [comment]
i knew you would say this :D

**Comment by fscan** [comment]
FWIW, we support cofh wrench now. I leave this open because something like a unified wrench support would be nice.
