### ISSUE TITLE
ME Network going off-line and on-line every 15 seconds or so.

### ISSUE THREAD

**Issue by duncanwebb** [AppliedEnergistics/Applied-Energistics-2#2948]
My ME Drives are connected by a dense cable to a face of a ME controller and are using 7 of 32 channels. Every 15-20 seconds the devices are going off-line and after another number of seconds are going on-line again.

#### Description

This is the terminal setup
![image](https://user-images.githubusercontent.com/4198031/27905774-594c3eee-6241-11e7-843d-d062bb9d8b67.png)

On another face of the ME controller is a quantum ring linked to another area in the same dimension.

I think that the cause is the remote end of the quantum link needs to be chunk loaded, placing down a spot loader seems to have fixed the condition. So the quantum rings need to keep their own chunks loaded.

#### Environment

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: 12.18.3.2254

**Comment by JelmarG** [comment]
Obviously you need to chunk load a quantum ring. You should chunk load every chunk that contains anything of AE2.

**Comment by duncanwebb** [comment]
Thanks it is not obvious, took a couple of days to figure that this was the problem. Would it be possible to auto chunk load it like the extra utilities mills that provide grid power?

**Comment by JelmarG** [comment]
It's usually up to the player to chunk load whatever needs to be chunk loaded. :)

Also make sure to power the receiving end of the QNB. Once it's up and running, it'll use the power of the network, but if the link gets severed for whatever reason, it'll not automatically get powered again.

**Comment by yueh** [comment]
We could chunkload it automatically. But due to the way ME networks can cover a huge area, you can exect server admins start complaining about it non stop. So it has to be a config option, which means no player will actually know, if it works. One modpack could disable it by default whole the other does it not.

We had ideas to add a chunkloader similar to the security station, so it would be obvious, which networks are chunkloaded as well as it can be disabled in a way that everyone can realise it (no chunkloader block).
But they can be quite tricky to get right without causing constant unloads/reloads, which are a major performance issue. Thus for now we leave that to the dedicated chunkloader mods.
