### ISSUE TITLE
Server crashes when AE is present

### ISSUE THREAD

**Issue by TheDutchMC04** [AppliedEnergistics/Applied-Energistics-2#2952]
#### Description
My server crashes everytime it starts. The problem is AE. I have tested rv4-alpha-11 and rv4-alpha-9.
I don't know how to fix the problem

#### Environment
Crash report: https://pastebin.com/kk3djWVp
Modlist: https://pastebin.com/3HQWd5ux

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: forge-12.18.3.2316

**Comment by TheDutchMC04** [comment]
I found that the problem is in my world, my world:
https://drive.google.com/file/d/0B3qM01xXWm5TOFh2ZnRqaTdYVDQ/view?usp=sharing

I really don't want to regenerate my world

**Comment by Ommina** [comment]
Well, the crash report comes down to "I was expecting an ME Controller.  Instead, I got an RFTools Security Manager.  WTH?  A pox upon you and your family." (I may be paraphrasing a bit.)

So, if you want to _try_ repairing the world, you could go in with MCEdit and look around for an RFTools Security Manager, and delete it.

No promises though, and the greater question of how it got into such a state remains.

Is the modpack as a whole publicly available somewhere?

**Comment by TheDutchMC04** [comment]
Yes it is! You can find it here https://minecraft.curseforge.com/projects/galaxy-tales or in the Curse Laucher

**Comment by TheDutchMC04** [comment]
I had a ME Security thingy next to the controller, I didn't have a RFTools Security thing. Could that be the problem?

**Comment by yueh** [comment]
It is pretty much a feature of Forge for 1.10 to corrupt your world. I probably lost 20-25% of my test worlds to it (and maybe 1 or 2 in all other minecraft versions combined). The best is that it is even local to chunks and not like the old ones converting every leaf to a diamond block or similar. So worst case it might just convert half of your storage blocks to cobble and you might not notice it for weeks.

We could safeguard against it and just swallow them silently. So the ideal solution to hide it until it is too late. Crashing at least indicates something is wrong and you can try and solve it. Like restore it from a backup, if possible. But otherwise there is nothing we can really do about it.

IIRC there is a config option for forge to delete crashing tilentities instead of actually crashing. It is disabled by default and should be. But it might be an option to try. Of course always make a backup before it.

As already suggest, MCEdit might be an option. But it is actually the other way. There is a ME Controller somwhere, which gets the state of a rftools security manager passed. I cannot give any direction which exact one it might be. But as it happens when starting, it is either located in a chunk loaded area or the spawning area. So disabling all chunk loaders might be an idea to locate it. If it still crashes, it is located inside the spawn area (or chunk loaders cannot be disabled correctly, which is a whole different issue). Or if not you can visit the chunk loaded areas until you find the crashing one.
