### ISSUE TITLE
You guys should make AE1 for 1.12

### ISSUE THREAD

**Issue by Jazoo1** [AppliedEnergistics/Applied-Energistics-2#2957]
Because AE2 sucks. What is the sense in finding tech in a meteorite? Also, why is the meteorite commonly found UNDER GROUND? What are you guys smoking.

**Comment by GuntherDW** [comment]
This is such a lovely comment that I'm not even going to take any time to retort anything.

**Comment by xciting** [comment]
While Jazoo1 does not stick to a proper choice of words, I still agree. AE2 is no fun anymore. I'm sitting here for 2 hours already, waiting for my first seeds to grow, currently at 7%
So either, I sit around doing nothing, or add a mod with a chunkloader, which I prefer not to have (Ressources, you know). Or, ofc, I am doing something wrong, in which case, you should have a more descriptive documentation on your homepage. (Craft seeds from sand and dust, throw into water - is exactly what i did in this case).
Next thing will be finding all those inscriber presses and those are pretty mcuh luck based... even if I find those meteors, it is not guarenteed that I find all of them.
I found two meteors but with the same inscriber each. so in worst case, i spend literally days only to get a chest full of Inscriber Calculation Presses for example.
This is, in my opinion, not acceptable for a mod, that was initially supposed to help organize and store my items.
Given that I didn't miss something, there should be at least option by default to make the presses craftable. Otherwise i have to side load yet another mod, just for that.

Please see this as feedback and consider at least some config options to make it a bit easier/faster again.

**Comment by mindforger** [comment]
you can disable channels and create alternative recipes ... Go and use refined storage and stop disrespecting the hundreds of hours of work the devs invested FOR FREE ... The way you act will only lead to the death of this mod you jerk
