### ISSUE TITLE
[1.12][Suggestion]Could you please update the mod

### ISSUE THREAD

**Issue by fluid-uu-matter** [AppliedEnergistics/Applied-Energistics-2#2958]
I need the version of AE2 for MC1.12, so please comment how soon you will done it.
I have a modpack made by myself in MC1.10.2.
When CoFH's Thermal series mods updated to 1.12 and added back the Tesseract, I wanted to update my modpack.
But unfortunely,AE2 has no version for MC1.12.
I have everything important in the ME net, so I can't update the entire modpack to 1.12.
In other words, AE2 prevents me from updating the entire modpack.

**Comment by mindforger** [comment]
> how soon you will done it

i will answer that because when the dev has to answer it will be around 5-10 minutes he can not invest to complete the port ...
it is pretty simple ... use the search first and you will come across an issue that is heavily discussing on changes that have to be done ... but to make it sort for you ... no ETA yet ... much things to do but one dev is sick and the other is having a private life besides this project 

please be patient and stop bothering the devs and don't steal time from the devs asking the same question over and over again without informing yourself using the search first.

this post may sound a bit angry and offensive but it is not meant so ... except for the "please search first" argument ... that one has become kind of annoying habbit on issue poster lately
