### ISSUE TITLE
Terminal GUI closes when trying to autocraft.

### ISSUE THREAD

**Issue by HrBatta** [AppliedEnergistics/Applied-Energistics-2#2976]
#### Description

When a terminal is placed on certain parts of cable, the autocrafting dosen't work. When pressing a craftable item in the terminal, the GUI where the amount of crafts is chosen, dosen't appear. The terminal GUI closes instead.

#### Environment
The world is played in FTB Beyond singleplayer. (1.10.0)

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha-11
- Forge Version: 12.18.3.2316

#### Extra
Here is the problem demonstrated in af gif: http://imgur.com/a/S0RBY

**Comment by mindforger** [comment]
while ingame, press and hold F3 + C until the client crashes intentionally and upload the crashlog to pastebin or attach it as a file

i suspect you have a lot more mods installed
if it is so, remove the following mods and test again to see if the issue is gone:
-wireless crafting panel
-ae2stuff
-extracells

**Comment by yueh** [comment]
Remove the Wireless Crafting Terminal mod. It is known to break it.

**Comment by HrBatta** [comment]
After "Wireless Crafting Terminal" was removed it worked ^.^
