### ISSUE TITLE
Lag with excess of items in ME system/ A card or tool to remove items under a certain # 

### ISSUE THREAD

**Issue by FireFalcon123** [AppliedEnergistics/Applied-Energistics-2#2977]
I noticed the mods don't matter it is just the quantity of items. 1million + cobble is fine but a mob farm just killing skeletons and getting different bows with dif. enchants and all that armor as well. Trash can mods or an addition to AE are a start as well. 
- Minecraft Version: 1.10.2
- AE2 Version: rv4 alpha 11
- Forge Version: .2316

**Comment by yueh** [comment]
To some degree that has to be expected, especially as long as we have to support external storages and the general shortcomings of minecraft/forge when handling any sorts of inventories with good performance.

But I usually only encouter it with a couple of thousand itemstacks stored inside the system. At the point also the GUI starts to behave strangly because there are not enough states for the scroll so each pixel maps to more slots than we can actually display inside the GUI, therefore the can only be reached via the scrollwheel on our mouse.

Nevertheless AE already gives you the tools to deal with it. Like the Matter Condenser or the buses and their upgrade cards. So there will not be no others for it.

Should you be able to [profile](http://ae-mod.info/Profiling/) and submit the snapshot, we can analyse it and reopen the issue, should there exist something to improve it. But without it, there is not much left to do.

**Comment by FireFalcon123** [comment]
Thank you for the advice
