### ISSUE TITLE
[1.12] Crafting terminal doesnt remember client-side settings when closing the terminal

### ISSUE THREAD

**Issue by 016Nojr** [AppliedEnergistics/Applied-Energistics-2#2988]
Nothing else to say other than the title

Mod list:
Forge 14.21.1.2426
AE2: rv5-alpha-1

Custom modpack, modlist can be provided if wanted.
Logs can also be provided if wanted

**Comment by ProxyPlayerHD** [comment]
any Terminal

not just Crafting... you can test it, i got a GIF as proof

also add to that, sometimes changing the Display settings of the Terimal doesn't change anything
GIF also shows that

[GIF](http://i.imgur.com/YdAkAdB.gif)

**Comment by GuntherDW** [comment]
This is on a server I presume? There's stuff that we still need to work out how/why as shown in #2961.
There's been an update in one of the libraries of vanilla/Forge and it changed some underlying methods we relied on.

I added a workaround back then but what is really needed in the long run is a rewrite of the packet system.
The changes in Netty are just bugs waiting to happen.

**Comment by 016Nojr** [comment]
This is in a singleplayer world, but it was working in the version I compiled, will test again in a few hours

**Comment by GuntherDW** [comment]
@ProxyPlayerHD the only time I have been able to effectively reproduce said bug is when the server is skipping ticks due to TPS lag. Also try to keep actual issue reports in an issue down to 1 bug per issue.

I can confirm that the settings do not get stored as they have in the past, with the exception being the wireless terminal.
When I get back to programing I'll take a look at said bug.
