### ISSUE TITLE
Auto-crafting & crafting status don't work or crash

### ISSUE THREAD

**Issue by Sagest478** [AppliedEnergistics/Applied-Energistics-2#3012]
#### Description
Behavior:
I discovered this while using the me pattern terminal, whenever I would try to click craft to use the auto-crafting the window would just close. If I click crafting status the game crashes, I removed everything from my inventory and it worked so I put it back one by one until it didn't work. I thought I had narrowed it down to a specific item but then if i put only that one item in my inventory it seems to work again, very weird.

I made a gif to demo it:
https://giphy.com/gifs/l1J3NyyHK5ZrKBw5O/fullscreen

I loaded it up and pulled those two items into my inventory and it worked soooo not really sure what's causing this.

Expected behavior:
Is for the game to not crash when I click on auto-craft or crafting status :).

#### Environment
Here is the crash log:
https://pastebin.com/0JkTR6ZF

- Minecraft Version: 1.7.10
- AE2 Version: rv3-beta-6
- Forge Version: 10.13.4.1614

**Comment by yueh** [comment]
We no longer support 1.7.10. Even if wanted, there is currently no way for us to release a new build as the buildserver did need some changes for 1.10 and these made it incompatible with 1.7.10.

But it is most likely the issue of running out of power during the crafting calculation. Adding a energy cell might help as buffer. Otherwise we can't really do more about it.

**Comment by mindforger** [comment]
remove wireless crafting teminal mod
