### ISSUE TITLE
Storage Bus on YABBA Barrel doesn't correctly sync data when connecting it.

### ISSUE THREAD

**Issue by cap1o** [AppliedEnergistics/Applied-Energistics-2#3021]
Hello !

I dunno if it's a bug or not but i have set up Yabba mod Barrels with storage bus to my ME systeme and then items already on the ME syteme won't to be added inside the barrel.

Exemple : I have got a yabba barrel lock to accept blaze rod is empty. I connect a this to my ME systeme with a storage bus and it still empty.
I have 250 blaze rod on my systeme and nothing on the barrel.

Thank you to help me.

- Minecraft Version: MC 1.10.2
- AE2 Version: 1.10.2 Stable v4
- Forge Version: 2316

**Comment by cap1o** [comment]
Any ways to get the fix on MC 1.10.2 ? Because most of modpack use both mod with this version of Minecraft ^^. Thank you !

**Comment by mindforger** [comment]
>I have 250 blaze rod on my systeme and nothing on the barrel.

did you actually take them out and re insert them? because an storage bus in an passsive component, it will provide the storage content to the ME and put items coming frmo the ME into the storage when all criteria (including priority) are met! It will not automatically shuffle things around just because it is connected, it will only deal with new items beein inserted! (And only if the bus has enough priority and the ietms are not routed anywhere else)

@mgdgfbhevdyeh what do you mean by fixed in 1.12? was there an actual bug i did not notice in 1.10?

**Comment by GuntherDW** [comment]
No, I think he's referring to another bug that was fixed with regards to the storage bus.
There's still a bit of stray cobble/... left in your ME storage somewhere.

This is not a bug though, it's probably a case of "I forgot to increase the priority of said barrels.", and "I did not make 100% sure that there is no cobble left in any of my other storages."

**Comment by mindforger** [comment]
if one has only drives and defined barrels i would always recommend a sifting of the items from the drives using an IO-Port :D

**Comment by GuntherDW** [comment]
Yeah, that's usually what I do as well. Doesn't always work as smooth when you have over 300 cells though :P
I usually add an export bus to said barrel, set the storage bus to "export only" and let it export from the main storage. (heck you can even disable the storage bus at this point).
When it's done I remove said export bus, flip it from export only to bidirectional and poof.

**Comment by leagris** [comment]
Don't forget to set priority on your storage bus, higher than that of your ME drives. So it stores to that storage bus before ME drive. Then it can safely overflow into the ME drive whan your barrel storage bus is full.

**Comment by mgdgfbhevdyeh** [comment]
sorry,i referring to another bug.

**Comment by cap1o** [comment]
Minecraft Version: MC 1.10.2
AE2 Version: 1.10.2 Stable v4
Forge Version: 2316

Hello,

So this an issue ? I tried prority and filters with storage bus attached to the barrel from YABBA, it still empty since i extract manually all blaze rod from the ME system to insert it to the YABBA barrel and then the system is sync to the barrel.

It's not a problem with 200 blaze rods but with 1 Million of cobblestone, i can't do it manually.
But storage bus works perfectly with a diamond chest full of wool for exemple.

I did try to setup only extract or import to the storage bus, set priority, nothing happen at all too.

**Comment by mgdgfbhevdyeh** [comment]
This should be a fixed BUG(in 1.12)
GuntherDW/Applied-Energistics-2#2

**Comment by cap1o** [comment]
Ok Thank you i will wait to 1.12 !

**Comment by GuntherDW** [comment]
@mgdgfbhevdyeh If you actually read what I put down there it states something completely different than what @cap1o is having an issue with.
Nevertheless it was an issue that we cannot solve on our end because those barrels, when locked, tell minecraft that it's actually storing items but not extractable. Other storage mods like RS or even rftools' storage scanner will get confused by it. Heck, you can tell by just looking at it with WAILA/The One Probe.

**Comment by cap1o** [comment]
But it's working for the 2 first ranges of 8 channels of barrels and after it stop work for more channels.
Anyway i can use Storage Drawers may it will work better.
I will check also if unlock barrels and One Probe said some clues too as u suggest.
