### ISSUE TITLE
Can't craft when item in "quick-slot 2"

### ISSUE THREAD

**Issue by i00** [AppliedEnergistics/Applied-Energistics-2#3067]
#### Description
In a certain game, when clicking on an item to craft the interface just closes (before asking to select the quantity)...
After ripping out my hair I found that it happens (in this game) when any item is in quick-slot 2 (regardless if it is selected or not).

#### Environment
FTB Beyond Stock

- Minecraft Version: 1.10.2
- AE2 Version: rv4-alpha11
- Forge Version: 8.0.99.99

**Comment by i00** [comment]
Ok... so I moved my ME system around a bit and now it appears to be slot 4???? This is strange.

... also appears to be when requesting crafted items through the ME Crafting Terminal only ... the Pattern Terminal works without issues.

**Comment by Ommina** [comment]
This feels like #2365 

If there as a resolution to it, I can't find it.

**Comment by mindforger** [comment]
Try removing wireless crafting terminal

**Comment by i00** [comment]
I don't have a wireless crafting terminal. :(

**Comment by i00** [comment]
Also I don't think this is the same as #2365 ... it is if ANY item is in the said slots ... I even tried emptying my inventory entirely... except for that 1 slot ... didn't work until I moved the item somewhere else

**Comment by mindforger** [comment]
so you have dual slot bar mod or anything that messes around with hotbars ?
first guess was wireless crafting terminal as it was the most often cause :) but yeah that one too

**Comment by i00** [comment]
"dual slot bar mod"?? ... I don't think so ... FTB beyond stock

**Comment by Ommina** [comment]
FTB Beyond does include Wireless Crafting Grid.  I'm (pretty sure!) this is the mod to which @mindforger was referring.

**Comment by yueh** [comment]
I would recommend reporting it to the modpack itself.

It might something mostly unsuspicious. E.g. the wireless crafting terminal can easily break anything related to AE2. or some hotbar mods conflicting with using items.

They are the ones having to know about incompatibilities. We can try to solve them once we know what mod causes it. But debugging every modpack out there is simply not possible due to the time requirements and some mods might not even run inside a dev environment.
