### ISSUE TITLE
Autocarfting not working

### ISSUE THREAD

**Issue by Teapoi** [AppliedEnergistics/Applied-Energistics-2#3075]
Hi,

When I was doing the autocrafting( the system was set properly), clikc the the craft item icon in the ME crafting terminal, there suppose to have a window to select how much you want to auto craft. However, the window wont show up and will exit the terminal when click the thing that with the "craft" icon. 

I guess the reason might because I took some mods out from the modpack due to my friend said his computer isnot able to load so much mods with the original modpack.

I opened two new test worlds on both offline and server, and the autocrafting works no problem. I guess the bug is caused by taking out of these mods. So is there a config file I could delete to reset the modpack cache? or any other solutions? Pls, I really love this mod.

- Minecraft Version: 1.10.2
- AE2 Version: Appliedenergistics2-rv4-alpha-11
- Forge Version: 12.18.3.2316

**Comment by Teapoi** [comment]
So, I found the solution on the reddit: [https://www.reddit.com/r/feedthebeast/comments/57k58u/ae2_autocrafting_problem/](url)
Basically, you just remove the stuff on your first quick slot. I thought it was because my save is broken, but it is not. Dont know why this bug is happening, but there is a lot of people seems had the same problem.

**Comment by Ommina** [comment]
I was under the impression this was caused by Wireless Crafting Grid, but maybe I'm just not remembering correctly.

Do you have Wireless Crafting Grid installed?  And if so, does the problem persist if you remove it?

**Comment by mindforger** [comment]
i am fraggled that nobody from wirless crafting grid yet ever dealt with this issue or cared to show up trying to get rid of this bug

**Comment by Teapoi** [comment]
I do have the Wireless Crafting Terminal installed. The Wireless Crafting Grid is for Refined Storage I think. I removed the Wireless Crafting Grid first which is for the Refined Storage it was still not working, then I removed the Wireless Crafting Terminal, the autocrafting worked when I logged back on my server again.

However, the thing is, if I use the Wireless Crafting Therminal, I will be able to do autocrafting with the terminal.

Plus I cannot find the energy cell block in the JEI manu( if I remeber the name correctly, the item manu that shows up at the right side when you use button E open your inventory). Which means I can't craft the Wireless Terminal, but the wireless terminal do exist in the JEI manu. So right now if I want to use the terminal wirelessly, I must cheat.

**Comment by Teapoi** [comment]
One more thing is I want to thank you guys who are working on those mods.(no matter which kind of mod you made) I don't know how to code, but I do know how hard to code. You guys are amazing and make my MC journey so much fun. :)

**Comment by Ommina** [comment]
OK.  So, Wireless Crafting Grid for RS, and Wireless Crafting Terminal for AE2.  (Which makes sense, although I may need to edit my reply to an earlier issue.)

Either way, if the issue goes away when WCT is removed, I think it takes us back to the actual issue being with them, rather than with the AE2 code.

And, indeed, there appears to be an open issue on the WCT issue page.  https://github.com/p455w0rd/WirelessCraftingTerminal/issues/151

**Comment by p455w0rd** [comment]
sorry to necro, but @mindforger - I have tried...everything works perfectly on my end..I've tried doing things, but when I ask for the people experiencing this issue to test after I implement possible fixes, no one replies...I can't very well fix a problem I am unable to reproduce without cooperation from the people experiencing the issue...either way..I'm working on 1.12 now...also, please keep in mind that some people have things going on outside of Minecraft..I have been in and out of the hospital a fair bit recently as I suffer from epilepsy...I actually recoded my 1.12 port today from the ground up due to how horrible my original port was when trying a day after a bad seizure...also...the codebase here not matching what's on Curse certainly doesn't make things any easier...you could always try to be a part of the solution and make a PR rather than being pompus...
