### ISSUE TITLE
ME-system ignoring high-priority storage bus for negative-priority storage bus

### ISSUE THREAD

**Issue by mickymaxx2** [AppliedEnergistics/Applied-Energistics-2#3084]
Is more or less explained in the title.
High-priority storage bus is connected to a empty chest only 1 block of cable from the controller,
low priority storage bus is connected to a unlocked Better Barrel.
The item in question is a damaged leather helmet.

- Minecraft Version: 1.7.10
- AE2 Version: rv3-beta-6
- Forge Version: 10.13.4.1614

EDIT: the same goes for all other kinds of damaged leather armor, they should all be going into the chest.

**Comment by GuntherDW** [comment]
1.7.10 Versions are no longer supported.
1.10 Will only get fixes for gamebreaking stuff, so test it out in a newer version on 1.12.

**Comment by mickymaxx2** [comment]
Well i'm using a premade modpack in the technic launcher.
Don't really wanna edit it :/

**Comment by mindforger** [comment]
i think this issue is a thing of the better barrel handling the items, i can remember there were issues with the deep storage units deleting items when beeing locked, because they still accepted the item during the simulation step but voided it when the actual transfer happened, maybe this issue is compareable
