### ISSUE TITLE
(1.12.1) AE2 processing recipes not working with Mekanism9 

### ISSUE THREAD

**Issue by devilunaworkshop** [AppliedEnergistics/Applied-Energistics-2#3126]
#### Description
Recipes for mekcrusher and mekinfuser does not work. Tried adding them in all described ways as in recipe guidelines, but to no avail. Is that compat broken?

#### Environment
SMP
Mods: AE2
Mekanism
Mekanism Generators
Mekanism Tools

- Minecraft Version: 1.12.1
- AE2 Version: appliedenergistics2-rv5-alpha-6
- Forge Version: 14.22.0.2474

**Comment by fscan** [comment]
Mekanism integration is still missing.

**Comment by thommy101** [comment]
Linking to https://github.com/aidancbrady/Mekanism/pull/4536, as in this commit the compat has been disabled. I'll look into a good solution to make it work as before ;)

**Comment by yueh** [comment]
With Mekanism being somewhat of an exception compared to other mods (5x ore, etc), it might be better to handle in directly in Mekanism just like before.

The only important thing on AE2 side would be the `1 crystal -> 1 dust -> 2 seeds -> 2 pure crystals -> 1 crystal`. Changing somethere here will immediately result in infinite resources. But that is the same as turning 1 iron ingot into more than 1 iron dust and smelting it back into more ingots.

If mekanism in the end allows to turn 1 ore into 5 crystals (or some combination of crystal and dust like other mods), it would be perfectly fine. But I have absolutely no idea about how ore processing is balanced in Mekanism. Thus it would certainly a better idea to let the Mekanism devs balance it.

**Comment by thommy101** [comment]
The recipes Mekanism added where:
1 certusore -> 4 dust
1 dust <-> 1 crystal (fluix and certus)

I'll take a look what's possible and let you know

**Comment by yueh** [comment]
To preface it, I mostly assume the full 5x process. Should it make sense to be used for certus. My near total lack of knowledge about Mekanism is not really helpful in terms of balance.

In terms of vanilla mechanics, Fortune 3 should already give 3.5 crystal/dust on average. Without fortune it should be 1.5. So if we just talk about the lowest tier, 3 dust per ore might fit a bit better. Due to fortune 3 not being achieveable in a reliable way compared to crafting some machine and be done with the first yield improvement.

Certainly it could make sense to add it to all tiers. No idea about how each step actually works. But if it ends up with +1 dust per additional tier, it should be ok. Should it only work with multiplication, maybe nerfing the first tier to 2 dust might work. But I have also no idea how Mekanism would handle generating the intermediate items (in terms of textures/models). Maybe that is not possible by just sending IMC messages around. Or if it is even intended by Mekanism, or if the ore processing is only designed around metallic ores in terms of "lore".

Also in terms of minecraft it is always balancing around infinite ore generation. Therefore if the refinement process results in 2 * infinity or 5 * infinity, is ultimately pretty unimportant and in my experience scaling up the ore production and 2x is usually way easier than using a higher yield process, which might even be more time gated.

**Comment by nlogozzo** [comment]
Fixes #3134

**Comment by SashaGelert** [comment]
> Tried adding them in all described ways as in recipe guidelines

It *is* possible to step outside recommended guidelines.  CraftTweaker includes support for all Mekanism machines.  

for example:[https://crafttweaker.readthedocs.io/en/latest/#Mods/Mekanism/Metallurgic_Infuser/](url)

Though care should still be taken not to produce an over-unity result.
