### ISSUE TITLE
RFTools / AE2 - Spamming Console 

### ISSUE THREAD

**Issue by Keaton1188** [AppliedEnergistics/Applied-Energistics-2#3140]
This is constantly spamming our console, any way to disable it? Or even why its doing it..?

(Ftb Beyond)
![untitled](https://user-images.githubusercontent.com/24898745/31298894-19f9a3d0-aae4-11e7-862b-de1228133812.png)

I put in an Issue on RFTools github and they told me to come here.

- Minecraft Version:  1.10.2
- AE2 Version: appliedenergistics2-rv4-stable-1.jar

**Comment by yueh** [comment]
It does exactly what it told you. Removing items because they are no longer valid for whatever reason. The reason is outside of our control, it can be that the mod in question removed these items, a config value was changed after the world was already created, or whatever else.

In general this is self cleaning once the cell gets saved once, but for obvious reasons cells do not save themselves immediately upon load. E.g. to avoid performance issues with rapid chunk reloading.

As this is a particular important message, there is no way to disable it. But as said it should stop at some point. As the mentioned items also form a visible pattern, it also indicates that some chunk is constantly reloaded, which is actually a way worse issue in terms of performance than a few messages being logged.
