### ISSUE TITLE
Question / Feature request - max items

### ISSUE THREAD

**Issue by sanados** [AppliedEnergistics/Applied-Energistics-2#3174]
After some time the system loads with insane amounts of everything.
Is there max limit you can set and AE2 voids all above?

Or you can export any item that you have in storage over a specific amount.

I know how to do that on single items.
But I would like to add (i.e. 50k ) a hard limit on items and void the overflow or create singularities out of those.

**Comment by mindforger** [comment]
>Is there max limit you can set and AE2 voids all above?

no, but you can build it yourself

>Or you can export any item that you have in storage over a specific amount.

configured exportbus into recycler + redstone card + redstone emitter configured on this item to emit when above limit

>I know how to do that on single items.

i really should learn to read the whole text before typing the answer .... but i suppose you will get a no on this, because the idea behind AE is handing you a ton of tools to combine and to create your own automation, but not to make it supereasy with configuring an function for your personal gamestyle on the fly

minecraft is still a building game, so building contraptions to achive something is part of the game

**Comment by fscan** [comment]
You can add a storage bus with LOWEST priority to a condenser. Everything that enters the system that doesn't fit anywhere welse ill go there. Next release you will even be able to extract the singularities from there :)
