### ISSUE TITLE
1.12.2 Appeng Rv5.stable build 1 - Ticking GridNode ImportNode crash

### ISSUE THREAD

**Issue by MagnusHellstrom** [AppliedEnergistics/Applied-Energistics-2#3201]
Had persistent errors in server console regarding ImportNode, spontaneously decided it would crash the server, now stuck in reboot-crash loop.

#### Description
As far as functionality goes, it works perfectly, aside from the errors, and now the crash.

#### Environment
Codechicken Ender chest bringing items from elsewhere, ME import bus attached to the top of it pulling everything, no upgrades or anything.
Here's the crash log, I have no idea what's causing it.
https://pastebin.com/1eJGYzjX

MC: 1.12.1
AE: Rv5.stable build 1
Forge: 14.23.0.2531

**Comment by fscan** [comment]
How does the rest of the me system look like? Also, as you said it worked before, what changed? New forge version?

**Comment by MagnusHellstrom** [comment]
Everything else worked fine, it just spontaneously started crashing as soon as someone loaded into the chunk then it started crashing upon server reboot.

**Comment by yueh** [comment]
I currently do not see any way to trigger a `NPE` for [this line](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv5-1.12/src/main/java/appeng/util/Platform.java#L1169). At least if we can assume the stacktrace is not being incorrect.

Only `cell` or `input` could trigger it. `input` cannot be null, otherwise it would have already caused it earlier. Same for `cell` which even explicitly throws a `NPE` should it fail to construct it.

The only issue I currently see is passing a field and not a variable around. Thus something could mutated it through a different thread. But the whole path is only accessible through the normal ticking, should that be multithreaded we can already stop. As it will cause issues everywhere.

The only other option is a import bus with a redstone card. This can also enforce a tick, should a neighbor of them update. E.g. one of the adjacent blocks sends it during the network thread and not the main one. Which would not be our fault, but a bug in that particular mod. But without knowing which blocks are around it, there is nothing we can really do for now.

**Comment by MagnusHellstrom** [comment]
The only blocks around it was a CodeChicken Ender chest and concrete blocks from Immersive Engineering

**Comment by MagnusHellstrom** [comment]
If it helps, the import bus was almost entirely importing the following; Inferium Dust, Blaze Rods and an assortment of Enchanted vanilla armour and tools from my Blaze Farm.

**Comment by fscan** [comment]
The referenced PR should fix your crash. Not 100% sure because i cannot reproduce it.
