### ISSUE TITLE
Search Box resets after crafting items

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#3213]
#### Description
When crafting items with applied energistics the search box will reset and you will have to re-enter your query in order to pick up the item.
I could be wrong but this is not how I remember the previous versions.
I don't know if this qualifies as a bug but I feel like it's not working the way it should be.

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-1 
- Forge Version: 2537
- Mods: [list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/1464047/list.txt)

**Comment by fscan** [comment]
To clarify, you are talking about the non synchronized mode?

**Comment by Xiaminou** [comment]
I tried both actually, both reset when crafting items or checking the "crafting in progress" window.

**Comment by Xiaminou** [comment]
Okay I should have looked closer, looks like there's one more mode now that keeps your search... Derp that's what I get for coming back after an extended period of time.

**Comment by fscan** [comment]
Still, shouldn't forget the search in the other modes. I'll keep this open.

**Comment by yueh** [comment]
This is more or less a minecraft/forge issue because it does not go back but instead open a completely new GUI instance. As far as I can remember, there is no way to pass some additional data around except using some global state shared for all GUIs. IIRC we at least have a reference to the last used GUI and can restored it. But for the confirm crafting dialog, this would be the select amount dialog, which has no search.

Probably without forge providing a way to distinguish between switching between GUIs or just closing it and having to deal with a corrupt states caused all over the place. E.g. some mod adding a hotkey for an ingame wiki, which afterwards closes all GUIs but leave our open state lingering around. 

Not sure if it's word putting time into it. Maybe if we rewrite the whole GUI part, it might be something to consider.

**Comment by juanitierno** [comment]
I just made this reddit post about this issue (should have checked here first I guess, was hoping I was using it wrong) https://www.reddit.com/r/feedthebeast/comments/7u0k9e/revelations_question_about_ae2_and_possibly/

What is the mode that does not forget the search box?

**Comment by Technici4n** [comment]
It could also be intended that the search bar is reset, since you might want to look for something else after ordering an autocraft.
