### ISSUE TITLE
Printed Silicon Crafting (FTB Beyond)

### ISSUE THREAD

**Issue by EternalDreamerVG** [AppliedEnergistics/Applied-Energistics-2#3233]
I have 2 processing patterns in an interface connected to an inscriber with a Silicon Press in it: 
 - 1x Silicon (AE2) = 1x Silicon Press
 - 1x Silicon (EnderIO) = 1x Silicon Press

I then also have a processing pattern in a furnace:
 - 1x Nether Quartz = 1x Silicon (AE2)

At first, if I had 0 nether quartz and 0 AE2 Silicon in my system, it still refused to use the EnderIO silicon that I put into the system. Sometime later, after fiddling around with recipes and interfaces, the opposite is now true; It will never use AE2 Silicon, no matter how much nether quartz or AE2 silicon is in my system. I'm not sure what I did to cause this swap, but the problem remains that it ignores the other pattern.

Since you can't set ore-dictionary for processing patterns I was hoping to simply use two patterns and have the system be able to decide based on which silicon is already present in the system, but it doesn't seem like that's the case. It uses either only nether quartz/AE2 silicon OR only EnderIO silicon. It will never try the other pattern if both are in the interface. 

I've noticed some issues with the two silicons in general (YABBA barrels will not accept enderIO silicon if AE2 silicon is in them either) so there seems to be a bigger overlying problem between the two. Perhaps I'm better off reporting it to....wherever one can report issues concerning oredict (or FTB Beyond in general) but I feel like this is a good place to start considering it concerns interface and pattern priority.

- Minecraft Version: 1.10.2
- AE2 Version: rv4-stable-1
- Forge Version: 12.18.3.2422

**Comment by fscan** [comment]
Sadly adding oredict to processing recipes is not really possible without introducing a whole lot of issues.
You could try to switch the order of the patterns in the interface so the crafting process tries to use the enderio silicon first (not 100% sure if this works as they have the same priority). The easiest way is to just use 1 kind of silicon or have a pattern converting 1 to the other.
Btw, AE2 even disables it's silicon by default if enderio (or another oredict) silicon is present.

**Comment by yueh** [comment]
While it might sound trivial for a human, it is pretty hard for a programm to decide between should I use all of item X, all of item Y, 25% of X and 75% of Y, or some other combination without telling it before. Picking it automatically usually results in the completely wrong case. E.g. using all silverwood planks before falling back to normal oak ones because the player has forgotten to define the rules for a few hundred log types.

Or having to pick every single ingredient from a list displayed while running the crafting calculation. E.g. something like "The crafting requires 10k logs, you have 2k oak, 1k spruce, 4k birch, 1k jungle, some random amounts of forestry logs, 2 silverwood logs. Please choose how much you want to use from each type by typing some numbers into 20 input fields". Basically pretty ridiculuous.

It is simply not possible without either nagging the user constantly each crafting request, forcing them to setup a perfect priority/rule system (e.g. oak > birch > jungle > spruce > dark oak > acacia > add a couple of forestry logs > other mod logs), or being a massive resource hog and probably still chosing the wrong path way too often. The one pattern per item was deliberately chosen with with performance in mind.

Pretty much the only fix would be once forge provides a real way to remove duplicate items from the world. No longer having to deal with a dozen of different copper ores/dusts/ingots etc. But probably impossible without also breaking things like logs. Which are not identical.
