### ISSUE TITLE
Network Tool and ME Interface

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#3240]
When right-clicking an ME Interface with a Network Tool it currently opens up the Network Details window. I believe it should instead switch the ME Interface direction like a normal wrench does.
This would remove the need to carry 2 AE wrenches around. (and improve compatibility with morph-o-tool)

**Comment by fscan** [comment]
Not sure what the correct behavior should be here. BTW, any TE compatible wrench should work for AE2.

**Comment by yueh** [comment]
That happens when a tool has more than 2 functions but there are only 2 keys/buttons/etc.

With the network status being the main usage for the network tool and the wrench just secondary, there is no way to really change it. Otherwise we end up with something like you have to rightclick a cable anchor to display the network status, because everything else has some wrench interaction like rotating an interface, inscriber, charger, or whatever else. Or the other functionalities like locking a monitor etc.

Maybe we can change it when adding a wall mounted version of it. Or reworking the block interactions completely to allow more than just rightclick and shift rightclick. But there are already open issues for them.
