### ISSUE TITLE
Network tool energy generation report?

### ISSUE THREAD

**Issue by ouroborus** [AppliedEnergistics/Applied-Energistics-2#3243]
In the screenshot fragment, what is "Energy Generation" measuring? I haven't been able to figure it out as my network isn't bringing in or generating anywhere near that much power.

![image](https://user-images.githubusercontent.com/392047/33098420-3e25a504-cec2-11e7-93a8-f39e0324b614.png)

**Comment by fscan** [comment]
I need some more info to say something about this. AE2/MC/Forge version, info about the setup (eg how is the power connected, maybe screenshots)

**Comment by ouroborus** [comment]
Applied Energistics 2 rv5-stable-2
Minecraft 1.12.2
Minecraft Forge 14.23.0.2531

Power is supplied via an energy acceptor. In the screenshot, on the right edge is the main network bus which connects directly to a controller.

![2017-11-21_14 13 26](https://user-images.githubusercontent.com/392047/33099606-466f0e4a-cec6-11e7-9c50-c6bb21b9e272.png)

**Comment by yueh** [comment]
Energy generation is measuring the total energy input going through the current network, even the amount shared with other networks via a quartz fiber or similar. While the energy consumption is only locally as there is no way to accumulate them in a sane way across all networks.

This was somewhat changed in 1.12 with reworking the energy system in general. Mainly because there was no real way to tell the total energy consumption without having to manually add all networks together.
Thus the generation was changed from what was inserted into the local network to what is inserted on a global level. To provide at least some clue about the total consumption indirectly.

Not sure why it is so high. Maybe some AE2 addon could handle the energy incorrectly. I somewhat doubt it is a bug in the energy grid itself. It tested it pretty thoroughly and fixed a couple of bugs already without spotting a new one. But it's kinda hard to test it indev as there is no mod working with a ForgeEnergy generator (Note to self, add a debug block for it).
