### ISSUE TITLE
Game crashing when looking at drives

### ISSUE THREAD

**Issue by AnZaNaMa** [AppliedEnergistics/Applied-Energistics-2#3254]
Sometimes randomly, I'm having an issue where if I look at a drive, my client will crash continually over and over until I go into the world and delete it using MCEdit

Edit: link to crash report: https://pastebin.com/FQXmke4i

#### Description
I'm playing in the direwolf20 1.12.2 modpack version 1.1.0

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-2
- Forge Version: 14.23.0.2531

**Comment by mindforger** [comment]
duplicate https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3251

**Comment by AnZaNaMa** [comment]
this may be the same issue as the one referenced. I am not sure. It looks like the CodeChicken library is calling vanilla render functions though. I'm not sure why it would be crashing the game or if it's an issue with CodeChicken or AE. However, I think its worth it to note that I haven't seen this happen with any block other than this specific one.

**Comment by mindforger** [comment]
that's just fair, but can you make a minimal setup with only AE and CCLib or any CC Mods to confirm this is can be reproduced easily? Maybe create a small world with this bug to download for the devs :)

i'll slap an "state waiting" on the topic for slightly more attention

**Comment by fscan** [comment]
Having a short dive into the code, the only reason i can see that this would happen is when the drive block cannot find it's associated tile entity when creating the extended blockstate. It needs this to render the appropriate drive models.
Hmm .. Can you confirm the BlockPos in the report is the same the drive is at?

**Comment by belathus** [comment]
I had a similar crash as this, but the crash only happened when I held the drive in my hand. In the report, it told me that the drive's location was 0, 0, 0. Once I placed the drive in the world, the crash stopped happening.

I'll be able to get you a crash report in a few hours.

**Comment by SquidDev** [comment]
I managed to [get a similar crash](https://gist.github.com/SquidDev/f998a5dcbd5621138995574478046ecc) in a dev environment for another mod. I only mention this as CCLib was not in the environment (or any core mods for that matter).

**Comment by Lemmmy** [comment]
I am also [having a similar crash](https://gist.github.com/Lemmmy/b07984d81142bafda6a44c629294deda) on a server - it is impossible to go near our base without crashing due to this error. 

The error occurs [here](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/08ee8f7656e37bc0bf206a12b82349317d7c4acc/src/main/java/appeng/client/render/model/DriveBakedModel.java#L73) - `slotsState` is null. 

The crash happened on rv5-stable-5 and rv5-stable-7. It started happening after the servers modpack was updated - I believe the most likely cause was the removal of Refined Storage. We had some RS items stored in our storage cells, and then RS was removed. My theory is that the drives are now invalid due to having nonexistant item stacks in them, and thus the drive state cant be fetched for rendering.

The crash should be mitigated with a null check for slotsState, at the very least. There may be a deeper underlying cause, though.

**Comment by xfl03** [comment]
If I copy the world of running server, it could be used correctly.
(Copy 'world' out before server close & Replace 'world' before server start can avoid this bug.)
But, if I close the server and start is again, a crash in client was be caused.

So, it it a bug of chunk saving?
