### ISSUE TITLE
Add P2P Tunnel Frequency ID to WAILA 

### ISSUE THREAD

**Issue by polysillycon** [AppliedEnergistics/Applied-Energistics-2#3269]
Players have been asking for ways to identify how P2P tunnels are connected, from source to destination.  

For AE2 versions 1.10 and up, the P2P Tunnel part provides helper functions to provide the connection state and connection count (INPUT only) to the WAILA tooltip.  The P2PStateWailaDataProvider class has a getWailaBody function that does this work.  

This request is to add the P2P Tunnel "Frequency" identifier to the WAILA text for the INPUT and OUTPUT states.  This frequency is a short int, originating from P2PCache . newFrequency, which essentially returns a Random number.  

The PartP2PTunnel part provides a getFrequency function returning an ID for the input/output linked parts.  If this ID were added to the WAILA body, then players could use this information to debug their P2P connections and quickly identify faults.  Because of the random nature above, I would also request that it is displayed as a 4-character hexadecimal (toHexString).  

Thanks.

**Comment by yueh** [comment]
As long as there is no way of telling without AE2 itself, we will not add any additional data to WAILA or similar mods.

The goal is that WAILA/etc must be totally optional for obtaining any information. This might be a bit harsh, but it is simply to avoid "Just use WAILA" and then forget about everyone not using it and enforcing WAILA as hard requirement to use AE2 itself.

It should just be used to enhance some features. E.g. avoiding the need to disassemble parts of the network due to a bad angle or something obstructing it or to help people with color blindness.
