### ISSUE TITLE
Suggestion [Percentage Full]

### ISSUE THREAD

**Issue by CTH999** [AppliedEnergistics/Applied-Energistics-2#3270]
I think It would be awesome to see how much space Is left on the disks (Percentage, and total possible items). I would love being able to see the percentage of used space in 50 64K storage cells.

Just a suggestion though.

Thanks

**Comment by mindforger** [comment]
could probably be added to the networking tool

**Comment by CTH999** [comment]
I like that solution, because where in the interface would you put it. Thanks!

**Comment by yueh** [comment]
That does not really work for a couple of reasons.

The first being that it depends on at least 2 independent variables. So neither can be predicted in relation to the other for a single cell. Thus it would be more of a range, e.g. a 1k cell with a total amount of 64 items can range between 0.8% to about 1.5% full and even worse the fuller a cell gets, the more spread the value will be. Like something about a range of 50% to 100% full for a nearly filled cell. Which is pretty useless for a player. And that is just for a single cell. Should we try to combine it, it gets even worse. Just guessing a random number is probably more accurate than trying to guess a range of values.

Secondly there is no way to tell it for many inventories. This is mostly due to the nature of cells, storage buses, etc being the same internally. Thus depending on the inventory attached to a storage bus it may or may not be possible to determine how much they can store. Or something in between and the inventory actually reports incomplete values. Thus it can literally go from 0% full to 125% with a single item being inserted and go back to 62.5% full a second item is inserted into the network.

Last but not least, as there is no reliable way to calculate a single inventory, there is also no way to aggregate them and share them across multiple networks. Thus any chained network will just multiply these errors even more.

In the end we would probably end up with displaying something like 5-99% full. With the 5% case jumping to 98-99% when adding a few items, while the 99% one might last forever as it's actually just 0.001% full.

**Comment by mindforger** [comment]
well you are showing already items count and item types, so displaying two % values would be sufficient but the representation would change both if i add additional new item types or only items already stored in the syste (this way you could see that one drive or storage bus is overflowig when sudenly the pervcentage of item count is rising)

the second issue is fact and i understand that fully but maybe we can simply ignore attaced inventory that do not report the full amount of items they can hold or how much different types the can store, just drives then would be a great help already

and for the third we should also ignore any external storages including chained storages but on the subnet this should work again imho

you could easily generate the data for the drives when you are parsing the components of the network as a driveby

it would definately be a QoL improvement .. i am looking into the code this afternoon and try to make a PR if you want but i feel a bit rusty in java so do not expect perfect work :P

**Comment by mindforger** [comment]
i am folding my hands, i don't get behind how you scan the network with this tool

i find methods and their interface declarations but nowhere the code behind the interface :(

can you give me a hint where the code starts that analyzes the contents ... or am i looking at the wrong branch?!

**Comment by yueh** [comment]
As said. It is simply not possible. At network level, there are no information about the cells available besides a common inventory, which is everything from single cells to whole networks. And at cell level there is no information about the network. There is a small window to forward it to the network and somehow store it. But that is once per network boot. So refreshing it would need a network reboot (costly) or server restart. Just useless.

Otherwise it means constantly scanning each TE containing cells. Which more or less already fails with someone using ExtraCell drives. Or is completely usless because you still have to manually look at every single cell and write it to a piece of paper. As well as being completely useless, if it cannot handle other networks as it just means the player has still to manually look up every single network. Which is even worse then looking at the drives an guess it according to the green/orange/red indicators.

The effort to change it is simply not worth it. Outside of a small network with a single drive and some terminals, it will always be a pure guess without any real hint about which changes affect it in whichever way. Or completely useless because it ignores pretty much every storage including our own storage.

**Comment by CTH999** [comment]
@yeuh, I can see what you mean. I just meant the total items, meaning the percentage of bytes left. Meaning It would be adding the total bytes in all of them, then subtracting the total used. (Though if that won't work, just say why.)

**Comment by CTH999** [comment]
@yueh,

Why wouldn't it be able to show what the percentage of bytes used?

Just wondering.
