### ISSUE TITLE
Security Terminal forgot the owner after serverrestart

### ISSUE THREAD

**Issue by xILikepuddingx** [AppliedEnergistics/Applied-Energistics-2#3276]
As mentioned in the title, the security terminal forgets the owner after a server restart. this bug already exists since the minecraft version 1.10.2. our servers are running on spongeforge, if that helps....

Minecraft-Version: 1.12.2 (since version 1.10.2)
AE2-Version: appliedenergistics2-rv5-stable-3
ModPack-Version: 2.7.2.2

**Comment by mindforger** [comment]
>our servers are running on spongeforge

well that is the actual issue, since sponge acts strange on loading the blocks and their data there can not be helped about this

**Comment by xILikepuddingx** [comment]
mh so you cant fix that?

**Comment by mindforger** [comment]
i'll leave it to @yueh to put a final nail into this coffin because i am not 100% sure if there is anything that has been considered to to about it

**Comment by yueh** [comment]
In general we do not support sponge due to it being way more agressive about changes to minecraft as compared to forge and also on a way faster pace. Thus it is not really possible to track which of their releases breaks what.

Also note that forge has/had data corruption issues since introducing a multithreaded chunkloading from bukkit in 1.7.10. Some are fixed in later forge versions for 1.12.x. But there are still a couple of questionable pieces. Should sponge hook into them and to their own changes for a bit of performance, they can easily cause data loss/corruption here.

So as long as you cannot reproduce it on a normal forge server, using the latest RB (14.23.1.2555) or maybe even a later version, there is nothing we can do about it. Keep in mind that forge is somewhat unstable lately. E.g. recipes are a mess since 14.23.0.2532 and not sure, if it's now fully fixed. Or some release like 2557 introducing API changes, which break at least one mod (maybe more) and were reverted in the next release.

If you can reproduce it, ideally with only AE2/Forge, we will reopen it.
