### ISSUE TITLE
[Suggestion] Actual loot inside the Meteor chests

### ISSUE THREAD

**Issue by ProxyPlayerHD** [AppliedEnergistics/Applied-Energistics-2#3281]
Sorry if this is not the place for these kinds of posts.

this has been bothering me for quite some time, every meteor you find only has 4 important things inside it... the presses. There is nothing else except some basically worthless nuggets.

why not have some more AE² Related loot?
Certus Quartz/Dust, Charged Certus, Fluix Crystal/Dust or even rarely some Pure Quartz?
maybe even something else too... idk, Fluix Glass cables or something similar.

better loot would make a lot of people actually grab Meteors on the go even after they already got all presses... because heck, there might be ME controllers, Storage cells, some Cables, (or etc.) inside there!

welp, that was the basic idea.

**Comment by yueh** [comment]
While it might sound nice, it is a pretty bad idea in regards to servers.

Balancing it is really hard and it can easily be not worthwhile to search them and ultimately it just adds random clutter to the inventory. Or the rewards are too good and everyone just pillages all meteors, causing the other players to whine even more because they do not find any meteor.

If we revisit datapacks for 1.13, it might be an idea to allow modpacker makers to change the contents. But the defaults will stay as they are.

**Comment by ProxyPlayerHD** [comment]
well that is one way. or being able to edit LootTables of Mods, kinda like how EnderIO had all these extra files to customize recipes.

that way the map/modpack maker could decide what you find.

but atleast but verations of quartz in it by default, who wants to find a Meteor with only nuggets.
