### ISSUE TITLE
[1.12.2] Facade Crafting with TiC2 does not work

### ISSUE THREAD

**Issue by JonasCiss** [AppliedEnergistics/Applied-Energistics-2#3291]
It is not possible to craft facedes made of TiC's seared bricks and other seared stuff.

I also reported that to TiC. 

https://github.com/SlimeKnights/TinkersConstruct/issues/3303 

Forge: 14.23.1.2562
AE2: appliedenergistics2-rv5-stable-3
TiC: TConstruct-1.12-2.8.1.49

**Comment by yueh** [comment]
Any block with a tile entity is disabled by default, but they can be forcefully enabled through the facade config (without any guarantee that it does not crash).

As the config file can be distributed as part of a modpack, there is intentionally no other way to whitelist blocks. This is mostly done to avoid someone whitelisting every single one without ever testing them, as well as to prevent new blocks from immediately crashing due to being untested.
