### ISSUE TITLE
ME Wireless Access Point is upside down

### ISSUE THREAD

**Issue by Xiaminou** [AppliedEnergistics/Applied-Energistics-2#3308]
![2018-01-03_00 19 59](https://user-images.githubusercontent.com/8670392/34504034-26dd0164-f01c-11e7-90b7-eebdd02e7c70.png)

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: stable-4
- Forge Version: 2583

**Comment by fscan** [comment]
Cannot reproduce, did you perchance hit it with a wrench?

**Comment by Xiaminou** [comment]
No, it was like that when I logged into my world, I tried replacing it but they all appear at the opposite of where you place them.

**Comment by fscan** [comment]
Ok, i get it with the most recent forge version .. we'll have to test and see what commit broke it.

**Comment by fscan** [comment]
https://github.com/MinecraftForge/MinecraftForge/commit/867698eb544666bb7f1f77c8a90ef9a49d337098 seems to have broken it.

**Comment by yueh** [comment]
Probably caused by the WAP having a default 180 degree rotation. No idea why, could be to avoid a bug or the whole model maybe having incorrect coordinates.

The first is something we cannot really fix currently as it would break compatibility with the latest RB. With forge release being extremly unstable lately, there is no valid argument to force any user to use the bleeding edge and drop every mod not supporting it.

At this point, it does really make sense to require a specific RB to avoid having users running into forge issues on a daily basis and just pure luck that it does not break down.

**Comment by Xiaminou** [comment]
Do you know which version of forge is breaking it? I'll just downgrade to a prior version until a mod forces me to update past it.

**Comment by fscan** [comment]
2575 is the last working one for this issue. Maybe we can fix it, but i fear that if we fix it for newer forge it breaks in older (including RB).

**Comment by Xiaminou** [comment]
Is it not possible to do a conditional? If it's below that version use this otherwise use that.

**Comment by fscan** [comment]
no, its a json file

**Comment by fscan** [comment]
FYI,  https://github.com/MinecraftForge/MinecraftForge/issues/4650

**Comment by fscan** [comment]
They fixed it.
