### ISSUE TITLE
Seed based feature (meteor) generation

### ISSUE THREAD

**Issue by Robijnvogel** [AppliedEnergistics/Applied-Energistics-2#3309]
[Tag]

#### Description
Using AE in the past, I have noticed that there doesn't seem to be a direct mapping from a world's seed to the placement of AE's meteors.
Specifically, I have noticed that AE meteors seem to be spawning along the edges of the world when using a pregenerator mod, in my case this would have been Forge Essentials, or maybe this was caused by Dynmaps loading chunks.
Either way, this causes an awkward placement of the meteors that heavily suggests my assumption.

Why aren't AE meteors placed in the way that, for instance, villages, temples and Nether Fortresses are?
This would enable you to predict where a meteor is going to be generated as well, which could have practical uses in addons or future features. I am specifically thinking about some kind of meteor compass.

If, by any chance, in my search through the repository and issues, I have missed that this feature is already implemented, then by all means close it, but then at least this issue tracker has an issue "documenting" it.

#### Environment
- Minecraft Version: -
- AE2 Version: -
- Forge Version: -

**Comment by yueh** [comment]
Not being predictable is exactly the reason, why it does not depend on the seed. 

Also it is designed around a the natural exploration achieved by a player, to somewhat guarantee that they will find one and not miss them like villages/fortress just because they are just a few blocks outside the explored chunks.

As well as a few smaller issues, like it is impossible to tell the contents of a chunk before it's generated. So the whole blacklist to avoid specific blocks or structures is simply not possible. At least not without generating a large area at once. Probably an 2k x 2k blocks large area or even more depending on config values. As well as trying to stitch non continuous exploration via nether transporation/etc together without running into placement conflicts.

**Comment by Robijnvogel** [comment]
Forgive me if I'm wrong, but isn't the ability to regenerate a world from the same seed one of the main points of seed-based generation in the first place?

Why does Applied Energistics of all mods have to break this principle? I know that there are other mods that don't really care about seeds when placing their worldgen features, but I don't think that something as harmlessly small as a bush can be compared to a 50-block wide crater with a huge meteor in the middle. :/
