### ISSUE TITLE
[1.12.2] Crash loading existing world using rv5-stable4

### ISSUE THREAD

**Issue by Morpheus1101** [AppliedEnergistics/Applied-Energistics-2#3318]
- Minecraft Version:  1.12.2
- AE2 Version:  *.rv5-stable4
- Forge Version: *.2586

Crash log @ https://gist.github.com/Morpheus1101/726fb45cd2bae64f7babf9b279b27a2f

**Comment by yueh** [comment]
Looks like some chunk corruption and a controller block was replaced with a wireless access point. E.g. the usual off by 1 error flipping it to the adjacent block.

I do not think there are many options besides restoring a backup or trying to fix it manually via `/setblock` or other tools. But that is currently not really possible due to the BlockPos not being logged.
We certainly should improve the logging on our side here.

**Comment by CCninja86** [comment]
@yueh a similar error has just happened on a popular Minecraft server and it also is posing an issue due to unknown location. ME Drive seems to be the source. Perhaps better logging should be made a priority?

**Comment by CCninja86** [comment]
@yueh a similar error has just happened on a popular Minecraft server and it also is posing an issue due to unknown location. ME Drive seems to be the source. Perhaps better logging should be made a priority?

**Comment by yueh** [comment]
Probably. The whole forge chunkloading is full of race conditions, cache invalidation issues and what not.
And that is why you don't multithread a non threadsafe code base...

Due to the different ticking behaviour of AE2, we could potentially run into them more easily. But Forge does not provide any better option for us to hook into a more fitting place. So if we have to choose between a better performance or a slightly lower chance to run into forge bugs, the first is certainly a better option. (As the bugs also should be fixed at some point)
