### ISSUE TITLE
Quantum Ring isn't craftable when Channels are disabled.

### ISSUE THREAD

**Issue by PiggyWhiskey** [AppliedEnergistics/Applied-Energistics-2#3323]
FTB Revelations 1.2.0 using appliedenergistics2-rv5-stable-4
Config changed to disable channels.

Quantum Ring requires Dense Cable which is disabled (Along with Smart Cable, ME Controller) when channels are disabled.
Preventing any interdimensional use of a common network.

Edit: Decided to cheat them in, and realised that with Channel's Disabled, the Quantum Ring's don't connect

**Comment by mindforger** [comment]
disableing channels always was an unplanned feature and never got additional support over all the time because the channel principle isn't all that hard and building giant networks is producing much more issues perfoormance wise than one would expect

so you are left to alter the recipes on your own to get to your quantum rings

>Edit: Decided to cheat them in, and realised that with Channel's Disabled, the Quantum Ring's don't connect

can you explain this a bit more detailed? what do you mean by "not connect" .. do you mean the multiblock not forming or the rings not actually connecting to each other?

if the last is the issue, did you cheat in the entangled singularities, because this never works, you have to make them using TNT, there is no other way than editing their data to get them work beasides the designed way

**Comment by PiggyWhiskey** [comment]
I made the Singularities legitimately, and entangled them with Tiny TNT to get the appropriate items.

The rings illuminate and have particles. To receive energy both sides have an Energy Acceptor.
However, my primary network (Simple Void World dimension) can't see anything on the other side (Overworld)

**Comment by Tahakk** [comment]
#453

**Comment by mindforger** [comment]
@Tahakk yeah this is the original discussion but it doesn't solve the actual issue and I am personally not able to test this within the next days

@PiggyWhiskey can you please confirm this issue with regular dimensions like nether and overworld and only AE2 installed ... sometimes addons like AE2Stuff and others may cause an issue and i am out of chance to test this yet

**Comment by yueh** [comment]
Duplicate. Also take chunk loading into account for the other issue.

**Comment by mindforger** [comment]
>Also take chunk loading into account for the other issue.

well i shouldn't try to help people when on ibuprofen ... this totally slipped my mind :D
