### ISSUE TITLE
AE2 System Lagging Whole server !

### ISSUE THREAD

**Issue by berni1212** [AppliedEnergistics/Applied-Energistics-2#3358]
#### Description
Server Laggs so badly when the Storage bus Bus on YABBA Barrels
and the TPS of the Server Goes down to 1-5 The whole time until i disconnected it  
it works fine again ! there are Many Barrels connected to a Storage bus and its Adding Mobdrops from a Mobfarm there are about 1M to 22M items in it and its Crashing almost the server

#### Environment
Minecraft 1.12 server 20 GB ram working without problems Player base from 2 People with a Soulshardmobfarm auto sorting stuff in barrels without Pipes and the Server laggs so badly  
Items in there : Solified Expirence ,Bones, Arrows, gunpowder , Wither ash , Necrotic bones , Wither Rips, Drop of evil , Wither skeleton Skull , Wither Dust , Skeleton skulls , Blaze rods , Sulfur , Molten core , Creeper heads , gland , Ripe bone , Cobweb, String, Spider theeths , Spider eyes , Nebulous hearts , Slime pearls , Slimeballs ,Core , Brick , Rotten flesh , Enderpearls , Gold nuggets , Zombie heart , Gold ingot , Bat wing ,  Sticks , Potion of Swiftness , Potion of healing , with hat , redstone , Sugar , Glowstone , Glas bottel , Pulverzied Obsidian , Snowballs , Niter , feathers , Raw chicken , Bliz rods , Blizz rods , Basalz rods ,  

- Minecraft Version:  1.12
-FTB MODPACK: Revelations 1.4.0
- AE2 Version:  appliedenergistics2-rv5-stable-5.jar
- Forge Version:  forgelin 1.6.0

**Comment by yueh** [comment]
We need profiler/sampler dumps, otherwise there is nothing we can do.

**Comment by berni1212** [comment]
How i get em !?

**Comment by yueh** [comment]
E.g. attaching visualvm to the running server and dumping a sampler result. But that is a basic administration topic, so your server admin should already know about it.

**Comment by EnderCorpsAlpha** [comment]
I can say for the most part that this issue might be related to the stack sizes involved, Not the connection between the two tile entities themselves per se, Since I've noticed that systems which have to deal with loading large numbers of items from external sources do have a large delay between reading with certain entities - This might be down to how the barrels themselves display the items, Since for instance, the Drawers mod just takes note of how many items is inside and gives an integer where the barrels could be trying to store each item inside visibly on the network.  - I'm just throwing my input on the matter in, But it's far easier to just fill a few stacks of drives automatically with 64ks or 16384ks (With EC2 installed) rather than just using barrels. 

Secondly, The lag on the server might be down to people also poorly optimising their builds - So make sure people don't have loops in itemducts and other forms of conduit since it causes memory leaks - big ones.
