### ISSUE TITLE
Allow JEI to "Move Items" in JEI for non-3x3 recipes

### ISSUE THREAD

**Issue by Beannsss** [AppliedEnergistics/Applied-Energistics-2#3360]
#### Description
Feature Request:

I've looked everywhere on this github to make sure this request wasn't made already, but to no avail; I apologize if this is duplicate. In AE, the terminals will only allow you to fill in the recipe from JEI if it is a 3x3 grid; however, if possible, it would be helpful if you could do the same with "processing recipes" (i.e. Furnace, Runic Altar from Botania, etc.) Refined Storage does have this functionality. I'm not sure (in refined storage's case) if JEI handles the shift clicking, or RS does it. A good use case for this would be to easily fill in processing patterns for interfaces. This also helps with the removal of using "ghost items" from NEI (in older minecraft versions) to fill in patterns.

Simple Example:

https://prnt.sc/i6t3s9 -> https://prnt.sc/i6t472

I would love to provide more detail if any is needed.

#### Environment

SP and MP

-JEI Version: 1.12.2-4.8.5.147
- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-5
- Forge Version: 14.23.1.2587

**Comment by yueh** [comment]
Not possible.

**Comment by Beannsss** [comment]
Thank you for the quick answer.

**Comment by fscan** [comment]
Sure, a simple implementation is possible (i actually had this implemented for AE2 at one point). The real issue is that we have no way to tell (at least at that time, maybe this has changed? ) if an output is optional or only has a drop chance.
The result would be that a lot of recipes ( eg almost all of TE pulverizer recipes) would be invalid because they would require the conditional output.
So, as this only works for a simple subset of processing recipes we decided to not support it to avoid confusion.

**Comment by dav20011** [comment]
Still doesn't look like that checking that is possible. If this is the actual reason it's not built in, I'd suggest to at least add it as a disabled by default feature (as mentioned before, RS has this feature and so far I did not see anyone complain about it). If you know what you are doing it's very useful since getting one of each item is tedious.
