### ISSUE TITLE
Forge Mod Loader detected that the backup level.dat is being used

### ISSUE THREAD

**Issue by rami-m01** [AppliedEnergistics/Applied-Energistics-2#3401]
I get this error when i load my world, and this happened after i updated my modpack,
i tried using older backups of the world but it does the same thing
i posted this on ae2 issues because i checked the crash log and seams to indicate that the problem is with ae2

crash log: https://pastebin.com/D8pHitwd

note: i tried using an older version of ae2 and it's still not working

- Minecraft Version: 1.12.2
- AE2 Version: rv5 - stable8
- Forge Version: 14.23.2.2618

**Comment by yueh** [comment]
Probably the usual world corruption, which seems to plague forge since 1.10 or maybe even earlier.

There might be a small chance that some other mod corrupts essential data, but the only option I can recommend is removing mods until you are left with just AE2 and for this case Botania. To prevent that forge deletes that particular block as it passes tha data of a botania enchanter to a ME controller.
If it still crashes with AE and Botania it's most likely some corrupted chunk, so an old backup is more or less the best option.

If it a some point it stops crashing, one of the removed mods was probably the one causing it. After that the best idea is to verify it with just that mod + AE/Botania. If so, the best idea is to report it to that particular mod. Worst option could be that 2 (or more) of the coremods together cause it.

Otherwise there is nothing we can really do about it.
