### ISSUE TITLE
Right clicking to grab a stack of crafted items doesn't give a full stack despite having the materials

### ISSUE THREAD

**Issue by Ghostbroker** [AppliedEnergistics/Applied-Energistics-2#3403]
#### Description
For example, I am crafting a copper gear with 4 copper and 1 iron. I right click the gear to pull out 64 of them, and get 36. There is still thousands of copper and iron (all of the same type, not ore dictionaried). I can immediately shift click the recipe back into the grid and craft it again, but I still don't get a full stack.

I tried the same thing with string to craft wool, and it gives me 45 every time instead of 64.

#### Environment
This is on a multiplayer server using FTB Revelations. Some other mods were added like Mekanism.

- Minecraft Version: 1.12.2 
- AE2 Version: appliedenergistics2-rv5-stable-8
- Forge Version: 1.12.2-14.23.2.2613

**Comment by mindforger** [comment]
kind of sounds like an power issue, install some energy cells. And no, infinite input means nothing, because input is limited ne the system capacity

You can install a creative cell for testing

**Comment by Ghostbroker** [comment]
I tested it with a creative energy cell and it worked. Adding an ae2 energy cell onto my network fixed the problem for the survival part too.

Has this always been required? I have my energy acceptor connected directly to thermal energy cell so I don't know why it's losing power. I've never used an ae2 energy cell before on older minecraft versions.

**Comment by amilliner** [comment]
I had the same issue in a custom modpack with AE2 rv5-stable-8 and Forge 14.23.2.2611, and the same solution (adding an energy cell to my system) fixed my problem. 

I haven't looked into the code at all to verify this, but I'm my guess would be that the energy acceptor has an internal energy buffer. I'm also guessing that when the system checks the available energy for an operation (such as removing items), it works on [energy buffer] - [per-tick energy drain on the system], as my maximum stack size was proportional to the number of machines connected to my ME system.

**Comment by mindforger** [comment]
> energy acceptor has an internal energy buffer 

other blocks too have an buffer, but they are all small

also don't calculate too much, there are a LOT of different operations that will draw power out of your system-buffer

any item moving consumes power and evaluating newly attached devices also does

and the math is quite simple, if you action consumes the last drop of power, the system shuts down and tries to reboot .... now that your system jsut passed a critical mark in size, it consumes more power to evaluate the "new" (because reboot) system and runs out of power ehile doing so

in result the system seems to not online properly anymore

if you manage to consume the power of your internal buffer and the system is not too big to reboot, it will LOOK fine from the outside, but any ongoing actions will be aborted, that is why you only get a partial stack, because you consumed all power during the process and the system did a quick reboot
