### ISSUE TITLE
constantly crashing when loading up base. tesselating block model error

### ISSUE THREAD

**Issue by kamrantekkit** [AppliedEnergistics/Applied-Energistics-2#3404]
#### Description
Every time when i try join a modded server. when the game try's loading up my base it crashes. Minecraft says tesselating block model error.i tried fixing the error but did not work.

#### Environment
ME system contains like 18 me drives half of them fillied with 64k drives. alot of thermal expansion machines. 3 to 4 mob farms 
i use MP on a modpack called direwolf version 1.8.0.
https://pastebin.com/dWwPnA8A minecraft crashlog

- Minecraft Version: 
- AE2 Version: appiledenergictics2-rv5-stable-5
- Forge Version: 14.23.1.2601

**Comment by mindforger** [comment]
>Java Version: 1.8.0_25

please download and install the lastest Java8 Version (64bit/mixed mode, this is important, have a look at the version you are downloading)

then go into your twitch and launcher settings and enable the system JRE to be used instead of the one bundled with Minecraft, as it is alsmost 3 years old now

pióint on the javaw file or stay in the bin forlder of your Java JRE, depending on if you use the older or the newest launcher

**Comment by yueh** [comment]
Maybe the usual suspects like Optifine causing it?

**Comment by mindforger** [comment]
could also be the exaCord Server transmitting wrong data to the client !? 

i found 2 at least "similar" looking crashes with other mods using exaCord server crashing during rendering becasue of blockstate issues

**Comment by yueh** [comment]
Did miss that. I guess, if they somehow change the data being send around to be smaller or whatever else, it could happen.

So as long as it cannot be reproduced with a plain forge server, I will close it for now.
