### ISSUE TITLE
Advancements errors after disabling features

### ISSUE THREAD

**Issue by Krosta8** [AppliedEnergistics/Applied-Energistics-2#3430]
#### Description

After turning off a few things in a config AppliedEnergistics2.cfg, on every start is there error from Json, that can't load Advancement string of turned off blocks/items.
Example: https://hastebin.com/guhipoliya.rb
Config: https://pastebin.com/mzh2pzfT
#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable10
- Forge Version: 14.23.2.2611

**Comment by yueh** [comment]
That simply happens when disabling items. I cannot say if it is currently possible, but in 1.13 a modpack maker is able to provide their own advancements matching their custom config. There are simply to many options to provide something out of the box.

Also should sponge have issues with it, that is not our issue as forge itself just ignores them.
