### ISSUE TITLE
Applied Energistics 2 crashes on startup due to dimension being taken. 

### ISSUE THREAD

**Issue by Mattsingen** [AppliedEnergistics/Applied-Energistics-2#3444]
After updating to the latest version of Nuclearcraft (v2.10) I get a crash on startup.
https://pastebin.com/TqSQRHyH

It can be resolved by changing the config to use an other ID than 2 for the I:storageDimensionID config setting. 

As it's an interaction problem I've logged it also at Nuclearcraft:
https://github.com/turbodiesel4598/NuclearCraft/issues/270

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.2.2640

**Comment by yueh** [comment]
This is happening due to Forge not persisting already registered dimension in any way. So once another mod is added or updated and registers a new dimension with the same id, it would mean you lose everything in that world or at least have it potentially corrupted in some areas. Thus we crash and give you the chance to reassign the newly added dimension to another id instead of risking the spatial dimension. Same will happe, if you decide to change the spatial dimension id instead of the newly added one.
