### ISSUE TITLE
Behaviour with the silicon from ender-io

### ISSUE THREAD

**Issue by TheBlackLuigi** [AppliedEnergistics/Applied-Energistics-2#3452]
When AE2 and Ender-IO are installed, Ender-IO silicon turns the one from AE2 into "this item is disabled"
Also the Ender-IO silicon does not fit in the inscriber.
When I set the silicon-option in "orecamouflage" to false I gain regular lag spikes in intervals of 10-15 seconds.

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 1.12.2-14.23.2.2624
-Ender-IO Version: 1.12.2-5.0.20
-Ender-Core Version: 1.12.2-0.5.18

**Comment by yueh** [comment]
That is simply intentional behaviour (disabling our silicon). And also there is the config option to disable it, if really necessary. Until now it worked fine with pretty much any other mod adding duplicate items. Just EnderIO seems to be the exception, which requires manual intervention.

The inscriber will (by default) accept any oredict silicon and it works just fine with default AE2/EnderIO settings for me. Most likely a mod pack issue without knowing any further details.

No idea about the lag spikes. Could also be modpack specific, But without any detailed information, sampling/profiling reports, it's pretty much impossible to say anything about it.

**Comment by GuntherDW** [comment]
I'm attempting to install EIO in my dev environment but I'm having difficulties with it. Their Mappings file seems to be either outdated, too new or just wrong.

Nevermind that, in an obf'ed environment I can insert the EIO silicon just fine into both the AE2Stuff and "Vanilla" AE2 inscribers.
![Proof](https://i.imgur.com/hBXP2NZ.png)

The lag issue couldn't be something that is caused by our config either. All that option does is skip a single check during boot to remove said items from the registry.
This happens before the main menu even shows up.
