### ISSUE TITLE
Disabled channel setting cause ME Crafting terminal to start bugging

### ISSUE THREAD

**Issue by weiqian1020** [AppliedEnergistics/Applied-Energistics-2#3493]
I've turn off the channel option in the config file, and I notice once my ME Network uses more than 128 channels (Note: I read this from ME Conduit from Ender IO), things start to get weird, such as auto crafting fail to work, ME Crafting Terminal pulls out less 64 even the item in the system is more than 64 (example: my network has 646 cobblestone and I tried to pull one stack out, which is 64 cobblestone, but it only gave me 45 cobblestone), sometimes ME Crafting Terminal can't even pull any item.

I read one Issues that had posted about the similar problem, but I do not really know how to fix it...
This happened in FTB Infinity Evolved 3.0.2

- Minecraft Version: 1.7.10
- AE2 Version: appliedenergistics2-rv3-beta-6

**Comment by mindforger** [comment]
you have multiple issues

First intall some Energy cells, your system runs out of power. Input is limited to capacity/ticks, use your network tool to check capacity. This may solve all issues but there may stay some issues because disabling channel was only a hacky feature in 1.7.10. Also this version is not supported anymore and i will close the issue therefor, just call back if it worked and if not we can maybe still work it out
