### ISSUE TITLE
Huge performance issue

### ISSUE THREAD

**Issue by TonyTheGOD** [AppliedEnergistics/Applied-Energistics-2#3519]
#### Environment

Pretty much i was find out why my world lagging very bad so i Spark, if you don't know what is Spark is a CPU profiling plugin based on sk89q's WarmRoast profiler. Anyways beside the point the my server was very lagging and i have no idea why so i look around this github page and try to find some answers i think the issue is related to this https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3417 or this https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/3490 here is the Spark WarmRoast https://sparkprofiler.github.io/?GJHzMhHjul if the link has expire i had save the webpage here

[WarmRoast.zip](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2054889/WarmRoast.zip)

on the website please select where it said "No Mappings" and move it too MCP 1.12.2 you can see better descriptions for some of the obfuscated methods

![fb87bc3a42505b4419bff6f3a11c1bb1](https://user-images.githubusercontent.com/39774190/40735297-d0be074a-6408-11e8-9ea9-7b6690fcf5b1.png)
![c86c33f1fe1a7d09d1140f9c86ba7376](https://user-images.githubusercontent.com/39774190/40735320-e2a75c0e-6408-11e8-8522-788bd0399e8d.png)

- Minecraft Version:  1.12.2
- AE2 Version: appliedenergistics2-rv5-stable-11
- Forge Version: 14.23.4.2705

**Comment by TonyTheGOD** [comment]
Also to addon to this to seem it does something to lighting and unloading chunks 
![ea1c8143130119b2ca6a31c4827cfde3](https://user-images.githubusercontent.com/39774190/40736052-e4f7d860-640a-11e8-859a-8edb3104c1b4.png)

**Comment by mindforger** [comment]
is your ME system chunkloaded properly? without chunkloading there will be hell lot of unloading and reloading of chunks, always make sure everythign that is connected is chunkloaded

also make sure you have enough energy cells installed, input is limited by the internal capoacity of the ME system!

**Comment by TonyTheGOD** [comment]
No sorry on the server i had banned the use of chunk loading cause they can cause bad performance.
Also even if i do need enough energy cells installed this issue shouldn't be here causing that much lag

**Comment by TonyTheGOD** [comment]
Sorry just a bit confuse on this, I'm not even too sure on how to fix this without removing Applied Energistics

**Comment by mindforger** [comment]
let me say it the apple way: your holding it wrong

What ommina and i want to tell is, you banned the only helpfull tool from your server!

Just try to understand the following. If an me System looses power or parts are being removed or added (due to unloading and reloading chunks), it has to reevaluate the network... Depending on the size this may take aweful long and causes quite a good CPU spike... And now take this in, there are dozends of mods that cause uncontrollable chunk loading and the only valid way is to keep the me system loaded... Same goes for quantum bridges, how do you expect them to work between distant spaces when the remote gate is not loaded

You should rethink your policy... Also there are bad chunkloader, you should test them first and avoid chunkloaders that only will work when someone is online, this will cause issues when the owner loggs off.


Ommina wanted to tell you, you exchanged an potential issue with an avoidable but absolute certain issue
