### ISSUE TITLE
Adding silicon(refinedstorage) to craft inscriber silicon plate.

### ISSUE THREAD

**Issue by Oleksandrigo** [AppliedEnergistics/Applied-Energistics-2#3534]
Adding silicon(refinedstorage) to craft inscriber silicon plate.
Why then it is impossible to make a silicone plate from it?

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv5-stable-11
- Forge Version: 14.23.4.2707

**Comment by GuntherDW** [comment]
We register our machine recipes alongside the normal recipes in the ForgeRegistry<IRecipe> event.
I checked with the current version of RefinedStorage on curseforge and it appears the silicon oredict is only registered during the FMLInitializationEvent event.

As most of our machines recipes are set in stone during the ForgeRegistry<IRecipe> event, as well as the method to check for other mods' OD values such as the aforementioned silicon (for example the Ender IO one correctly overrides ours), the RS one gets skipped and not used.

Is there a reason the RS devs only register the silicon to the OD that late, instead of when they register the Item itself?

**Comment by Oleksandrigo** [comment]
https://github.com/raoulvdberge/refinedstorage/issues/1814

**Comment by Oleksandrigo** [comment]
In general, I eased my life and just downloaded the galactic craft.

**Comment by fscan** [comment]
RS registers oredict entries to late. They have to be available at recipe registration.
