### ISSUE TITLE
Implement Fluid Interface

### ISSUE THREAD

**Issue by fscan** [AppliedEnergistics/Applied-Energistics-2#3554]
This is the only thing missing to have functional fluid support.
Decide if we need a new GUI or reuse the EC2 one.

**Comment by yueh** [comment]
The EC2 has a bit of additonal features, which we currently do not need (patterns etc).

Further it does not fit particular well into the normal AE2 parts due to exposing `EnumFacing` through the GUI, so without using F3 there is not always a reliable way to determine, which way a side is facing.

Also exposing only 1 tank per side is not consistent with the normal interface.
`IFluidHandler` can support multiple tanks per side, so we could offer up to 9 tanks to match the interface. 

But that might be a bit overkill as there are way more items than fluids available. Something in the range of 1-3 tanks exposed on all sides might be better. 1 for a block interface is really limited, but could work for a part one. 

So also the question about adding a block interface, part interface, or both.

**Comment by leagris** [comment]
My 2 cents about patterns in fluid interface, as I remember I have already mentioned it:
Having support for patterns in fluid interface was a great feature of EC2.
When pattern has a fluid container, the fluid interface will send the amount of given fluid as recorded by the container content in pattern, and it will also send items and return everything from the connected machine/tank.

This allow on-demand crafting automation of machines using specific amount of fluid and items.
Can be Tinkers Construct casting tables, sending for example: 144mB of molten aluminum  and an ingot mold, returning mold and aluminum ingot to ME
Can be Gregtech fluid solidifier, chemical reactors or whatever, receiving precise amount of fluids, cells, and return result into ME

I use this EC2 feature extensively in older AE2 and EC2 for 1.7.10.

IMHO patterns with precise amount of fluids is what makes fluid handling in an ME a relevant feature. Otherwise, it is just about storage and piping. It loose all attractiveness of the logistic powers of an ME.

**Comment by fscan** [comment]
Pattern/Crafting support would be nice to have. I don't know if it viable for this version. 
I would definitely like to have both, block and a part version. It is kinda needed if we remove the facing tanks.
Regarding the number of tanks ... 6 for block and 3 for part would be ok i think.

**Comment by fscan** [comment]
The fluid interface is in rv6 now, crafting support is planned for a later stage.
