### ISSUE TITLE
Can't craft ME covered cable with auto-crafting

### ISSUE THREAD

**Issue by Therideru** [AppliedEnergistics/Applied-Energistics-2#3582]
- Minecraft Version:  1.12.2
- AE2 Version: rv5-stable-11
- Forge Version:  14.23.2705
- Mod-Pack: modern skyblock 3 Departed

So  i  have  the problem that i can't craft the ME covered cable over auto-crafting or in the vanilla crafting grid from the crafting terminal. but i can craft the covered cable in a normal crafting table.

**Comment by Therideru** [comment]
it was the mod pack it self

**Comment by MrChros** [comment]
What was the specific solution to this issue? I'm having the exact same behavior playing the Modpack Modern Skyblock 3 Departed.
Using Google, I could not find any other post or website mentioning this problem. The guys at discord are also not sure what the problem is. 

Thanks in advance. :)

**Comment by Back2Attack** [comment]
I would like to know the solution myself as i am finding this a brick wall when coming to producing the automation i am aiming for.,

**Comment by MrChros** [comment]
The problem is the stages mod within the modpack. Certain items are gated and they are unlocked for you (the player). Autocrafting isn't the player, so they are still locked.
What you can do is, delete the stages file from the scripts folder of the modpack. You don't have gates anymore and you can autocraft. If you keep the gates and stages is now up to you.

I'm talking about version 3.4.1.4 of Modern Skyblock 3 Departed. I heard, that this issue will be fixed in the next version. But when the next version will be available nobody knows.

Good luck and hopefully more fun. :)

**Comment by FlocraftHD** [comment]
You are Right MrChaos I have "Solved" the Problem on my way
I placed A Chest Next to my Interface with These recipes Ad a Comperator and a Redstone Lamp next to mY System
So if the System has to make one of those I will be remebered to do ist With the JEI Extention 

It isnt perfect but it works

Sry for my bad English
