### ISSUE TITLE
JEI integration no 'missing items' tooltop

### ISSUE THREAD

**Issue by avix133** [AppliedEnergistics/Applied-Energistics-2#3652]
**Description:**
There is some interference in the Just Enough Items (4.10.0.199). 
![jei1](https://user-images.githubusercontent.com/20650765/43294688-f5e0f324-9140-11e8-870c-bc379edfc5bf.jpg)
I can click "Move Items" even if I don't have any of them.

It would be nice to have at least "Missing items" prompt.
![jei2](https://user-images.githubusercontent.com/20650765/43294776-6a0f91e2-9141-11e8-9d74-8fc727f3249f.jpg)

Any help how can I set it up will be appriciated!

[mod_list.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/2235032/mod_list.txt)

- Minecraft Version: 1.12.2
- AE2 Version: RV5 Stable 11
- Forge Version: 14.23.4.2709

Issues with ME Terminals' UIs #2627

**Comment by ProxyPlayerHD** [comment]
good thing i used the search fucntion, was about to post the same issue.

it really is inconvenient because without this you either just need to hope you have the right items and/or search for each indivitual ingredient to check if you even have it/enough to craft whatever you wanted.

also i find it ironic and funny that you use a RS Item as example for a AE2 feature/issue

**Comment by warbaque** [comment]
Is there any fix or workaround for this?

**Comment by yueh** [comment]
This actually needs further JEI features to be actually useful.

For one it can only be an error. Not something like a warning. Therefore it would completely block every action in case of a single item being missing. 

This might be fine if like everything is missing. But in case it's only 1 or 2 items, it would be way more user friendly to display a warning about which items are missing, while still allowing a partial transfer and then say use autocrafting to aquire the missing items.

Maybe even go as far as having an info in case items are missing, but are craftable and a warning in case items are missing and no crafting available.

As long as JEI is that disruptive in how it handles these cases, it is a simple no.
If they revisit it and make it less disruptive, it is certainly up for reconsideration.
Just some things like validating against autocrafting might also require that JEI provides a serverside component to handle  them. What most likely won't happen, because the additional network delay/traffic is certainly too high.
