### ISSUE TITLE
A Enderman stole my Me Dirve is this Possible ?

### ISSUE THREAD

**Issue by Carrier3000** [AppliedEnergistics/Applied-Energistics-2#3684]
#### Environment

 FTb Invinity Elved 

- Minecraft Version: 1.7.10
- AE2 Version: 
- Forge Version:

**Comment by Pingger** [comment]
First, what is AE2 version?, What is the Forge Version?, What is the ModPack Version?

Then, you are playing on a modpack, so there might be a mod, that whitelisted ME Drives for Endermen to pick those up.

So it is possible, that an Endermen picked up the Drive, but extremely unlikely since Endermen can't pick those up by default.
