### ISSUE TITLE
[Proposal] Power Failure Inidicator (Update Indicator)

### ISSUE THREAD

**Issue by mindforger** [AppliedEnergistics/Applied-Energistics-2#3701]
As a result of playing Sevtech and having an early on power issue due to an dirty network setup (resulting in a TPS lag due to rebuilding the network)

and also concidering the numerous non-issues about items not moving and crafting jobs canceling due to power outage

i want to propose the addition of an power failure indicator

i looked through the code and found GuiMEMonitorable.java

this looks like the "frame" around all terminals and GUIs from AE2 as far as i understand

this is also checking wether it is connected to storages in any way and should be able to obtain informations from the ME network

it would require the network a tiny bit recoded to present an property like "powerIssue" to the Monitorable, that is FALSE whenever the system has operated for 100 ticks without running out of power once (or being forced to update even) , otherwise TRUE

if you would go that far to not only monitor power but bind it to any network updating action (attaching or detatching, not item updates), this would also help to resolve chunkloading issues like a remote QNB being in a forcefully un/reloading chunk!

A toolip could then tell Power Failure in the last 5 seconds, add more energy cells or check power input
The updating indicator would be a bit too technical imho but could help at least to find known weakspots faster

**Comment by yueh** [comment]
Basically not in this form.

Adding it to a terminal can easily be missed, yet it would always be displayed for the first couple seconds after booting a network, thus creating a false negative and further bug reports about "but I have enough power".

The networks themselves already track any power outage and only reactivate after 30 ticks or so.
However this currently only applies to static consumptions by parts etc, but not dynamic consumption like item transfers.

My current plan was to fix it at some point and completely shut off a network on power failure and not have it silently ignore it. Which certainly is a better indicator, because many more things will indicate it. E.g. the terminal GUIs being disabled until the power is restored, controllers,smart cables,panels will power down and so on. With the additional benefit of not allowing the player to ignore it like any other control lamp, because it's always lit without any effect otherwise.
