### ISSUE TITLE
Add in JEI ghost item support when configuring filter/bus slots

### ISSUE THREAD

**Issue by Keridos** [AppliedEnergistics/Applied-Energistics-2#3787]
JEI since quite some time has a feature which lets you configure ghost slots using the JEI pane instead of the actual items/fluids from your inventory. It would be great if this could be integrated into AE2

**Describe the feature**
Take a look at EnderIO, the filters for its conduits support this.

**Reasons why it should be considered**
Makes configuring ghost slots much more convenient with JEI

**Additional Context**
This is Refined Storages implementation for it: https://github.com/raoulvdberge/refinedstorage/commit/861e67c9d17a2f8cfe6dd90259dfc2edbbc5c94c

**Comment by yueh** [comment]
While it certainly would be a nice feature, it is quite common that the itemstack shown in JEI won't match the data of the existing item (except trivial ones like cobble). Therefore there won't be any indication why they do not work even when configured correctly without exposing minecraft internals to every player.

While export/import buses might be a bit more forgiving, there is no way to allow it for some cases like crafting as it is guaranteed to fail very frequently. So further to not working randomly, it would also be pretty inconsistent that some slots allow it, while others do not or even cause subsequent faults somewhere else. Which we already had with drag&drop from JEI as it sometimes work automatically.

Hopefully 1.13 will allow us to revisit it as it technically makes filtering them a bit easier. But that only works as long as no mods start to actively break it because the want to be special.

**Comment by Keridos** [comment]
Could you at least consider this for fluids?
