### ISSUE TITLE
ME Interface with Crafting Card & Storage Bus never completes crafting job

### ISSUE THREAD

**Issue by MisterInsane** [AppliedEnergistics/Applied-Energistics-2#3829]
I've used a interface with a crafting card to maintain a certain amount of items in the network and a storage bus so they items are "visible" to the crafting process. It has been troublesome to keep this functionality working, and it seems impossible in RV6.

**Describe the bug**
The storage bus is not properly relaying the inventory of the ME interface. The ME interface will initiate a crafting job, but the crafting job never "finishes" despite the items being available within the ME interface with an attached storage bus.

**To Reproduce**
Configure an interface to craft items from a processing pattern on the attached machine. (See screenshots below). Have the interface populate itself with the items crafted from its attached machine.

**Expected behavior**
The crafting process will finish and free up the crafting processor for another crafting job.

**Additional context**

![image](https://user-images.githubusercontent.com/45139360/48670241-81716180-eae2-11e8-9d66-1f75e0f17316.png)
![image](https://user-images.githubusercontent.com/45139360/48670249-afef3c80-eae2-11e8-9d2b-1748e55b65ec.png)
![image](https://user-images.githubusercontent.com/45139360/48670251-b54c8700-eae2-11e8-8403-10295fb2b10f.png)

After removing some processors to make the interface initiate a crafting process, it doesn't report the crafted items back:
![image](https://user-images.githubusercontent.com/45139360/48670273-0b212f00-eae3-11e8-97b1-603903560f1d.png)

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: RV6-Stable-3
- Forge Version: 14.23.5.2768

**Comment by yueh** [comment]
Items inside an interface are exported from a network and no longer visible to it. A storage bus can change the visibility, but it still means the item is not returned to the original network starting the crafting. 

Changes in external storage cannot be used to determine, if a crafting step was complete, as regardless of the final or an intermediate product, the crafting CPU cannot determine at that point, if the item is actually accessible. E.g. stored in a read only storage. Therefore it can only process what is returned to the CPU as otherwise it cannot guarantee that the item will still be there once it actually needs it for the next crafting step.

**Comment by MisterInsane** [comment]
As long as the items that you configure in a interface with a crafting card are in a SEPARATE interface that is not attached to the machine used to craft items, this works.

Just FYI for anyone who may stumble upon this.
