### ISSUE TITLE
Item transfer handling gregtech ce tools

### ISSUE THREAD

**Issue by Swabek** [AppliedEnergistics/Applied-Energistics-2#3837]
Tools from GregTech Community Edition not working in crafting terminal with JEI.
They dont get moved with the "Move items" button from JEI.

Please see this [video](https://swabek.de/stuff/github/jei-aeNotMovingTool.mp4).

This should be a bug in the item transfer handler.

- Minecraft Version: 1.12.2
- AE2 Version:  appliedenergistics2-rv6-stable-4
- Forge Version: 14.23.5.2768 
- GregtechCE Version: gregtech-1.12.2-1.0.124
- JEI Version: jei_1.12.2-4.13.1.225

**Comment by yueh** [comment]
That is most likely due to them wanting a very specific version of the tool and any version of the tool. Depending on how they even implemented it, it might not even be a valid item at all.

Your best chance it to suggest they update their recipes to be more open about the accepted inputs.

**Comment by Archengius** [comment]
Wrong, we use simple oredict entries like toolHardHammer for recipes. Issue is not on my side.

**Comment by yueh** [comment]
Except that JEI does not care about oredict entries at all and will just pass an exploded itemstack list to us. Which is based on your oredict registration.

So it simply moves it from being an incorrect recipe to an incorrect oredict entry. E.g. it only registers a very special instance of the hammer. Like only accepting completely undamaged one and only accepting that particular type shown on the video. Otherwise you could see JEI scrolling through alternative hammer variants.
