### ISSUE TITLE
[Meteors] [Mystcraft] Too Many Meteors Spawns 

### ISSUE THREAD

**Issue by 77wisher77** [AppliedEnergistics/Applied-Energistics-2#3845]
When enabling Meteor spawns in other dimensions, the spawns dont seem to follow the config settings

**Describe the bug**

When Meteor spawns were enabled in a mystcraft dimensions, Meteors spawned with EXTREME regularity

**To Reproduce**

Make a few mystcraft ages, ones that are not skylands should work.
If unable to reproduce with random ages I will provide a templated age.

**Expected behavior**

Meteors will dot the landscape

**Additional context**

https://i.imgur.com/mUxfBtc.jpg
https://i.imgur.com/WWf2Deb.jpg

**Environment**
This was tested in single player on the Onion Sage Adventures modpack (development build, after version B-0.2.0.2, my pack, currently making the next version || Version B-0.2.0.2 is available on curse)

**Config**
    I:meteoriteMaximumSpawnHeight=180
    I:minMeteoriteDistance=707
    I:quartzOresClusterAmount=0
    I:quartzOresPerCluster=0
    D:spawnChargedChance=0

- Minecraft Version: 
1.12.2
- AE2 Version: 
rv6-stable-4
- Forge Version:
14.23.5.2772
- Mystcraft Version:
0.13.7.01

**Edit**
Also made and issue on the mystcraft github
https://github.com/XCompWiz/Mystcraft-Issues/issues/328

**Comment by yueh** [comment]
There is a chance to spawn a cluster of meteories each time. The 3 in the back of  the second screenshots for example look like it.

Otherwise I do not have an idea currently. There should be an `AE2/spawndata/` folder inside the save folder for the world. Which should contain something along the line of `dimensionID_X_Y.dat` files for tracking their location. No idea how mystcraft handles the world gen, but something could influence it. But if it should most likely generate some log entries.

Depending on what it actually causes it, there might be no way to fix it currently. We plan to move to a different system with 1.13. But that is not possible now without a chance to break existing worlds. And if Forge does not remove it for some  reasons again.

**Comment by 77wisher77** [comment]
Would you like the .dat files for the worlds which presented the phenomenon?

This happened in multiple different world, clusters seemed to be spawning on the spawn point and more nearby.

**Comment by yueh** [comment]
I do not think we actually have the tools currently to really validate the files. So just the existance of them plus a full server log when creating a completely new dimension might help already.

**Comment by yueh** [comment]
Closing for now as it's too late into the 1.12 lifetime and 1.13/14 should see a new system to handle meteor spawns. Depending on what happens with forge.
