### ISSUE TITLE
Meteor impact compatibility with Cubic Chunks

### ISSUE THREAD

**Issue by Zethalion** [AppliedEnergistics/Applied-Energistics-2#3873]
AE2 is currently not spawning meteorites in a Cubic Chunks overworld. Tests done by @SpaceBuilder2020 led to amazing world generation but also came with great lag on the server. 5 KM high mountains were taken down. Imagine the lag.

In case AE2 detects CC, AE2 should wait until CC is done with light calculation per chunk before it tries to spawn a meteorite. The meteorite should always stick within a few blocks range of a max Y calculated location so it won't beserk an overworld

Please visit https://github.com/OpenCubicChunks/CubicChunks and https://discordapp.com/invite/kMfWg9m

https://cdn.discordapp.com/attachments/508381195336155166/513806384375267338/unknown.png

**Comment by spacebuilder2020** [comment]
To clarify, Cubic Chunks does not call the IWorldGenerator in it's world generation.  The results from the above screenshot were from adding additional code to Cubic World Gen (Custom Cubic) to hook into the IWorldGenerator forge bus.  The reason there are so many meteors is due to the code having the input random seed include the cube y.  This in addition to calling the world generation per cube instead of per chunk resulted in extra meteors.

That said, world generation in Cubic Chunks ideally needs to be done per cube by implementing the ICubicPopulator interface and registering the generator with Cubic Chunks via the CubeGeneratorsRegistry class.   It is important that generation is separated into cubes to reduce the lag and limit generation on one cube prematurely generating an adjacent cube.

Similar to Chunks, Cubes in Cubic Chunks are 16 blocks by 16 blocks in area.  However, their height is also limited to 16 blocks and they are then stacked on each-other.

**Comment by yueh** [comment]
This is most likely not the only incompatibility. There are a couple things, which make the assumption that a minecraft world is never higher than what vanilla allows. E.g. for performance reasons. 

In case of meteors we pretty much have to generate them until the hit the y level and all at once. That is usually fine with vanilla. But with cubic chunks pretty much impossible.

To support it, we pretty much had to rewrite the whole worldgen for it. Like be able to generate them only partial per chunk/etc and so on. Which sadly is just out of scope currently. So for now there won't be any support from us.

Yet in case someone would decide to contribute a better worldgen, we would happily accept it.
It would just have to match the usual requirements, like no hard deps on other mods and not put too much work towards minecraft upgrades.
The best time to include it would probably be the 1.13 migration, as the world gen itself would benefit a lot from features introduced into forge during 1.12. At least if Forge ever makes it to 1.13. So it is probably up to debate, if depending more on forge is a good idea currently. At least some sort of abstraction layer would probably be wise.
