### ISSUE TITLE
Security Terminal destroying parts of the network

### ISSUE THREAD

**Issue by ElectronicManuel** [AppliedEnergistics/Applied-Energistics-2#3891]
**Describe the bug**
I'm playing the [FTB Revelations 2.6.0 pack](https://www.feed-the-beast.com/projects/ftb-revelation/files/2637807) and have an issue with the security terminal. 
Once a security terminal is connected to a network, said network will start losing parts of the network, such as cables, interfaces, terminals, controllers, quantum rings, p2p tunnels, buses and even drives. The issue generally arises upon restarts. This behavior is consistent across every me network on the entire server.

**To Reproduce**
Setup an me network, it might need to span more than one chunk.
Then attach a security terminal.
Restart the server.
Observe how parts of the network disappeared.

**Expected behavior**
There shouldn't be any parts of the network disappearing.

**Additional context**
I know of #3387 but this is not the same issue since AE2Stuff is not in the Revelations modpack.

**Environment**
I'm playing on a multiplayer server running [FTB Revelations 2.6.0](https://www.feed-the-beast.com/projects/ftb-revelation/files/2637807).

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-3
- Forge Version: 14.23.5.2768

**Comment by yueh** [comment]
Chunkloaders are useless here.

It might be an idea to enable `LogSecurityAudits` in the config and post the complete server log when it happened.

**Comment by mindforger** [comment]
oh okay well in the past there were  alot of this kind of issues witrh missing chunkloaders ... sorry :P

**Comment by bookerthegeek** [comment]
Also can you ask the servwr staff if they slow down chunks without players in them and if so what plugin they are using to do so please?

**Comment by chaos234** [comment]
@yueh - Since support for 1.7.10 was dropped I won't open a new bug but what is described in this bug also happens on my 1.7.10 server but not related to server restarts ... it happens every time, when I placed the security station on my main ME system. - Yes, AE2Stuff is installed but no machines are used from them, not even disks.

MC: 1.7.10 - Forge: 1614 - AE2: rev3-beta6 - Maybe it is an issue since that version but was never reported or occoured rarely and is now also "available" in current versions? So if you have time to investigate and find out that this problem described here comes from 1.7.10 times, then please release a hotfix for this version too, thanks.

**Comment by chaos234** [comment]
Direclty closed without any comment?

**Comment by krisjenner** [comment]
This is happening to me on 1.12.2 with AE version rv6-stable-6 (All The Mods 3: Remix) server

**Comment by mindforger** [comment]
then make a new proper and complete issue report and link to this one. It will not get reopened
