### ISSUE TITLE
Destroyed Space Station with Galacticraft

### ISSUE THREAD

**Issue by DhagProGaming** [AppliedEnergistics/Applied-Energistics-2#3898]
When I decided to add the applied energetics mod to my world i loaded in and my space station was gone.

have a world with a space station and then add applied energistics 2. then try and go to your space station

- Minecraft Version: 1.12.2
- AE2 Version: rv6.stable build 6
- Forge Version: 1.12.2-14.23.5.2768

**Comment by yueh** [comment]
Most likely an issue with overlapping dimension ids. Best idea is to restore from a backup. And set the dimension id inside the ae2 config to a free one before trying it again.

Nothing we can do, but it might be an idea to report it to Galacticraft. E.g. to verify, if they check for dimensions not being registered and then stop loading instead of potentially corrupting it.
