### ISSUE TITLE
Server Crash upon using Network Tool on ME network.

### ISSUE THREAD

**Issue by AngelShadow9451** [AppliedEnergistics/Applied-Energistics-2#3925]
I use the most recent version of AE2 and it is on a server i co run, but everytime I go, or anyone else, uses the Network tool, i.e. right click a cable or other ME block, it causes the server to crash.

**To Reproduce**
Use a Network Tool on a network with an auto-craft setup.
**Expected behavior**
Server will crash.

**Additional context**
https://pastebin.com/bAJT5cQe
**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Forge Version: 14.23.5.2808

**Comment by yueh** [comment]
This is most likely caused by some AE2 addon missing a representation when being displayed in the network status.

Currently I cannot say which one it might be. Best approach for now would probably be to make a backup of the save and remove one AE2 addon, start minecraft, and repeat that until the crash stopped. Then report it to whatever addon was removed last.

Otherwise I will look into adding some logging for it in the next release. Technically I could skip it, but resolving it correctly would be better.

**Comment by purpleposeidon** [comment]
Probably the same crash:
https://gist.githubusercontent.com/purpleposeidon/c42f16d22c8c5146c215ba73fdf5dce8/raw/74bce155aef1aa539150a6911e1498d29e0b65e3/gistfile1.txt

**Comment by AngelShadow9451** [comment]
Yea that looks like it.

**Comment by purpleposeidon** [comment]
Spoiler alert
![2019-02-20_19 30 16](https://user-images.githubusercontent.com/150333/53141712-fcb13c00-3545-11e9-846e-9f07ca1bdf33.png)
