### ISSUE TITLE
Activated Void Tear can not be taken out of ME System

### ISSUE THREAD

**Issue by Cazadorsniper** [AppliedEnergistics/Applied-Energistics-2#3927]
**Describe the bug**
Can not remove the Reliquary Void Tear from the ME System manually.
Can remove it with an export bus.
**To Reproduce**
1. Activate Void Tear by shift-rightclick
2. Place activated Tear inside the ME System
3. Try to take it out

**Expected behavior**
I expected to put the void tear in and then take it out the ME System.

**Additional context**
Already reported to Reliquary issue tracker
https://github.com/P3pp3rF1y/Reliquary/issues/364

**Environment**
Reliquary-1.12.2-1.3.4.780
SP

- Minecraft Version: 1.12.2
- AE2 Version: RV6 Stable 6
- Forge Version: 2808

**Comment by yueh** [comment]
There is not really much we can do about it. Forge made it pretty much impossible in 1.12 to reliably address some itemstacks between server and client in certain cases like these ones.

At least not without putting way more load onto the server as sorting and so on cannot be done client side anymore. Which of course also means less features as sorting by name is no longer possible due to the translation not being available server side. Or similar things.

**Comment by etaylor4848** [comment]
If can't easily acquire a second void tear to use in an export bus, you can stick a storage bus onto a chest with a high priority and use the me io port to take the void tear off the storage cell and it'll put it into the chest.
