### ISSUE TITLE
ConcurrentModificationException when startup a Quantum bridges

### ISSUE THREAD

**Issue by Luohuayu** [AppliedEnergistics/Applied-Energistics-2#3928]
https://paste.ubuntu.com/p/cVtnyn7f4h/
Running on CatServer, not Sponge

**Comment by Luohuayu** [comment]
https://paste.ubuntu.com/p/hNT7T8JJfY/
I print stacktrace when remove node

**Comment by KomiMoe** [comment]
Sponge: Excuse me ? the bug is from me ??????
CatServer: emmmm??????

**[yueh](/yueh) ** commented [on 8 Jan](#issuecomment-452031156) :
Asking to try it without sponge is perfectly fine. It could easily be caused by some changes to chunkloading or similar system, which sponge likes to do and some other mod might simply include similar changes because they claimed it should be 5% faster but crashes in return.

It would simply remove some variables and could make it easier. Or at least rule it out as possible cause.

But it appears you are not actually interested in identifying a potential cause as well as reject a simple and quick request. So I do not see any chance to get something useful out of it from discussing it any further.

**Comment by yueh** [comment]
We do not support anything like Sponge or Bukkit officially. Only a standard forge environment.

Should you be able to reproduce it without it, please update the issue accordingly and we will reopen it.
