### ISSUE TITLE
Compact machines support

### ISSUE THREAD

**Issue by DemonfangArun** [AppliedEnergistics/Applied-Energistics-2#3932]
https://github.com/SleepyTrousers/EnderIO/issues/5034
https://github.com/thraaawn/CompactMachines/issues/373

From what I can tell, this falls back onto ae2 to fix. If not, please inform the proper mod dev.

**Comment by Mordenkainen** [comment]
I dont think the grid is changing to capabilities in the near future if ever.

I have been using https://minecraft.curseforge.com/projects/capability-adapter and it solves the issue quite nicely in most cases.

**Comment by DemonfangArun** [comment]
The problem with that mod is that it only allows 8 channels. Additionally, the mod doesn't meet my track record requirements for my pack to ensure it will update in the future.

**Comment by Mordenkainen** [comment]
Technically it supports up to 256 channels 8x32 channels using ME P2P adapters.

As far as your modpack requirements, that is your call.

CM decided to drop support for anything that doesnt use capabilities, and thats fine. But there are things that capabilities does not lend themselves to well, performance being one of them. Since AE performance is an important aspect, capabilities just dont work well here. I would say its not a bug, but a design choice, and one that was made well before the CM change.

**Comment by yueh** [comment]
Caps are simply too limited for our needs, overall offer a pretty poor performance for internal use, and a couple other issues.

We offer an API for other mods to add AE2 support, but that only works when another mod does not refuse to use it. The other option would be an somewhat sophisticated API offered by the other mod, e.g. similar to how IC2 allows easy integration. But as far as I can see compact machines does not even offer a basic one.

**Comment by DemonfangArun** [comment]
Thanks for the inputs. I left a note on the CM ticket that they will need to stop being stubborn, and that in the meantime I have elected to remove the mod as I don't support developers that act the way those ones do.

Thanks for taking the time to explain things, and keep on making AE2 the great storage mod that it is!
