### ISSUE TITLE
Ae2 Chunkloading itself

### ISSUE THREAD

**Issue by 123Kappa** [AppliedEnergistics/Applied-Energistics-2#3957]
Hello ae2 system, seems to be chunkloading itself.  This is killing my server, is there any way to disable it?

**Comment by 123Kappa** [comment]
It is probably the same issue as #1656 . But the link for the fix doesn't work.

**Comment by yueh** [comment]
Please refer the provided issue template, otherwise there is not much we can do about guesses.

**Comment by yueh** [comment]
I would recommend forwarding it to modpack itself. 

The old issues were caused by multiblocks not checking for loaded chunks, which is not the case here. Both contain RF accepting machines, so it could for example also be some other mod monitoring them or injecting their own caps etc. The modpack author should be more aware about potential issues with these.

**Comment by bigenergy** [comment]
+1, i have the same problem

**Comment by 123Kappa** [comment]
I assume you have a po3 server, i talked with the devs and they said it's fixed next update
