### ISSUE TITLE
crafting CPU and repices RE-batteries from IC2

### ISSUE THREAD

**Issue by simchanu29** [AppliedEnergistics/Applied-Energistics-2#3974]
Crafting CPU stay stuck when crafting repices containing RE-Batteries from IC2.

I come from the modpack FTB Ultimate Reloaded (version `1.4.0`). I opened [an issue on their github](https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/165). It seems this is a known bug they can't fix on their part.

**Describe the bug :** Machines crafted with RE-Batteries such as a Generator can't be crafted with the Crafting CPU from Applied Energistics 2. The crafting CPU stay stuck with the RE-Battery shown as available. I did again the pattern several times to be sure I had the right item : each time the pattern was created with a freshly created RE-Battery. Right now it seems i'm not the only one with this [issue](https://www.reddit.com/r/feedthebeast/comments/b2dhci/cannot_get_ae2_autocrafting_to_use_rebatteries_in/).

**To Reproduce**
Use FTB Ultimate Reloaded modpack in version `1.4.0`. Make a basic AE2 setup with a molecular assembler and a crafting CPU. Make a pattern for RE-Batteries and another for the IC2 Generator. Launch a autocrafting of a Generator. The process should be stuck on the crafting of the generator.

**Expected behavior**
The Generator can be autocrafted.

**Additional context**
No crashlog. I could provide screenshots if necessary but I don't have any at the moment.

**Environment**
- Minecraft Version: 1.12.2
- FTB ultimate Reloaded : 1.4.0
- AE2 Version : (from FTB Ultimate Reloaded) rv6.stable6
- IC2 Version : (from FTB Ultimate Reloaded) 2.8.11-ex112
- Forge Version : (not sure where to check that in the modpack)

**Comment by simchanu29** [comment]
**Worksaround** : from the issue from the FTB Ultimate Repository
[https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/165#issuecomment-476454600](https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/165#issuecomment-476454600)

**Comment by yueh** [comment]
The normal process with freshly crafted RE batteries works fine for me.

Charged ones seem to be of an issue, but cannot really tell what the issue is. Other IC2 tools like the cutters work fine.

On the other hand that particular modpack breaks our autocrafting process, so it's up to them to debug it and eliminate that they don't cause it even for the freshly crafted ones.

**Comment by Orygeunik** [comment]
Was released this fix?
Because i have version "appliedenergistics2-rv6-stable-7" on server and this problem haved.


In storage (2 types of re-battery)
![InStorage](https://user-images.githubusercontent.com/6960655/72686422-a4900a80-3b05-11ea-8d0b-03d88af3baa2.png)
In template
![InTemplate](https://user-images.githubusercontent.com/6960655/72686424-a8239180-3b05-11ea-80e2-04b54e07a477.png)
Tried make
![TryMake](https://user-images.githubusercontent.com/6960655/72686426-ab1e8200-3b05-11ea-99b5-3707fcf8ff49.png)

Thanks for reply

**Comment by EnterFor** [comment]
> 当制作包含来自IC2的RE电池的物品时，制作CPU会卡住。
> 
> 我来自modpack FTB Ultimate Reloaded（版本`1.4.0`）。我[在他们的github上](https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/165)打开[了一个问题](https://github.com/FTBTeam/FTB-Ultimate-Reloaded/issues/165)。看来这是一个无法修复的已知错误。
> 
> **描述一下错误：**不能使用Applied Energistics 2的Crafting CPU来制作用RE电池制造的机器，例如，可用的RE-Battery。我再次进行了几次模式确定自己有正确的项目：每次使用新创建的RE电池创建模式时。现在看来，我并不是唯一一个[遇到](https://www.reddit.com/r/feedthebeast/comments/b2dhci/cannot_get_ae2_autocrafting_to_use_rebatteries_in/)这个[问题的人](https://www.reddit.com/r/feedthebeast/comments/b2dhci/cannot_get_ae2_autocrafting_to_use_rebatteries_in/)。
> 
> **复制版本中**
> 使用FTB Ultimate Reloaded modpack `1.4.0`。使用分子组装器和工艺CPU进行基本的AE2设置。制作一个用于RE电池的图案，另一个用于IC2发生器的图案。启动发电机的手工制作。该过程应停留在发电机的设计上。
> 
> **预期行为**
> 发电机可以手工制作。
> 
> **其他上下文**
> 没有崩溃日志。如果需要，我可以提供屏幕截图，但目前没有任何截图。
> 
> **环境**
> 
> * 我的世界版本：1.12.2
> * FTB Ultimate重装版：1.4.0
> * AE2版本：（从FTB Ultimate重新加载）rv6.stable6
> * IC2版本：（从FTB Ultimate重新加载）2.8.11-ex112
> * 伪造版本：（不确定在modpack中的哪个地方检查）

There is actually a solution that USES the following Mod version without this error
Industrialcraft -2-2.8.164-ex112
appliedenergy istics2-rv6-stable-7
