### ISSUE TITLE
[Idea] Gas Support

### ISSUE THREAD

**Issue by MineTech123** [AppliedEnergistics/Applied-Energistics-2#3988]
Add mekanisim gas support

**Comment by mindforger** [comment]
Isn't gas a liquid in the mechanics of MC anymore?!

**Comment by 34486** [comment]
It has mekanism gas support I beleive... well, partly. I don't see my tritium and deuterium in the gas terminal but i can import and export it.

**Comment by yueh** [comment]
Forge Fluids are designed to also work with gaseous variants and mekanism could simply use it.

Otherwise there won't be any support for it as it is not a part of Forge itself or it is used ubiquitously similar to RF. But currently it is only used by mekanism and pretty much nothing else. And the fork due to mekanism being inactive for nearly a year is at least considering switching to normal fluids and just work.
