### ISSUE TITLE
Game crash when moving energy cell with piston

### ISSUE THREAD

**Issue by PlasmaMatrix** [AppliedEnergistics/Applied-Energistics-2#3990]
Game crash from piston attempting to move an energy cell

The description is "Exception ticking world" and that is a repeated thing, not a one-time event.

Place a piston (any type will do as long as it is vanilla) with the head facing an energy cell. Then, activate the piston.
The piston should have moved the cell, but instead crashed the game. 

full crash report: https://pastebin.com/LTkEBbW0

a mod that may be causing the problem is Redstone++ but I am not sure.

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2780

**Comment by leagris** [comment]
Energy cells are tile-entities. Piston are not supposed to move tile-entities.
Your crash is caused by `sandro.RedstonePlusPlus.Modules.PistonFix.BlockPistonBaseFix` a mod that hack pistons to move tile-entities. 

See: https://www.curseforge.com/minecraft/mc-mods/redstoneplusplus
> ##### Improved Pistons and Sticky Pistons
>
>    Can now push TileEntities (Chests, Hoppers, Droppers, Dispensers, ect.)
>    Config option to change the Push Limit (Default: 12)

Maybe report issue here: https://minecraft.curseforge.com/projects/redstoneplusplus/issues
or find way to blacklist AE2 tiles from this mod.

Not AE2's fault.
