### ISSUE TITLE
Light Gray Dye can't be added to the Colour Applicator

### ISSUE THREAD

**Issue by sam-kirby** [AppliedEnergistics/Applied-Energistics-2#3992]
**Describe the bug**

Light Gray Dye cannot be inserted into the colour applicator - this is due to it looking for an item in the 'dyeSilver' ore dictionary, which does not exist without another mod/CraftTweaker script creating it. Forge creates 'dyeLightGray'.

**To Reproduce**

Place an ME Chest, put a Color Applicator in the cell slot and attempt to insert Light Gray Dye.

**Expected behavior**

Light gray dye should be accepted by the colour applicator.

**Additional context**

**Environment**

Tested in minimal environment with JEI, AE2 and Forge. Happens in SP and MP.

- Minecraft Version: 
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2825

**Comment by AzazeII** [comment]
Do you trying to insert the regular dye in color applicator? Or you mean dye ball?

**Comment by sk2048** [comment]
Regular dye, all other colours of dye can be inserted and used as ammo for the color applicator.

Light Gray is the odd one out due to the mod accepting only entries from the dyeSilver oredictionary which is not created by Forge or Applied Energistics itself.

https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/rv6-1.12/src/main/java/appeng/items/tools/powered/ToolColorApplicator.java#L91-L98

**Comment by yueh** [comment]
No idea how to deal with it really. We rely on the vanilla dye names to match their corresponding oredict entry. Mostly to avoid Mojang/Forge from renaming them somehow (e.g. gray to grey or similar).

It is also not the chat colors but explicitly dye colors, which are used by normal blocks like carpets, glass, etc.. So to some degree it could be considered a Forge bug for not providing the correct oredict entry for this particular dye variant.

**Comment by Carnaxus** [comment]
Maybe add dyeLightGray to the list of stuff the applicator can accept, without removing dyeSilver?  I'm not a modder/coder, I don't know how hard that would be or if it'd even work, but since AE2 literally doesn't function without Forge, it probably wouldn't cause a crash unless Forge changes it (pfft).

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
