### ISSUE TITLE
Preformance issues and error removing ic2 ingots

### ISSUE THREAD

**Issue by Hexton** [AppliedEnergistics/Applied-Energistics-2#4005]
Server having preformance issues and repeated error 
#### Description
My server has had major preformance issues and i have gotten the following message constantly. 

[12:31:35] [Server thread/WARN] [AE2:S]: Removing item {Craft:0b,**Cnt:21216L**,id:"ic2:ingot",Count:1b,**Damage:6s**,Req:0L} from storage cell because the associated item type couldn't be found.

The numbers in bold have changed but not completely randomly as they switch from a couple of diffrent numbers. 
I have tried running the server overnight to see if it was just a matter of time but it doesn't seem like it is.

#### Environment
I am running a Tekxit 3 server on version 0.88

- Minecraft Version: 1.12.2
- AE2 Version: latest?
- Forge Version: forge-1.12.2-14.23.5.2824-universal

**Comment by yueh** [comment]
This log entry just reports, that a cell contains an item, which no longer exists.

Having it constantly repeat very likely points to something else constantly reloading chunks, without persisting the changed cells again. To resolve it, you should identify, what is causing these chunk reloads.

Otherwise we cannot really do anything about performance issues without an actual profiling/sampling dump.
