### ISSUE TITLE
Quantum Bridge resets after Server restart

### ISSUE THREAD

**Issue by X1machinemaker1X** [AppliedEnergistics/Applied-Energistics-2#4017]
**Describe the bug**
Every time the server I play on restarts whether it be a scheduled restart or a crash or whatever, I have to reset the quantum bridge.

**To Reproduce**
The server we play on is running the Project Ozone 3 Pack for 1.12.2. I created a network bridge between the Overworld and the SimpleVoidDimension.

To "reset" the bridge, all I have to do is break all the ME Cables attached to the network bridge in the SimpleVoidDimension and then immediately following breaking the last cable attached to the bridge, it reactivates and I can place them back.

**Expected behavior**
Well I would like the bridge to not require attention once its setup and has constant power.

**Environment**
Its a multiplayer server running Project Ozone 3: A New Way Forward

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable=6
- Forge Version: 14.23.5.2808

**Comment by mindforger** [comment]
Do you have a chunkloader installed -> if yes is it from chinkenchunks -> if yes, use a spotloader in top of the chunk where the chunkloader is, because they behave funky on restarts and spotloaders fix this

Second possible issue, did you install enough energy cells everywhere, to properly load, the bridge needs some energy to build the connection ... Please be advised that me system power input has a limit that is internal capacity/tick and energy cells provide just that 

Third possoble issue, you are using some modified server like sponge which has unpredictable behaviour which Can not be helped unfortunately

**Comment by X1machinemaker1X** [comment]
Sounds like the first point is my issue. I use chickenchunk chunk loaders. As for the second point, yes. I have a dimensional transceiver moving energy between locations and there is an energy cell buffer that feeds into an energy acceptor that powers the bridge on the other side.

And for the 3rd point, I’m on a private project ozone 3 server.

**Comment by mindforger** [comment]
>energy cell buffer that feeds into an energy acceptor

i think you misunderstood, i was speaking of ae2 (dense) energycells, feeding external energycells as power into an acceptor will be limited by the capacity of the local network while booting, the energycells from ae2 provide more internal storage to allow more inmput per tick

**Comment by X1machinemaker1X** [comment]
I feel like I could accomplish they same thing with any energy storage block sending energy thru an acceptor into the bridge. Maybe I am misunderstanding...

**Comment by mindforger** [comment]
The server is on average calculating 20 operations a second which we call each a tick. If your system is big and enough things are moved, your system can run out of power because it can only take in as much power in a single tick as there is space inside the system. 

Think of a car, it can transport as much stuff as you want consuming more and more fuel, but if there ist only one station per mile it might run out of gas, so you need a bigger tank
