### ISSUE TITLE
how can I get infinite ae2 channels?

### ISSUE THREAD

**Issue by Rafaelutzul** [AppliedEnergistics/Applied-Energistics-2#4018]
is there any way to change the limit of the dense cables from 32 to any number? i already tried changing the config file of the channel to false but if i do that it just bugs my world and controllers and all cables and some more things dissapear from the world and some ae2 items in my inventory are named as "Disabled item"

**Comment by Ommina** [comment]
Short answer: no.

Just disable the channels.  Controllers, dense, and smart cables are only useful in the context of showing channel details.  Since they are pretty much superfluous in a channel-free world, they can be safely removed.

This can be tricky if you are changing after you have already started the world, I admit.  If you want to mitigate the transition, replace your existing cable with the base version (not smart, not dense) before you change the config.

**Comment by mindforger** [comment]
Disabling channels only removes items, you may encounter broken recipes due to unobtainable items, keep this in mind ...
