### ISSUE TITLE
Question about spawndata folder in world/AE2/

### ISSUE THREAD

**Issue by Trnrr** [AppliedEnergistics/Applied-Energistics-2#4045]
I found a question relating to this in #1445 but I have one more.

Do these files ever change once generated?

I pregenerate my world and my survival world is completely generated atm. I have around 20k files in `world\AE2\spawndata` and am curious if they ever change. Since it takes ages to back them up, if they don't change I will just skip that folder when I back up my world. That way I don't have to backup 20k files every time I do a server backup.

**Comment by yueh** [comment]
They can change until the corresponding region file is fully explored. But they are also required to let AE2 behave correctly, otherwise they wouldn't exist. And probably when some debug tools are used.

But your backup should really take unchanged files into account and produce an incremental one based on the previous backups to reduce the size by skipping them.
