### ISSUE TITLE
Autocraft incompatibility with cracttweaker recipe with Item giveBack

### ISSUE THREAD

**Issue by Fireztonez** [AppliedEnergistics/Applied-Energistics-2#4047]
**Describe the bug**
In the modpack I currently working on, I add somes recipes using Craftweaker, and all my custom recipes with a giveBack, transformDamage, transformNew, reuse or transformReplace simply consumed the item without giving back anything, when using the Applied Energistics Autocraft. 
All my recipes work's great when craft normally in the crafting therminal or using a regular crafting table. So, currently, this work only if the recipes is pre-register transformDamage or giveBack recipes, but not with all the one added with crafttweaker.

I have test in a really small pack with only Crafttweaker, JEI, Applied Enegistics 2, and the issue still appen, so this is not a caused by any AE2 extension mod, this is clearly a problem with AE2 directly...

**To Reproduce**
1- Install Applied Enegergics and Crafttweaker in the pack
2- Create a simple script using a transformDamage or giveBack
3- Start the pack and create a pattern with that recipe.
4- Start the craft and enjoy all the items lost!!

**Expected behavior**
Should give back all items, like it does with pre-registered recipes...

**Additional context**
Here my simple test script for my small test pack...
https://hastebin.com/zebaqupuqa.css

**Environment**
I have test all that into a creative test world in singleplayer, but the issue have been report by one of the beta tester for my modpack running into a server, so it appen in both, single player or multiplayer (on server)... Let me know if you need more information.

- Minecraft Version: 
- AE2 Version: 1.12.2 - rv6-stable-6
- Forge Version: 14.23.5.2838
- CraftTweaker2: 4.1.18

**Comment by yueh** [comment]
Basically CT approach is slightly hacky and spawns the item directly into the player inventory at some point. Naturally auto crafting implies there is no player doing it, therefore there is also nothing to spawn it into.

Further we use an optimized approach for autocrafting, otherwise it would be a major performance issues considering how badly crafting is implemented with forge when taking the crafting volumes AE2 usually creates into account.

Vanilla already provides a way to achieve reusable items with container items. E.g. buckets or other tools. This is fully supported by and a slightly saner approach, but still way more cpu intensive than normal recipes. E.g. it can change the initial calculation to take a couple seconds or even minutes instead of being virtually instantaneous.

**Comment by Fireztonez** [comment]
Ok Yueh,
I just open an issue with a link here about that into the Crafttweaker Issue Tracker... I hope this issue can be fixed, because, CraftTweaker is in pretty mutch all modpacks, so I think this can probably be fixed by some way without too mutch performance issue, and personnally I think this is a big issue how should be fixed if possible...

But, I totally understand and agree with you, a solutions  how increase soo mutch  calculation time or is too heavy for the CPU, is not really good...

**Comment by Fireztonez** [comment]
@yueh Can you look and reply into the CraftTweaker Issue, the CraftTweaker developpers have send somes messages about that issue, and there have probably a way to fix that issue without being soo mutch CPU intensive...
