### ISSUE TITLE
Cannot ignite Tiny TNT with Fire

### ISSUE THREAD

**Issue by ADDSynth** [AppliedEnergistics/Applied-Energistics-2#4048]
#### Description
Hey I'm using the latest version of Applied Energistics which is rv6-Stable-6.
Tiny TNT does not ignite when using the Flint & Steel or Fire Charge. I managed to activate it with a redstone signal however. 
If this is intentional behavior then please update [https://ae-mod.info/Tiny-TNT/](url)

Both Fire and a redstone signal will activate vanilla TNT but fire does not ignite Tiny TNT.

Forge version: 14.23.5.2831    for Minecraft 1.12.2

**Comment by MonoToast** [comment]
are you in a claimed area?

**Comment by ADDSynth** [comment]
like what do you mean? I don't think so. I tested this on a brand new single player world.

**Comment by yueh** [comment]
To be honest, I have absolutely no recollection about them reacting to flint&steel or not...

They are mostly designed as a less invasive option to vanilla TNT, so having them explode through random effects like nearby explosion is not really intentional. Probably have to grab some old 1.7 version to look at the behaviour at some point.

**Comment by lukas2005** [comment]
I remember them being activated by flint&steel as early as 1.5.2

**Comment by Dr-Turtle** [comment]
The Tiny TNT can be activated with a redstone signal, I have tried this with flint and steel and can confirm that it does not currently work, I am unsure if this is intended.

**Comment by yueh** [comment]
Should be fixed for 1.15
