### ISSUE TITLE
Filled Clay Buckets from Ceramics cannot be removed from ME system

### ISSUE THREAD

**Issue by katubug** [AppliedEnergistics/Applied-Energistics-2#4058]
**Describe the bug**
A player reported to me that they couldn't retrieve a Clay Water Bucket from their ME system. I tested this and can replicate. I can neither remove the Clay Water Bucket, nor the Clay Hot Spring Water Bucket from my ME system. Empty and Unfired Buckets do not seem to be affected.

I am reporting this issue to the author of Ceramics as well.

**To Reproduce**
- Place a filled clay bucket inside an ME system via terminal
- Attempt to retrieve clay bucket from ME system via terminal

**Expected behavior**
I expect the bucket to be pulled from the ME inventory and placeable within player inventory. However, clicking on the bucket does not do anything. Shift+Click does not work, either.

**Additional context**
Difficult to screenshot.

**Environment**
We are running a multiplayer server. I have not tested this in singleplayer.

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6
- Ceramics Version: Ceramics-1.12-1.3.7
- Forge Version: forge-1.12.2-14.23.5.2838-universal

**Comment by katubug** [comment]
Per this issue, the mod author of Ceramics says it doesn't arise from them: https://github.com/KnightMiner/Ceramics/issues/50

And per this issue, the author of Astral Sorcery says that it is not theirs either: https://github.com/HellFirePvP/AstralSorcery/issues/1118

**Comment by yueh** [comment]
In case Astral Sorcery really adds random NBT data to itemstacks, this would explain the issues. Especially if these are not perfectly synchronized between server and client and for every existing itemstacks (even temporary ones used internally)

For us they would be considered completely different items, simply due to the fact that some mods use this approach to distinguish between completely different items. Or at least different variants of the same item. I doubt anyone would find it particularly useful when clicking on an copper ingot, that the system returns them a machine from the same mod. Or even something like clicking a fully charged battery but getting only a uncharged one.

Usually this would also cause issues with other mods. Like items no longer stacking, recipes not working.

**Comment by meiskam** [comment]
Still seeing the issue with AE rv6-stable-6, ceramics 1.12-1.3.7, and forge 14.23.5.2836

I was able to pull out 3 of the affected buckets with a ME Interface, here is the NBT data associated with them (found with /crafttweaker hand): 

> <ceramics:clay_bucket:0>.withTag({fluids: {FluidName: "if.protein", Amount: 1000}})
> <ceramics:clay_bucket:0>.withTag({fluids: {FluidName: "water", Amount: 1000}})
> <ceramics:clay_bucket:0>.withTag({fluids: {FluidName: "lava", Amount: 1000}})

https://i.imgur.com/MoStfIw.png
