### ISSUE TITLE
Fluid Autocrafting ideas

### ISSUE THREAD

**Issue by frizzle101101** [AppliedEnergistics/Applied-Energistics-2#4072]
Fluid Autocrafting ideas seem to have been lost with time but im interested to see if anyone else is interested in it

**Describe the feature**
It would be really nice if i culd specifiy how many mB of molten iron it takes to make an ingot with an integrated fluid autocrafting system that allows fluid patterns with the normal pattern system that can specify not only liquid to items but items to liquid. It would be nice because rn you have to autofill a bucket to get the autocrafting system to see that 1000mB of whatever just entered the system. then you have to try to scale everything to the B so like 1B of molten somthing is like 6.9444 ingots and how annoying is that with excess liquids getting acumulated.

With a item to fluid pattern it would be nice to have fluid integration in the terminal maybe an advanced terminal of somthing that has the fluids in one tab and items in another combining both terminals making it easier for the wireless terminals to be developed but in the fluid terminal the craft fluid would show up where you can specify in mB how much you want and it will just do like it does with items and the interfaces and give you the specified amount or above depending on processing. so item goes in and the autocrafting system can detect the min mB coming in of processed liquid.

With fluid to item its simple when an item is requested the fluid interface which has patterns in it will output the fluid to one of its internal buffers, i think it shld be 1 pattern to internal fluid buffer in the fluid interface, maybe there would be reasons for more?

**Reasons why it should be considered**
I believe the fluid system is sorta useless in ae2 as it is and I feel the whole point of having fluids in the system is to autocraft with them wether that be liquid to item or item to liquid or just using 1B of something in a crafting recipe

**Additional Context**
I want to make ae2 a smart middle man in auto crafting for tinkers construct using the infrastructure that is already here for the aloy mixing and creating fluids with request of the aae2 autocrafting system

**Comment by lukas2005** [comment]
Yeah I think it would be great if the fluid interfaces were anything like the regular ones (eg. You can have a crafting recipe with a fluid + items) extra cells kinda addresses this problem with their fluid crafting but it only works with crafting recipes not stuff like fluid transposers or thinkers construct

**Comment by frizzle101101** [comment]
There culd also be fluid to fluid patters to support tinkers metlorgy and mixing

**Comment by Famous5000** [comment]
Something like what RefinedStorage can do? Because I'd totally be down for that if that were the case.

**Comment by dupontct** [comment]
From a gameplay perspective (not a coding perspective I don't know if any of the following ideas are feasible to put into code) I have several comments

It would be nice if there was only 1 interface, export bus, import bus, ... that could handle all of the stack types (eg, item, fluid and custom types) instead of there being separate interfaces, export buses, import buses, ... for each stack type.  (I am not saying to combine interface, export bus, import bus, ... into a single super omni-block)

For processing patterns the ability to mix and match stack types such that you could automate something that requires a specific amount of liquid in addition to other item components.  The different types don't have to be in the same pattern provided you could somehow link two or more patterns together, so they would both be activated when the ae system was asked to craft the result.

For recipe patterns the ability to specify bucket amount of a liquid in place of a item bucket of the liquid would make liquid storage much more useful.

**Comment by yueh** [comment]
Fluid crafting is simply not worth the effort. Pretty much no mod uses it on a higher level besides a mechanic to prevent a player from easily taking some output from a machine and putting it into another manually, but ultimately it's just a more complex way of turning item A into item B.

Also it is a major hassle in terms of UX. It is not possible to handle directly like normal item stacks. E.g. for easy splitting and so on. Recipes scale from a few mB required to several Buckets, which either needs clicking a few thousand times or some approaches like using many different modifier keys to easily scale to increase/decrease by 1/10/100/1000/10000 on top of not being able to actually populate the pattern without the help of some container like a bucket. Which in return means you can no longer craft a bucket of X, because the system considers it as fluid and not item anymore. (Or any other fluid container). Or it needs another key to flip between item and fluid mode. And the next step would be to also support other types like thaumcraft stuff and so on.

And that is not even thinking about having to rewrite everything, because we no longer can assume that a machine accepts every type from a single side. If item and fluid inputs/outputs are on different sides, it's a massive effort to correctly distribute the items/fluids across multiple interface while using a single crafting task.

If there is time for it, we might rework the internal crafting code to support generic stacks, but the heavy lifting like new patterns/interfaces will most likely be left to whatever addon might decide to pick it up.

**Comment by exzhawk** [comment]
Well, I just can't bear lack of fluid in autocrafting with GT. Wrote this mod to deal with some situations. Hope it helps. https://www.curseforge.com/minecraft/mc-mods/volumetric-flask
Sorry to bother you

**Comment by frizzle101101** [comment]
U da bomb dude told u guys it was needed lol

**Comment by asd0210a** [comment]
Put a tank near machine like mekanism support bucket output
pattern with fluid bucket , use item pipe from other mod or Storage Bus (always need sub-network), export bucket in tank,then output empty bucket in network.

**Comment by frizzle101101** [comment]
I have begun work on this over on my fork if anyone is interested in helping I could use some help from ppl who know the system https://github.com/frizzle101101/Applied-Energistics-2/commit/4a486b1abe5a5b6e4503dde3fdf7296fadae4cdb
