### ISSUE TITLE
Textures seem to be broken.

### ISSUE THREAD

**Issue by DragonmasterDJ** [AppliedEnergistics/Applied-Energistics-2#4077]
**Describe the bug**
Textures from the mod seem to be broken, such as the me controller appearing semi-invisible when power, drives not lighting up when connected to the system, etc. 

**To Reproduce**
just place down the blocks, 

**Expected behavior**
The textures to render properly.

**Additional context**
![2019-06-30_14 18 37](https://user-images.githubusercontent.com/29170640/60392236-f52c2000-9b41-11e9-9b1e-ad7ceec5042c.png)
![2019-06-30_14 18 34](https://user-images.githubusercontent.com/29170640/60392237-f5c4b680-9b41-11e9-8769-1059c55b930b.png)

**Environment**
Other mods relating to Ae2

- Ae2 Stuff
- Extra Cells
- Wireless Crafting Terminal 2

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-6.jar
- Forge Version: forge-14.23.5.2838

**Comment by Ommina** [comment]
"Other mods relating to AE2" is a good start.  Are there other mods related to rendering?  Coremods that affect rendering?  Resource packs?

At the end of the day, if there were something fundamentally wrong with the model rendering in AE2, we would have heard about it, extensively, months ago.   As such, the effect you are seeing is almost certainly the result of an unknown factor, listed or otherwise, in your particular pack.

**Comment by yueh** [comment]
Do not use things like optifine or similar, they will break rendering in modded with a quite high chance.

**Comment by XevianLight** [comment]
I’m having this exact same problem, and the “don’t use optifine” doesnt help me because I’m not using optifine. The issue was even closed before he got an answer that fixed the problem!
