### ISSUE TITLE
Dense smart cables render incorrectly (junctions should not be there)

### ISSUE THREAD

**Issue by hubertnnn** [AppliedEnergistics/Applied-Energistics-2#4089]
Dense smart cables render as a junction in a few situations that they should not.

**Describe the bug**
![dense_smart](https://user-images.githubusercontent.com/1189576/60770752-ccc29980-a0de-11e9-9e1f-2740b749fadf.png)

As shown on the image above, I have 3 strait lines using a mix of covered dense and smart dense cables.
In all 3 cases there are no cables behind, just the strait line.
Order of cables in each line:
1. covered, smart, smart, covered
2. covered, smart, covered, controller
3. covered, covered, smart, controller

Only second case renders correctly, 
If a smart cable touches another smart cable it renders as junction.
If a smart cable touches controller it renders as junction.

**Expected behavior**
All 3 cases should render without junctions.

**Environment**
- Minecraft Version: 1.12.2 SP
- AE2 Version: rv6-stable-6
- Forge Version: 14.23.5.2838
- Modpack: Omnifactory 1.2.1 with channels enabled as only config change

**Comment by yueh** [comment]
The actual bug is rendering a smart connection towards the dense covered cable, this should be a covered one. As well as rendering the dense smart between two covered ones as cable core.

We did change the cable rendering to always render a core when changing the type with downgrading the connection between both to the lower one. E.g. connection between a smart cable and covered cable will be rendered as completely covered and not one half smart and the other one covered.
