### ISSUE TITLE
my me system is shuting down with plenty of power and power storage

### ISSUE THREAD

**Issue by hacker104** [AppliedEnergistics/Applied-Energistics-2#4109]
Description
my me system is shuting down with plenty of power and power storage pls help me

#### Environment
https://youtu.be/Q_Cz76sdTrk
- Minecraft Version: 1.10.2
- AE2 Version: 2-rv4-stable
- Forge Version: 12.18.3.2511

**Comment by mindforger** [comment]
from the look at the video i see no appearant issue (real energy cells and quite a few, 4kRF seems a bit heavy, are thos dense energy cells by the way?)  but 1.10.2 is not supoported anymore i suppose, but let's have some of the actual dev have a comment on that

please try to chunkload every last part of the network because unloading distant chunks trigger reboots and with that size they become longer and longer

**Comment by hacker104** [comment]
the energycells are dense energycells and it is chunk loaded

**Comment by samuraijack120** [comment]
I have a similar problem with rv5-stable-11 with minecraft 1.12

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.12 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.
