### ISSUE TITLE
Applied Energetics 2 Crashing

### ISSUE THREAD

**Issue by OrenJinx** [AppliedEnergistics/Applied-Energistics-2#4132]
Hello, I am currently having an issue with Ae2 that is completely breaking my server. I don't know what to try to get this fixed all I know is /fml confirm is not working. please if anyone could help it would be very much appreciated. I have even tried deleting the mod and it wont start with it in or out now. 

https://pastebin.com/CeuVeg7f

**Comment by Pingger** [comment]
Can we please get the full crashreport (including the FULL stacktrace not only the second half).
We need the other information to make sense from the part in the pastebin.

**Comment by OrenJinx** [comment]
https://pastebin.com/5jix0S6p sorry

**Comment by Pingger** [comment]
According to the crashlog "Quark" is at fault here. Which might be failing because you are using a **sponge** server which is incompatible with both QUARK, EnderIO, magenticraft and at last AE2

`[58] 25.08 08:20:20 [Server] main/INFO ============= Please report this to Quark! =============`

Which caused cascading exceptions for several mods inlucding EnderIO and magenticraft, but also for the server itsself.
