### ISSUE TITLE
Crafting Storage drops items on the ground.

### ISSUE THREAD

**Issue by SuperKosi** [AppliedEnergistics/Applied-Energistics-2#4139]
**Describe the bug**
Everytime we start a new job via Applied Energistics Auto Crafting our 64k crafting storages drop all requiered items on the ground. 

**To Reproduce**
I actually cannot say how to reproduce it. We have several ME networks on our server, all are equally set up, and on every network except this one it works fine.

**Environment**
- Minecraft Version: 1.7.10 (Feed the Beast infinity Evolved 3.0.2)
- AE2 Version: 1.7.2

**Comment by mindforger** [comment]
unfortunately 1.7.10 is no supported anymore

but make sure you keep the network chunkloaded, crafting cluster that cross chunk borders may be temporarily deconstructed droping all stored items when one of the chunks gets unloaded!

also make sure to use proper chunkloaders, i can tell from my own experience that the chicken chunks chunkloaders do not work well on dimension loading or after server restarts, setting up an spotloader on top of the chunkloader fixes this issue or use MFR chunkloaders, they work well too

also just as a side node, always attach a few AE2 Energycells to each network, because input of a network is limited by it's capacity/tick
