### ISSUE TITLE
Cannot place wheat into Grindstone

### ISSUE THREAD

**Issue by iJoeyMonster** [AppliedEnergistics/Applied-Energistics-2#4148]
I'm unable to place vanilla minecraft Wheat into the Quartz Grindstone.
**Describe the bug**

" "
**To Reproduce**

Made a Quartz Grindstone. Placed it down. Cannot Shift+click or manually place Wheat into the machine. 
**Expected behavior**

Be able to place Wheat into the Quartz Grindstone to make Flour for bread.
**Additional context**
N/A
N/A
N/A

**Environment**
At my home. 
N/A

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 1.12.2-14.23.5.2844

**Comment by yueh** [comment]
Most likely your modpack disabled the recipe for some reason.

**Comment by iJoeyMonster** [comment]
I'm not using a modpack.

**Comment by mindforger** [comment]
do you use any other mods? maybe some other mod hooked that recipe or the ore dict entry.

**Comment by tenrousei** [comment]
Hey just because i found one of the causes if you have this issue you have probably installed Pam''s Harvest Craft
I fixed this by setting wheat as eadible item as "false"

You'll find it in the modded minecraft folder config/harvestcraft.cfg

This section need to be set like this:
`"food items" {
    # Enables Wheat as an edible item [default: true]
    B:makeWheatEdible=false
}`
