### ISSUE TITLE
Generator not crafting

### ISSUE THREAD

**Issue by gerasimus95** [AppliedEnergistics/Applied-Energistics-2#4184]
Put ic2 generator in auto craft, accumulators, furnaces corpuses had been crafted, but the generator not crafting.
![Adventure-Time_80--1920x1080](https://user-images.githubusercontent.com/57034056/67617976-91bdb080-f80a-11e9-81f1-8ae637d7e801.jpg)
![Adventure-Time_48--1920x1080](https://user-images.githubusercontent.com/57034056/67617977-91bdb080-f80a-11e9-805e-acf1d1762d77.jpg)

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2_rv6_stable_4
- Forge Version:14.23.5.2838

**Comment by sagesse-cn** [comment]
I have also encountered this problem. If allow substitutions, the synthesis cannot be started directly, I guess it may be caused by the durability of the re-battery?
<img width="1366" alt="image" src="https://user-images.githubusercontent.com/6903353/67629302-a05da380-f8ae-11e9-9dc8-dc2ea39def43.png">

**Comment by yueh** [comment]
Please report all autocrafting related bugs directly to your modpack as most are using addons which intentionally break it.

**Comment by Rameron** [comment]
@sagesse-cn I cloned your branch and successfully compiled ae2 build from your sources, but this bug remained :(
