### ISSUE TITLE
Errors in the console

### ISSUE THREAD

**Issue by Kennar** [AppliedEnergistics/Applied-Energistics-2#4218]
When starting the server, the following errors appear every time: https://hastebin.com/xesojaropi.rb

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7
- Forge Version: 1.12.2-2847

**Comment by clienthax** [comment]
Your log is blank, use gist.github.com

**Comment by Kennar** [comment]
https://pastebin.com/Tbtm2ifn

**Comment by Kennar** [comment]
and https://pastebin.com/hfXPCPGp

**Comment by yueh** [comment]
That is simply how forge reacts to missing items. At least it just prints warnings to the log and does not actually hard crash. Which will most likely happen once we actually start and try to disable certain achievements/recipes/etc depending what items are disabled. If that is even feasible due to the absurd amount of different config options.
