### ISSUE TITLE
possible performance issue with isValidItemForSlot()

### ISSUE THREAD

**Issue by runescapejon** [AppliedEnergistics/Applied-Energistics-2#4279]
**Describe the bug**

So, I'd been experiencing performance issues and seem it's coming from AE2, i have no idea how to attempt to fix these issues it  any advice greatly appreciated thank you.

https://gyazo.com/2b394cc145048c40a6f63b6425426c06
https://gyazo.com/571e8ed667da0bc696a1caef52f4d430
**To Reproduce**

I don't know how to reproduce...
**Expected behavior**

A way to make a temporary fix or an fix to these lag issues
**Additional context**

https://sparkprofiler.github.io/#c7enpB2ihU
**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 4.23.5.2847

**Comment by runescapejon** [comment]
this may be related to this but i am unsure...
https://pastebin.com/raw/qdukDR5B

**Comment by yueh** [comment]
Ultimately it is caused by how badly forge handles recipes/crafting once it is used faster than a vanilla workbench.

AE2 pretty much caches recipes as much as possible (within sane limits), but we still have to hit the Forge part as fallback as otherwise crafting would not work at all. For this reason, we log the offending recipes, so a player/admin is able to identify it to some degree and try to resolve it themselves.

**Comment by runescapejon** [comment]
Is there a way to better log the offending recipes? for example putting cords or what player that is doing this. Cause it's very hard on bigger servers to identify where is the ae2 machines that is producing these recipes.

Also, how would I resolve the offending recipe that is causing these issues?
Thank you

**Comment by yueh** [comment]
No, not really. The crafting process is not aware of which interfaces/assemblers are responsible at this point.

It mostly comes down to teaching players to not do stupid things.
1.13 and later technically offer a huge improvement for it, when just looking at vanilla crafting recipes. But Forge will probably do whatever they can to keep the current behaviour including all performance issues.
