### ISSUE TITLE
Real Filing Cabinets and AE2 inventory interaction

### ISSUE THREAD

**Issue by Rithenar** [AppliedEnergistics/Applied-Energistics-2#4290]
**Describe the bug**

I am not sure whether this is an AE2 or RFC issue so I am posting it in both pages.  If I remove all the content of a folder via AE2 (crafting or direct request) and then pu the items back in the system, the items will not go back to the filing cabinet even though they are prioritized on the Bus.

For example I have 120 iron ingots in a folder in a cabinet connected to AE2 with a Storage Bus with a 100 priority. I take all the items out of the system manually leaving the folder empty. I put the ingots back in the system and they get stored in a disk drive instead of the cabinet.

If I have at least 1 item left in the folder, however, the items will route properly. Unfortunately AE2 will pull all items out when requested.

**To Reproduce**

* Place a filing cabinet with a folder with some items in it
* Take out the items via crafting terminal
* Ensure the filing folder is empty but still remembers the configuration of the item
* Put items back into AE2 through the terminal'
* The items route to a disk drive instead of the folder
* Repeat the process but leaving one item in the folder. When putting the items back in they will route as expected to the folder
**Expected behavior**

AE2 to respect the channel priority and place the items in the pre-assigned storage regardless of the current content of such storage

**Additional context**

**Environment**

- Minecraft Version:  1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 14.23.5.2847
- Real Filing Cabinets Version: 0.2.0.20
- AE2 Wireless Terminals Version: 1.0.34

**Comment by yueh** [comment]
I have no idea how their cabinets really work. The easiest option is probably to replace them with normal chests to check if it is caused by AE2. But I would mostly doubt it. Just keep in mind, that it can still pick another location with the same priority.

Currently I would guess it is caused by the cabinets itself. Their code is not that straightforward to scan over it and understand it mostly. Yet it looks like it only accepts items which are already stored. So removing all iron ingots will prevent it from inserting them again through other machines. Especially as it also has a different code path for manual interaction

**Comment by Rithenar** [comment]
Yeah, I tried it with other storage methods and worked as expected. I did go back to the cabinets (because this modpack doesn't have drawers or barrels) and it seems to have fixed itself. !?  Thank you for responding though!
