### ISSUE TITLE
Cannot get AE2 to work

### ISSUE THREAD

**Issue by ShadyCracker** [AppliedEnergistics/Applied-Energistics-2#4307]
**Describe the bug**

After I put the AE2 file in the mods folder and started the Forge installation in the Minecraft Launcher, the game showed me this message https://media.discordapp.net/attachments/626812256105005085/687219608708448276/unknown.png?width=728&height=442
**To Reproduce**

Install the AE2 mod from curseforge.com and put it in the Minecraft mods folder, then enter the Minecraft Launcher and select the Forge installation, hit play and wait.
**Expected behavior**

I expected the game to load and that I'd be able to play normally.
**Additional context**
 

https://paste.dimdev.org/gufuraqeve.mccrash
**Environment**

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable
- Forge Version: 14.23.5.2847

**Comment by yueh** [comment]
`Caused by: java.lang.SecurityException: class "appeng.api.storage.ICellGuiHandler"'s signer information does not match signer information of other classes in the same package` with the signed jar.

E.g. not downloaded from any official source, modfied after downloading it or maybe some other mod potentially shipping some parts of AE. But I have no idea how forge would handle the last case actually.

Actually Forge shouldn't crash. At least not if they did not change anything about it. It was always more or less optional and under the authority of the mod itself on how to handle an invalid certificate. For us it is mostly just to ensure we are dealing with a valid release and not some patched one with unknown and/or unreproducable bugs.

It is also pretty strange, that no other mod is listed with a signature. I know that at least inventorytweaks is signed, too. Which is a bit strange.
