### ISSUE TITLE
An option to make cables have the same thickness

### ISSUE THREAD

**Issue by balthild** [AppliedEnergistics/Applied-Energistics-2#4309]
**Describe the feature**

Currently, smart cables and dense cables are thinner at the positions near their corners:

![Snipaste_2020-03-15_16-15-43](https://user-images.githubusercontent.com/2662758/76698096-c1962380-66d9-11ea-9b9c-1f14efdaea45.png)

But when two corners are close, the thickness becomes the same:

![Snipaste_2020-03-15_16-15-57](https://user-images.githubusercontent.com/2662758/76698112-f30eef00-66d9-11ea-95c7-cc44b360f61e.png)

I suggest there could be an option to make the entire cable to be the same thick, just like the following picture made by photoshop (lol):

![qqq](https://user-images.githubusercontent.com/2662758/76698146-66b0fc00-66da-11ea-8ca7-85b33da0d7c9.png)

**Reasons why it should be considered**

Just my personal preference. Nevermind if you think it's not good.

**Additional Context**

**Comment by yueh** [comment]
Cable rendering is already way too complex with linking between 5 different cable types, different machines/parts, anchors and so on. I am currently not perfectly certain that some machine connections would need the slightly ticker option to connect properly without any visual glitches.

Also it would potentially affect hitboxes, so it really has to be a server option. Otherwise there will be glitches when interaction with cables and parts. Thus enforcing it on every player and not just some visual thing, which could be toggle for a single client only.
