### ISSUE TITLE
Buses not working

### ISSUE THREAD

**Issue by Rams59** [AppliedEnergistics/Applied-Energistics-2#4311]
Im Playing the Mod in a bigger Modpack and the System is working fine for most of the Time. But Sometimes all my Import and partly Export Busses stop working. I havent changed anything on the System. The System has enough power (i even tried and gave it a creative energy cell), there are enough channels left.

#### Environment

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable6
- Forge Version: 14.23.5.2836

**Comment by MyticZ** [comment]
Hello Rams, 
I'm also playing in a modpack with AE2 and my system do the same.
But for me it's not only my Export/ Import busses who aren't working but it seems like my applied system is "freezed". 
I play on a little server with a friend (the server can handle applied without any problem because he is at 40% charge).
I don't know if this problem is recurent or not but i really want to know a solution for our problem. 

I have the same version of the mod than you

If someone can help us. It should be fine

**Comment by mindforger** [comment]
did you also try to attach an creative energy cell? (the one from AE itself not any other)

**Comment by MyticZ** [comment]
> one
Nop didn't work i tried with the one of applied ...

**Comment by yueh** [comment]
`Does not work` is simply not enough to do anything about it. In most cases it is actually just some user error. E.g. assuming something differently than it actually works, power issues, chunk loading, or similar stuff. Way to varied to help in any way.

We really need a way to reproduce it in some way. If this can be provided, we can reopen it. And it is is not some user error.
