### ISSUE TITLE
Buildcraft Redstone Engine issue

### ISSUE THREAD

**Issue by ThatOneGuy513** [AppliedEnergistics/Applied-Energistics-2#4315]
So I was playing a modpack, and I was doing stuff to set up a ME system.
Trying to figure out how to power stuff with engines, I tested the redstone engine but it didn't seem to work, I ended up Shift Clicking the Inscriber with a Redstone Engine in-hand, and it corrupted the world save, now anytime I try to get back in the world, it shuts the game down.

**Comment by Pingger** [comment]
Ok,
first thing: redstine engines have such a low output, that it is not nearly enough to power the ME.
Why your world crashes, no idea since you deleted the template, that tells you to add a crashlog, mc version, forge version and ae2 version

**Comment by ThatOneGuy513** [comment]
I know that now, i was experimenting at first, I watched some videos after,
but that's not the point, idk what happened but it causes it to corrupt the
world data. :/

**Comment by Pingger** [comment]
> Why your world crashes, no idea since you deleted the template, that tells you to add a crashlog, mc version, forge version and ae2 version

DO YOU EVEN READ WHAT I WROTE?!
WE NEED A FREAKIN CRASHREPORT! OTHERWISE WE CAN'T HELP YOU!

**Comment by ThatOneGuy513** [comment]
> > Why your world crashes, no idea since you deleted the template, that tells you to add a crashlog, mc version, forge version and ae2 version
> 
> DO YOU EVEN READ WHAT I WROTE?!
> WE NEED A FREAKIN CRASHREPORT! OTHERWISE WE CAN'T HELP YOU!

Never got a crash report, it just completely closes out

**Comment by ThatOneGuy513** [comment]
> > > Why your world crashes, no idea since you deleted the template, that tells you to add a crashlog, mc version, forge version and ae2 version
> > 
> > 
> > DO YOU EVEN READ WHAT I WROTE?!
> > WE NEED A FREAKIN CRASHREPORT! OTHERWISE WE CAN'T HELP YOU!
> 
> Never got a crash report, it just completely closes out

I start it up, I go to world's, I try to load the world, it does that thing where it goes to home page for a second, then closes mc

**Comment by CitiesXL2815** [comment]
now the template there for reason so we can help you even didn't give crash log you can still upload full latest log file when and before game crashed but if there is crash then look in the crash-report folder @ThatOneGuy513

**Comment by ThatOneGuy513** [comment]
> now the template there for reason so we can help you even didn't give crash log you can still upload full latest log file when and before game crashed but if there is crash then look in the crash-report folder @ThatOneGuy513

Where would I find that folder??

**Comment by Pingger** [comment]
Whereever you have installed minecraft.
I do not know where you installed it and what version you installed, since you still haven't provided us with that information, but it should be at one of those locations:
1. C:\Users\<name>\AppData\Roaming\.minecraft\logs   (or crash-reports) `%appdata%\.minecraft\logs` is your easy way there (just paste it into the address bar of the windows explorer)
2. <Feed-The-Beast installation directory>\<modpack>\minecraft\logs. (In my case that would translate to "Y:\Files\Games\FTB\FTBRevelation\minecraft\logs", but yours will be at a different location.)
3. any other Modpack Launcher/Twitch launcher, you would go the minecraft installation directory and would search for a folder containing the folders "config" "logs" "mods" "resourcepacks" "resources". There you go to "logs".

In all cases we need the latest.log just after the game has closed unexpectedly (e.g. you load that world, that crashes)

**Comment by ThatOneGuy513** [comment]
> Whereever you have installed minecraft.
> I do not know where you installed it and what version you installed, since you still haven't provided us with that information, but it should be at one of those locations:
> 
> 1. C:\Users<name>\AppData\Roaming.minecraft\logs   (or crash-reports) `%appdata%\.minecraft\logs` is your easy way there (just paste it into the address bar of the windows explorer)
> 2. <modpack>\minecraft\logs. (In my case that would translate to "Y:\Files\Games\FTB\FTBRevelation\minecraft\logs", but yours will be at a different location.)
> 3. any other Modpack Launcher/Twitch launcher, you would go the minecraft installation directory and would search for a folder containing the folders "config" "logs" "mods" "resourcepacks" "resources". There you go to "logs".
> 
> In all cases we need the latest.log just after the game has closed unexpectedly (e.g. you load that world, that crashes)

I have my mc downloaded on technic launcher

**Comment by yueh** [comment]
I am not aware how technic stores their packs at all, thus I would really recommend reporting/asking your modpack dev directly. 

They should be way better at supporting it for the initial part. Maybe even know what causes it and if there might even be a fix already available (with the next modpack update or similar). 

Otherwise they can easily forward it to us or even to a different mod, if that is the actual cause.
