### ISSUE TITLE
Why did Gradle version change and break setup

### ISSUE THREAD

**Issue by frizzle101101** [AppliedEnergistics/Applied-Energistics-2#4331]
#3698 committed changes to update the gradle distribution to 4.8 from 2.14 but I dont understand why the whole project wasn't updated, the commit only updates the wrapper discretely breaking the operation of the setup scripts. I have reverted the change in my local and am continuing to use 2.14

**Comment by yueh** [comment]
Honestly I habe no idea. Gradle is always a bit delicate and ForgeGradle on top certainly does not improve it at all.

The CI works just fine as well as locally for me personal without any issues.
As long as this is the case I will not waste time on it. In my experience doing so did always break it and required like 2 days to get it working again.

**Comment by frizzle101101** [comment]
thou i am having issues getting the project to work in eclipse, have any suggestions

**Comment by yueh** [comment]
Sadly no. I also do not want to risk my own workspace currently. In the past it was always like a 50:50  chance to break it on something simple like a dependency update. Quite often just because the Forge repo being unreachable at this point and waiting a day or two would solve it automatically.

Or maybe they updated ForgeGradle and somehow broke it again, while locally I still use an older version just fine. Cannot check it currently and as said the prospect of trying a local (or CI) update and probably having to waste the weekend fixing it is not a particularly great one.
