### ISSUE TITLE
Constant Rendering Block Entity Crash

### ISSUE THREAD

**Issue by Jwilson106** [AppliedEnergistics/Applied-Energistics-2#4334]
Just started playing M.C. Eternal and within 4-5 minutes of loading a new world game grey screens and crashes.

**Describe the bug**
MC Eternal v1.3.5b from the twitch launcher; When I load into a new world I can move around and interact with the world for about 4-5 minutes before the game freezes and grey screens to a crash log for Applied Energistics 2 about issues rendering the sky stone chest. 

**To Reproduce**
Download the 1.3.5b version of MC Eternal from the twitch app and run a new world.

**Expected behavior**
I was expecting to be able to play the game without running into an issue with a mod that I haven't had any interaction with in the first 10 minutes of play.

**Additional context**
Last play test crash log:
https://paste.dimdev.org/azibowoyur.mccrash

**Environment**
Win 10 OS 16gb Ram total 8 dedicated to Minecraft
Single Player
Default and Biomes o' plenty world types
Cheats - Off
Starter chest - Off
Generate Structures - On
Win 10 OS 16gb Ram total 8 dedicated to Minecraft

- Minecraft Version: 1.12.2
- AE2 Version: rv6-stable-7
- Forge Version: 14.23.5.2847

**Comment by yueh** [comment]
Could you please post the complete `fml-client-latest.log`. At first glance it looks like some other mod is potentially changing our code but failing to do it. (Or probably very unlikely a modified build of ae2).
Hopefully the log might contain information about which mod it could be.

Raising it to the modpack might also be an idea. They should have a better picture about what mods they are using. Most notably are probably anything related to "performance enhancing".

**Comment by Jwilson106** [comment]
[latest.log](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/4465152/latest.log)
Is this the log file you need? It is the only file that comes close to the name you asked for.

Ok I will also try opening a support ticket with them as well.

**Comment by yueh** [comment]
Yes, exactly what I needed. It does not give an single solution, but I would guess it is one of these options

1. **Modpack/download corrupted.** 
Probably the easiest option. Just try to download the pack again.
2. **There is a warning about a bad signature**
Could just be 1). Otherwise the modpack might ship some custom .jar. But I would doubt it.
3. **Disabled coremod MDECore-Core**
Just a guess, but it appears a bit strange. One of the coremods is disabled and no idea if Forge even supports it. But might be worth to move `mdecore-1.12-1.1.jar` somewhere else to test it. Or just rename it from `.jar` to `.disabled` or similar.

**Comment by Jwilson106** [comment]
Deleted the entire directory folder in my Minecraft directory and redownloaded and installed it and so far it has been stable for 1.5 hours. So far so good so I am going to close this. 
Thank you for the advice.
