### ISSUE TITLE
Instant Singularity

### ISSUE THREAD

**Issue by TRRESTGHGYTCFTGBCXSZD** [AppliedEnergistics/Applied-Energistics-2#4343]
**Describe the bug**
With Pressure Pipes Mod, (https://github.com/bdew/pressure, https://www.curseforge.com/minecraft/mc-mods/pressure-pipes (BdLib Required, https://www.curseforge.com/minecraft/mc-mods/bdlib)) You Can Make Singularity Instantly!

**To Reproduce**
1. Look At The Screenshot.
2. Recreate it.
3. Insert 64K Storage Module Into Matter Condenser and change Into "Condense To Singularities".

**Additional context**
![2020-04-15_11 33 53](https://user-images.githubusercontent.com/40109698/79292905-4197ef00-7f0d-11ea-9ce8-8c7c355c7cb2.png)

**Environment**
- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable7
- Forge Version: 14.23.5.2847

**Comment by yueh** [comment]
Please report it to pressure pipes, if you consider their transport speed too fast.

**Comment by TRRESTGHGYTCFTGBCXSZD** [comment]
Pressure Pipe Feature Is Unlimited input/output.

**Comment by mindforger** [comment]
in my (very own personal) opinion, fluid to singularity is a bit broken as many water sources are infinite and do not cost power (and in this case produce water infinitely fast)

water -> ice -> singularity (since ice is an item) sounds more apropriate and would require an infinite speed/no power freezer machine which seems broken by design 

but infinite water transport speed is pretty common among many mods and does not require power but only advanced materials at best!
