### ISSUE TITLE
Fluids getting incorrectly voided into sink

### ISSUE THREAD

**Issue by mlbarnard** [AppliedEnergistics/Applied-Energistics-2#4355]
#### Description
I kept importing fluids into my ME system but they were not appearing in the cells as expected.  I went and disconnected all the other fluid stuff I had connected and it started working again.  As soon as I added the storage bus attached to my sink new fluids started getting voided again.  The workaround I found was setting the priority on the sink to -10 but it would be better if it acted like drawers and just wasn't able to accept fluids it cant fit.

#### Environment
Playing on a personal E2:E server

- Minecraft Version: 1.12.2
- AE2 Version: appliedenergistics2-rv6-stable-7 (sorry don't know how to turn this into a real version number)
- Forge Version: forge-14.23.5.2847

**Comment by mindforger** [comment]
Did you limit the bus?

**Comment by Ommina** [comment]
Sinks (I presume you're talking about the Cooking For Blockhead's sinks here; you didn't specify) will happily void any fluid pumped into them.  You'll find the same behaviour if you use conduits or whatever.

This may very well be intentional on CFB's part, I don't know.  Maybe fluids go down the drain.

Just be aware that, from the standpoint of the storage bus, the fluids ARE being accepted by the other tile.  So, yeah, limit that bus to water only.

**Comment by yueh** [comment]
This is not a workaround, that is exactly how it is supposed to work.

And as already mentioned, if some sink accepts the fluid it will be stored there. There is no way to know beforehand, if it will be actually stored or just voided.

**Comment by mlbarnard** [comment]
Sorry, I thought (CFB) sinks were only meant to accept water, thanks for explaining.
