### ISSUE TITLE
Autocraft stuck at simulating while crafting NC cooler

### ISSUE THREAD

**Issue by fdevx** [AppliedEnergistics/Applied-Energistics-2#4372]
### Mod versions
AE2 version: rv6.stable build 7
Nuclearcraft version: 2.18r-1.12.2
Forge: 14.23.5.2768

### Description
Unable to autocraft liquid helium coolers if more than 1 liquid healium bucket is in the AE system.
(this issue does not exist for water coolers)

### How to reproduce:
- create AE system with autorafting capabilities
- create pattern for liquid helium
- place the pattern into an interface connected to a molecular assembler
- Add 2 liquid helium buckets and at least 1 empty cooler to the system
Then try to autocraft 1 or more liquid helium coolers.
Result:
GUI gets stuck in simulating.

![image](https://user-images.githubusercontent.com/20913882/80964420-1f5d0700-8e11-11ea-9daf-6997f2feb91e.png)

Fun fact:
if only 1 liquid helium bucket is in the system autocrafting works

![image](https://user-images.githubusercontent.com/20913882/80964668-94304100-8e11-11ea-91d1-fbebbfd7a646.png)

### My setup
![image](https://user-images.githubusercontent.com/20913882/80964854-db1e3680-8e11-11ea-8ebb-b2acab56be0c.png)

AE2 contents
![image](https://user-images.githubusercontent.com/20913882/80964998-1d477800-8e12-11ea-93dc-2fb1605ea681.png)

**Comment by yueh** [comment]
Many thanks for the detailed report. Especially the hint about it happening with more than 1 bucket was really helpful.

What basically happens is we push the whole amount of buckets to the recipe. Usually that is fine because simple recipes will automatically be normalized to stacksizes of 1. However NC uses a non simple recipe for whatever reason (not important). Here it is left to the recipe itself to handle different stacksizes and it simply rejects anything above 1.

A (simple) fix is easy, but the whole "non simple recipe" is a bit difficult to anticipate. E.g. in case there are recipes out there, which actually need more than 1 items for a single slot. But I am not really aware of any mod actually using it. Most likely it will even run into other issues currently.
So I probably need a bit more  time to verify it.

**Comment by fdevx** [comment]
Thank you for the detailed explanation.
Sounds like I should create a ticket for Nuclearcraft then.

**Comment by yueh** [comment]
Probably does not require a ticket for NC. Might be interesting to know why it does not use a simple recipe. But that is plain curiosity.

Also we are actually limiting most recipe interactions to a stacksize of 1. Just this particular case not. So in case some mod really uses different stacksizes, they will certainly run into issues. If it's even possible with normal vanilla crafting tables and similar.

**Comment by fdevx** [comment]
The strange thing is nuclearcraft seems to also use a "non simple recipe" for their water coolers but the autocraft bug only occurs for the helium ones.

I could be wrong about the "non simple recipe" cuz I haven't worked with mods before but nuclearcrafts recipe building class basically only contains the same codelines with a few changes for the differtent coolers and ingerdients.

**Comment by yueh** [comment]
Maybe related to the used bucket. Iirc the water bucket should still be the vanilla one, whilst helium is  the forge bucket, which can hold any fluid. So maybe it actually requires a different handling to account for the contained fluid.
