### ISSUE TITLE
Can't autocraft duplication recipes

### ISSUE THREAD

**Issue by Tsuarok** [AppliedEnergistics/Applied-Energistics-2#439]
So, thaumcraft has a variety of duplication recipes in which you throw, for example, an ink sac into the thaumatorium and it uses essentia (liquid magic) to create 2 ink sacs.  Since I can't specify essentia as a crafting ingredient, I simply set up my system to always keep the appropriate essentia on hand, and created a pattern where 1 ink sac = 2 ink sacs.  However, when I go to craft it, the start button is grayed out.  This also occurs for the glowstone and gunpowder doubling recipes.  All other non-doubling thaumatorium recipes work just fine, and I definitely had sufficient cpu memory (it was only asking for  300ish, and I have ~30 unused 1k cpus available).

**Comment by dylanpiera** [comment]
I've had the same problem. I just use translocators and an interface to keep 2 stacks of glowstone always there :)

**Comment by GammaPaladin** [comment]
@Tsuarok I went the opposite direction. I told it 1 cobblestone = 2 glowstone. Then I have the interface output to a chest, and that chest is on a subnetwork that acts as a buffer, using a level emitter and a redstone timer to output that cobble one unit at a time to yet another subnet, which has two level emitters, one pointed at an import bus that sucks the cobble back out to the main network, and one pointed at an export bus on the thaumatorium configured to output one glowstone each time it gets a redstone pulse.

So if you tell the system to craft 100 glowstone, it dumps 50 cobble into chest A, which starts the timer ticking. Each time it ticks, a cobble is transferred out to chest B, and each time that gets a cobble, 1 glowstone dust is dropped into the Thaumatorium from the main network, and the cobble is removed from chest B, so that the emitter turns back off until the buffer network drops it the next piece.

That continues until chest A is empty again :D
