### ISSUE TITLE
Mekanism mechanical pipe placed next to Fluid interface causes game crash and world is unable to load without crashing

### ISSUE THREAD

**Issue by NiamiTV** [AppliedEnergistics/Applied-Energistics-2#4529]
**Describe the bug**

Attempting to connect a Mekanism mechanical pipe to an AE2 fluid interface causes an issue that causes the world to not load and crash on startup

**To Reproduce**

1. Place AE2 fluid interface block (Specifically the full block not the smaller interface that goes on the side of blocks)
2. Place a Mekanism mechanical pipe next to the interface block
3. Expect game to immediatelly crash and the world is now unable to load

**Expected behavior**

I expected the mechanical pipe connects to the interface with no errors.

**Additional context**

Forge: 1.15.2-31.2.23
Mekanism: 1.15.2-9.10.9.422
AE2: 7.0.0-beta.1

This isnt just a client side issue this also crashes servers and locks up the world.
https://pastebin.com/wMvtDVLd

**Environment**

- Environment:  https://pastebin.com/Yah7ZMZK
I've been having this issue running on a server but copying the world to singleplayer results in the same issues.

**Comment by pupnewfster** [comment]
Going to comment here given an issue (https://github.com/mekanism/Mekanism/issues/6408) was also opened on the mek repo though they were not linked. The issue is that in forge 1.14+, `getCapability` is nonnull, but AE2 is returning [null](https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/master/src/main/java/appeng/fluids/helper/DualityFluidInterface.java#L213) instead of returning `LazyOptional.empty()`. On a similar note you (AE2) should not be doing what is being done a few lines above that (returning a new lazy optional every time `getCapability` is called); I recommend reading the JavaDocs on `getCapability` and `LazyOptional#invalidate`

**Comment by shartte** [comment]
Should be solved in next beta (see attached PRs).
