### ISSUE TITLE
Cannot craft ME Quantum Ring when channels are disabled.

### ISSUE THREAD

**Issue by tgstyle** [AppliedEnergistics/Applied-Energistics-2#453]
The recipe calls for Dense cable. When channels are disabled, there is no Dense cable.

**Comment by Zaflis** [comment]
Here's a Minetweaker script for making Quantum ring with ME glass cable instead of dense:

recipes.addShaped(<appliedenergistics2:tile.BlockQuantumRing>, [[<ore:ingotIron>, <appliedenergistics2:item.ItemMultiMaterial:22>, <ore:ingotIron>], [<appliedenergistics2:item.ItemMultiMaterial:24>, <appliedenergistics2:tile.BlockEnergyCell>, <appliedenergistics2:item.ItemMultiPart:16>], [<ore:ingotIron>, <appliedenergistics2:item.ItemMultiMaterial:22>, <ore:ingotIron>]]);

**Comment by Cisien** [comment]
You don't need minetweaker, AE natively supports custom recipes

**Comment by Zaflis** [comment]
Sure maybe not, but i don't know exactly how and seemed very easy to use the tweaker. Especially since it's needed for other mods aswell. I also would never have been able to find out those ingame names without ingame tool, it would seem http://ae-mod.info/Custom-Recipes/ needs them too.

**Comment by thatsIch** [comment]
I am not even sure, how the recipe should look like, when you disable Feature A. What happens, when you also disable Feature B etc.

There is like over thousands of combinations you need to handle. 

One way would be to invalidate unknown recipe ingredients. But then there is a high collision chance

**Comment by yueh** [comment]
Also all the transitive dependencies (Disabling Feature A disables B, which then disables C, D, and E). Also we would also suddenly depend on every other mod, in terms of mod loading and what recipes they provide.

For example (already used in another issue)
Disabling the Grindstone basically disables every dust, making nearly every item not craftable. Like cables, buses or the crystal purification.
Except if some mod adds a grinder and a way to grind these dusts. So we had to register our recipes after everything else, which is the only way to guarantee that there is a way to obtain the required items. This means also loading after mods like MineTweaker.

**Comment by Zaflis** [comment]
You are way overcomplicating it. You don't necessarily need to disable anything but simply offer alternative recipes. (For example have 2 recipes for Quantum ring; 1 that uses dense cable, and 1 that uses maybe energy cell)

I was actually very surprised that ME controller or dense cables were no longer craftable after disabling channels. They would have at least aesthetic uses if nothing else. I don't know, maybe it was easier for you to remove blocks rather than change their functionality based on configs. Smart and dense cables could just light up all the channels at all times with that config setting, and ignore the channel limitations.

**Comment by yueh** [comment]
And then the next person comes along and disables energy cells. So no, the moment we make recipes depending in disabled features, we have to consider every possible combination. Or like currently, if you want a custom experience, then you need to plan for possible issues. Say disabling meteors will also remove presses. The same way you need to deal with in other custom maps.

Disabling channels already causes enough issues, I would probably vote for removing that option completely before introducing more bugs with it (as it will with controllers and smart/dense cables)

**Comment by XFactHD** [comment]
I don't understand why you would disable the channels. They are the feature that makes ae2 different from ae1 and I think they are a good nerf that forces the player to think about his setup and not only place some cable here, some cable there, attach the controller to whatever power source and then have a base of about 200 by 200 blocks controlled by ae (I had something like that on a multiplayer server and since I started playing ae2 I think that this was much to easy and pretty boring). I really like the new way and I think it has to offer many cool features and new possibilities.

**Comment by Zaflis** [comment]
I beat the channel metagame long time ago, it's that some people who play my modpack are not as interested about it. P2P has limitations, such as not being able to start another P2P from within other P2P, and it also seemed there were issues with autocrafting about it. Only way you can reliably make a big network is 1 big connected cable with parallel dense cables. I'm sorry but i also am a little perfectionist for server and client performance.

**Comment by thatsIch** [comment]
lets not discuss this here please, its a feature and players can choose their play style. If you have nothing to add to solve the actual problem, I can as well delete your comments.

**Comment by tgstyle** [comment]
I think we are all over complicating this. How about just adding another item that is recipe equivalent to a Dense ME cable that can be used as well to craft a quantum ring? When channels are enabled, it can just be crafted 1 step further to a Dense Cable (in case anyone crafts it unintentionally), when channels are disabled it will only be used for a Quantum Ring.

**Comment by thatsIch** [comment]
This would lead to the same problem we are discussing. At this point to detect that the Alternativ recipe ist needed, we can just inject our own new recipe. The problem arises, what to do if 2 or more of the ingredients are missing, so we need to handle every permutation and add replacements for them? 

The other Alternativ is to revamp the recipes, that they do not need specific parts anymore. Why does the QNB need a dense cable, if it still works without channels (obviously the idea was, that the QNB can transfer 32 channels)

**Comment by eduardog3000** [comment]
How about just not disabling dense cables when channels are disabled? I can't even join servers when I have channels disabled in my client config because my client doesn't have dense cables registered, but the server does, I just get "Fatally missing blocks and items".

**Comment by Zaflis** [comment]
Same change needs to be applied to ME controller too then. But i agree with it, it's easier when no blocks are disabled.

**Comment by yueh** [comment]
We need to disable controllers, dense and smart cables, otherwise disabling channels itself is not possible. It basically results in giving infinite channels to ad hoc networks and these a separate to controller based networks. Smart/Dense cables are expecting 8/32 channels at max, otherwise the rendering as well as synchronize it between the client and server will not work.
It is really the choice between these downsides or not having that option at all.

Also after some more consideration, I do not think it is possible (feasible) to provide alternative recipes for different configuration.
There are way to many having an effect on the default crafting recipes, at least 5-10 should directly interfere with eachother. The worst part is that most options result in transitive dependencies, so disabling a single one will make most recipes not craftable anymore without providing an alternative recipe.

This basically forces us to provide a recipe set for every possible permutation. So we are speaking about 5! (120) to 10! (3628800) different sets or even more. Maybe we could reduce it by making the recipe system aware of options/features. But it will still be a huge effort to make them working and also every modpack maker will need to provide valid recipes for every permutation.
I could even imagine more fine grained options. Like disabling controllers (but leaving channels active), which will make it even worse.

The best option would really be a community driven project to collect some recipe sets for different configurations. For example one for the default configuration but disabled channels and we could then provide a central location to download these.

**Comment by Zaflis** [comment]
>> Smart/Dense cables are expecting 8/32 channels at max, otherwise the rendering as well as synchronize it between the client and server will not work. <<

Somehow you did make it work with Fluix cables and covered cables though, they too are expecting 8 channels at max. It sounds to me that the cable's behavior code does know if that config option exists or not, and can choose to behave 1 way or other.

They could use some kind of material priority list for each of the 9 crafting slots? If the highest priority material is from mod that doesn't exist, it falls back to use next highest, until eventually all the way to vanilla minecraft one. Making tens of variations of whole recipes doesn't sound like a maintainable idea. Needless to say, the recipe has to be created and cached when Minecraft starts, not on every lookup of the recipe.

**Comment by yueh** [comment]
Fluix and covered cables do not sync or render the used channels (this is what requires a fixed amount). This is also the reason Waila does not show the channels (besides design reasons).
This may sound a bit harsh, but there is really not need to discuss it further as long as it not directly related to the code (say someone makes a PR for it). Not disabling it will cause so many possible bugs, and the few people requesting it are probably also the first ones complaining about them.

It is not just alternative ingredients, it is about adding completely new recipes or only using materials with are craftable, because the items can still exist but without a valid recipe.
For example you can disable inscribers (no processors), meteors (no processors), presses in meteors (no processors), in world crystal purification (no calculation processor), in world fluix crafting (basically nothing anymore), grindstone (no dusts obtainable, also nothing anymore), in world singularity crafting (QNBs not usable), no TinyTNT (no guaranteed way to obtain singularities when explosions are canceled), chargers (this will change the balance completely and probably needs completely different recipes when they are only obtainable through mining)
The grindstone or TinyTNT is a good example how we even would depend on the recipes of other mod (which includes minetweaker for example) and can only resolve our recipes after they have registered theirs, basically making ae2 unchangable with minetweaker or are even depending on random mods disabling things like explosions, which are not part of the recipes at all.
