### ISSUE TITLE
Server reboot in Combination with unable to load World again Mekanism Item autocrafting failure

### ISSUE THREAD

**Issue by fkempf78** [AppliedEnergistics/Applied-Energistics-2#4603]
Server reboot because of "hang" cause Tick is longer than 60.0s- World reboot again and again, cannot join to cancel crafting

**Describe the bug**
Server repeats same error again and again until reboot because supposed hang

**To Reproduce**
Autocraft Ultimate Induction Cell with all needed parts also build with Pattern in AE2

**Expected behavior**
Part is build with autocrafting all missing Parts

**Additional context**

https://gist.github.com/fkempf78/a420bebcc10f9855860349fe5ec2975a

**Environment**

- Environment: 
Windows 2019 Server
AMD Ryten 5 3600 6.Core Processor
32 GB RAM
1 TB SSD as only Disk

Forced CrashReport from my Client, as Server Crashs automatically. Crash Report from Server in Additional context linked.
https://gist.github.com/fkempf78/3b194d8f613f20edc63dc4597da74220

**Comment by Pingger** [comment]
Hi,

this behaviour looks weird, since AE2 Autocrafting tries to keep within the usual ticktime limits.

Could you possibly add the crashreport that is mentioned at the end of the logfile? (C:\ATM3-6.0\.\crash-reports\crash-2020-08-16_22.54.57-server.txt)

But from the first look it seems, that MANY mods in combination with the weird crafting implementation of Mekanism are causing the issue.

First Step: Make a backup of your world. (Just in case)

As a first debugging step you could try increasing the maximum ticktime from 60s to something larger like 6000s and see if after a few minutes the behaviour changes. (in your `server.properties` change the value of `max-tick-time`. unit is `ms` afaik)

Greetings

**Comment by mindforger** [comment]
You could try to increase the limit to a very high value in your server config

**Comment by Ommina** [comment]
Thing is -- beyond the CraftingManager fallback reports, which are wholly normal, I don't see any good reason to conclude that it is AE2 that is freezing on the server thread.  Like @Pingger suggests, it would be (perhaps) helpful to see the crash report listed.

**Comment by mindforger** [comment]
i was just suggesting a workaround to get on to the server and attempt to disable the crafting, since the reason was "ticking too long" which means the watchdog process aborted the server not a hard crash, but the stacktrace on this crashlog may help to identify what was going on when it timed out

**Comment by fkempf78** [comment]
OK, here ist the Crashlog:
https://gist.github.com/fkempf78/651a87c18a66fbf4d2325db7208e26b2

**Comment by yueh** [comment]
We no longer support any minecraft version older than 1.15 at this point.

Should you be able to confirm that this issue still applies to the most recent version, please update the issue and we will reopen it.

**Comment by mindforger** [comment]
>Edit: Workaround is fine, Server works again. It creates the Ultimate Induction Cell, but with a horrendous Number of Server Warnings.

that is a known issue with mekanism and it's crafting recipe/item id style

you could probably try to change the loglevel and take a bit load off the logfile (this does have a real influence) but the issue is with the recipes that escalate a bit due to how items are registered, nothing you can change easily
