### ISSUE TITLE
Crash with Applied Energistics crafting terminal and itemscroller

### ISSUE THREAD

**Issue by IchigoGames** [AppliedEnergistics/Applied-Energistics-2#4652]
I am having an issue with trying to use the mouse scroll wheel in an Applied Energistics crafting terminal. Everytime I try to scroll while the mouse is in the middle of the screen the game crashes. Happens on server and single player. Happens on multiple computers.

This is from a player who plays my modpack after looking at the crash report i think its a compatibility issues with this mod and AE2.[edit after posting this on itemscroller Github i was told its a issue with this Mod

Minecraft 1.15.2
Forge 31.2.36
appliedenergistics2-7.0.1
itemscroller-forge-1.15.2-0.15.0-dev.20200412.215325
https://pastebin.com/KQT20GqL
for reference https://github.com/maruohon/itemscroller/issues/41

**Comment by shartte** [comment]
Huh. This _is_ a bug that was introduced in 2017 (1.12). Weird.

**Comment by yueh** [comment]
Technically this is a bug in Forge. There are absolutely no details about it having to be backed by an `IItemHandler` and that `null` is not valid. Or it is and they except to wrap everything into a specific call, which would evaluate to `false`, but also will not mention it anywhere. So this really needs some clarification from upstream.

As far as I can remember, we actually make use of this subclass of `Slot` quite heavily and having `SlotME` extend is is purely convenience as it would otherwise require a massive amount of `instanceof` checks. 
Also we cannot really provide a fully `IItemHandler` compatible approach as the inventories are not clientside and would have to wrap around a blocking server request. Handling this at a `Container`/`Screen` level is fine, but slots are not aware of it.

We could maybe use a `NullItemHandler`, but that can introduce a bunch of bugs by no longer using `null` and some code paths could then pick the `IItemHandler` aproach instead of the methods we actually override.
