### ISSUE TITLE
Is it possible to add an automatable way to get the ae2 quartz dusts later in the game?

### ISSUE THREAD

**Issue by ChronHD** [AppliedEnergistics/Applied-Energistics-2#4705]
Looking for a block that will crush up quartz into their respective dusts without manual interaction

**Describe the feature**
Basically an ae2 pulverizer that doesnt rely on other mods for automating dusts and seed production

**Reasons why it should be considered**
Because using a pack with only ae2 means that all seeds and "pure" quartz can never be fully automated

**Additional Context**

**Comment by shartte** [comment]
It's true that AE2 somewhat depends on other mods for this, and since the mods that would usually have the recipes are currently not updated to 1.16, there's a bit of a problem for AE2 players. I don't see us adding an automated grindstone however.

**Comment by ChronHD** [comment]
Can you add a config option to allow grindstone automation with an autoclicker then?

**Comment by shartte** [comment]
You should also specify which modding API you are on (and which version)

**Comment by ChronHD** [comment]
Im using forge 32.0.108 and ae 8.0 beta

**Comment by shartte** [comment]
And you only use AE2? No Mekanism or similar?

**Comment by ChronHD** [comment]
no only botania at the moment as the people im playing in a server with are new to mods

**Comment by yueh** [comment]
AE2 is not really designed to be used standalone. E.g. energy production will be most likely pretty lacking and is not really renewable with just AE2 + vanilla.

Usually with some mod being present for energy production, some sort of pulverizer is also available. It might currently be missing the recipes for it, that's simple due to how recipes in forge now work and offload more work on the actual modpack author.

Also we only have a single recipe which only accepts pure certus. And if needed that can be easily changed with a custom datapack. Otherwise everything works with normal crystals, which can be mostly automated, except for mining them.
Or maybe some other approach like using a botania mana pool to convert ingots/ore into dusts at the cost of mana.

If we have to assume the presence of some activiator block, it is the same as assuming another pulverizer is present.
If this is not the case, it is still not possible automate it.

We had some concepts for adding a powered crank at some point. But that is extremely low in terms of priority. It is simply not useful except for some extremely special modpacks. And even then it can be solved by using custom recipes. So I would not expect anything about it in the near future.
