### ISSUE TITLE
ME Dark Cable

### ISSUE THREAD

**Issue by virtualdxs** [AppliedEnergistics/Applied-Energistics-2#4776]
**Describe the feature**
AE1's ME Dark Cable, similar to a normal ME Glass Cable except would only pass traffic if a Redstone signal was applied

**Reasons why it should be considered**
- Was present in AE1
- Allows for better power management (especially with regard to quantum bridges)

**Comment by shartte** [comment]
This exists in AE2, it's now called a "toggle bus". You put it onto the cable, then connect a cable to it so that the toggle-bus is between the two cables. There's also an inverted version of it (that will disconnect on redstone signal).

See: https://ae-mod.info/ME-Toggle-Bus/
https://ae-mod.info/ME-Inverted-Toggle-Bus/

**Comment by virtualdxs** [comment]
Perfect, thank you! I searched for dark cable and a few related terms, but had no luck. Hopefully this will help future people searching.
