### ISSUE TITLE
JEI/Quark Compatibility - NBT on vanilla items

### ISSUE THREAD

**Issue by jeremiahwinsley** [AppliedEnergistics/Applied-Energistics-2#4930]
**Describe the bug**

When attempting to fill a recipe containing a clock or a compass from JEI, everything but the clock or compass is filled in.

**To Reproduce**

With AE2, JEI, and Quark, attempt to fill a map recipe.

**Expected behavior**

JEI fills the recipe in a vanilla crafting table, it should be able to fill it here as well.

**Additional context**

Quark adds NBT to the clock and compass. I assume this is what causes the issue. 

Relevant issue here, from another bug: https://github.com/Vazkii/Quark/issues/2688

**Environment**

- Environment: ATM6 1.3.9b

**Comment by yueh** [comment]
As mentioned in the other issues this is because they add custom NBT data to a clock. Which is something we have to take into account. For example a recipe might ask for only fully charged items, a specific enchantment, or something similar. 

As minecraft/forge does not provide a way to know which data we can safely ignore, we have to err on the side of caution and consider these different items, which are incompatible with the requested recipe when fetching them from the network.
Leading to these incompatibilities without much we can do about it sadly.
