### ISSUE TITLE
Blocking mode on interfaces not working

### ISSUE THREAD

**Issue by Fey142** [AppliedEnergistics/Applied-Energistics-2#4933]
I have an interface with crafting patterns for various alloys in it above an induction smelter (thermal). When trying to craft more than one at a time the system ignores blocking mode on the interface and just fills the smelter with eveything from all recipes.
**Describe the bug**

appliedenergistics2-8.2.0-beta.2 (DW20 1.16 pack v. 1.3.0)
**To Reproduce**

Preety self explanatory.
**Expected behavior**

Should craft recipes one by one not mash them all together in blocking mode.
**Additional context**

https://prnt.sc/wl20bj
https://prnt.sc/wl20q3

**Environment**

- Environment:

**Comment by mindforger** [comment]
do you have setup the port on the machine as in and output at the same time?
maybe the readback of the slot fails?

please add a screenshot of the setup and the slot config as well

**Comment by Fey142** [comment]
Yes it's in in/out mode, it usually worked so it pushes the ouput back into the interface.

**Comment by mindforger** [comment]
then try it with dedicated in and output to confim my suspicion please

**Comment by Fey142** [comment]
When seperating the output it worked as intended yes (one by one).

**Comment by Fey142** [comment]
I guess it's a thermal issue then?

**Comment by mindforger** [comment]
more like a forge issue imho since the capabilities are not designed for this kind of special use

**Comment by yueh** [comment]
This is a pretty old issue. The problem here is that mods started to hide the input slots from external observer and only make the output visible or similar approaches. So until it has not produced a single output, for us it is always empty.

In some cases they will make the inputs visible, but not extractable, but here we have to be lenient as other machines also expose their upgrades. Which would cause it to always block and never be able to craft anything. So the fallback is to not block at all and at least allow it to work normally.

Ultimately this is something which can only be resolved by forge providing a way to indicate a machine is actually working. But I would not have high hopes about it ever happen.
Technically we could provide our own handling for it, but that means every mod out there has to explicitly support AE2 and 99% probably won't do it without a way to indicate it for a player.

**Comment by Fey142** [comment]
Thanks for looking into it. I guess I never noticed it because I mostly used EnderIO machines in the past which didn't have that issue.
