### ISSUE TITLE
On a server after a while import and export busses stop working

### ISSUE THREAD

**Issue by Thorsten6697** [AppliedEnergistics/Applied-Energistics-2#4940]
**Describe the bug**

I play on a server and after a while (around half a Day) some (not all) import and export busses stop working.
If you insert an acceleration card it starts working again.

**To Reproduce**

Run an AE system on a server for a while

**Expected behavior**

The busses working normaly

**Additional context**

**Environment**

- Environment: 
FTB DireWolf20 1.16 v. 1.31
AE 8.2.0 Beta 2
Force crash client:
[crash-2021-01-12_14.57.36-client.txt](https://github.com/AppliedEnergistics/Applied-Energistics-2/files/5802526/crash-2021-01-12_14.57.36-client.txt)

**Comment by Thorsten6697** [comment]
Correction:
The issue happens after a server restart

**Comment by yueh** [comment]
Which inventories are you using? For performance reasons many AE2 machines will go to sleep when they cannot do anything.
In case of the export and import buses for example, if there is no adjacent inventory. This could be caused by some inventories not being available immediately and need some time to work correctly, but without notifying any neighbor about their change. So for us they still count as not usable and the buses won't resume their work except for some other external trigger like changing their config or upgrades.

**Comment by Thorsten6697** [comment]
First I am exporting into an inscriber, but the export bus doesn't always have the resources available. But when the resources get available the export bus doesn't start exported until I update something inside (add / remove a card or an item).
The second block is the output port from an environmental tech miner. There were almost half a stack of crystals inside and the import bus doesn't bother to import them, but was able to to it earlyer.

**Comment by yueh** [comment]
Actually as this is the dw20 mod pack, it might be up to them. They are using other mods affecting how our machines tick/work in a negative way. Or at least used to, I have not followed their decisions at all.

So I would further recommend reporting it directly to the modpack as it might be caused by some mod interaction and they should certainly have a better picture of it.

**Comment by shartte** [comment]
@Thorsten6697 Are you using FTB chunks to chunkload?

**Comment by Thorsten6697** [comment]
Yes I use FTB Utilities for Chunkloading
