### ISSUE TITLE
Documentation for fluid equipment missing

### ISSUE THREAD

**Issue by Hawk777** [AppliedEnergistics/Applied-Energistics-2#4994]
[The mod website](https://ae-mod.info/) does not, as far as I can tell, have documentation for any of the fluid-related equipment (fluid interface, fluid storage cells, fluid annihilation/formation planes, fluid import/export/storage buses, fluid terminal, etc.). While they do work somewhat similarly to their item counterparts, (1) it would be useful to have at least stub pages so that someone visiting the site knows that they exist, and (2) it would be useful to know their differences (e.g. a fluid interface is not just the fluid equivalent to an ME interface, because an ME interface can accept patterns while an ME fluid interface can’t).

**Comment by yueh** [comment]
The website still heavily relies on mechanics from 1.7.10 like the old recipe system, making manual changes pretty tedious.
We still hope to replace it at some point to make maintaining it easier. But that takes a good amount of time, which is naturally not unlimited.

There are also plans for an ingame documentation, but that is still pretty slow due to limited time.

So for now we sadly have to leave it as it.
