### ISSUE TITLE
Add mod priority list to item outputs 

### ISSUE THREAD

**Issue by Wxrlds** [AppliedEnergistics/Applied-Energistics-2#5003]
Add a mod priority list to allow item outputs from items from other mods

**Describe the feature**
It would be nice if you would have the ability to specify what mod the item ouput is from. Immersive Engineering for example does this and helps as it unifies ores, ingots, dusts,... for example if you throw an Iron Ingot into an Immersive Engineering Crusher to make Iron Dust and set the priority list ``1. Immersive Engineering 2. Thermal 3. AE2`` what would happen is that it first checks if Immersive Engineering has Iron Dust (which it has) and therefore you only ever get IE Iron Dust, even if you were to use a AE2 Grindstone or a Thermal Pulverizer. Same for other resources, let's assume you crush one Quartz in the Grindstone and crush one in the Immersive Engineering Crusher currently the Grindstone would give you Quartz Dust from AE2 and the IE Crusher gives you Quartz Dust from Thermal but with the priority list it would give you Thermal Quartz Dust, no matter if you use the Grindstone or the Crusher.

**Reasons why it should be considered**
This allows players to play the game without having multiple of Gold Dusts, Ender Pearl Dusts,... filling their chests/storage systems.

**Additional Context**
Just letting you know that Botania also adds a priority list for it's Orechid in case that's somehow useful.

**Comment by yueh** [comment]
In previous version, it was possible to deactivate duplicate ores and their various related items. This is now no longer the case, so you could say it is the preferred way of Forge having the player deal with a myriad of equal blocks and items.

Further making it a config option means it will not be synchronised to the clients. In case they run different they can run into various issues like recipe shown via JEI being incorrect or maybe even cause problems when trying to craft these items in a crafting bench.

Also it would require additional effort for modpack makers to deal with each and every config file, because we now replace their custom recipes, which they picked certain outputs intentionally. Leading to confusion about why changing it is not possible, spent more time on debugging and fixing it and so on.

The recommended way is really to just provide a custem datapack, overriding the existing recipes. These are synchronised between the client and server each time a player joins a server. This allows to easily join different servers using different recipes as long as the modpack is the same one. Without having to restart the whole client each time. And many mods like JEI will use the same data to display recipes and various other details, ensuring these are correct, up do date and ideally can even be changed at runtime without restarting the client or server.
Further this also includes tags, which can easily be used for configuration like cases like synchronising the ores an orechid produces in case there is a JEI info page available and it is not done by actual recipes.
