### ISSUE TITLE
Autocrafting Item packages

### ISSUE THREAD

**Issue by Dylan-Git** [AppliedEnergistics/Applied-Energistics-2#5024]
Allow the creation of a item package within the autocrafting system. This would allow players to request a bundle of items that are already craftable via your ME system.

**Describe the feature**
Example: you have 3 patterns in ME interface attached to a molecular assembler . These 3 patterns are to craft a crafting table, furnace, and torch. Instead of having to click on each individual one and clicking "craft", you can just click craft on the package and it will make all 3.
Maybe have a special view for it on the list of views such as "stored items" and "craftable items'. Add a new view for "packaged items"
It could be crafted in the pattern terminal and have a 3rd option instead of the "crafting pattern" or "processing pattern", you could add "packaged pattern" where you would just enter all the items you want the system to craft and it will make them all and put them in the system.

**Reasons why it should be considered**
This would help with 2 things:
1. Save time instead of having to craft 9 different items that may all come together for one purpose.
2. Remove the possibility of when you craft and item, then you craft an item after that but the second item requires the first item as an ingredient but you needed to have both. Example: I need exactly 8 ME glass cables and 4 ME Drives for something I plan to do multiple times. When I craft the cables first, then the drives, the system will uses the cables as an ingredient for the ME drives.

**Additional Context**
The inspiration came from working with ME systems and other mods such as Environmental Tech.

**Comment by Mari023** [comment]
well you can technically already do this, so I doubt that such a feature is going to be added.

(you would have to make a Pattern like 
stuff to be bundled -> some unique but "useless" item (renamed items might work))

**Comment by Dylan-Git** [comment]
> well you can technically already do this, so I doubt that such a feature is going to be added.
> 
> (you would have to make a Pattern like
> stuff to be bundled -> some unique but "useless" item (renamed items might work))

True but then you would need to have a separate inventory of these items to provide to the system once they are crafted so that the system thinks that the craft is complete. Overall hacky and error prone solution that I thought about but thought it could be done better.

**Comment by yueh** [comment]
As @Mari023 already said, that is already possible.

**Comment by Ommina** [comment]
The "unique item" trick -- I'm going to call it a work-around -- is super error-prone, particularly when wanting to craft more than a single package.  You must return n items for n packages requested, or the craft will stall, waiting for the item.  You WILL get n packages, but will have to manually cancel the craft request.

No, you can't use blocking mode on an interface to send only one package at a time, as the presence of the work-around item will prevent the interface from inserting the package contents.  No, you can't leave blocking mode off, because then the interface will insert items for all requested packages, leaving the user with no way to know how many work-around items to return.  No, you can't use a level emitter, as it will leave you depending on the timing of different components.

The intermediate item work-around looks great on paper, but fails reliably in game for anything but the most simple test.
