### ISSUE TITLE
i cant craft dirt shoe

### ISSUE THREAD

**Issue by buttpooper23** [AppliedEnergistics/Applied-Energistics-2#5056]
whenefver you make the dirt clothing you can only make dirt hat and dirt shirt and dirt pants but not the dirt shoe i am playing on the online modded verson of mine craft

**Comment by buttpooper23** [comment]
can u fix it ben 34 minute ago sence i posted this please

**Comment by buttpooper23** [comment]
@mindy15963 @masakitenchi

**Comment by buttpooper23** [comment]
@kylev @yueh @dshadowwolf @GuntherDW @Adaptivity @Akai1 @AlgorithmX2 PLEASE FIX THE ISUE

**Comment by buttpooper23** [comment]
![enker](https://user-images.githubusercontent.com/80023047/110737183-82b68300-81f2-11eb-9daa-cb17e737d56d.PNG)
* I Am Getting Impaetient. Michael ATTACK ONE DEFENSE ONE.
* You Feel Like Your Gonna Have A Bad Time
* ( megalovania plays

**Comment by buttpooper23** [comment]
@vectorwing

**Comment by Mari023** [comment]
First of all: don't mention random people
second: not everyone is online all the time. due to time zones, some people might sleep when you are not
third: which mods are you using? applied energistics 2 doesn't even have "dirt clothing" and I presonaly don't know any mod that has
what do you mean with 

> online modded verson of mine craft ?

there is only applied energistics 2 for the java Version.

**Comment by Mari023** [comment]
after looking at other issues you created elsewhere, I am pretty sure you are just trolling/spamming
please stop
