### ISSUE TITLE
Decorative stuff 

### ISSUE THREAD

**Issue by faion** [AppliedEnergistics/Applied-Energistics-2#507]
Can you add some AE2 style decorative stuff ? I think blocks with neon glow like cable or ME Controller
will be very cool for building sci-fi looking house.
AE style blocks for wall floor window and doors will be very cool.

**Comment by Anomerly** [comment]
I personally love the look of the skystone bricks, I was wondering if there could be a way of gaining a more abundant supply than endlessly chasing down meteorites?
My thoughts were some way of combining a quantity of stone and skystone dust to create a couple of raw skystone blocks. This would allow the construction of machines that could produce sizable quantities in a similar way (if more complicated) to a cobblestone generator and it would not interfere with the initial learning\limiting curve as you start out with AE2.

**Comment by thatsIch** [comment]
Sounds like multiplication to me,

you can just add it to the worldgen with mods like CofH Core

**Comment by Anomerly** [comment]
I was thinking of a legitimate crafting recipe that would be native, but if you don't think that is a good idea I always have creative mode. (I also though it would be a nice first use for skystone dust)

**Comment by XFactHD** [comment]
How would you want to get the skystone dust without getting skystone first?

**Comment by Anomerly** [comment]
I wouldn't, as I said I was not suggesting anything really that game changing. You would still need to find at least one skystone block and have a tool that could mine it, in the same way you still need to find at least one of each of the presses. but once you have them they can be duplicated at the cost of one iron block in an inscriber.
I was suggesting a similar idea, mixing skystone dust with stone, to net a greater return of skystone at the cost of some other, more common resource. I only suggested stone because it is the MOST common resource.
It is not like it has many uses aside from decretive, I believe four skystone blocks are used in an ME controller, and that is about it. I wouldn't want to upset the balance by making something that is supposed to be hard too easy, I just like the dark skystone bricks.

**Comment by yueh** [comment]
Any duplication recipe without any serious costs is just bad and stone is basically freely in massive quantities available. Also it would really not fit into the AE2 "lore".

Your best bet is really something like EE3, MystCraft, CofH Core or manually add a [custom recipe](http://ae2.ae-mod.info/Custom-Recipes/) for it.

An idea for AE2 to obtain more is probably a way to manually "attract" new meteors with a large power cost (and would also allow some other options)
