### ISSUE TITLE
A Way to Update "AE2 1.7.10" to "AE2 1.16.3"

### ISSUE THREAD

**Issue by serveradmin9912** [AppliedEnergistics/Applied-Energistics-2#5113]
Im looking for a way to update AE2 from 1.7.10 to 1.16.3.

If i want to update my world from 1.7.10 to 1.16.3. All AE2 Blocks and Items get removed. 
Maybe its possible to make AE2 detecting old AE2 Blocks an Items and converting them to the new version.

Many Players on my server have all their stuff in their MEs and it would be horrible to loose everything, because of this update.

______
If its not possible to implement this:
Could you tell me a way to copy the ME Drives or maybe only the content of the me drives to the new version?
Where is this data located in my server files?

**Comment by yueh** [comment]
This is simply not possible. There are massive changes between 1.7 and 1.16 and how minecraft handles the basic data, which makes an update pretty much impossible. Further it still requires that every other mod is also ported from 1.7 to 1.16 without a single change, otherwise the data is pretty much lost, too. Updating major minecraft versions in a modded environment will nearly always be a complete reset except for some extremely rare cases like only using mods, which add more commands or similar.

**Comment by serveradmin9912** [comment]
ok thanks for info!
