### ISSUE TITLE
Storage Bus Sight Filter

### ISSUE THREAD

**Issue by Nexow91** [AppliedEnergistics/Applied-Energistics-2#5115]
I find it bad that i actualli can say let things in a chest but dont can say dont schow me all that things in the chest 

Best way that i see is that i can add Sight Cells to say what i can see, but the way to use the import / export White list as Sight Filter where okay to

I Play now at 1.12.2 and 1.7.10 i realy hope fore future Update to add it in that Versions

**Comment by yueh** [comment]
First off anything older than 1.16 is no longer supported.

Otherwise this is an intentional behaviour for various reasons. Like the more simple ones like having the implicit "garbage collection" slowly clean up items in inventories without a respective whitelist (when configured correctly).
But the more important reason is the performance impact it would have. Having to filter the visible items with a storage bus, is a massive overhead as we have to update it. This can get extremely bad fast when using it to filter a whole ME network with thousands of items.

E.g. a simple case like inserting a piece of cobble into a storage bus with a filter is a pretty quick test as we only have to test, if a single item is part of a white or black list. However this has now changed the inventory, so we have to update the storage bus and check of every stored itemstack is in the white or black list for viewing. So a single change now forced us to do thousands or more checks and this will happen every single time a single item enters the storage bus and could now in turn make the overall performance 1000 times worse or even more.
