### ISSUE TITLE
Pressing any modifier focuses the search field in any terminal screen

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#5121]
(It shouldn't)

**Comment by yueh** [comment]
That might be caused by how minecraft handles key presses.

Alphanumeric and special characters keys in auto mode should autofocus the input field. The question is now, should this also apply to modifiers and other control keys. Do we really want to start whitelisting/blacklist certain keys? 
I certainly don't want to go through [HID Keyboard page 53 ff.](https://www.usb.org/sites/default/files/documents/hut1_12v2.pdf) and start making exceptions for each. E.g. it would make sense for space/backspace/del. Probably tab for focus (if that isn't already handled specially). All F1-F24 keys? etc.

**Comment by shartte** [comment]
Nah, you just need to blacklist the keys that we use ourselves for inventory interactions.
I.e. SPACE+Click, SHIFT+Click, etc.
Those should not cause the search field to become focused if it isn't already focused.

**Comment by yueh** [comment]
Focus happens (currently) on key down not release. So we either have to change that completely to on release, which as far as I am are is completely against anything in minecraft. So it might feel clunky.

Or there is also `net.minecraft.client.gui.INestedGuiEventHandler.charTyped(char, int)`. That might be more fitting for text inputs.
