### ISSUE TITLE
spatial storage not working in some worlds

### ISSUE THREAD

**Issue by Mari023** [AppliedEnergistics/Applied-Energistics-2#5136]
**Describe the bug**
The Spacial IO Port does nothing when activated with redstone
There is no output in the log even when debug mode is activated

**To Reproduce**
build a spatial storage setup (like in the screenshot below)
put a Spatial Storage Cell in the Spatial IO Port
activate the Spacial IO Port with redstone (e.g. press a button)

**Expected behavior**
The spatial IO port should swap the contents of the Spatial Storage Cell with the blocks in thew spatial pylon

**Additional context**
this only happens in some worlds.
it does NOT happen in a newly generated world

it seems to be linked to a broken/missing spatial dimension.
/ae2 spatial tp 1 gives an error rather than teleporting to plot 1 / responding there is no plot 1

the one thing all non-working worlds I tested have in common is that at some point, I removed an (unrelated) mod.

![2021-04-10_13 15 57](https://user-images.githubusercontent.com/38946771/114268323-cb837680-9a00-11eb-8fb7-108d3b20964a.png)
![2021-04-10_13 16 13](https://user-images.githubusercontent.com/38946771/114268325-cc1c0d00-9a00-11eb-8680-4a90831e35b5.png)

**Environment**
[debug crashlog](https://gist.github.com/Mari023/daf706db2688d16d00ae166134393642)

**Comment by shartte** [comment]
This is a Vanilla bug.

If you remove a mod that has a dimension, depending on the order in which dimensions were initially added, all dimensions past that mod's dimensions are also removed from your world.

There's not a lot we can do here, other than trying to fix this Vanilla issue ourselves. Forge does attempt to fix it, but only for Vanilla dimensions (since the bug can also lead to NETHER/END disappearing).

If you're adventurous, this can be fixed by hand using an NBT editor pretty easily. What you'd need to do is add back the AE2 dimension to your level.dat, since the world-save files themselves are still present.

The highlighted area in the following screenshot is what is missing in your level.dat. If you restore that, the spatial dimension will return. The same issue should not occur again since Forge now guards against the entries going missing in the first place.

![image](https://user-images.githubusercontent.com/1261399/114270454-c1677500-9a0c-11eb-9188-63d9422beb12.png)

**Comment by Technici4n** [comment]
On fabric you can install https://www.curseforge.com/minecraft/mc-mods/dimension-fix-some-forge-patches-ported to prevent this from happening again, but you'll still need to re-add the dimension yourself.
