### ISSUE TITLE
Tie the Craft Amount Buttons to the max. stack size of the item being crafted

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#5162]
I.e. for ender pearls it should be +16/-16 rather than +64/-64.

They should also _set_ the amount if the initial amount has not been touched (so clicking +16 sets it to 16, rather than 17)

**Comment by yueh** [comment]
In this case the initial value should also be changed back to 0. The times someone wants to craft 65 items when clicking on +64 is probably non existing. Pretty much always a multiple of a full stack is the desired amount.

Default value for unchanged should however still be 1.

Also how to handle the steps? Currently it is 1, 10, 100, 1000. Which is pretty universal.

I guess +-1 is something we could actually move around, e.g. two small buttons with + and - right to the input field resembling a html5 number input (or alternatively up/down icons)

Otherwise having a quick access to a multiple of a stack is nice, but for the default of 64 it might be a bit to step. In this case a quarter stack might be nice as the first option. For ender pearls however it might be too fine-grained.
Further 1000 is still a nice number for humans, not sure how useful say 1024 or something similar would be.

Maybe have the buttons as something like `maxStackSize/4`, `maxStackSize`, `maxStackSize*8`, and `maxStackSize * 32`?
So for the normal 64 it would be `+8`, `+64`, `+512` and `+2048`.

Also what about a max of 1? `+1`, `+1`, `+1`, `+1`?
