### ISSUE TITLE
Level emitter crafting support for checking whether *anything* is crafting

### ISSUE THREAD

**Issue by Hawk777** [AppliedEnergistics/Applied-Energistics-2#5163]
**Describe the feature**
Right now, the level emitter with crafting card in “crafting emitter mode” works fine to indicate whether a specific item is currently being crafted. However, if you do not select a specific item in the filter, it always outputs low. It would IMO be useful in this situation if instead it output whether *anything* is being crafted at this moment.

This is what #1747 was asking for, I think, but that ticket wasn’t explained very clearly so was closed due to a misunderstanding.

Rather than the level emitter, this could also be a block that forms part of a crafting CPU and outputs a redstone signal when the CPU is busy.

**Reasons why it should be considered**
This would allow detecting whether your network is busy or idle, perhaps driving some indicators, or even cutting power when the network isn’t needed (since AE has so much idle draw). At present I have a power switch, but it would be nice to be able to start some jobs, push the power switch, and have a redstone circuit keep the AE network powered until all the jobs finish before powering down. This can only be done if it’s possible to detect whether any jobs are running.

**Comment by yueh** [comment]
I don't really see an easy option to solve this with a level emitter due to the current implementation. As well as communicating the functionality would not be really clear.

The best option would be to allow crafting cpus to interact with comparators similar to chests. Potentially even use the strength to indicate the progress.

As we plan to revisit the multiblock structures in 9.0.0, this is probably a good option to look into it then. As this also has to take into account how rapidly it might change and how big crafting cpus can get.

**Comment by Hawk777** [comment]
I don’t particularly care where it gets implemented (level emitter versus crafting CPU block), as long as it’s somewhere. The level emitter just seemed like the most obvious place to look from a UI perspective, since it already has the “if X is crafting then emit redstone” behaviour; this would just mean that not filling in the item filter sets X=wildcard. However if you prefer to put it somewhere else that’s fine by me.
