### ISSUE TITLE
I think there is a bug with the formation plane in combination with an ME Chest

### ISSUE THREAD

**Issue by JoeJoke22** [AppliedEnergistics/Applied-Energistics-2#5342]
Hello there,
I think there is a bug with the formationplane in combination with an ME Chest. If I use a Chest for holding the storage card, I can do whatever I wand, the formation plane wont work. 
But if I use a ME drive for the storage card, the formation plane work like it should.

![2021-07-18 20_08_54-Minecraft_ 1 16 5 - Singleplayer](https://user-images.githubusercontent.com/75525798/126078255-d820b2aa-f6f4-425c-a384-26f868dc3708.png)
![2021-07-18 20_10_14-Minecraft_ 1 16 5 - Singleplayer](https://user-images.githubusercontent.com/75525798/126078257-aaa3c175-0e18-49a9-8b66-8b8da4783b91.png)
![2021-07-18 20_08_54-Minecraft_ 1 16 5 - Singleplayer 2](https://user-images.githubusercontent.com/75525798/126078258-08ab9d91-4ea1-4ca3-b3b9-011d278a4827.png)

You can easily reproduce the bug when you setup a short ME System like at the screenshots shown. Just put down a ME Controler and a Me Chest. Put a storage card inside and place a formation plane like inside the screenshot. You will see it wont work. But if you replace the ME Chest with an ME Drive, you will see the formationplane works.

**Comment by Mari023** [comment]
the formation plane works like a storage bus.
as in, a new item enters the network, the formation plane will place/drop it.
it does NOT work like an export bus and will NOT extract items out of a storage, regardless if it is a me drive or a me chest

**Comment by JoeJoke22** [comment]
> 
> 
> 
> as in, a new item enters the network, the formation plane will place/drop it.
> 

I know that. I tried to take everything out of the system and then put it inside again. If I use the chest, the plane do nothing. If it is a Drive it works fine.

Maybe I can make a video about it tomorrow so I can show you that the Chest is the problem.

**Comment by JoeJoke22** [comment]
Okay, today I tried a bit around and found out what the problem is. Maybe it is a bug, I think so.
If you use a terminal erything works fine. You put your stuff inside the system and everything you want to come out come out. 
But if you use the Terminal on the top of the ME Chest nothing happen.

I made a short video about it. There you can see that the Chest terminal isnt working with the formation plane.

https://user-images.githubusercontent.com/75525798/126119927-d5ac6409-fd37-4cad-b33b-2f749d341520.mp4

**Comment by Ommina** [comment]
I'm not convinced this is a bug.

When you use the chest, you are inserting the item directly into the storage cell contained within that ME Chest.  Instead of "enter network, get routed to Formation Plane or Storage Cell as appropriate", it is "store into cell".  Since the item never has to go through the "where am I going to put this" step, the Formation Plane never becomes a viable option.

Likewise, when you put an item into the chest, Cells in connected drives are not considered viable storage locations.

While the network as a whole can see the Cell in the Chest, the Chest interface itself sees only its Cell.

I can't help but believe this is intended.

**Comment by yueh** [comment]
The chest giving only access to the chest is intended.
