### ISSUE TITLE
Unable to use spatial storage (ATM6 Sky)

### ISSUE THREAD

**Issue by MisterZucc** [AppliedEnergistics/Applied-Energistics-2#5347]
**Describe the issue**

I am unable to power and use the spatial io port, everything seems to work well except that it won't actually put the blocks in the drive.

**Environment**

-All the Mods 6: To the Sky modpack version 1.1.6

**Comment by shartte** [comment]
This is a recurring issue. The dimension got lost and you'd need to recover it using an NBT editor.
Vanilla bug, sadly. This happens when one of the mods that had a dimension removes it in an update, or is itself removed.

Sadly there's currently nothing we can really do about it.

**Comment by MisterZucc** [comment]
So do you know what mod is the issue?

**Comment by shartte** [comment]
No, this happens if _any_ dimension is removed after your world has been created. The Vanilla bug then leads to all information about dimensions that come after the removed dimension in the list being lost forever.
If you're feeling adventurous, you can restore it by using an NBT editor to copy the ae2 spatial dimension from a fresh level.dat to your own level.dat, since it's just the info block that is lost, not the actual level data.
