### ISSUE TITLE
[Fabric] Block#rotate fails during placement with mods like Campanion

### ISSUE THREAD

**Issue by Xechorizo** [AppliedEnergistics/Applied-Energistics-2#5364]
Horizontal orientation of terminals, tunnels, facades, etc. maintain their original orientation after specific placements.

**Describe the bug**

Placing AE2 Terminals, P2P Tunnels, and Cable Facades using mods like [Campanion](https://github.com/TerraformersMC/Campanion) results in the original panel horizontal orientation kept, instead of the new horizontal orientation. Campanion mod authors advised Block#rotate may be the cause of the failure to reorient the horizontal axis.

**To Reproduce**

Place an affected horizontally-oriented block in range or within a Campanion 1.3.5 Tent.
Pick up the Tent with the Tent Bag.
Rotate the Tent.
Place the Tent.
Observe the affected horizontally-oriented blocks have wrongly maintained their original orientation.

**Expected behavior**

Place an affected horizontally-oriented block in range or within a Campanion 1.3.5 Tent.
Pick up the Tent with the Tent Bag.
Rotate the Tent.
Place the Tent.
All blocks and panels placed reflect the new orientation.

**Additional context**

![image](https://user-images.githubusercontent.com/14857131/128981342-db18c1bd-ca01-4f61-8649-95ccf32a18a2.png)

**Environment**

Minecraft v1.16.5
All The Fabric 3 v2.8.5
Applied Energistics 2 v8.4.0-alpha.2
Fabric v0.11.3
Fabric API v0.34.7+1.16
Oracle JDK v16.0.1

https://pastebin.com/h5ey6vz1

**Comment by yueh** [comment]
Cables are extremely complex with parts and facades and trying to rotate them is not a trivial task. E.g. it's just not about rotating the block itself, but each part also has to potentially be rotated under certain conditions. While in others you do not want to rotate them at all like facades to not have an odd texture sticking out. Or they need to be rotate because they are part of a pattern. Nothing we can really decide on our side as it would be up to the player to decide for each individual cable and each part.

Therefore cables are simply considered non rotatable on our side for ease of use (in terms of development)
