### ISSUE TITLE
Exploit to get any items out of JEI Using AE2

### ISSUE THREAD

**Issue by JoeSGT** [AppliedEnergistics/Applied-Energistics-2#5369]
**Describe the bug**
Exploit using AE2 and JEI to get any items out of JEI

**To Reproduce**
How to reproduce to get any item out of JEI:

1) Require to have AE2 Currently using appliedenergistics2-rv6-stable-7 
2) Setup a basic ME Terminal using ME Drive and any storage cell with power.
3) switch yourself into CheatMode (you don't need permission from the server to access any item using the exploit)
4) Go into any server that offers AE2 and JEI you don't need permission or /op <name> and simply go into terminal and drag and drop the item you want into the terminal and there you have any item you out want of JEI
Also, the server-side require to have JEI otherwise it wouldn't work, but you don't need permission or OP to access any item

**Expected behavior**

get any item you want out of JEI without permission from using the JEI Cheat Mode feature. Mezz thinks that permissions checks may be done by AE2's JEI plugin.

**Additional context**

**Environment**

- Environment: 
jei_1.12.2-4.16.1.302
appliedenergistics2-rv6-stable-7

**Comment by shartte** [comment]
We don't support 1.12 anymore, sorry.
I hear there's a 1.12 fork that continues support, but I don't know where it is and it's unofficial.

**Comment by Ommina** [comment]
Since I had a 1.12 world open I gave this a try with no success.  Opened my SSP flat testworld.  Toggled JEI cheat mode, ensured it was enabled.  Logged into the server, cheat mode was back off, and no amount of fiddling would turn it on.

In the past, when this kind of thing has come up on the JEI issue tracker, it has been the result of permission mods or plugins, typically by making ALL players Ops, then doing permission handling itself.  Given you don't seem to be seeing JEI's "you do not have permission to use JEI's Cheat Mode" message, I expect something similar is happening here.

**Comment by mindforger** [comment]
i second ommina opinion, could not reproduce
