### ISSUE TITLE
Tag Card

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#54]
Card that can be have a 'Tag' (such as weapon, machine, bee, etc...) given to it.

When used with anything that places items into the system this card causes items imported to receive the tag. When used with anything that can retrieve items from the system, this card limits the retrievable items to anything with that tag.

So, placed in an access terminal that card would cause items items you place into the system with that terminal to be tagged and the terminal would only display items with the matching tag. Consequently, any items placed into the system with this method would also end up using a separate slot from items without tags or with different tags.

Finally, when placed in an export bus the card would cause the bus to be considered 'configured' even if it is, causing the bus to export all items with that tag if otherwise unconfigured.

Originally Posted by Darinth

This issue was migrated; For original details see http://ae-mod.info/Tracker/0525/

**Comment by joekaiser** [comment]
Instead of a tag, what about a search filter? So a card that you can type text into and anything that matches would be a valid item.

Examples are "boots" to get all boots of any material or "boots|helm" would match both.

Essentially being able to mimic the search capability of the terminal but in a card

**Comment by joekaiser** [comment]
Instead of a tag, what about a search filter? So a card that you can type text into and anything that matches would be a valid item.

Examples are "boots" to get all boots of any material or "boots|helm" would match both.

Essentially being able to mimic the search capability of the terminal but in a card

**Comment by yueh** [comment]
I do not see any particular use case to implement this.

The terminals can already be filter with view cells and distributing items can be done by using dedicated networks.

Also it would require a huge rework on how AE2 handles items internally. We have to basically redesign everything around tags. Storing them inside NBT data would even break most things like autocrafting or other mods (except if we would purge that data once something is exported from the ME network)

@joekaiser 
There are enough other issues about it on the tracker and why this is impossible.
