### ISSUE TITLE
Improved search in the Terminal

### ISSUE THREAD

**Issue by imcasper** [AppliedEnergistics/Applied-Energistics-2#5417]
**Describe the feature**
Fuzzy search. 
For example, one letter out "Iron re". It is unlikely that the person was looking not "Iron ore".
It is also convenient to search by capital letters (and some first char):
"IrOr" -- pattern for "Ir*Or*" (iron ore and may be Irridium Ornament, etc.)
"SI" -- pattern for "S*I" (steel ingot and not only)

**Reasons why it should be considered**
Its more comfortable for search in complex mod... For example:
GenFlu -- Generator Fluid
GenSo -- Generator solar
WoD -- wooden door
etc.

**Additional Context**

**Comment by yueh** [comment]
Similar to other more advanced search options, it is not reallly feasible in terms of performance. We do not have the luxury like JEI to take 10-15 seconds to build a sophisticated search tree once every time a world is loaded. Instead we had to do it each time a terminal is opened. Taking into account that the network inventory is dynamic and can constantly change, has to deal with custom item names and similar.

Having to backtrack parts of the search query can be quite costly. Especially as it will scale at least linearly with the amount of stored items (or probably worse). We already had issues in the past of having the search in which it would get stuck for a few seconds after each keypress until it finally filtered all items and updated the view.

So for now it is not really an option due to performance problems.
