### ISSUE TITLE
Failed to load datapacks, can't proceed with server load

### ISSUE THREAD

**Issue by AmonRay** [AppliedEnergistics/Applied-Energistics-2#5509]
### Describe the bug

Cant generate a new world/cant enter to existing world

Throws an error:

[03:32:29] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Item appliedenergistics2:charged_quartz_ore does not exist.

### How to reproduce the bug

Try to create new world/use existing world

### Expected behavior

Create/use a world :D

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/2908rCez

**Comment by SadBluez** [comment]
#5508 My problem was with the mod Modern Industrialization, and it's probably for you too, I see it in your mods list.

**Comment by AmonRay** [comment]
> #5508 My problem was with the mod Modern Industrialization, and it's probably for you too, I see it in your mods list.

true, world was successfully created after removing Modern Industrialization mod

**Comment by AmonRay** [comment]
removed this mod, no luck. Still got crash

**Comment by AmonRay** [comment]
if we'll dig deeper in attached file, we can find this lines:

[03:31:24] [Render thread/ERROR]: No data fixer registered for appliedenergistics2:singularity
[03:31:24] [Render thread/ERROR]: No data fixer registered for appliedenergistics2:charged_quartz
[03:31:24] [Render thread/ERROR]: No data fixer registered for appliedenergistics2:tiny_tnt_primed
[03:31:24] [Render thread/ERROR]: No data fixer registered for appliedenergistics2:growing_crystal

**Comment by SadBluez** [comment]
> 2. launched the world without any other mods (only AE2 + Fabric API). Can't see charged_quartz_ore 

They reworked the mod. This was the mod's changelog :
Early game rework. Including but not limited to: removed pure crystals (you have to grow regular crystals), amethyst shards are now required for energy-consuming blocks, certus quartz ores drop mostly dust. You can have a look at the new recipes in REI. We are interested in your feedback regarding these changes, so don't hesitate to come discuss them by opening an issue, or joining our discord server.

You can make a charged certus quartz by crafting a charger which now requires amethyst shards instead of fluix crystals.

**Comment by shartte** [comment]
Charged quartz was removed in the latest alpha. If MI has a tag that includes charged quartz, that will lead to this problem.

Nothing we can do about that, sorry.

(Not quite true, since the maintainer of MI is also an AE2 maintainer. They'll fix it soon, I am sure :-))
