### ISSUE TITLE
Unloading a Chunk with AE2 Machine Causes Some Stuff to Unload

### ISSUE THREAD

**Issue by SadBluez** [AppliedEnergistics/Applied-Energistics-2#5534]
### Describe the bug

[Title]
My machine
![image](https://user-images.githubusercontent.com/54856793/137063644-4a89e09f-42fe-4c4d-aed0-b1623392af34.png)

My machine after chunks gets unloaded.
![image](https://user-images.githubusercontent.com/54856793/137063709-781f31fe-962b-437a-b174-7ee6d4879acf.png)

You can see in the screenshots that I have a chunk loader too. (The purple table with green outlines on top.)

### How to reproduce the bug

Not sure how to reproduce the bug.

### Expected behavior

Stuff to not unload.

### Additional details

The cables are still there but they need a block update to reappear. They don't connect until the cables are there.

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/dhXJ6cxy

**Comment by Technici4n** [comment]
Yes please, world downloaded with instructions on what to do would help a lot.

**Comment by XFactHD** [comment]
This looks extremely similar to the problem I fixed in my mod here: https://github.com/XFactHD/FramedBlocks/commit/2bb44a0906a57538aa7153fbeebeb27dd9597d4c (Forge 1.16 code with MCP names).
You should be able to do something similar to that fix by getting the `LevelChunk` from the `Level` yourself after checking for its existence and then requesting the `BlockEntity` from that instead and passing in the additional argument that I added in my fix.

**Comment by Technici4n** [comment]
It turns out the problem was actually us returning `null` in `toClientTag` in some cases. Should be fixed by #5572.
