### ISSUE TITLE
[Fabric] Crystal growth accelerators shouldn't cost fluix crystals

### ISSUE THREAD

**Issue by Gerdathlete** [AppliedEnergistics/Applied-Energistics-2#5546]
### Describe the feature

In previous versions of AE2, the fluix crystal recipe yielded fluix crystals, which were used to make crystal growth accelerators. Now that the fluix recipe gives fluix dust, the only way to get fluix crystals is to use fluix seeds, but since growth accelerators cost fluix crystals rather than fluix dust, they cannot be crafted until you have already waited the full 20 minutes for fluix crystal seeds to grow. Instead of crystal growth accelerators requiring fluix crystals, they should require fluix dust, so that there is not a required 20 minute wait period for the first time a user begins in the AE2 mod. 

### Reasons why it should be considered

A 20 minute wait period is likely to put off new users of AE2, especially when there is no way for them to skip the long wait by actively working towards growth accelerators.

### Additional details

I am using AE2 version 9.0.0 alpha through the All of Fabric 4 modpack.

**Comment by SadBluez** [comment]
> It gives you fluix dust in the new version of AE2 Fabric.
Didn't knew they changed that. Thanks for telling me!

> A 20 minute wait period is likely to put off new users of AE2

AE2 is a technical mod. If the technicality of the mod isn't going to put new users off, I don't think waiting 20 minutes will. Especially when AE2 is normally in modpacks with many other mods, so everyone can just go do something else while waiting for the Fluix Seed to grow like preparing the ME system that doesn't require a Fluix Crystal.

**Comment by Gerdathlete** [comment]
> > It gives you fluix dust in the new version of AE2 Fabric.
> 
> Didn't knew they changed that. Thanks for informing me!
> 
> > A 20 minute wait period is likely to put off new users of AE2
> 
> AE2 is a technical mod. If the technicality of the mod isn't going to put new users off, I don't think waiting 20 minutes will. Especially when AE2 is normally in modpacks with many other mods, so everyone can just go do something else while waiting for the Fluix Seed to grow like preparing the ME system that doesn't require a Fluix Crystal.

Well I sure as hell didn't enjoy wasting 20 minutes doing nothing in the game. Easy to fix, makes the mod more entertaining. No reason to not want this changed. Please don't act like adding a 20 minute wait period at the start of a mod's progression is fun.

**Comment by Mari023** [comment]
I liked the idea of using amethyst.
maybe an alternative recipe for the crystal growth accelerator that uses amethyst instead of fluix?
It would have the advantage of not having 20 minutes waiting, but would also allow an alternative path to avoid hunting for geodes for ages.
I am not sure if this is feasible tho

**Comment by lilrichy** [comment]
#5545 This was kinda my thinking of having an alternative recipe for the fluix crystals. Gives the player a bit of a choice in the direction to take when starting the mod - wait out the 20 min doing other things or hunt down a geode  - possibly finding one beforehand and having it ready when time to start the mod. Also makes more choices later on when needed since once you find a geode you can get more amethyst shards but not at a crazy fast amount almost like the seed process. Seems well balanced to me. 
Although fluix dust for the growth accelerators seems a little too fast to start - maybe add a 2 tier growth accelerator like the energy cell is- regular accelerator and dense accelerator one for dust and one for crystals the crystal one having the fastest growth time.

**Comment by shartte** [comment]
Amethyst sounded like a good idea until we found out the actual spawn changes for it.
According to the wiki, every 1/53th chunk may have a geode. (https://minecraft.fandom.com/wiki/Amethyst_Geode)
Interestingly, they just updated it to 1/24th for 1.18, but that is still a shit-show to find for an early-game item in the mod.

So generally: We're still trying to figure out a good progression and see 1.17 as the "experimental version" to do it :-D

**Comment by shartte** [comment]
Currently we're considering to just enclose the skystone chest found in meteorites in fluix blocks.

**Comment by Technici4n** [comment]
Addressed by #5549.
