### ISSUE TITLE
Annahilation planes break blocks that have no drops.

### ISSUE THREAD

**Issue by NinjaPhenix** [AppliedEnergistics/Applied-Energistics-2#5640]
### Describe the bug

As stated in title, annahilation planes break blocks which do not drop anything such as incomplete amethyst buds.

### How to reproduce the bug

Have annahilation plane placed against a growing amethyst crystal and observe it will break incomplete crystals that don't drop anything e.g. small amethyst bud.

### Expected behavior

Would be better if the annahilation plane waited until it found a state which produces drops or not break the block at all.

### Additional details

Issue requested to be opened by Technici4n.

### Which minecraft version are you using?

1.17

### On which mod loaders does it happen?

Fabric

### Crash log

N/A?

**Comment by mindforger** [comment]
would you explain a bit more detailed how this should work?

how should one "configure" the annihilation pane to check for specific block states? There are blocks whithout any item that correlates to their block and their possible blockstates

and there are blocks that don't drop anything and that one is willing to still destroy but not letting you anymore since we now wait for "anything" that drops?! Also i am not sure if you can properly check the block drops before it actually being destroyed ... 

on top all my questioning, there are blocks that only by chance drop an item at all, how should them be handled?

the only thing you can do, to work around this, is using a toggle bus to disable the anihilation pane until the block is considered "ready to harvest" by you switching the bus on imho

**Comment by Technici4n** [comment]
I was thinking that we could have a setting in the GUI that will prevent breaking blocks that don't have any drop. Of course, this implies adding a GUI in the first place... And maybe filter slots in the GUI then :P

**Comment by mindforger** [comment]
yeah but that still leaves open how to properly check for the drop in first place or do i seem to overlook some obvious checkable listing?! isn't items droppping still handled during the break event?!

**Comment by Technici4n** [comment]
We already compute the drops to check if the network can accept them I think, so checking if the drop list is empty shouldn't be a problem. It's more about the implications (GUI etc).

**Comment by urmet** [comment]
I always thought that was an intentional challenge. just like when using annihilation planes for crystal growth automation. and automated amethyst farm was actually the first thing I made with 1.17 fabric AE2. 

normal annihilation planes didn't work. final working setup had identity annihilation planes with fully grown clusters whitelisted in storage bus pointing at main network interface. breaking them up would have been another step using a formation plane instead of storage bus. these placed grown cystals could then be broken by normal annihilation plane
![2021-11-04_11 55 40](https://user-images.githubusercontent.com/1254293/140293849-ef0592c9-c588-4258-b59d-9e0d281e1641.png)

**Comment by Technici4n** [comment]
Oh indeed if you use silk touch you get the small bud. I didn't know that it also existed in item form. Then yeah this can be done with identity annihilation planes (i.e. silk touch annihilation planes), so I'm closing this issue! Thanks @urmet :smile:
