### ISSUE TITLE
Early game change: removal of crystal growth

### ISSUE THREAD

**Issue by Technici4n** [AppliedEnergistics/Applied-Energistics-2#5687]
### Tentative plan for 1.18 early game changes
The goal is to get rid of the current quartz growth mechanic, which is annoying and quite hard to automate correctly, and isn't very fun anymore at this point I think.

- Allow crafting "imperfect" budding certus quartz blocks which behave similarly to vanilla's budding amethyst blocks, except that they can be picked up and moved around, and they have a small chance of breaking after successfully growing a certus quartz crystal. (Maybe 20% chance to degrade, and it has to degrade 3 times to delete itself). A side-effect is that certus quartz is going to be infinite with the proper automation setup.
- Crystal growth accelerators will now accelerate the growth rate of budding amethyst and certus quartz.
- Fluix: I'm not too sure, I need to check if removing fluix dust entirely and replacing it by fluix crystals in the recipes would be possible. If that's ok, in-world crafting of fluix will require crystals and produce crystals.

I'd appreciate feedback or other ideas.

**Comment by 19175** [comment]
I really like the idea of copying amethysts mechanic over as a replacement to the seeds. For moving them it would make sense that silk touch is required (maybe it 'degrades' a level if you don't). Because these would be automated using annihilation planes, it would make sense for there to be a version with fortune, allowing for increased drops automatically. Unless thats outside the scope of the mod, so then players would have to manually fortune it if they wanted increased drops.

With the idea of these being imperfect ones, it makes sense for there to be perfect ones too. An idea for this (extending from the surrounding meteor chests with fluix blocks idea) would be to have a meteor be either certus type or fluix type (maybe also amethyst type, not sure what use they would have tho). A certus type has the centre surrounded by certus blocks and a couple pure budding certus, and a fluix type has fluix blocks and the a couple pure budding fluix. You could possibly hide some of these in the rest of the meteor too. They would never degrade and be immovable like amethyst ones.
The advantage to using these would be they do not degrade. A speed bonus would probably be a good idea too.

A problem with providing pure versions is they can actually be moved, using spatial cells. While it provides an incredibly good use for it, I can understand it may break balance. If it does break balance too much, have all pure budding blocks get corrupted by the spatial field and turn into their impure counterpart when transported to/from the spatial dimension. 
I would prefer if they could just be moved with no downsides however.

Another thought is the growth accelerators increases the chance of an impure budding block degrading.

**Comment by EnderProyects** [comment]
I think that instead of removing the seeds you can put the two forms, being that of the crystals a superior and more efficient form, and the seeds a way of passing the powder to crystals, in the same way, mining certus without silktouch could give only dust. 

Another interesting thing for the new block that you propose would be that the block from which the amethysts grow if you hit it with a seed of its corresponding type, it will transform.

And for example, the block instead of destroying has a probability of being a block again from where the amethysts grow (I don't remember the name), having to click again with the seed or another, I suppose that it could be automatable with a bus or formationplane.

**Comment by Shnupbups** [comment]
I really like the idea of Certus Quartz coming from Meteors, them serving as an analogue to Amethyst Geodes. Perhaps you could even... get rid of the ore? **_gasps!_**

Would give more purpose to the meteors beyond just getting the presses and then they're useless. Could even inject some lore and say the meteors are fragments of a once bold and technologically advanced civilization on a planet called Certus, and that's why it's named "Certus" Quartz in-universe. (like how "Nether" Quartz comes from the Nether) But I'm just spitballing here.

And then having very rare Fluix ones (as well as being able to still create Fluix from Certus somehow) would be neat, plus maybe occasional Charged ones to replace Charged Certus Quartz Ore.

But yeah, using the vanilla Amethyst growth mechanics for Certus and Fluix seems like a really good idea to replace the current seed mechanic. Would this be big enough of a change in mechanics to call it AE3 at that point?

**Comment by xanthian** [comment]
I don't think the seed thing is too bad, once you have 1 growth accelerator its a non issue can even be automated with vacuum chests from other mods and droppers/dispensers.

Being in an established 1.17.1 world with AE at mid high tier, changing the core functionality of the base materials will be a bit of a pain and will probably make me not want to upgrade, 

For me an option would be to turn the existing growth accelerators in to a machine that works similar to the charger, 
with toggleable input and output slots so it can be automated.

**Comment by Shnupbups** [comment]
> Being in an established 1.17.1 world with AE at mid high tier, changing the core functionality of the base materials will be a bit of a pain and will probably make me not want to upgrade,

I mean, upgrading modded worlds between Minecraft versions has never really been a thing. Mods haven't mastered the art of the datafixer just yet!

**Comment by xanthian** [comment]
> > Being in an established 1.17.1 world with AE at mid high tier, changing the core functionality of the base materials will be a bit of a pain and will probably make me not want to upgrade,
> 
> I mean, upgrading modded worlds between Minecraft versions has never really been a thing. Mods haven't mastered the art of the datafixer just yet!

On the most part they are ok, at least when I last upgraded it was :)
But when the core functionality of a mod changes, that impacts world gen and would require either chunk refresh or a new world, its a bit of a pain.

**Comment by Shnupbups** [comment]
> that impacts world gen and would require either chunk refresh or a new world, its a bit of a pain.

1.18 already completely overhauls world generation, so you'd need that anyway!

**Comment by Technici4n** [comment]
Regarding fluix, the plan could be:
- The in-world recipe produces fluix crystals as in 1.7-1.16.
- You can crush these crystals into dust with a block of iron in an inscriber.
- There would be no way to turn fluix dust back into crystals though.

**Comment by DoomSquirter** [comment]
do whatever you wish with the ore.  But please don't remove the ore.  I know you cannot gauge ae or guide it knowing other mod interactions or even pack interactions, but I always look at anything a mod does to itself and think what happens when a expert pack gets ahold of it.  I would personally hate having to grow 10k certus crystal blocks vs mining a bunch of ore.  

I did many iterations of setups for fluix/etc when ae2 first hit.  But, there came a time when, if the pack didn't have ae2stf, I had to add it myself.  In-world stuff, while nice, wasn't always fun.  

I thought the initial creation of fluix crystals to be ok since it was fast, but the seeds, even with growth accels, was truly slow, prone to magnets, and I just didn't trust the despawn mechanic, especially on a server that you'd occasionally have to run clearlagg or something.  Making them full blocks instead is a really nice improvement tho.  I like that idea a lot.

and just fyi, I made the pures out of necessity.  you needed both pure certus and pure fluix for things, but you didn't need pure quartz, and thus, I never made them.  a block which is a lot more manageable in game versus some entities would probably change my mind there and would be a good alternative to getting more nether quartz.

> Regarding fluix, the plan could be:
> 
>     * The in-world recipe produces fluix crystals as in 1.7-1.16.
>     * You can crush these crystals into dust with a block of iron in an inscriber.
>     * There would be no way to turn fluix dust back into crystals though.

my normal procedure was to crush all fluix into dust and make 50% of what I have into pures.  Is the plan to remove pure altogether?  I'm not entirely sure if pures are still a thing in this new idea or not.  If pures are out then I would just crush half of all my fluix crystals.  

Even tho I didn't have a big issue with making fluix from the charged certus/quartz/redstone in world cause it was pretty much immediate, it would be nice if there somehow became a way to do this all in world as block form as well.

**Comment by Technici4n** [comment]
Going to put this on hold for the moment, we'll see how the current early game fares before reworking it further.

**Comment by Xastabus** [comment]
Personally, I like the current mechanic of crafting seeds and growing crystals in water, despite the problems mentioned.

I really don't like the idea of crafting an imperfect budding node with a chance of losing the node if I decide it's in the way and needs to be moved.  Plus, adding crystal growth accelerators (and the cable infrastructure to power them) in close proximity to budding nodes means figuring out how to place things so one doesn't accidently break the wrong things while farming the crystals.  It would be more frustrating than the current method.

I feel like just adding a machine to contain and incubate the current crystal seeds (much like the Charger does for Charged Crystals) would fix a lot of the annoyance and automation difficulty.  A "Crystal Incubator" maybe.  Perhaps the machine would have a limited throughput of a 1 stack per 20 minutes, but it would process crystals one at a time (@3.2 Crystals/min based on current base growth rate) so individual crystals would be ready faster.

Perhaps the Crystal Growth Accelerators could be used as they are currently, or they could instead be installed in upgrade slots around the incubation chamber in this proposed machine to accelerate its function.

Mostly, my thoughts are this proposal wouldn't change the current mechanic so drastically while still providing a remedy for the annoyance and automation problems.  It can be jarring when a game mechanic that has been around for years is suddenly scrapped and replaced with something that might be more annoying and difficult to interact with than what came before it.

The current crystal growth mechanic is an interesting mechanic, it just needs a machine block similar to the Charger to keep the crystal seeds contained and provide I/O slots for contained automation.

**Comment by Technici4n** [comment]
>  (How does this provide an automated farm? What automatically breaks and collects the fully developed crystals?)

Identity annihilation planes can be used to only harvest fully grown amethysts... The same would be possible here.

> The current crystal growth mechanic is an interesting mechanic, it just needs a machine block similar to the Charger to keep the crystal seeds contained and provide I/O slots for contained automation.

That would defeat the entire point of the in-world crafting though... It would basically turn crystal growing into the classic recipe in a magic-block machine.

**Comment by Xastabus** [comment]
Thank you for answering my questions.

> > (How does this provide an automated farm? What automatically breaks and collects the fully developed crystals?)
> 
> Identity annihilation planes can be used to only harvest fully grown amethysts... The same would be possible here.
> 

Sorry for not understanding the potential here.  Knowing that totally changes my opinion.

So, the idea is we could build a frame of CGAs around budding certus quartz blocks and have annihilation planes collect the fully grown crystals?  Kinda like this?
![2021-12-22_14 55 28](https://user-images.githubusercontent.com/1816386/147148374-758f0aae-ddde-4d5a-8cad-435767e99c15.png)

I like this much better than the current mechanic or the machine idea I suggested.

I'm still not terribly fond of a crafted block having an unavoidable chance of being destroyed if it needs to be moved for any reason. I found the similar randomly lossy nature of machine blocks in Industrial Craft to be unnecessarily punishing to new players just learning the mod mechanics and having to move things around a lot as they make mistakes.  Sure, with experience players can learn to plan their builds better, but watching a (very expensive) crafted block just disappear after trying to pick it up with "the right tool for the job" made me nope out of anything IC related.

Really, the only similar mechanic in Vanilla I can think of is how Anvils get damaged when used or dropped, which makes me avoid using them unless absolutely necessary (or unless there's a reasonable way to repair the damage).

If the degradation mechanic could be optionally disabled or be reversible for a reasonable cost then this idea would make the whole crystal growth process much better.

**Comment by Technici4n** [comment]
Yes, that's the idea.

> I'm still not terribly fond of a crafted block having an unavoidable chance of being destroyed if it needs to be moved for any reason.

My idea is that the budding certus quartz would only degrade when a crystal is grown, not when it is moved. So a fully automated setup would require using formation planes to replace budding blocks as they get destroyed, but you could probably get 30 crystals or so on average with a semi-automated setup. (manual bud placement, automatic harvesting)

**Comment by Xastabus** [comment]
With the budding block surrounded in CGAs, Identity Annihilation Planes and cables it will be difficult to tell when the block has broken and or which budding blocks may be broken if someone has multiple blocks set up like my image above.

Manually replacing the budding crystal blocks will require taking part of the cage apart and (assuming one is farming all 6 sides of the block) placing a temporary block.

Using a Formation Plane to replace it would sacrifice one of the growth sides, which would make the setup easier to maintain at the cost of a slightly slower production rate and a bit higher energy usage due to the additional network components required to fully automate placement.

With the goal of getting to an "automate and be done with it" setup, the tradeoff seems reasonable.

**Comment by ntindle** [comment]
I would like to voice support for these spawning in the form of the meteor. 

It would be cool if it encouraged spacial things to transport/automate but that may require more work than it’s worth.

**Comment by Xastabus** [comment]
Considering the "imperfect" budding crystal mechanic, being able to collect "perfect" (but normally immobile) budding crystals from meteors with spatial storage would probably encourage me to actually learn how to build and use spatial storage.  (Assuming the "perfect" budding crystals don't get blacklisted).

Discussion of the imperfect budding crystals pushed me to actually learn how formation and annihilation planes work because I finally understood a purpose for using them.

Having access to budding crystals that don't break and require replacement eliminates the need for a formation plane in the fully automatic crystal farming setup.  I feel like being able to move pure budding crystals with spatial storage could be a kind of end-game goal?

I wouldn't want spatial storage to degrade or corrupt pure crystals as suggested much further back in the conversation. It would be really discouraging to put in all the work to learn about spatial storage and build and power the system (twice) only to get impure budding crystals out of it that I could have just crafted myself.

Could it break balance? ... I mean, once you have the ability to digitize an entire room and store it on portable media what does "break balance" really mean?

**Comment by Mementh** [comment]
adding my 2 cents here.
I like the growth as it is. its been stable and works, yes it takes a bit of work with other mods.
so, why not make a multiblock deal that helps do this? 
has on top a part that "automates" it and thats the expensive part for later on/making it easier.
on the bottom you have the standard 5 accelerators .
this way at the start its "easy but takes time"

the crystals can be found in meteors thats ok, using sand to "grow new ones" from seeds would be ok, but i would say there needs to be a way to always have a seed so you don't run out.
So lets say you use a master seed to grow with? it always outputs, aka master seed + 2 of the other crystals. 

you can make more master seeds but they grow like the nodes i saw mentioned..  placed on the ground.. waterlogged? and accelerators make it faster?

could use crushed netherrock as the thing to combine with the dust to make the nether crystal.
redstone to make the fluix
default is the certus

charged used for the power systems ( energy cell, acceptor and controllers )

**Comment by Technici4n** [comment]
Might be for 1.19 or even later yeah, I agree that we definitely need to give AE2 earlygame a breath of fresh air, however I'm mostly focused on small-ish bug fixes or features at the moment.

**Comment by Mementh** [comment]
I like the idea of something being special, grown in the real world but not of it ( no ores ) and using the matter balls as the core/material to make them.
I think having it as the start is a good thing, but it could use the growth accelerators as we have now to grow faster .
And integrate the ae2 stuff box of a growth chamber but making it a multiblock.

the idea would be, growing is going to give great quality/quantity.
And artificial or super speed up gives just a few or basic.
And over time you learn to make better faster ?

**Comment by Mementh** [comment]
I can understand, its almost a multiblock as it is then? just not magicly together when done.

strait up, the planes i have seen no guides use them and know not how to do that! 

i do like the idea of a growing bed, using the growth machines to accelerate it as they do already.

**Comment by Tahakk** [comment]
You have to consider multiplayer tho. 
From a client point of view you don't want to run miles because other meteors are mined by other players.
From a server point you don't want to really generate 10k world because of the backup sizes.

That said another style of crystal growth would be nice - doing it crop style (actually growing crystals). Or instead of ores you could make it into similar style as amethyst block pockets, where you find huge pockets or ore/blocks that could be mined but are quite rare.

**Comment by Technici4n** [comment]
For multiplayer, maybe we could add an AE2 villager, or add imperfect / inert budding certus to loot chests in structures (again, more exploration). 

BTW, I think we will be going for some variation of @l-ricardo's suggestion in https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/5687#issuecomment-1115237110.

**Comment by Silfryi** [comment]
> You have to consider multiplayer tho. From a client point of view you don't want to run miles because other meteors are mined by other players. From a server point you don't want to really generate 10k world because of the backup sizes.
> 
> That said another style of crystal growth would be nice - doing it crop style (actually growing crystals). Or instead of ores you could make it into similar style as amethyst block pockets, where you find huge pockets or ore/blocks that could be mined but are quite rare.

And you don't want to have to deal with the fact that everyone has grabbed up all the certus _ore_ near spawn or a base, or that everyone has taken that structure some other mod needs for progression's loot, or that there's no good villages with the XYZ thing you need in range. Sometimes the world just doesn't have things in the way you're worrying about and players can always share their crystal growth setups or products.

And I do agree with Technici4n that the villager there would help alleviate the pressure.

**Comment by Technici4n** [comment]
Please have a look at https://github.com/AppliedEnergistics/Applied-Energistics-2/pull/6380 for a detailed list of the changes. Feedback is welcome, preferably on our Discord server for more interactive discussion (#dev-talk channel will do for this), but on Github it is also fine.
