### ISSUE TITLE
Suggestions: ME Data Monitor, ME Power Monitor, ME Storage Optimizer

### ISSUE THREAD

**Issue by lrwerewolf** [AppliedEnergistics/Applied-Energistics-2#598]
A few ideas I had while trying to manage my AE2 network.

ME Data Monitor
Would display summary data showing how many K available, how many K used, how many item types in use, how many item types available.

ME Power Monitor
Would display power utilization in AE/t for the network.  Optionally, right click with empty hand to cycle through various power types (ie: BuildCraft, Mekanism) equivalents.

ME Storage Optimizer
Would scan storage for opportunities to combine split stacks (an amount of cobblestone on two different storage units) by moving them to different or higher capacity storage.  Would attempt to locate items with the same ID but different data to the same storage unit.

**Comment by Mochnant** [comment]
The ME Storage Optimizer is a great idea, and one I have considered before.  As far as it being too difficult because everyone's needs are different, I'd have to disagree.  If it simply found opportunities to combine stacks and move small stacks to small storage and large stacks to large storage, it would remove a lot of the tediousness of AE2 storage management.

**Comment by Cisien** [comment]
The io port combined with pre-formatting cells will accomplish what you are requesting

**Comment by Mochnant** [comment]
@Cisien I would call that a manual process in that case, not what an "auto balancer" would be doing.

**Comment by yueh** [comment]
It does not need to be a manual process nor does it require pre-formated cells.

Your example might work if it would not miss something very important.
There is no large or small storage in AE. Just storage and if it is full or not full.

**Comment by Mochnant** [comment]
@yueh Perhaps I am missing something, but I do not understand what you mean.  There is large and small storage, 1k vs 64k cells.  When you bring the type limit into it, cobblestone could fill many 1k cells that would be better used storing items with very low counts, and ignoring large 64k cells that could better handle the large amount.  

That means I'd have to preformat all my larger cells with items I want there and set priorities correctly, and then push all existing cells through an IO port.  This does work, and I expect most people have to do this or else spam storage cells.  I would, however, consider it a "manual" process.  I'd rather have a block that would move items around to maximize my storage efficiency.

**Comment by yueh** [comment]
They appear to humans as storage with different sizes. But for AE2 it is just the cell is full or not full.
Also we deal not only with cells, but every other inventory through the storage bus and just one inventory with a strange size is enough to completely disable anything about an autodefragmentation.

For example a condenser/trashcan is basically an inventory which can hold an infinite amount of types and stacksizes. I am sure you would find it very helpful to attach one to your network and then the network just dumps everything into because it is the best available inventory.

Or another reason against it, is that it will cause horrible feedback loops. The system does not know anything about how it should predict the possible amount for each itemtype. So it would just stick it into the smallest inventory first and then start moving the stack around if it gets to large. Doing so will take inventory space away from another itemstack, causing this to be moved to somewhere else and so on until the complete network got shuffled around in a single tick. With the next tick the very first itemstack shrinks enough to fit into the smallest inventory and everything will flow back. Until everything repeats the next tick.
Of course it would result in a perfectly organized storage system, but I am not sure if you want to play with 0-1 FPS.

Back to the IO Port, it is the block that moves items around. And no, it does not require preformatted cells or priorities (maybe besides your condenser, but that can be prevented).
Just be creative with it.
Just to throw it in, the only thing (I currently know of) which prevents from AE2 storage being self contained and needing no more manual intervention, is that formation planes cannot be configured to place parts in a configurable direction.
And this is probably the last comment about the IO Port, as I do not like to give build help on a bug tracker.

**Comment by Mochnant** [comment]
@yueh I appreciate the insight, and while I do understand where you're coming from, I think I'll just agree to disagree on the usefulness of a storage balancer.  As to your point on the lag caused by constant movement, I agree, and I would not suggest the system would reshuffle your storage network every tick.  Once a minute or even once per hour would be an improvement.

As pointed out earlier, all the tools are available already for this to be made by a 3rd party, so that avenue is open to any interested people.

Thanks again.

**Comment by Blue64** [comment]
I would recommend it cycle once on a Redstone Signal (meaning I regardless of if it's a Button or a Lever, it runs ONCE, then waits for the signal to stop before being able to be triggered again). Obviously you'd want to only run it on specific Cells, no Void Planes or Trash Cans, but alternatively, is it possible to automate the I/O? If you can pull the full Drives out of their slot, then run em through the I/O for a Data Dump, then return the Empty Drive to it's Slot, it'd save much frustration, especially since once the 6 slots of the I/O are full, it'd be unable to get more items stuffed into it.

On a similar note, is there a way to specify certain conditions on the Import/Export Bus such as Extract Fully Charged Wireless Controller, regardless of it's link status? Alternatively, Storage Cell with 63 types of items, even if the size isn't filled up, or vice versa?

**Comment by mindforger** [comment]
>I would recommend it cycle once on a Redstone Signal (meaning I regardless of if it's a Button or a Lever, it runs ONCE, then waits for the signal to stop before being able to be triggered again)

would you please test things first before posting/necroing about it ? This is already implemented!

**Comment by Blue64** [comment]
@mindforger I've been testing, tweaking, and tinkering, in creative, for days, I've yet to find a way to automatically dump drives into the ME IO Port once they're full. I haven't gotten to the level emitter yet, but as it's primary purpose is to emit a redstone signal, I don't see how it would recognize a full ME Storage Unit, pull it out of the ME Drive, dump it into the ME IO Port, then put the emptied drive back.I suppose that might be possible with a Whitelist on an Import/Export Bus, but what if it's not full on types too? I can only add 45 variations of a full drive, assuming the whitelist doesn't check the contents as well (which I'm going to assume it does for now as I'm in the middle of 3 other AE2 tests currently and I get easily distracted), but apart from that route, what rv & version is it implemented in? I'm on rv2 Stable 10, so if it's implemented into rv3, there's a reason I'm oblivious to this information, it's an entirely different build.

**Comment by mindforger** [comment]
redstone behaviour on import/export busses is either available through GUI directly or after adding an redstone card ... click the tiny redstone symbol until you find "pulse mode" ...  `I would recommend it cycle once on a Redstone Signal` done! ... sorry if i spoilered somebody with this info ...

**Comment by Blue64** [comment]
Ah, in that case, all they'd need to do is implement the Redstone Card, well done mindforger, I hadn't seen that function yet either (I usually idiotproof my builds to prevent issues from various environmental variables [creepers, water, etc] so I never learned to effectively Redstone, thus my lack of experience with it).

But as the suggestion is for the storage optimization device, and I've yet to find any such method of automating this short of perhaps a text filter with a wildcard (which AE2 as far as I can tell doesn't have available, it's all fuzzy/explicit, not even oreDict support, noticed Extra Cells added that, so I'd need to outsource it), then the suggestion still stands.

**Comment by Blue64** [comment]
This idea is still possible to some extent, just make a little mini Virtual Intelligence that you can tell to store certain things I certain priority ranges, and it can run once every X amount of tick/sec/min/hr with X being a variable, and the measurements being various options. If y'all feel it's too OP, you could simply make it require it's own Dense Cable, but then you'd need to correct the Dense Cables only providing 8 Channels per Connection (can't Daisy Chain 2 sets of 16 ME Interface Blocks for Molecular Assemblers as I wanted, so I had to do 4 sets of 5 and 2 sets of 6 to keep it in the chunk). Was that an intended feature, or accidental?
