### ISSUE TITLE
1.18.1 meteors dont seem to be spawning

### ISSUE THREAD

**Issue by Flame115** [AppliedEnergistics/Applied-Energistics-2#6023]
### Describe the bug

ive flown all over my world and haven't encountered a single meteor. I've tried to use the /locate command aswell and have had no luck.

### How to reproduce the bug

not really sure, they just dont seem to be spawning.

### Expected behavior

to have them generate.

### Additional details

ive checked the config and the spawning for them is indeed set to true

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/QEJzZwjN

**Comment by mindforger** [comment]
please check past issues, if i remember right, terralith may cause this, but i don't know if it has been fixed

**Comment by MrJorman** [comment]
+ fix pls.

**Comment by Panderine** [comment]
I have this issue as well but it only happens when combining Terralith + Terrablend. If you use just one of them with AE2 it works. Also this is the only structure mod that fails with both other mods. Terralith and Terrablend are wildly use because of their nice features. Could someone from AE2 team have a look a this?

I did 3 tests with this mod versions:

ae2 10.1.0-beta1
Fabric API 0.46.4+1.18
SeedFix + Terralith 1.0.0
TerraBlender 1.1.0.73

The results:

All the mods = NO meteorites
Terralith + AE2 = meteorites
Terrablender + AE2 = meteorites
So there must be something having both that doesn't work for AE2 i guess?. 

Other structure mods have no issue with this combination.

**Comment by urmet** [comment]
I just figured out a smaller list:

AE2+yung's api = meteorites
AE2+terralith = meteorites
AE2+terralith+yung's api = no meteorites

**Comment by buhanec** [comment]
I briefly played around with AE2 in combination with YUNG's API and Terralith, see: https://github.com/yungnickyoung/YUNGs-API/issues/22#issuecomment-1079957633.

Seems either AE2 with Terralith or AE2 with YUNG's API works fine, the two combined don't generate the meteorites.

Tested with:
- `appliedenergistics2-10.1.0-beta.2`
- `fabric-api-0.46.6+1.18`
- `Terralith_v2.0.12_Fabric+Forge`
- `YungsApi-1.18-Fabric-36`

**Comment by shartte** [comment]
We're honestly not going to invest a ton of time into this for 1.18.1

1.18.2 has overhauled the entire system for deciding where structures spawn and these problems should go away entirely from 1.18.2 forward.

**Comment by Panderine** [comment]
makes sense! Thanks for reaching back!
