### ISSUE TITLE
Cannot craft fluid buckets (reliably)

### ISSUE THREAD

**Issue by mnsnownutt** [AppliedEnergistics/Applied-Energistics-2#6065]
### Describe the bug

Fabric version - 10.1.0-beta.2
Other relevant mod TechReborn - 5.1.0-beta.5

I have a ME fluid drive with water on it and tried crafting water buckets, but could not.  Evidently, you cannot autocraft them from the drive itself using a process pattern in a pattern provider.  I then set up a system using a Tech Reborn tank, to insert buckets into it (see photo) and it works, but only for awhile.  Eventually, it stops working and the only way to get it working again is to break the tank and the pattern provider and place them down again.  It will then craft buckets for an indeterminate amount of time and then stop again.
![2022-02-12_11 35 21](https://user-images.githubusercontent.com/31514693/153723229-adeb75a1-6092-42ef-921f-a66571229914.png)

### How to reproduce the bug

Above

### Expected behavior

Expect to be able to autocraft water buckets when needed without having to break everything to reset it.

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Fabric

### Crash log

https://pastebin.com/SjV06uHT

**Comment by Technici4n** [comment]
Is this specific to `10.1.0-beta.2`? Or do you have the same problem with `10.1.0-beta.1`?

**Comment by mnsnownutt** [comment]
Happened with both.  I went to file the bug report for beta.1 and noticed there was a beta.2, so I updated and tried it and had the same results.

**Comment by mnsnownutt** [comment]
Does not craft at all, just hangs in the computer.

**Comment by mnsnownutt** [comment]
I will close this issue.  I discovered that if you remove the water as a crafting ingredient, it then crafts the water buckets using the tank.  Not sure why that worked, but it did.

**Comment by GHXX** [comment]
Sorry for sortof necro-ing this ticket, but i also have experienced this a couple times in the past (on 1.12 (most recently using AE2 rv6-stable-7 ) when filling buckets using a pattern as such: input: 1x empty bucket; output: 1x filled bucket (using a thermal expension fluid transposer)
The reason i am writing a comment instead of a new ticket is that a) i haven't had the time to make a clean install with just AE2 (as we are running with wireless crafting terminal right now), and b) this issue is likely related

It appears that AE2 is re-using intermediate buckets (which is very nice), but there appears to be a bug when a recipe uses two water buckets. (Assume there are no buckets nor water buckets in the system) and you want to craft a few blocks, each of which using two water buckets (such as nuclearcraft infinite water sources). 
If there are no water buckets nor empty buckets available, one bucket will be crafted. Crafting gets stuck
If there is one empty bucket only, no extra bucket will be crafted, Crafting gets stuck
If there is one empty and one water bucket (or two empty buckets), no extra bucket will be crafted, but crafting will succeed

**So i think what the issue comes down to is the fact that AE2 only crafts a single empty bucket no matter how many buckets are required, when it really should craft as many buckets as needed** (essentially the total number of buckets in a single recipe, minus the number of filled buckets in the system, minus the number of empty buckets that are already available)
I attached a few screenshots in sequential order, to visualize whats happening
### Case: No buckets at all
Initial state
![image](https://user-images.githubusercontent.com/5289076/156282957-4122b8cd-3df4-4e59-ab71-de966802aac7.png)

Recipe
![image](https://user-images.githubusercontent.com/5289076/156283004-63d3b515-38a7-4fcf-a76b-e837c2ccf6dc.png)

Appears to be crafting, but is already stuck on the buckets essentially
![image](https://user-images.githubusercontent.com/5289076/156283040-18b29e4b-5e3e-4961-8565-f808213eb2b0.png)

Final stuck state
![image](https://user-images.githubusercontent.com/5289076/156283069-923593cd-136f-459f-b2f3-28014d31ceb8.png)

Items, while the task was still running (Still had the one water bucket locked)
![image](https://user-images.githubusercontent.com/5289076/156283125-ded43a50-2629-43ba-a943-b31717595623.png)

Items after cancelling the task
![image](https://user-images.githubusercontent.com/5289076/156283165-dc151489-6690-4933-bdd3-e1fae12458cd.png)

### Case: 1 Water bucket, No empty
This is exactly the state we are in after running the case above, and it actually just is stuck immediately as it does not craft any extra buckets. (Same screenshot outcome as the last crafting-view screenshot in the first case)

--------------------------------------------------------------
### Case: 1 Water bucket, 1 empty

Initial state
![image](https://user-images.githubusercontent.com/5289076/156283593-3f0ccbfe-e6e0-49f8-950f-176306439c22.png)

Crafting plan
![image](https://user-images.githubusercontent.com/5289076/156283631-e313b2f8-50db-4040-9ee8-456c68448946.png)

Crafting status
![image](https://user-images.githubusercontent.com/5289076/156283648-041bb753-56aa-4e29-a597-f66b781f128b.png)

The bucket-job is just always green until its done, so yes, in this case it does work as intended.

A good workaround for now seems to be keeping a large stock of buckets.
**I want to point out again that Wireless Crafting Terminal is installed, but i think you should be able to reproduce the issues.**

**Comment by Technici4n** [comment]
Please don't necro issues, and in any case we don't provide support for 1.12 anymore.
