### ISSUE TITLE
Invisible cables

### ISSUE THREAD

**Issue by Raft08** [AppliedEnergistics/Applied-Energistics-2#6146]
### Describe the bug

Cables are invisible and i need to cause a block update to make it visible again.
And i glitch when i run on cable

You can find a video [here](https://www.youtube.com/watch?v=8J1LmNF4rMI)

### How to reproduce the bug

I'm not sure

-Create a Minecraft Forge Server
-Create a simple applied system with cables
-Unload the chunks

### Expected behavior

That i will see the cables

### Additional details

[My modpack](http://raft.ddns.net/modded/bug/modlist.html)
And cable does still work i can start a craft without any issue

### Which minecraft version are you using?

1.16.5

### On which mod loaders does it happen?

Forge

### Crash log

https://github.com/Raft08/Modded-Bugs/blob/main/latest.log

**Comment by Technici4n** [comment]
This looks like it could be a modpack issue, since it's the first time I've seen this issue in 1.16 forge. That's also why I suspect it's not our fault, but rather a bad interaction with another mod. I'm afraid you'll have to find the culprit mod yourself though, especially since 1.16 doesn't receive much support from us anymore.

**Comment by N7NobodyCats** [comment]
did you find out what was causing the issue raft? im having a similar issue with cables and terminals going invisible.
