### ISSUE TITLE
Export All/Wildcard card 

### ISSUE THREAD

**Issue by NFLD99** [AppliedEnergistics/Applied-Energistics-2#6314]
### Describe the feature

This would be a card that allows for exporting everything in the system, or a card that you can enter tags (like ae2:*) to export all items matching the regex 

### Reasons why it should be considered

Currently exporting everything or everything from a mod is a long process of multiple filters, adding this card would allow the process to be more streamlined

### Additional details

If performance is the main factor, make the card only obtainable via creative

**Comment by Technici4n** [comment]
Exporting all is not going to happen due to performance issues.

> If performance is the main factor, make the card only obtainable via creative

No, the mod is designed to be played in survival. We won't be adding problematic features just for creative mod. Before you say it, the creative cell exists for easier developer and setup testing, mostly, and it doesn't cause performance issues. Plus modpacks would find a way to make it obtainable, thereby destroying performance anyway. :P

Exporting by tag is already tracked by #6143.
