### ISSUE TITLE
Chain Pattern Providers / Pattern Providers with more than 9 slots

### ISSUE THREAD

**Issue by Technici4n** [AppliedEnergistics/Applied-Energistics-2#6344]
Maybe we could have a mechanic where "chaining" pattern providers by placing them on top of each other would achieve a similar effect? The main concern here is that blocking mode should ideally work with the whole pattern provider "chain".

We could also give Pattern Providers additional pattern rows, that would be unlocked with capacity cards. I feel like this might be way too OP though, which I don't like. So the first solution is likely better.

**Comment by atlgeek007** [comment]
I would say that expanding processing patterns should be considered, not standard pattern providers - even if it's using a special pattern expansion card that's really expensive to make.

**Comment by Tahakk** [comment]
Definetely not stacking. Really like how you can put interface on every side of the block, but in that case you could not stack them. 

Interface tiers or rather card expansions seems like way better solutions.

**Comment by BonaireDreams** [comment]
I like the idea of expanding with capacity cards. Limit it to 2 additional rows for a total of 27 recipes. The downside to using additional cards of course is you still end up waiting for assemblers to be available if you're requesting multiple crafts from the same provider. In my current custom modpack I already have 32 providers full of recipes for shaped crafting and will most likely need double that. Its also nice not having to make a second set of machines just because you need, say 12 gear recipes and only 9 fit in a pattern provider.

**Comment by Technici4n** [comment]
I don't like the idea of using a capacity card, it just feels like "bigger" for no reason. I think using a subnetwork is appropriate for these situations, i.e.

```
pp -> interface -|
pp -> interface -+- storage bus -> machine (then here a way to import back to the main network)
pp -> interface -|
```

The only issue is that this won't work with blocking mode currently, however I already have a fix in mind for that.

**Comment by 62832** [comment]
Just my two cents, but should the larger pattern providers with more rows be an option in future I suggest there be the catch that they only support processing patterns when going beyond 9 slots. I imagine otherwise it could become clunky for large Molecular Assembler / Pattern Provider arrays to have to deal with yet more stored patterns competing for the same set of Assemblers.

**Comment by atlgeek007** [comment]
I definitely concur that it should be processing only. Those of us who hate duplicating machines unless absolutely necessary would love the option.

**Comment by DAmNRelentless** [comment]
Also not a huge fan of stacking providers. It makes everything pretty clunky. Tiered providers would be cooler or upgradable providers.

**Comment by Technici4n** [comment]
Ok so this is not going to be implemented because subnetworks are a good alternative, and I heavily dislike features that are just "same as <other feature>, but better/bigger/faster".

To fix blocking mode when multiple pattern providers are used, I would like to look into linking pattern providers, details tbd: #6359.

**Comment by set92** [comment]
I'm curious, mainly because of lack of tutorials or good explanations on how to use channels/subnetworks... but if we can't have bigger pattern providers, what is the right way to connect a furnace? Because there are plenty of different ores which I want to smelt, but if a pattern provider only allows me for 9 recipes I suppose I would need a need furnace every 9 ores? 

I suppose I could surround the furnace with pattern providers, but don't think that's pretty or a good solution

**Comment by Tahakk** [comment]
You can connect your furnace on multiple sides, or you can pump the items to the chest/s and then pull it with pipe to the chest... many options
