### ISSUE TITLE
Add a setting to Pattern Providers that waits for a Redstone signal before inserting another set of items for crafting/processing

### ISSUE THREAD

**Issue by Mylezz** [AppliedEnergistics/Applied-Energistics-2#6346]
### Describe the feature

Add a setting that makes Pattern Providers wait for a Redstone signal before inserting the next set of items for crafting/processing.

It would be similar to the crafters in refined storage,

- Redstone pulse inserts next set
- Redstone signal locks crafting
- Redstone Signal unlocks crafting
- Redstone Signal Ignored

### Reasons why it should be considered

It would allow for automation with mods that AE2 cant directly interface with, and gives greater customizability to how we can set up automation flows for mods we could not previously automate. 

It also provides an interesting way to lock recipes behind Redstone logic which can be useful in certain scenarios where timing is critical.

### Additional details

I am currently trying to automate Botania's runic alter in ATM7 but I can't directly connect a pattern provider to it because it's not a standard inventory, so I'm using a hopper and an open barrel to deliver the items into it. However, I can't stop the flow of items if I am crafting more than one of anything at a time or multiple recipes in the same pattern provider, so it just dumps everything onto it and creates a giant mess. Refined storage has an option to make the crafter wait for a Redstone pulse before sending the next queued crafting recipe into the container and this allows me to automate it but I prefer AE2 over refined storage and I think this would be an excellent addition for AE2 that gives greater flexibility for automation.

**Comment by Technici4n** [comment]
What you are trying to achieve should already be possible using blocking mode. In blocking mode, a pattern provider will not push the recipe if it detects that the inventory it is connected to contains an item that is an input for one of the patterns.

So for example, placing the pattern provider in blocking mode on the open barrel seems like it should work, since the pattern provider will refuse to push a new recipe while there are still items in the open barrel.

**Comment by Mari023** [comment]
you can always work around such inventories with e.g. a hopper

**Comment by Mylezz** [comment]
I've tried using blocking mode and I've had some success with it if I'm only crafting one of each it'll just dump the items on top of it craft one then do the next. But anytime I requested to craft more than one of the same item it clogs up. I am currently using a hopper but It only continually dumps, and I've tried Hopper locking it but I can't get the signal quick enough to stop it from dumping prematurely. This would be something completely different and distinct It would be quite useful for more than just my use case.

**Comment by Mylezz** [comment]
Here is a video example 

[https://youtu.be/M2QE7LZ9-Wg](url)

**Comment by Technici4n** [comment]
I see. However, it seems like you should still be able to solve your issue with some redstone wiring. ;)

For example, what you could do is: connect the pattern provider to a subnetwork with a toggle bus, disable the toggle bus when you detect that items enter the crate (using a comparator), and then re-enable it once the botania craft is done. If you want to discuss this, some people should be able to help you further on the AE2 discord.

I don't want to add this feature because it should be possible to achieve what RS' redstone blocking mode does in other ways. Most of the time, the AE2 way is easier, but in some edge cases like this one, it will probably take a bit more redstone.
