### ISSUE TITLE
Molecular Assembler showing as "Device Offline" when placed under certain conditions

### ISSUE THREAD

**Issue by Sakreton** [AppliedEnergistics/Applied-Energistics-2#6383]
### Describe the bug
EDIT: nvm this seams to be completely random i reproduced it a few times in a row with the method a describe further down, but while trying to fix the others to do their RGB thingy i cant seam to do so.
If this somehow helps you anyways, nice if not just close this issue ^-^

In the "The one Probe" tooltip molecular assembler are shown as Device Offline, even though they are connected and can indeed craft.

### How to reproduce the bug

Place a molecular assembler against a pattern provider while being adjacent to another molecular assembler
![image](https://user-images.githubusercontent.com/55781722/174680081-db971c65-5b51-42df-8843-1360abdfb467.png)
Power is supplied to the very bottom assembler
### Expected behaviour

Show them as online when they are online and as offline if they are offline

### Additional details

Running on a Server, tried relogging and replacing the block

im sorry... BUT there is a typo in the bug issue template, "Expected behaviour"
### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

**Comment by Technici4n** [comment]
> im sorry... BUT there is a typo in the bug issue template, "Expected behaviour"

No, behavior is American syntax.

In that specific setup, the molecular assemblers do indeed seem to be online, because a pattern provider in directional mode (so either the part, or the block with a visible arrow) will not connect to its target. You need another cable or quartz fiber to power the assemblers most likely. Can you check?

**Comment by Sakreton** [comment]
ahh well my bad then^^ <- Wannabe typo

Already "fixed" it while doing so i could not find any way to reliably do it though, it felt random.
If i somehow find a way to reproduce it i will let you know / open a new issue.

**Comment by MisterMyst** [comment]
I appear to be seeing this same issue. I'm not sure I understand what you mean by "directional mode" on the pattern providers. Doesn't seem to matter how I set it up, the molecular assemblers will randomly appear as offline. As far as I can tell it's purely visual, the assemblers still craft things and work perfectly fine, they just don't light up and TOP says "Device Offline." They don't start offline, but after some time they'll change to offline. Could be relogs, could be server restarts, could be something else. They're chunkloaded and on a server. Breaking and replacing them makes them online again. Also the network is fine on power.

**Comment by MisterMyst** [comment]
![image](https://user-images.githubusercontent.com/86211311/187052722-dd993934-9f4c-48f9-b9ec-5fbca8a3f696.png)
Here's a quick snippet of the assembler working even though it's not lit up and TOP says "Device Offline"

**Comment by mindforger** [comment]
Patternprovider in blockmode can be omnidirectional or directed, indicated by an arrow when wrenched, and the target will then not be connected. Your setup seems to encourage path finding issues, blocks can only share 8 channels to each other, meaning of you have a 8 channel connection which by chance blocks all faces of a particular 9th block it might end up without a free channel.

As an advice, try to omit block connections larger than 8 blocks or provide enough cable connections on different points ... This info might be outdated, since I did not try out this version yet

**Comment by Technici4n** [comment]
That sounds like the same issue as https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/6432, the fix is ready and will be in the next release.
