### ISSUE TITLE
1.19: Rework meteorites a bit

### ISSUE THREAD

**Issue by Technici4n** [AppliedEnergistics/Applied-Energistics-2#6399]
Meteorites should be hollow, with some certus quartz blocks, and a few budding quartz blocks with buds on top. They should also not contain fluix anymore because the crystal is crafted directly.

**Comment by Silfryi** [comment]
Also from linked PR: I suggest the possibility of only _underground_ meteorites being hollow (like the underground water hollowed them out), and instead having aboveground ones be solid certus quartz with budding blocks intermixed randomly

This would create a little bit of a fun dichotomy, I feel - if you want the fastest and _easiest_ way to _farm_ first, you find an underground one, and can farm right away

The largest _quantity_ of certus quartz and of quartz nodes is on the surface, but because they're not in the surface of the internal hollow, they're harder for farming even if there's more of them.

**Comment by Mementh** [comment]
The growing would like to see in game videos.
In terms of meteors what made them? Or who? 
why do they have chests? And stuff inside the chest?!?

If natural it should not have anything but the raw stuff inside.

instruction manual would be good via other means.

 I did not get a chance to comment but i love the matter ball idea for growing crystals. You just make the can and dump stuff in and "compact it "

i do think "electric/charged" crystals are not needed in general. 
maybe if making a battery system or related to power?

The idea of fluix for the parts that grow and shrink should stay but not be hard, crush certus and redstone and nether in grid to make 2-3 dust and grow special?

**Comment by Technici4n** [comment]
Meteorites will look like this for now:
![image](https://user-images.githubusercontent.com/13494793/177218547-7297b351-b927-4de6-afd4-991697a96d1f.png)

Further improvements might come one day:tm:, but for now I want to get this release out.
