### ISSUE TITLE
How I'm can cancel interact with multipart cables 

### ISSUE THREAD

**Issue by Serious07** [AppliedEnergistics/Applied-Energistics-2#645]
Hello, I'm have a problem on my server with ME Glass Cable, I'm develop a simple system to protect blocks of player in pryamoygolnoy area, I cancel any BlockEvent.BreakEvent and PlayerInteractEvent inside protected zone, but MultiPart cables don't react to this Events, when I'm use shift + Quartz Wrench on cable in this zone, any can use Quartz Wrench and steal stuff.

I'm want ask, your team, how I'm can cancel using Quartz Wrench, on ME Glass Cable for example, I'm realy try find way by my self, but it was 6 hour exploring, with out any result.

I'm use AE2-rv1-stable on my server.

Sorry for my bad english, it is not my primary language.

**Comment by axelpx** [comment]
One of my friends solved this problem somehow. I know that he edited the mod using Eclipse and recompiled it for me. It took him like 30 min. Now he is away from home, so when I updated the mod to the latest version this issue came back.

"So without breaking it and rewriting the part placement, we could probably only prevent some cases." - sorry, but that's not true. :(
