### ISSUE TITLE
Autocrafting lockup bug

### ISSUE THREAD

**Issue by halvors** [AppliedEnergistics/Applied-Energistics-2#648]
Autocrafting lockup bug when crafting Mekanism solar panels. Tested using both the rv1.stable build 1 and rv2.beta build 3.

This seems only to affect Multiplayer, works great on Singleplayer.

Here is a video showing the issue: http://youtu.be/I7JpRtMfjGA

**Comment by halvors** [comment]
Any idea why this is happening? Should work as shown in the video all the items is crafted using ME.

**Comment by thatsIch** [comment]
Maybe another mod interfering with the setup?
You give us not much of a hint to reproduce it, but the Forge Version and the AE version.

**Comment by ignisthedragon** [comment]
Same here with Forge 10.13.2.1230 and rv2.beta build 7 /rv1.stable build 1. The problem is, that his video shows everything which we can provide. There isnt any log entry at the server or client log for this bug. The only thing I figured out is, that the problem gets even worse, if youre using storage buses at deep storages. ( https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/682 ).
At my world, the problem started at one point where my system became realy huge and started to use many channels and many p2p tunnel as well. But to disconnect parts of the network or resetting the controller didnt help, so I think thats an fortuity.
@halvors - Can you please try to put the items, which are required for the crafting job into a chest, which is provided via an storage bus instant of an me drive?
@thatsIch - If you need any specific information, feel free to ask

**Comment by desagas** [comment]
I have more than 200 deep stores hooked up to storage buses, so I believe they are not the issue. I only had an issue when I had multiple storage buses for 1 type of item, as when I fixed or removed the duplicates, it worked 100%. Sounds more like an auto-crafting issue based off of the system recognizing both storage areas and requesting the same crafting component item twice.

**Comment by yueh** [comment]
I do not think so.

But as you never stated which mekanism version you used, I assumed the recommended one.
The changelog for .144 says something about making more OreDict compatible (or break it more?)
But even with .145 I cannot reproduce it. The only change is that before .144 every Energy Tablet did work and with .144 and later only the one produced by the defined pattern.
But it still works and can craft the solar panel.

Mekanism also has a hard dependency on FMP, so it is more or less impossible to try it in my dev environment (which it also broke for now).

As I cannot reproduce and it is working with both version in a fresh world with only AE2 and Mekanism, I must consider it as working for now. At least until someone can provide a detailed description on how to reproduce it reliably.

**Comment by halvors** [comment]
I've done some more testing and figured out that this only happens in SMP (I thought that SSP basically was a server running on the local machine?). Anyways, work just fine in SSP. When using this in SMP i get the following error in the chat.

[01:53:07] [Client thread/INFO]: [CHAT] Error: java.util.concurrent.ExecutionException: java.lang.RuntimeException: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/AdvancedModelLoader

**Comment by halvors** [comment]
Think i cought some releavant crash information here: http://pastebin.com/gWD7W14M

**Comment by ignisthedragon** [comment]
I dont think this crash is caused through AE2

**Comment by halvors** [comment]
Debugged this the last 2 hours. Finally figured it out. It was Resonant Induction who caused this with somehow screwing up the et/minecraftforge/client/model/AdvancedModelLoader.

Thanks for any help with this. My apologies for blaming this on AE2 :)
