### ISSUE TITLE
Add FTB industrial contraptions support

### ISSUE THREAD

**Issue by alice1212123** [AppliedEnergistics/Applied-Energistics-2#6605]
### Describe the feature

The Energy acceptor would support energy from FTB industrial contraptions machines 

### Reasons why it should be considered

 it will make energy generation more convenient for some people that don't want to add other mods to their modpack

### Additional details

FTB uses Zaps (not EU) thanks to Random832 for this lol

**Comment by Random832** [comment]
After some investigating:
- FTB:IC uses its own energy system called "zaps", not EU.
- Block entities supporting it directly must implement an interface rather than using capabilities, so it's impossible for a mod to be fully compatible with it without being a hard dependency
- It has a configuration option that will automatically convert to Forge Energy, which AE2 already supports.
- However, while FTB:IC cables visually connect to energy acceptors, for some reason the energy never actually transfers.
- Connecting a cable directly to an ME Controller *does* work [at the cost of a controller face], but neither block nor panel energy acceptors do for some reason.

**Comment by alice1212123** [comment]
thanks for the find that is odd that a generator from FTB:IC can power a ME network without something like an energy acceptor 
most mods like thermal expansion, mekanism, and immersive engineering work fine with an energy acceptor because I think they all use differently named versions of FE. From my knowledge, zaps are different or incompatible from FE?

**Comment by Technici4n** [comment]
Closing as this is an FTB:IC issue.
