### ISSUE TITLE
Crash with REI

### ISSUE THREAD

**Issue by Sunekaer** [AppliedEnergistics/Applied-Energistics-2#6765]
### Describe the bug

Crash when looking up recipes
ae2 1.18 has native rei support
but rei still loads its jei plugin
so there are duplicate displays for the same category id

### How to reproduce the bug

Look up recipes with REI installed 

### Expected behavior

To not crash

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

https://pste.me/@/iV91Fzv2qTg

**Comment by Sunekaer** [comment]
Thanks @Technici4n

**Comment by Technici4n** [comment]
@Sunekaer Should be fixed in 11.6.4 that will be out in a few minutes. I also polished the REI integration a bit to fix various issues, such as the crafting terminal "move items" preview being misaligned. I also recommend that you set `enableFacadesInJEI` to `true` moving forward, as this release properly supports adds them as collapsible entries: :wink:

![image](https://user-images.githubusercontent.com/13494793/200899138-2c131686-bb6c-4da8-a2bb-30c19a15899e.png)
