### ISSUE TITLE
Wireless Terminals print the "Out of Range" message three times

### ISSUE THREAD

**Issue by shartte** [AppliedEnergistics/Applied-Energistics-2#6840]
Used it only once, got the message three times:

![grafik](https://user-images.githubusercontent.com/1261399/208247358-15e7344c-6e32-47d4-8d1a-615683616f12.png)

**Comment by Mari023** [comment]
Since I suspected ae2wtlib to affect this, I did some testing on different minecraft versions, mod loaders and with and without ae2wtlib, and the message always appeared *two* times, except on aof 5, where it was printed 4 times 
(in a different 1.18.2 fabric instance with just ae2 and ae2wtlib It only appeared two times tho)

**Comment by moshner** [comment]
I am having this issue as well but I cannot ever open the wireless terminal even 1 block away from the ME Wireless Access Point
