### ISSUE TITLE
upgrade for interface

### ISSUE THREAD

**Issue by krakel** [AppliedEnergistics/Applied-Energistics-2#685]
A interface can only hold 9 recipes. With a special new upgrade this could be increased. Thereby machines can be used more efficiently.

**Comment by yueh** [comment]
I am 95% certain this was already rejected, maybe some other dev can step in and assure it?

**Comment by AlgorithmX2** [comment]
Yes, it was rejected.

There is almost no reason why you can't use things like subnetworks or something akin to hoppers to extend surface area of a machine to apply a limitless number of recipes to a single machine, and shoving every recipe in a single machine is slow anywhere, so most people prefer to use a few machines instead of 1 to improve processing speed, or concurrent recipes.
