### ISSUE TITLE
JEI support for MC 1.19.3 Forge

### ISSUE THREAD

**Issue by SubSonicEr** [AppliedEnergistics/Applied-Energistics-2#6901]
### Describe the feature

Hey there,

since JEI is available for MC 1.19.3 Forge, more and more mods in my mod collection will need JEI if I update them. So if I want to update this mods I need to use JEI instead of REI. I like more to use JEI instead of REI unfortunately if I'm switching to JEI, I can not use AE2 in my mod collection because the JEI version is to high and MC won't start. I don't like to play my mod collection without AE2. Is there a plan to make a mod support for JEI in MC 1.19.3 Forge?

Thanks and greetings :)

### Reasons why it should be considered

I think I'm not the only one who want the support for JEI in MC 1.19.3 Forge.

**Comment by Zelioth** [comment]
Support is already present in AE2 for 1.19.3. The only issue is the Dependencies Version needs to be updated since JEI is now updated. 

AE2 Requesting 11.30.230 - 12.0.0. 
JEI is now version 12.0.2.2

To fix this for future reference and updates and to make it easier on the AE2 team would it be possible to just add a universal Dependencies from say the first version for 1.19.3 to Any  that references 1.19.3 compatibility

**Comment by SubSonicEr** [comment]
Hey there, thx for your fast and nice response :)

For now I've created my workaround at my own risk. I've modified the version range of JEI in the mod.toml in the META_INF folder to 13.0.0.0 max version. It seems to work, of curse at my own risk, that I may cause ugly errors. But now I can use AE2 with JEI :)

Greetings
