### ISSUE TITLE
Spatial anchor loading does not propagate across dimensions through quantum rings

### ISSUE THREAD

**Issue by Sea-Kerman** [AppliedEnergistics/Applied-Energistics-2#7013]
### Describe the bug

A spatial anchor on a network in the overworld will not load a section of the network in the nether, even though the network is propagated through a quantum bridge.

Interestingly if I then place and break an anchor on the quantum ring in the nether it stays loaded until I reset the quantum ring connection by removing and replacing the singularity

### How to reproduce the bug

https://youtu.be/ChHtWlKq9Dk

### Expected behavior

since both sides of the quantum ring are the same network, the spatial anchor should keep the entire network loaded

### Which minecraft version are you using?

1.19

### On which mod loaders does it happen?

Fabric

### Crash log

https://gist.github.com/Sea-Kerman/f82c6262d6b34dac0a731f7545454e90

**Comment by Technici4n** [comment]
> A spatial anchor on a network in the overworld will not load a section of the network in the nether, even though the network is propagated through a quantum bridge.

This is more or less intended. It originally comes from limitations with the Forge chunk loading API (a block can't load another dimension), but I would argue it's fine from a design POV.

> Interestingly if I then place and break an anchor on the quantum ring in the nether it stays loaded until I reset the quantum ring connection by removing and replacing the singularity

I could reproduce this, but it turns out that the chunk in the nether will eventually unload. It's just Minecraft taking its time. You can use `/forceload query ~ ~` to check if a chunk is currently being force loaded (which is how the spatial anchor is implemented on Fabric).
