### ISSUE TITLE
Make cables and similar blocks not path-findable

### ISSUE THREAD

**Issue by AlexiyOrlov** [AppliedEnergistics/Applied-Energistics-2#7042]
### Describe the feature

Mobs should avoid navigating through cables and such

### Reasons why it should be considered

Mobs should be able to move around these blocks without getting stuck. This is especially noticeable on flying mobs

### Additional details

I think you should override `isPathfindable` in Block class and return false

**Comment by Minebrine66** [comment]
Is this issue being worked on? I'd like to try my hand at it if no one else is working on this.

**Comment by Minebrine66** [comment]
So I've implemented the fix as @AlexiyOrlov described and I've done some testing. These are the behaviors I've noticed.

### Without the fix ###
Hostile mobs, such as zombies, will see through the cables and attempt to walk through the cables, only being stopped by the physical cables.
Allays will see a dropped item through the cables and attempt to fly through the cables, only occasionally being stopped by the physical cables due to the thinner cables not being as wide as a normal block.

### With the fix ###
Hostile mobs, such as zombies, will still see through the cables but will navigate around the cables to reach either the player or a villager. 
Allays don't seem to see dropped items through the cables. However, once guided around the cables, allays will pick up the dropped item and navigate around the cables to deliver them to the player.

The cables still function as normal as my fix didn't change how the cables worked. Is this the behavior that you are expecting?

**Comment by AlexiyOrlov** [comment]
I think so

**Comment by Technici4n** [comment]
Sounds good

**Comment by Technici4n** [comment]
Fixed by #7153.
