### ISSUE TITLE
Level emitter with crafting upgrade keeps emitting

### ISSUE THREAD

**Issue by djmulder** [AppliedEnergistics/Applied-Energistics-2#706]
So I automated crafting of pure crystals by use of level emitters. The condition is simple: while it's crafting .. emit redstone signal (keeping the growth accelerators on)

Now for some reason 1 level emitter keeps emitting (the one with the pure certus quartz crystal). My crafting status is empty, 0 of my cpus are being used. 

Attached are images of the situation. I'm using version: rv2 alpha 29

![image](https://cloud.githubusercontent.com/assets/10437793/5649314/23e6f6b0-9695-11e4-88dd-f734071f0122.png)

![image](https://cloud.githubusercontent.com/assets/10437793/5649325/31b8b10c-9695-11e4-8b84-84832f738aed.png)

![image](https://cloud.githubusercontent.com/assets/10437793/5649329/38be379c-9695-11e4-9f04-31d39d615e04.png)

**Comment by melchisedekko** [comment]
the same is happening to me.
I can confirm the problem.

**Comment by gkuba** [comment]
This is an intermittent problem for me too. Generally I fix it by removing the item filter and crafting card from the level emitter and putting them back. On one occasion I had to remove and re-add the emitter. I have not had it get stuck on after crafting only while setting it up.

**Comment by yueh** [comment]
Level emitters themselves are pretty dumb, if they do not trigger it means the did not get notified about every finished crafting and then query the crafting cpus again if it is still crafting that item.

So if the crafting cpu is really not sending these events, this would affect more level emitters not just a single one.

The best option would be, if you could reproduce it in a fresh creative world and then upload it.
I have used a similar setup long ago and never encountered something similar. Also the level emitters and other parts for should not have changed since rv1.

**Comment by djmulder** [comment]
I fixed it by re-issuing a craft... it should be chunkloaded (it's right underneath the chunkloader) 

I'll try to reproduce it.

**Comment by yueh** [comment]
Not just the level emitter, the whole network. Just one cable somewhere or other side of a QNB is enough.

**Comment by djmulder** [comment]
Ahh ok, hmm might be that.. I was building my new AE network in another dimension 


Talking about multi dimension I might have found a bug with multi dimension crafting and yes chunkloaded... I just have to pinpoint what's going wrong as my creative tests all seem to work, so I can't just make the ticket yet, it seems to have problems accessing a storage subnet while in another dimension, it sees the subnet and draws items but won't put the crafted item back I'll keep you posted when I find out what's going wrong

**Comment by djmulder** [comment]
Yeh seems to be that... I haven't encountered it anymore.. no matter what I try
