### ISSUE TITLE
Make p2p tunnels "remember" their names

### ISSUE THREAD

**Issue by Mathe172** [AppliedEnergistics/Applied-Energistics-2#707]
I'm using p2p tunnels to carry my complete network through one dense cable, which is why I have a lot of p2p tunnels placed on my controller. In order to distinguish them, I renamed them using an anvil. There is just one issue - the name doesn't always show properly in Waila:
They show if the p2p tunnels settings are set by a memory card, but this only works until a world reload, after that the names are hidden again.
I hope I could explain my issue clear enough, if not, I'll try to clarify myself :)

**Comment by yueh** [comment]
We have not really found a good solution for the problem.
Anything requiring Waila is basically a no-go as we cannot assume it is always present, just add some support if we have a own solution.
No idea what causes Waila to display the name, but this might be just a somewhat useful bug.

Colors are not an option. Using the 16 default minecraft ones would require 16 different colors for each p2p tunnel.

I will probably close it tomorrow, because of this:
Duplicates #38, #43, #395, #691

**Comment by Mathe172** [comment]
Fair enough...
But would it be possible instead to have a similar future for the network tool? Like you right-click on something, and it displays the name or even some more specific information in the interface for that part (and not just the whole network). It could even be enough if the memory card displayed the name of the saved component...
