### ISSUE TITLE
Storage bus - using interface as chest

### ISSUE THREAD

**Issue by Mathe172** [AppliedEnergistics/Applied-Energistics-2#708]
I have a problem and I'm not really sure if this is a bug or intended:
I have the following setup:
![2015-01-07_22 05 02](https://cloud.githubusercontent.com/assets/3540742/5653320/79913ef8-96b9-11e4-8554-f4f6b5f9ab23.png)

The green network exports cobblestone into the interface of the blue network. The blue network has a storage bus attached to an interface of the red network, which has a simple chest for storage.
Now to the problem:
I want the cobblestone of the green network to be stored in the chest of the red one. To achieve this, I configured the red interface to keep an item stocked, so it is treated as chest by the blue storage bus (according to the wiki). However, the items are getting stuck in the blue interface.
In my test world (seen in the image), I could resolve the issue by removing the item from the red interface, allowing the blue storage bus to include the red network. This doesn't seem to fix the issue on my server, (it may have to do something with the fact that the red network on the server is the huge main network and not some simple sub-network) but it also isn't intended that way (that the blue network sees everything in the red one)

If you need further configuration details, (of the test setup, my environment or the real setup) just ask and I'll try to provide them

**Comment by yueh** [comment]
This might become a quite complex explanation.

First of all you do not need to configure the interface to something in the network. Just attaching the storage bus from the blue network to an interface on the red network will cause the blue network to store everything matching the filter on the storage bus to be stored inside the red network.

Configuring the interface will make it appear as a chest to the attached storage bus, which then wants to store everything in the interface. But this is quite pointless as the interface will try to push out every item which is not configured and simultaneously trying to extract the requested items from its own network to keep it stocked. So for example it will never prevent the interfaces from overflowing the network.

The real problem here is that interfaces will never insert or extract items from other interfaces.
The interface getting items from the green network is the one trying to get rid of the items, but it will only see other interface available on the network and so not insert them.
If we would allow this behaviour, interfaces will start to steal items from eachother of they are not full or try to overflow other interfaces to get rid of overstocked items and causing a horrible feedback loop as this will never stop.

If you for example change the setup and replace the export bus in the green network with an interface exporting some items from it and then use an import bus on the blue network it will insert items into the red network as the interface is no longer the active part in it.

**Comment by Mathe172** [comment]
Thanks a lot for the detailed explanation!
I see that it could lead to problems if you would allow interfaces to insert items into other interfaces/extract from them, but why does this also hold if the interface is just a "chest" behind a storage bus?
I will try to implement your idea with the import-bus into my setup, it seems like it could fix the issues.
I have one question however:
My "real" setup looks like this:
![2015-01-08_13 40 23](https://cloud.githubusercontent.com/assets/3540742/5662655/601a57f6-973c-11e4-85d5-5a91ff6b9ba6.png)
The blue network on the bottom (covered cable) is the equivalent of the blue network in the example above, the magenta one is the green and the blue on the right (smart cables) is my main network.
A bit more details:
* The bottom blue network has one interface on the left with default configuration, one storage bus on extract-only in the center (pointing away) and one storage bus on the interface of the main network (insert-only, it is behind the cable on the right pointing up)
* The interface of the main network is in default configuration
* The main network is a big network with controller, the storage is a Super-Soaryn-Drive connected through p2p-tunnels
* The magenta network just has an export-bus (redstone controlled) exporting into the interface, and a storage bus (pointing to the right)

The problem now is: No matter how I configure the storage bus of the bottom blue network and the interface of the main one, the interface of the bottom blue one refuses to store its items in the main network (even if the storage bus is set to default mode - I checked that in this case the bottom network sees and can access everything in the main one). Any ideas how to fix that? I tried reproducing the problem in my test world, however I wasn't able to reproduce the problem. (Only difference is that the main world is running on a server and the size of the main network obviously)

**Comment by yueh** [comment]
It is still an interface with all the advanced functionality, it just announces the internal inventory instead of the whole network. Of course in this case it could be possible to allow it, but it is way easier to say we prevent this always instead of introducing some different cases and introducing some strange bugs.

Your setup looks a bit like a supplier network (that is one of the use cases for the configured interface, just for smaller amounts to keep stocked). So the alternative with import buses might not really work.

Did you replace the interface on the main network with a chest? This could indicate that the main network can not store these items. If the storage bus will still not insert into the chest, maybe increase the priority for the storage buses?

**Comment by Mathe172** [comment]
Hmm... I think I tracked down the cause of the issue: It seems to be the security terminal in my main network (I only use it for the wireless access terminal). First I thought it was caused by some EnderIO conduits I used in a few places (I read that they cause some issues), but the issue also occurs when adding one to the red network in my example build (which has never seen EnderIO conduits)

**Comment by Mathe172** [comment]
Confirmed for a minimal example:
![2015-01-08_23 01 52](https://cloud.githubusercontent.com/assets/3540742/5671711/740d34e2-978a-11e4-85e7-ea8ec0191016.png)
As soon as the security terminal is added is stops working. (items are put into the right interface, chest should be the output)
Environment:
Java 1.8.0_25, 64bit (Windows 8.1:amd64:6.3)
MCP v9.05
FML v7.10.85.1230
Forge 10.13.2.1230
AE rv2-alpha-29

**Comment by yueh** [comment]
That is intended as it prevents access to the network without permission.
Either add a blank card to the security station and set the default permissions, which apply to everyone not defined. Or add a security terminal to every other network.

**Comment by Mathe172** [comment]
I didn't realize that, but now that you mention it it makes a lot of sense - Thanks a lot!
