### ISSUE TITLE
wireless terminals drain 50% instantly upon opening

### ISSUE THREAD

**Issue by 9bananas** [AppliedEnergistics/Applied-Energistics-2#7473]
### Describe the bug

when opening any wireless terminal, they instantly delete 50% of their charge, then continue working with the reduced capacity.
this has little impact on useage, other than putting considerable drain on power generation.

exact description here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/4096#issue-1956422397

### How to reproduce the bug

see the link above

### Expected behavior

wireless terminals should not drain 50% of their charge while in use.
instead power should drain at a constant rate during use, starting at 100%.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

https://mclo.gs/C2nBY8a

**Comment by Mari023** [comment]
ae2wtlib causes this.
it is intended behavior.

add more energy storage on your network, and make sure you can supply your network with enough energy.

the reason this happens is because if your terminal is quantum linked, the system will charge your terminal, but if your system doesn't have enough energy, the terminal will reverse charge your system, to make sure it won't run out of power.

**Comment by 9bananas** [comment]
thank you for the quick reply.

...still VERY unexpected behaviour...
