### ISSUE TITLE
Lag Spike when searching something in Wireless Terminal

### ISSUE THREAD

**Issue by MKr4zy** [AppliedEnergistics/Applied-Energistics-2#7698]
### How to reproduce the performance issue

Whenever I search something in my wireless Terminal, my game freezes for ~2 sec.
This happens when reopening a Terminal with a saved search, or when first searching upon opening.
When searching something else, it works fine. Just the first Search after opening is causing lag.

### Spark profile link

https://spark.lucko.me/iOkDBelGRC

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Additional details

I'm playing the ATM9 Modpack, Version 0.2.51
AE is version 15.0.21

**Comment by Technici4n** [comment]
Reported to GT: https://github.com/GregTechCEu/GregTech-Modern/issues/964.

**Comment by andrewjbennett** [comment]
This is fixed in gregtech as of [1.1.3.b-build_515](https://github.com/GregTechCEu/GregTech-Modern/releases/tag/1.20.1-1.1.3.b-build_515). The fixed version isn't yet available via CurseForge etc, but you can easily download it directly from the github releases page and manually put it into your mods folder.

(thanks for the bug report and the fix, I came here to file the bug myself then discovered it had already been reported and fixed 🙂)
