### ISSUE TITLE
Energy acceptor as cable accessory

### ISSUE THREAD

**Issue by monkeybug34** [AppliedEnergistics/Applied-Energistics-2#785]
I was thinking, why does the energy acceptor have to be a full block? it seems to add unnecessary bulk to the network. I was hoping that perhaps we could get an Energy Acceptor type attachment to place on cables, much like what we have for the ME Interface.

**Comment by yueh** [comment]
Mostly because the way energy system are working,
If it would be a part, every cable would basically be an Energy Acceptor and handle all power input.
The part would just enable one side to accept power. It is a pretty large overhead.

It might even result in other pipes randomly connecting to every cable or it might not be even possible to prevent every power system from only powering a single side or connecting to one.

But else it is not a bad idea. Just might be not feasible to integrate it.

**Comment by Entoarox** [comment]
@yueh cant you make it work similar to the energy p2p's, or do they handle the energy that different?

**Comment by Deshiba** [comment]
Am I misunderstanding how the Energy Acceptor works? Because I was under the impression that it was a machine like the interface that let chanels trough as if it was a cable. From the test-case image below, the network still functions normally. 
Having the energy acceptor as a part would just be for aesthetic reasons?

![2015-01-21_11 46 20](https://cloud.githubusercontent.com/assets/10565800/5834966/4a692ad2-a163-11e4-9453-37852054fb26.png)

**Comment by yueh** [comment]
It transfers channels, but it is not a cable. Cables are just a subset of tileentities, who are able to transfer channels.

If I remember the debugging correclty, the P2P tunnels are replacing the normal cable container. Think of them as invisible blocks, which hold parts like buses or cables (as they are just parts).

Energy Acceptors are way simpler and probably also much older compared to P2P tunnels. So the code to replace the containers was probably not available and maybe also limited to P2P tunnels.

Just saying it might be complicated to implement.

**Comment by Deshiba** [comment]
@yueh if I understand correctly it would be safe to say that energy acceptors are "ghost" dense cables. I'm sure there is a technical distinction involving tile entities, but to the user this is how it functions equivalently.

What I was getting at with my previous comment, is that the statement that Energy acceptors "...add unnecessary bulk to the network" would actually only be visual. Making it into a part would mean that you'd have to run a smart/covered cable off a dense cable in order to place it. Taking up 2 block-spaces where it can now do it in 1 block-space.

Changing code that you say "might be complicated to implement" for the sake of aesthetics or uniformity at the cost of actual block-space management seems... more trouble then it's worth.

**Comment by yueh** [comment]
Not exactly about the "ghost" cables.
A TileEntity is just something with a function, like a vanilla furnace, hopper, chest. Basically any machine. With the exception of some decorative blocks most AE2 blocks are TileEntities, which can transfer channels/power/etc. Like the Inscriber, Crystal Growth Accelerator or just cables.

Cables are just a bit different. If you place you are actually placing an invisible block/tileentity, which can transmit cables. And the actual visible cable is just a part defining how it should be rendered.

This is still handled internally, so we are safe to look at a neighbor and decide this is acutally a cable and not just a random TileEntity and can directly access every part directly.

The moment we are speaking about power it is completely external. TileEntities providing power will usually look at their direct neighbors and if it is a cable the will just see there is something. But nothing which can accept power and they do not care if it is a cable or something completely different.
To be noticed, we need to replace that invisible block holding the cable into something accepting power the moment we attach a Energy Acceptor part and also make sure it does not lose any other part or setting while doing so. As well as change it back into what it was before if we remove it again.
Also P2P tunnels may influence it, like if you add a fluid p2p tunnel it might change it to just a fluid handling block and losing the power functionality.

I will probably look into it. But I cannot really promise anything.
It is just not a high priority as it might get complex and just removes a single block from you network (which still acts as a cable and can be a replacement for any cable)

**Comment by monkeybug34** [comment]
I had no idea that it could be inserted in the line of a smart cable. I tested it out and it can only allow 8 channels through though. also the suggestion was not to remove the acceptor block, just add a new item as a cable accessory. Last but not least, I was trying to create a micro network, that takes up only a single block, and that's where the idea sprouted.
![2015-01-23_15 08 25](https://cloud.githubusercontent.com/assets/10613697/5884411/e088a682-a311-11e4-93d1-bdfc37db334b.png)
I want to just be able to plug the power cable into the back of the device. T_T

**Comment by Deshiba** [comment]
Didn't actually test the energy accepter chanel troughput, that actually would warrent an update to the block.

**Comment by monkeybug34** [comment]
so, it's been a while. any news on this? did you look into itYueh? Is Deshiba right in it warranting an update? it feels like this post got dropped, kicked under the table, and then forgotten.

**Comment by yueh** [comment]
Nothing new, mostly busy with other things and it has not a high priority.

**Comment by monkeybug34** [comment]
hey, just a quick little bump to see if anything new has happened to this topic.

**Comment by thatsIch** [comment]
sorry, we are all busy. We currently rely on more community contribution or we need a new maintainer
