### ISSUE TITLE
Allow unstackable items to stack when creating a processing pattern.

### ISSUE THREAD

**Issue by ericBG** [AppliedEnergistics/Applied-Energistics-2#801]
For example, I am trying to make a recipe that an ender-lilly seed + 4 buckets = 4 resonant ender buckets, but I cannot do that because of the limitations on the output.

**Comment by ericBG** [comment]
I want to add the [type-enhancement] label but it isn't letting me :/

**Comment by ericBG** [comment]
Aand misclick *facepalm*

**Comment by yueh** [comment]
Should definitively be changed.

**Comment by TheJulianJES** [comment]
I like the suggestion.

**Comment by Blue64** [comment]
This is completely possible as shown via CodeChicken's Item Translocator Mod using an Item Translocator with a Diamond Nugget upgrade, it uses phantom images to set the item count, though I'd recommend including a limit of the Stack Limit * the area of the largest Crafting Grid available.

Idk how to write it all out in code, as I've not yet learned to mod MineCraft myself (kinda enjoying other people's mods, though I'd likely do very well).

**Comment by mindforger** [comment]
also as temporary workaround (dunno if this is added by extra cells by any chance) when you draw the item from NEI (only in recipe mode) you can draw a full stack of phantom items into the pattern terminal ... but it is a bit of a hassle as you ALWAYS get a full 64 stack, irrelevant if left or right clicked .... soooo .. if you by chance can have a look into that too ;)  something like right click drag = 1 item(instead of 64), left cklick drag = 64

**Comment by Blue64** [comment]
There's an adjustable number at the bottom of the NEI section

**Comment by mindforger** [comment]
ok it's an NEI thing then, nevermind i said nothing and thx for the tip

**Comment by Blue64** [comment]
I was reading through looking to see if what I'm wanting to post is already posted (I didn't see it, went back all 9 pages to #13 ), figured I'd help out where I could.
