### ISSUE TITLE
Annihilation plane and ME Storage bus on same cable dissappear after world reload

### ISSUE THREAD

**Issue by jtb1313** [AppliedEnergistics/Applied-Energistics-2#8016]
### Describe the bug

When making a certus automation I noticed that when my annihilation plane is enchanted with fortune 3 and on the same cable I have a ME Storage bus set to only allow certus quartz crystals that it will disappear when reloading the save.  It also crashed the game when I went to dismantle the same block to move it to another location.

### How to reproduce the bug

Annihilation plane enchanted with fortune 3 and on the same cable have an ME Storage bus set to only allow certus quartz crystals then reload the save.

### Expected behavior

that the blocks are persistent in the world and do not crash the game when broken

### Additional details

using mod pack craftoria 0.0.7 ATLauncher Version: 3.4.36.9  I did not download the mods that are not allowed to be bundled with modpacks and need to be downloaded seperately.  Included picture of setup in crash log section.

### Which minecraft version are you using?

1.21

### On which mod loaders does it happen?

NeoForge

### Crash log

https://imgur.com/a/UTK5iDQ

**Comment by Mithi83** [comment]
You did not provide a crash log as requested, so we don't know which AE2 version you are using. My best guess is that the AE2 version is 19.0.6 or lower and the bug is likely a duplicate of #7969, which was fixed in #7979, which in turn was released in 19.0.7.

Your first step would be to always keep your craftoria instance up to date. Curseforge shows 0.0.12 as the latest version, you reported against 0.0.7. That will probably already have a more recent version of AE2 and fix your problem. If AE2 was not updated step two would be a manual update of AE2.

**Comment by jtb1313** [comment]
Upon reading it seems that you would be correct that it is a duplicate.  I have marked closed.
