### ISSUE TITLE
Wireless Pattern Encoder will not add recipes using EMI

### ISSUE THREAD

**Issue by SGZ-Creations** [AppliedEnergistics/Applied-Energistics-2#8182]
### Describe the bug

Wireless Pattern Encoder won't accept making processing recipes.

have video on medal and my discord. tho with all the limitation can share it here or by link as after a day or say the link is deemed 404

### How to reproduce the bug

EMI/JEI won't allow to create processing pattern in Wireless encoder.

### Expected behavior

Be allowed to create processing pattern in Wireless encoder

### Additional details

Playing SkyGreg modpack not saying it's a modpack issue as it does not look like that. When the the other processing pattern works.

### Which minecraft version are you using?

1.20

### On which mod loaders does it happen?

Forge

### Crash log

NA no crash

**Comment by Mari023** [comment]
1. The Wireless Pattern encoding terminal is from an addon (ae2wtlib)
2. ae2 and ae2wtlib don't support EMI on 1.20.1 (*)
3. please provide a forced crash report in the future (hold F3 + C for 10 seconds), it contains valuable debug information

(*) while ae2 and ae2wtlib get EMI support through JEI, this doesn't work for EMI native recipes (which includes gregtech recipes)
for this reason, gregtech includes an EMI plugin for ae2 (that is why it works in normal pattern encoding terminals), and in newer versions it also does the same for ae2wtlib.

my guess is that you just need to update your gregtech version, and it should work, tho I can't say that for certain since you omitted the crash report

**Comment by SGZ-Creations** [comment]
Updating will not work ether as that will have the server crash/ or not boot. due do bugged fluid tanks on server side. for Greg on newer version. so have no other idea to what to do. 
[crash-2024-09-06_03.36.51-client.txt](https://github.com/user-attachments/files/16901776/crash-2024-09-06_03.36.51-client.txt)

**Comment by Mari023** [comment]
> Updating will not work ether as that will have the server crash/ or not boot. due do bugged fluid tanks on server side. for Greg on newer version. so have no other idea to what to do. [crash-2024-09-06_03.36.51-client.txt](https://github.com/user-attachments/files/16901776/crash-2024-09-06_03.36.51-client.txt)

this is fixed since gregtech [1.2.3.a-build_716](https://github.com/GregTechCEu/GregTech-Modern/releases/tag/1.20.1-1.2.3.a-build_716), you have `1.1.4.b
if you can't update gregtech we can't help you either`
