### ISSUE TITLE
Version upgrade item loss caused by mod id change

### ISSUE THREAD

**Issue by LUNACYGG** [AppliedEnergistics/Applied-Energistics-2#8243]
### Describe the bug

When attempting to upgrade AE2 from version 1.16.5 to 1.18.2, I encountered an issue that resulted in all my AE2-related items disappearing. This problem seems to be caused by the change in AE2's mod ID; in version 1.16.5, it was [appliedenergistics2], but in version 1.18.2, it was changed to [ae2]. Minecraft was unable to locate the mod corresponding to these items, and consequently, all my items have been removed

### How to reproduce the bug

just need to upgrade AE2

### Expected behavior

Do you know of any way to fix this, or could support for it be added in a future update？

### Additional details

English is not my native language, I use translation for conversations, there may be some errors

### Which minecraft version are you using?

1.18

### On which mod loaders does it happen?

Forge

### Crash log

appliedenergistics2 (version 8.4.7 -> MISSING)

**Comment by Mari023** [comment]
upgrading worlds isn't really supported.
while it will usually work between most versions, as you have discovered, ae2 changed the modid between your specific versions.

It would be theoretically possible to write "datafixers" for this, but that is a lot of effort we weren't willing to do back then, and it is even less worth the time for us now.

you could in theory write them yourself, or use some external tool and do it manually, but both involves a lot of effort.

in theory you could also compile the mod yourself with the old mod name, tho the amount of changes that needs is kind of large, and you will forever have to compile your own versions (tho as 1.18.2 won't get upgrades anyway, this would effectively be a one-time thing)

--- 
and all of the above assumes you have a backup of your world before upgrading it. If you don't, then there is nothing you can do anyway.

**Comment by 62832** [comment]
These days with the popularity of pre-existing modpacks as the usual way to play modded Minecraft, the expectation is that you wouldn't even bother trying to move any modded worlds over to another Minecraft version. There's no guarantee that whatever pack you have in the other version is going to include the same mods simply because different mods and their teams follow different schedules or might just decide never to release the mod for another following game version.

Even if we did bother to write datafixers, we'd be only one such mod in a sea of at least a couple of hundred of them in the pack which might continue to not care enough to implement those or even keep themselves up-to-date at the same rate. There just isn't really much reason to bother. Sorry.
