### ISSUE TITLE
export & import bus stop working

### ISSUE THREAD

**Issue by parlador** [AppliedEnergistics/Applied-Energistics-2#838]
export and import bus stop to working after many minutes, need to disconnect cable and reconnect for work and return to no working.

**Comment by Roversword** [comment]
I have the same issues. Observed with import buses only so far.
It happens that they work fine (seeing them "sucking" in the items from chests and TE machines) and all of a sudden they stop working...the items stay in the machines or chests.
Happens to me with rv1...everything in one chunk actually. However, chunks in 3x3 are loaded.
I am inclined to say it happens when I have a big order in a crafting unit, but it also happens when nothing is made automatically.
Dismantling and reattach the import bus can help, at least for a time...but sometimes it does not work as a workaround.
Is there anything you need for further investigation? Screenshots? world? server data so you can check yourself? Logs?

**Comment by Teots** [comment]
I have the same problem as @Roversword On random occasions the ME Import Buses in my network stop working. I cannot pin it down to certain events, e.g. large crafting tasks or power outages. But it happens about once a day on my server. The whole network is within the area covered by a chunkloader.

I'm using version rv2-beta-7 (the Karma mod pack from ATLauncher). Do you need any additional information for identifying the problem?

**Comment by Teots** [comment]
I found a way to reproduce my problem! 

I have a export bus with a crafting upgrade. It is requesting yellorium ingots for my reactor. So when there is no yellorium in the network, it's requesting one. And now comes the problem: When I'm out of yellorite ore (which is used to produce yellorim ingots) all input interfaces stop working! It seems to be the non-fulfilled crafting task this system cannot handle.

**Comment by yueh** [comment]
Cannot reproduce it with that description.

**Comment by MortalDanger** [comment]
I have this problem as well.  Seems not to really relate to anything in particular.

Mine relates to pulling items out of a Diamond Chest that is attached to a Tesseract that pulls items in from other tesseracts around the world.  Seems to happen everywhere, really, its just I notice the chest malfunctioning because I'm not getting mats.

**Comment by XFactHD** [comment]
I have the same setup with a tesseract to a crystal chest with an import bus and it is all working the way it should. I have attached the glass cable with the import bus directly to the controller and the cable has only one other component on it.

**Comment by MortalDanger** [comment]
Yes, I have the same setup as you've mentioned.

**Comment by ImaCrazyGuy** [comment]
I just rage quit out of my game because of the frustration AE2 has been causing me.  I just finished spending 6 hours painfully building an enourmous 240k rf/tick big reactor, have it running flawlessy with 4 ender quarries and my issue is I am trying to make compressed cobblestone.  I was a master at AE1 so I know exactly how import/export busses work.  I have a molecular assembler cube plopped down, an import on one side, export on another and a plan to craft 9 cobble into a compressed cobble.  Problem is, it isnt doing squat.  It wont even pull out the crafted compressed cobblestone using the attached import bus when I manually drop stuff into it.  The export wont do anything.  I got it to randomly start dropping cobble into a wooden chest, then it randomly stops working again.

Plenty of power, plenty of knowledge to set up a complicated AE1 system, but the mod itself for AE2 is just a broken piece of crap currently, it is not functioning whatsoever.

**Comment by thatsIch** [comment]
Please provide a world with only AE2 installed where you can re-produce this problem.

**Comment by MortalDanger** [comment]
I will try to reproduce this issue on an AE2 only world, but don't count on it.  A simple server restart resolved the issue, and in the amount of hours played it would take a while to reproduce it.

**Comment by mst3in** [comment]
Restarting does help.  In our server, when the issue starts happening, you can place the import bus and watch it work for a few seconds, then it quits again.

**Comment by thatsIch** [comment]
https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1010

**Comment by Lodran** [comment]
I've found that this bug (or something similar) also affects interfaces, but in a specific way.  When an item is placed into an interface by an assembler, it will always be removed if the item was ordered to fulfill a pattern's needs.  If it is the output of the final pattern (the item that the user requested at a terminal), it may end up being "stuck" in the interface.

**Comment by Lodran** [comment]
One quick hack to resolve this might be for interfaces/import buses/export buses to ask to be moved to the head of the queue whenever an an item needs to be imported/exported by them?  Of course, this would require that re-ordering the list of active interface things be fairly optimal.

**Comment by Zephyrox7** [comment]
I think I found out why this is happening. I had a Mekanism smelting factory and I upgraded it while the interface and import bus was attached to it. This caused some of the other import busses in my network to fail. But when I removed the interface and the export bus from the smeltery and attached them again, the bug was gone. So the reason why this is happening is probably that if you change/modify a device while an interface is attached to it, it creates some kind of bug in the network that affects both interfaces and busses. Can anyone confirm this?

**Comment by Jeppeskovsgaard** [comment]
I can confirm @Zephyrox7 observation. I upgraded a Mekanism crushing factory to an advanced crushing factory. I only replaced the factory and not the ME Interface nor the Import bus. This caused the Import bus at my advanced inscriber to stop working.

Removing and placing the ME Interface and Import bus at the crushing factory fixed the problem.
