### ISSUE TITLE
drives give a server sound

### ISSUE THREAD

**Issue by AlgorithmX2** [AppliedEnergistics/Applied-Energistics-2#89]
what im suggesting is that the drives them self when active give the hum common to server farms since that what they are basically it will give a bit of realism and when no power is present or no cells in the drive it should not emit the sound

Originally Posted by shivachirr

This issue was migrated; For original details see http://ae-mod.info/Tracker/0924/

**Comment by rebio** [comment]
I'm not sure what the user had in mind with "server sound". The only real sound I could think of is a fan. If there is a/more storage drives in the me drive it could play a sound of running drives. When the terminal is accessed it could play the clicking sound if a HDD is accessed.
On startup it could play a spin up sound for each drive which is inside the me drive. If autocrafting is going on and the drives are accessed it could play a sound of a louder or spinned up fan to give the feeling of a hot, hard working system.

If the me drive is broken the sound should fade-out, like an extra utilities generator does when you put something in it and breakit whlle it is running. The sound does not stop right away, but fades out over like 2 sec.

What do you think about the 'server' sounds?

BTW: Some different sounds could be used for the me chest as well...

**Comment by yueh** [comment]
It could be a bad idea. Most players are more or less annoyed by the constant sounds from passive animals, so this would likely apply to drives constantly humming. On the other hand I would not expect that players are annoyed by missing sounds. So they should be at least optional and probably disabled by default. Which makes it questionable as not many players will search in the config for an option to enable sound effects.

**Comment by rebio** [comment]
Players are annoyed if eg. cows go "MOOO" right in your face and that's all what they hear all the time. So many players build them not inside their house even it would be possible/easier.
If the sound is annoying or not is determined not ony by the sound itself but also by it's level - the sound would have to be tested if it fits the setup. 
Would a player be annoyed if a mod as whole would not exist, probably not - that is however not a reasonable argument for me since the absence of something does not prove that a feature would be scorn. 
I would think of it that way: Does your PC/Laptop has a too loud fan/whatever noise four you? On my system it is a background hissing which is there, but does not bother me in any way and does not disturb me while working. And that is what I want to achieve. To bring more 'life' into AE without being a pest to the player. I can eg. think of some really nice 'server storage' rooms - that would be a little bit louder of course but would give you the feeling of a real server rack or something like that.
I agree that it's a good idea to make the sound a config option. However it should be on by default or sounds wouldn't needed to be included in the first place. The sounds should furthermore be affected by the "Blocks" level in the "Music & Sound Options" part in the MC options menu and by extra utilities sound mufflers if the player really wants to have no sound.

**Comment by yueh** [comment]
I am not against it, just that it can be more annoying than providing an additional benefit when not done right.

Also I did not think of the rare "MOO" from a single cow, more about cases where you stick 50-100 animals in the same spot and the constant overlapping effects (including stepping sounds) and all the overlapping interferences it causes through randomness. As opposed to you fan background noise which is mostly a static sound. If they would randomly speedup/speeddown the RPM every couple of seconds you would also start to consider it annoying.

So for example it should not be a block level sound, as it will be extremely hard to synchronize every single drive to not overlap multiple sounds.
It is more of an ambient sound as long as you are in the vicinity of a drive, maybe even scale it depending on the amount of drives. So a single drive will be nearly unnoticable, but 20 more clearly (and cap it at a certain volume). But more complex to actually implement (I doubt that the sound engine used by minecraft has support for these cases).

The question is what sound really fits AE? The cells are pretty much solid state, so technically soundless as they cause no vibrations. Also there is not really a concept of heat (compared to AE1), so fan sounds for cooling are a bit questionable.

**Comment by rebio** [comment]
I wasn't talking about one single cow which makes a random noise every now and then, but more like mob spawners and something from 20 to 200 cows/pig/chicken/sheep or whatever you want to have in one spance.
They would not randomly speed up and down as random sounds every now and then because it would not make much sense. And if they would it would not be like a change in a short time but more a change that would fade in and out over like 2min.
That has to be done while sounddesign to create sounds that could overlap without going overboard. You don't need to synchronise them. One drive makes one sound and another one would make another one if they are next to each other you would be able to hear both. For every disk you can either: start a new sound, the sound level could be adjusted or the sound file itself can be exchanged with one for two/three drives or more. The question is what would be possible. If you know what can be done it's easier to plan the sound files...

I can see that you don't like the idea of sounds in AE2 - for whatever reason - and you try to get some argument's against it. Only because Storage Cells have not like a 'magnetic disc' as crafting component does not mean that they are SSDs or that you can't use whatever sound you think fit for something like that.

**Comment by yueh** [comment]
Before making any guess, I recommend that you look at the source on how minecraft handles sound effects. Then you will notice that most sound effects have a slightly random pitch (which will pratically just play the sound a bit faster or slower). This applies to animals, explosions, eating, step sounds, block breaking and many more. The sounds for baby mobs are for example just played faster to achieve a higher pitch.

I do not dislike the idea of sounds in AE2, I just dislike if it sounds bad.
Actually I really like audible feedback or ambient noise, but it needs to be done right.
I am not good at creating sound effects, but I know enough that sound is something which can easily be done wrong, thus causing a bad experience for the player. Most likely even easier than graphics.

For example the power can fail with every tick (every 50ms) and there should be a clear feedback in that case. It is probably ok if it plays the sound slightly longer, but it should not play for a full second after a drive has gone offline. Of course there could be different effects based on the state (online, powered/no channel, completely offline/no power). But might be not that usefull for a large server room.

Let us assume we use 250ms long sound effects and play them back to back. This should be fine for possible changes in the state of a drive. But there is no guarantee that we can start the next effect exactly 250ms later. So there will probably be a short gap between both and that this will be noticable as stuttering. I would need to do some research or the exact values, but a single ms (probably even less) is clearly audible. Mabye overlapping 2 effects slighly might work. But the question is probably where a real sound effect ends and plain noise starts. Because then we could just play (brown?) noise.

Another issue is that drives are actually pretty dumb blocks. They do not tick. So they cannot play sounds at all. The only time they change their state, is when then inventory or power state changes on the server. This is mostly done for performance. AE2 is even designed to not tick every minecraft tick, but dynamically adjust to the requirements. Some parts might only tick every couple of seconds.
Also it is designed to only tick on the server. Putting more load there is not a good idea, but clientside might not be even feasible to play something per block/drive. Maybe playing some ambient noise based on the player location and surrounding drives might actually be easier.


Real life examples might not be ideal. For example not every server has fans.
There are enough passively cooled ones (but mostly low performance). Or mineral oil based cooling solution.
I honestly have no idea how it could sound. But a simple fan sounds a bit to simple for mod around advanced technology and crystals.

**Comment by rebio** [comment]
Sorry if I have mistaken your words, but by reading things like "It could be a bad idea", "Most players are more or less annoyed by the constant sounds", "I would not expect that players are annoyed by missing sounds", "optional and probably disabled by default", "The cells are pretty much solid state, so technically soundless", "so fan sounds for cooling are a bit questionable" just gave me view that you don't see sounds as a really welcome feature in AE2. Even "I am not against it, just that it can be more annoying than providing an additional benefit when not done right." was for me more like 'Let's be on the safe side and do not test sound effects'.
I know MC sounds and I have noticed that the same sound is played differently. I would suspect - at least I would program it that way - that if MC can change the sound before playing it, it should be possible to not change the sound since it seems like an additional feature to the sound engine. If you look at http://minecraft.gamepedia.com/Commands#playsound is says 'pitch (optional)'. So you could tell /playsound to not use any pitch.
I would also rather have no sound effects than bad ones, but I would decide if the sound is bad if I have done everything to make it better. So creating a sound, including it and if that does not sound good maybe someone else has an idea for a sound that sounds better - so it would not be a wasted coding time since you may would only have to exchange sound files.
Again: How the sound effects will sound like will be determined by what is possible with the audio code. If there is an option to stop or fade out a recording (like the extra utilities genertor does when you break it), the sound files can be as long as you like. Maybe the level can be dropped to 0 while playing the file. So it is playing, you just don't hear it. If they can not be interrupted they can't be longer than x seconds. A solution to a strict length could be to blend in a 'shut down' noise that is louder and overlays the 'working' noise so that the working noise can stop without somebody notices it. In general you shouldn't think of audio files with a length of 250ms. That is usually too short and does not sound well if you stack them together for longer files. It only works for rather short thing like block breaking, steps, etc.
I don't know how the internals of AE work so I don't know how the sound would/could be handled there, but maybe the me drive is a bad example to start with if it's really that of a simple block. Maybe there is somethig else that can be done easier and as a test sample which may even uses the plain vanilla code.
How AE could sound is actually a really good question. How does advaced technology sound? I don't think that crystals have a sound (except those ambient 'your are now in a crystal cave' sounds in older games). If you look at advanced technology they often are represented with some synth sounds. Not sure if this is really the way to go.

I have made two sound design studies which actually do sound pretty bad I would argue, but may give some idea for further discussion how AE could sound.

The molecular assembler:
Link: http://www.mediafire.com/watch/tdfqr7i0dqr1l12/molecular_assembler_sound_design_study.mp4
The concept here is that the molecular assembler has (who would have thought) a synthy sound to it which changes if the molecular assembler has work to do. There are these 4 different sounds which are played if the molecular assembler has finished crafting a type of item. However, only one of them would be there (so not all 4, but only one with slight variations) since they all sound somewhat different. The first one is more like a harder click, the second one is more of a 'computer' sound, the thrid one is a blunt click and the last one is again a more metal kind of click. If the metal clicks are really the way to go for a 'tech mod' is written on the other side of the paper. The computer sound does not really sound like something I would include, but is a possible direction which can be improved.
I want to note again that this is a DESIGN STUDY to check how AE could sound like and which I have done in like 1 hour or so. A better sound for the molecular assembler would may be something similar to https://www.freesound.org/people/burning-mir/sounds/149069/ What I would try is to get the sound 'changing' like the colours - so that it fades through sound - no static sound but changed the sound level and pitch. The 'I have finished crafting some type of block' thing could also sound different of course. Now they are actually reworked gun reloading sounds (https://www.freesound.org/people/MentalSanityOff/sounds/153560/ and https://www.freesound.org/people/Paul368/sounds/201907/). The layout I though of was: is online - has work - just finished crafting a type of item.

The crystal growth accelerator:
Link: http://www.mediafire.com/watch/kcv96v04k7j7doi/crystal_growth_accelerator_sound_design_study.mp4
This is something which is maybe a little bit closer to sound like something that would be in AE. I though that the crystal growth accelerator could have something like an electric/spark/flash/(high)volatge sound to it. I don't think that this is that far away since it already has little zapy flashes coming out of it. Of course it can be improved. I don't like the included electric sound that much (it is build with using https://www.freesound.org/people/JoelAudio/sounds/136542/, https://www.freesound.org/people/BigKahuna360/sounds/160421/ and https://www.freesound.org/people/Bekir_VirtualDJ/sounds/132834/), but again design study.

A third things which I could thing of is the meteorite finder thing to work like a mine detector. It eg. will play a 'beep' sound when you are like 3 chunks away. The closer you get the meteorite the faster the 'beep' sound would be.

Let me know what you think of that.

**Comment by Deshiba** [comment]
First off, I'd like to mention that you are far likely to hear someone vocalize that they dislike something (sounds) then people that like the sounds. People like me that like to play WITH sound are generally content with MC as a whole.... Except for stupid witches -_-


Onto the real contribution! Depending on the server and what year it was created it will make several sounds, which are similar to your own computer. Ref: http://www.computerhope.com/issues/ch000302.htm. Assuming AE2 tech is somewhat similar to state of the art real world tech, the 2 most viable sound sources would be the **power supply** and the **fan**. Both of these are technically created by parts moving at a high velocity producing a light hum (disregarding air displacement).

So you'd want a really soft and low pitched sound that doesn't really bother anyone much, Ref: https://youtu.be/lPGOXhT0Te0?t=1m40s. Paired with a way to progressively lower the pitch and volume when the power goes off, much like a jet engine, Ref: http://soundbible.com/1712-Power-Down.html

I have to say though, there are servers that hardly produce any sounds at all, there's some comparison video's out there. This reference has some annoying music; https://youtu.be/bVCxqtur1q8?t=8m
