### ISSUE TITLE
getCableConnectionType returns GLASS for terminals

### ISSUE THREAD

**Issue by MatthiasMann** [AppliedEnergistics/Applied-Energistics-2#900]
PartMonitor should override getCableConnectionType to return NONE

**Comment by yueh** [comment]
It is probably reasonable to make them consistent in general, if this does not cause any issues with our rendering.

But checking every possible combination is a bit tedious. So as long as there are more important issues and limited time, I cannot give an ETA on it.

**Comment by AlgorithmX2** [comment]
Why should it return NONE? The default for almost all the parts appears to be GLASS

https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/a27ed6d9babaa6598cb7211377d6b5e89784e883/src/main/java/appeng/parts/AEBasePart.java#L265

Technically NONE that it can't connect, so i'm not sure why you think it should be that.

**Comment by MatthiasMann** [comment]
I'm no longer using this method - as it did not provide any reliable data.

**Comment by yueh** [comment]
EnderIO cannot get their conduits to behave correctly. It was an idea, but after digging through more code, I do not see any real reason to change it. Anything needed is provided through the API.

**Comment by AlgorithmX2** [comment]
This method probably didn't do what you wanted, the proper way to detect connectable faces should be asking for a the grid node from the IGridHost, if it has a node it can connect, if it doesn't, it can't; This  only works server side, AE2 requires syncing connection state to the client to be accurate.

Thats just a guess as to what your looking for however.

**Comment by MatthiasMann** [comment]
AE2 does not provide a static information which sides of it's tiles can accept an ME connection.
The issue is mostly with special IPart implementation like P2P ME tunnel, QuartzFiberCable etc which do not list connectable sides in the IGridBlock of the center part. But the external facing node which has it's own IGridBlock is only available when the network is finished booting. But AE2 does not cause neighbor updates for that.

**Comment by MatthiasMann** [comment]
Also just getting the IGrodNode from the IGrodHost is not enough - as tiles like the CGA return nodes on all 6 sides. One has to query the connectable sides from the IGridBlock to determine which sides can really connect.
But on TielCableBus all sides which have an IPart will be removed from that list - which is what I wrote above.

**Comment by AlgorithmX2** [comment]
Nvm my previous comment, not being involved in development for 6 months has the effect of making the knowledge go away over time.

What you really looking for is,

onGridNotification - to tell you that connections changed ( this is on IGridBlock )

and

getConnections() which is part of your grid node.

this informs you of which sides your node is connected too.

AE2's approach to connect, is to let the grid manager handle when your tile/parts connect, rather then you having to check each and every time you want to render something, if you get a notification, update your connection state from the IGridNode.

**Comment by MatthiasMann** [comment]
I need to have a static information (eg not depending on the current network state, only on user actions like modifying a tile) which shows possible connections. And that before connections are made.

And the grid notifications don't help at all - because they are not receivable without having a connection.

**Comment by yueh** [comment]
That is the main difference between EnderIO and AE2.

EnderIO needs to check if it can connect to an adjacent tile before really connecting and becoming part of the Grid. So any callback like `onGridNotification()` or the `@MENetworkEventSubscribe` is not feasible as they are not part of the Grid.

There is a way to obtain the `IGridBlock` from an `IGridNode`, but some parts like the tunnels are only ready at a later point and do no return a `GridNode` for some time.
AE2 does not care about that and just reevaluate, if something changes.
But EnderIO has a hard requirement on this to be available at world load or need to rely on a block update to reevaluate their connections.

**Comment by AlgorithmX2** [comment]
Yeah, thats kinda backwards from how AE2 works, since AE2 just creates nodes for everything and the nodes build the grid, and then tell the owners of the nodes how things ended up.

I guess the only thing you can do is look at,
https://github.com/AppliedEnergistics/Applied-Energistics-2/blob/52c512635d7c9c70774544e069e182a53b06b104/src/main/java/appeng/me/GridNode.java#L362-L369

which is how the grid manages connect-ability. which basically is IGridNode.canConnect called twice, once per node involved in a possible connection. However this is not part of the API; but can be reflected on the GridNode, unless someone wants to add it to the API; kinda a mixed bag.

**Comment by yueh** [comment]
It will not change anything as the `GridNode` is not always available at this point. Still the p2p tunnels as example, the will only create their `GridNode` after `onReady()` is called. If `GridNide.canConnect` can be called, then it would also be possible to obtain the `IGridBlock` through `IGridNode.getGridBlock()` and use the `IGridBlock.getConnectableSides()` to obtain the possible connections.

**Comment by AlgorithmX2** [comment]
Very true, AE2 makes no requirements about when nodes are made available, you can simply delay node creation for 5 minutes because you can, and this is valid in terms of the AE2 API, it sounds like ender IO and AE2 are just not compatible.

**Comment by MatthiasMann** [comment]
The IGridBlock is always available - just add a getGridBlock() method to IGridHost which has the same logic as the getGridNode() except that it doesn't depend on the external facing node.
Or maybe directly provide a isConnectableSide() method.

**Comment by yueh** [comment]
Except there is no guarantee that it returns the right `IGridBlock` without using `getExternalFacingNode()`.
It is probably possible to do so. But it has a higher implementation cost, adds redundancy and a possible future bug as not 100% conforming the contract can break it, compared to obtaining it from the `GridNode` (except someone decides to ignore the "do not implement" and make their own `IGridNode`)

The debate about it is comparable to saying POSIX is incomplete because it does not support the Windows API. But we are really needing some sort of compatibility layer to make it work.

For example. It would be pretty trivial to add something like a wireless transmitter, which can directly inject a connection into a cable without needing a reciever (From the game design it is of course a bit ridiculous). Out of the box it would currently only work with perpendicular directions and maybe line of sight, as there is no concept of multiple connections per side. But that should mostly mean a change at grid level and not every tile/part.
If they were freely rotatable, AE2 just needs to draw a path in that direction from the transmitter and look for a `IGridHost`. Whereas EnderIO would need to scan a sphere around every conduit, searching for them and when they found some, calculate their path based on some possible unknown variables like the orientation, the origin (which might not be the center of the block) and where it hits the conduit. Potentially every (few) ticks.

**Comment by AlgorithmX2** [comment]
IGridBlock are assigned to the IGridNode, not to IGridHost; and this shouldn't change since its an important level of abstraction for IGridNodes, which don't require Physical sides to connect; See QNB for an example..

Another more complicated example is Cables and Cable Parts; which have interior connections on the cable to the parts, and possibly exterior connections to parts, or the cable.

These interior connections, and trans-dimensional connections have no IGridHost Side; and could have different IGridBlock Settings then the other physical connections on the IGridHost.

The core issue with your approach of trying to use static logic is that you expect AE2 and its Addons to notify you of when AE2's Grid Entities are ready to be connected to. Which you will not get unless you are subscribed to the AE2 Grid; Most of AE2's parts/blocks initialize early, however this is by no means a requirement of the API; any users of the AE2 Grid can destroy and create new grid nodes whenever they like the AE2 Grid fully supports it; but your logic will not since your expecting block updates, which are expensive and avoided in AE2.

**Comment by MatthiasMann** [comment]
Currently the AE2 API has a timing race. There is no defined event or time when the external facing grid node is constructed. Trying to obtain the grid node for any side of a TileCableBus results in different answers depending on the time of your question.

I don't want to know when it's ready to be connected or not - only if that side of a tile has the potential to connect. And that information is already available but not accessible.
If you have a tile which randomly allows connections depending on your favorite PRNG result - then just return true for that new call.

**Comment by AlgorithmX2** [comment]
That is not consistent with how AE2 works internally, the data your looking for is runtime, not static. the node may or may not exist, and thus the connection may or may not be possible.

AE2 Has no timing race, You do; Because your not using AE2's API How AE2 is designed.
