### ISSUE TITLE
Energy Acceptor drops in world upon load

### ISSUE THREAD

**Issue by Astrianna** [AppliedEnergistics/Applied-Energistics-2#912]
Added a security terminal today, and wireless, and every time i login(chunk load maybe) the energy acceptor simply breaks/drops in the world. Every time, energy acceptor is just lying there on the ground, waiting to dispensary.

**Comment by yueh** [comment]
Do you use EnderIO ME conduits by any chance?

**Comment by Astrianna** [comment]
i havent been, no

**Comment by Astrianna** [comment]
removed security terminal, problem no longer occurs.

**Comment by TheJulianJES** [comment]
Are there any errors in the log?

**Comment by missmag** [comment]
Do you have a controller in your system, i was having that problem but then i added a controller and it fixed it.

**Comment by SkinBe** [comment]
Sorry to jump onto this toppic ... 

I had a simular issue with specific dense cable that broke all the time at the same place . 
Found out that it had something to do with security settings and the security terminal ... 
But i still wanted to use the wireless so one solution that worked for me : 

insert a blank memory card into the security terminal  with full access and since then no more disconnects 

Maybe not the best solution because everyone can access now the terminals/network , but seems security settings are not working either ( speific user only read/imput/... )

**Comment by thatsIch** [comment]
Closing in favor of https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1074
