### ISSUE TITLE
Allow for processing patterns with more than 9 slots

### ISSUE THREAD

**Issue by Yadokingu** [AppliedEnergistics/Applied-Energistics-2#938]
To automate the more complicated flowers in botania with AE it would need bigger patterns, with more slots, than the one that is currently supported.

**Comment by mindforger** [comment]
like an storage upgrade card into an updateslot of the pattern terminal :D

**Comment by yueh** [comment]
I am not sure about it as I do not really know any other mod besides Botania with these large amount of crafting materials.

A change would imply some rather large behaviour changes, like resizing the slot and losing the ability to switch between both modes without losing the already defined pattern.

Let us assume we change it to say a 3x4 grid with 12 total slots. Maybe Botania did choose the amount of required items on purpose to be not craftable with AE2 (or another mod). So what then happens is, that Botania just increases the amount of different materials to 13. Which is just annoying for everyone not using AE2 and in the worst case sending us both into a loop of constantly increasing the grid size and amount of materials. Probably something noone wants to see.

As an idea, you could maybe use something like a token item to split the recipe into different parts.
Like "Petals + ItemA => ItemB" and then "ItemB + seed => Flower + ItemA".
If you request the flower, it will dump the petals somewhere and if you ensure that Item A gets converted to Item B and routed back into the network it will then dump the seed somewhere.
I am not sure if it works because of the recursive nature, but you could add a prerequisite to create ItemA and then just thrash ItemB at the end.
For example you could use inscribers with name presses to name then like "Flower X Step Y" and rename it with every crafting step in another inscriber. Probably something renewable like cobblestone or sticks is the best option.
